### ISSUE TITLE
New datastore binding requires changes on YCSB Client class

### ISSUE THREAD

**Issue by stnot** [brianfrankcooper/YCSB#1006]
Our work group developed a datastore binding for our recently published key-value store. Now, we would also like to publish our YCSB binding for it. However, in order to work correctly, it requires modification on the core/src/main/java/com/yahoo/ycsb/Client.java class, currently.

During the loading phase, the implemented (YCSB) Client is running on an instance of our storage instead of creating a connection to a daemon. When loading is finished, the client is exiting and also shuts down the running storage instance with it (same process). To avoid this, we added some code to the ClientThread's run method (after the call to db.cleanup()) that blocks the Client from exiting if it is a storage instance keeping all loaded objects alive for the benchmark instances (which needs to be after the completeLatch.countDown(); call).

Before we can submit our binding to the YCSB repository, we would like to discuss a proper solution for our problem. If there is already a solution without involving modification of the Client class, we are glad to implement it. 
Otherwise, we can propose our solution that allows the (implemented) client to indicate if the current YCSB instance has to shut down after it finished.

**Comment by manolama** [comment]
Hi! The common procedure for your use case is to create a mutex of some sore in the client DB implementation, synchronize on it in the initialize method, then initialize your shared object if it was previously null. Then just reverse the process by counting down the latch on the ``cleanup()`` calls. For example, take a look at the HBase implementations: https://github.com/brianfrankcooper/YCSB/blob/master/hbase10/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java#L147-L157

**Comment by stnot** [comment]
Thank you for your answer manolama.
We already handled initialization and cleanup of a "connection" similar to HBase which isn't the problem I tried to explain.

We don't open a connection to our storage like to a common database. Our storage system is compiled with the YCSB client. The YCSB client is running on an instance of our storage system. This applies to both, the (YCSB) storage/load instances as well as the benchmark instances.
We don't create a connection to a remote which can be closed without taking down the loaded (remote) storage instance. The (YCSB) instances loading data to the storage are initializing and accessing our storage system directly. If loading data for the benchmark is finished, the YCSB clients are shutting down and also take our loaded storage offline.

Here is our YCSB client implementation: https://gist.github.com/stnot/ff17af56542e9726736fd61532a78d9a
Furthermore, to avoid shut down of the storages, we currently have the following lines added to com.yahoo.ycsb.Client.ClientThread at the end of the run method:  https://gist.github.com/stnot/da6812fa7f450e0a5a003936f3d274d0

If you have questions about our code or anything I have explained so far, don't hesitate to ask.

**Comment by busbey** [comment]
So what does an end-to-end workload test look like with your current local changes?

**Comment by stnot** [comment]
First, you have to start ZooKeeper and a DXRAM superpeer which are required to start (storage) peers. Then, you start a peer with storage capabilities which runs the YCSB load client. Finally, you start another peer (without storage) that runs the YCSB benchmark client.
Instead of executing shell commands, you can write a deploy configuration file (https://github.com/hhu-bsinfo/dxram/blob/master/script/deploy/conf/example/YCSBTest.conf) and run it with our deploy script (https://github.com/hhu-bsinfo/dxram/blob/master/doc/QuickStart.md).

Our full fork of the YCSB repository with the DXRAM client is now available here: 
https://github.com/hhu-bsinfo/ycsb-dxram/tree/master/dxram

**Comment by busbey** [comment]
Closing as stale. We'd love to have an additional contribution, so please open a PR of you'd like to continue working on this issue with us.
