### ISSUE TITLE
Windows environment, YCSB finished load data,but failed to finished the load data threads and didn't write information into load.log

### ISSUE THREAD

**Issue by kesihai** [brianfrankcooper/YCSB#1009]
![image](https://user-images.githubusercontent.com/18085658/29247932-afeae024-803d-11e7-8a31-5c68339dbb2a.png)

when I test in linux environment, everything is fine, now problems occur in windows, I think the progress is that when all threads finished , their information will be collected and write test result in to file load.log. but now threads are dead loop, so there is nothing is load.log,  what should I do?  Have anythone met the issue?

**Comment by busbey** [comment]
what windows version? what YCSB version? what command line exactly did you use?

**Comment by busbey** [comment]
closing as stale. if you're still having issues please reopen and address the questions above.
