### ISSUE TITLE
MongoDB Benchmarking Using YCSB

### ISSUE THREAD

**Issue by postformeravi** [brianfrankcooper/YCSB#1014]
Hi,
 What is role of thread count while i am using YCSB as a benchmarking tool?
If i am increasing threads count, what will be the affect of this on throughput?

Regards,
Ravi

**Comment by busbey** [comment]
if the datastore you're testing can handle additional load, then increasing the client thread count should get you additional throughput.

**Comment by postformeravi** [comment]
Thanks for response. I am using MongoDB Database for benchmarking. My server CPU Core is 4 core. for this, what is the max thread count for max throughput?

**Comment by postformeravi** [comment]
Even though, when i am increasing thread count, the throughput(ops/sec) is fluctuating, like sometimes it being increase and sometimes, it being decrease randomly.
It is really hard to determine, at what no of thread count , throughput will be max.
Please suggest here.

Regards,
Ravi

**Comment by busbey** [comment]
unfortunately, that will depend on the deployment (hardware and configs) for MongoDB. One thing that usually helps is isolating the YCSB client on a different machine so that it isn't competing for resources with the data store.

@allanbank might be able to provide more guidance on tuning.

**Comment by postformeravi** [comment]
ok. I am sharing my hardware configs.

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
Stepping:              4
CPU MHz:               1999.993
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              20480K

I am doing it on standalone machine. Now  why am i facing this issue?
@allanbank , please suggest the needful.

Regards,
ravi

**Comment by busbey** [comment]
it might just be that you're already overloading the instance. Have you tried plotting the throughput as you vary the thread count for the client?

**Comment by allanbank** [comment]
The only thing I can suggest (and what I have done in the past) is the automate the running of the trials and do lots of them. 
* Start the trials at a level that is much lower (10% or less) of what you expect the maximum performance of your setup to be. 1 thread with a specific low target throughput.
* Modify one variable (threads, throughput, etc) in the run at a time. Run a trial, modify 1 variable, run, modify, run...
* Run each trial multiple (at least 5) times to get a reliable variance. Do not run the same trial 5 times in a row, mix the trials up.
* Make sure the state of MongoDB gets reset after each run. If your workload does not fit in memory that means you have to drop the database (not just the collection) and reload to dataset. If your workload does fit in memory you can get away with not doing the drop but if you see high variance try repeating the trials after wiping and reloading the database to see if it disappears.

**Comment by postformeravi** [comment]
yes @busbey . i had done the same thing by varying  the thread count . But , it give me various throughput.
i want throughput in an exponential manner atleast at a max thread count so that i can suggest to customer , that at this thread count, throughput will be max .
i am sending a snap of various throughput with various thread count.

![image](https://user-images.githubusercontent.com/17312719/30198770-27ab0c66-948d-11e7-93ff-106a57d6163b.png)

Now you can suggest me , where was i wrong. 👍

**Comment by postformeravi** [comment]
@allanbank  please check the above snap and give your input according to this.
I am running a script in which i am varying the thread count for same no of record count and same no of operation. And i got the result, as i mentioned.
I ran the script approx 5 times, every time i got variable throughput for no of thread.
Please suggest a exact solution which could help for mongoDB benchmarking.

Regards,
ravi

**Comment by busbey** [comment]
are these single runs? you should either run for longer or do multiple runs.

**Comment by allanbank** [comment]
Yes - If you want to get reliable results you need to scale the operation count so that the test runs for much more than a minute. I would suggest running with at least 10,000,000 records and operations and consider going higher than that.  Ideally you want each test run to be in the 10 minute range.

I would also, again, start with a thread count of 1 and scale linearly (1, 2, 3, 4, 5, 6, 7, 8 or 1, 3, 5 ,7 9, ...). You should see nearly linear scaling like [here](http://www.allanbank.com/mongodb-async-driver/images/ycsb/2014-05/workload_b_throughput.png) until you hit a bottle neck in your setup.

Based on the numbers you posted I'm going to guess your max throughput is around 8 threads. After that you are seeing flat results until you start getting contention on the client due to the high thread count. Where the bottleneck is will require looking at all of the various metrics (disk, cpu, network, etc.) of the client and mongodb machines. To be clear figuring out where the bottleneck is, is beyond the scope of what we can really do over github.

**Comment by postformeravi** [comment]
@allanbank  Before that i am using script to run the workload with 20 sec sleep count. Below are my script -
echo -e " Starting MongoDBBenchMarking Test1....\n" >> /opt/softwares/ycsb/ycsb-0.12.0/MongoDBBenchMarking-4Sep.txt
echo "---------------------------------------------------------" >> /opt/softwares/ycsb/ycsb-0.12.0/MongoDBBenchMarking-4Sep.txt
echo 3 > /proc/sys/vm/drop_caches
./bin/ycsb run mongodb -s -P  workloads/workloada -p recordcount=1000000 -threads 16 -p operationcount=1000000 -t  >> /opt/softwares/ycsb/ycsb-0.12.0/MongoDBBenchMarking-4Sep.txt
sleep 10
echo -e " Starting MongoDBBenchMarking Test2....\n" >> /opt/softwares/ycsb/ycsb-0.12.0/MongoDBBenchMarking-4Sep.txt
echo "---------------------------------------------------------" >> /opt/softwares/ycsb/ycsb-0.12.0/MongoDBBenchMarking-4Sep.txt
echo 3 > /proc/sys/vm/drop_caches
./bin/ycsb run mongodb -s -P  workloads/workloada -p recordcount=1000000 -threads 4 -p operationcount=1000000 -t  >> /opt/softwares/ycsb/ycsb-0.12.0/MongoDBBenchMarking-4Sep.txt
sleep 10
echo -e " Starting MongoDBBenchMarking Test3....\n" >> /opt/softwares/ycsb/ycsb-0.12.0/MongoDBBenchMarking-4Sep.txt
echo "---------------------------------------------------------" >> /opt/softwares/ycsb/ycsb-0.12.0/MongoDBBenchMarking-4Sep.txt
echo 3 > /proc/sys/vm/drop_caches
./bin/ycsb run mongodb -s -P  workloads/workloada -p recordcount=1000000 -threads 8 -p operationcount=1000000 -t  >> /opt/softwares/ycsb/ycsb-0.12.0/MongoDBBenchMarking-4Sep.txt
sleep 10
echo -e " Starting MongoDBBenchMarking Test4....\n" >> /opt/softwares/ycsb/ycsb-0.12.0/MongoDBBenchMarking-4Sep.txt
echo "---------------------------------------------------------" >> /opt/softwares/ycsb/ycsb-0.12.0/MongoDBBenchMarking-4Sep.txt
echo 3 > /proc/sys/vm/drop_caches
./bin/ycsb run mongodb -s -P  workloads/workloada -p recordcount=1000000 -threads 16 -p operationcount=1000000 -t  >> /opt/softwares/ycsb/ycsb-0.12.0/MongoDBBenchMarking-4Sep.txt
sleep 10
echo -e " Starting MongoDBBenchMarking Test5....\n" >> /opt/softwares/ycsb/ycsb-0.12.0/MongoDBBenchMarking-4Sep.txt
echo "---------------------------------------------------------" >> /opt/softwares/ycsb/ycsb-0.12.0/MongoDBBenchMarking-4Sep.txt
echo 3 > /proc/sys/vm/drop_caches
./bin/ycsb run mongodb -s -P  workloads/workloada -p recordcount=1000000 -threads 32 -p operationcount=1000000 -t  >> /opt/softwares/ycsb/ycsb-0.12.0/MongoDBBenchMarking-4Sep.txt
sleep 10
echo -e " Starting MongoDBBenchMarking Test6....\n" >> /opt/softwares/ycsb/ycsb-0.12.0/MongoDBBenchMarking-4Sep.txt
echo "---------------------------------------------------------" >> /opt/softwares/ycsb/ycsb-0.12.0/MongoDBBenchMarking-4Sep.txt
echo 3 > /proc/sys/vm/drop_caches
./bin/ycsb run mongodb -s -P  workloads/workloada -p recordcount=1000000 -threads 48 -p operationcount=1000000 -t  >> /opt/softwares/ycsb/ycsb-0.12.0/MongoDBBenchMarking-4Sep.txt
sleep 10


According to you, i have to run each test seprately with 10 min interval . Can i use same script for running the test with 10 min interval?

Is it okay or i have to run seprately each test?

Regards,
Ravi

**Comment by postformeravi** [comment]
@busbey  i am using script for running the test as i mentioned above.

**Comment by postformeravi** [comment]
@allanbank  , please should i use single run?

Because i am getting again fluctuation in throughput while using script.

**Comment by allanbank** [comment]
@postformeravi - 

Please read my previous comment.  You have still not:
* Increased the number of records per run.
* Increased the number of operations per run.
* Scaled the threads linearly.

When I referred to running the test for a 10 minute interval I was referring to making sure that the test is running for 10 minutes. Not the time between the tests. You can increase the length of the test by increasing the number of operations. 10,000,000 being a good place to start.

Also, again, based on your posted data I am guessing that your test setup scales up to about 8 YCSB client threads. I cannot tell if that is a client bottleneck (cpu and network being the usual suspects on the client side) or a server/MongoDB side bottleneck (cpu, network, and disk all being potential issues). If I am correct then adding any more threads to client side will not improve performance and adding significantly more threads (like you are doing) _will_ induce contention on both the client and server side which will cause the performance to degrade and fluctuate. 

Rob.

**Comment by postformeravi** [comment]
Thanks @allanbank .

I need little bit assistant regarding sharding. If i will do sharding in MongoDB and than i will do MongoDB benchmarking using YCSB,. What will be the required steps in that case?
and what are the scenario in this case, which should be considered for MongoDB benchmarking?
Please suggest.

Regards,
Ravi

**Comment by allanbank** [comment]
Sharding adds a lot of complexity to your cluster and testing.

You should make sure you read and implement all of the suggestions in the production notes for each server: https://docs.mongodb.com/manual/administration/production-notes/

You now need to determine the architecture for your sharded cluster. Will each shard member be a single mongod instance (not recommended) or a replica-set? If a replica-set how many data members and how many arbiters will you be using? 2+1? 3+0? 3+2? 5+0? Do you have multiple data centers? How do you want the data distributed across those data centers? All of those answers will impact performance.

Where are you going to locate the mongos routing daemons? Next to the shards? On a distinct set of edge nodes? Next to the clients? There are pros and cons for each configuration.

Once that is done you will need to shard and pre-split the collections used by the YCSB client manually. A good place to start is here: https://docs.mongodb.com/manual/sharding/

Now you are ready to run the YCSB client. There the same strategy applies. Start small, increment slowly, find the knee in the curve.

**Comment by postformeravi** [comment]
Yes sure . @allanbank 

I am going to do shading on a testing level only. I am not doing it on production level right now.
I just want to check what is the performace of MongoDB after sharding by using YCSB.
Could it be helpful for mongoDB benchmarking?

**Comment by allanbank** [comment]
> I am going to do shading on a testing level only. I am not doing it on production level right now.
I just want to check what is the performace of MongoDB after sharding by using YCSB.
Could it be helpful for mongoDB benchmarking?

All things being equal, yes, sharding should increase performance... That assumes that the bottleneck is not on the YCSB client side and you are not doing sharding on a single machine. 

Even for testing you will still want to shard and pre-split the collections used by the YCSB client.

I also still recommend looking at the production notes. There is lots of good information in them on common issues that impact performance and why they are issues.

**Comment by busbey** [comment]
closing as stale. if you're still facing this issue please reopen.
