### ISSUE TITLE
Does YCSB support the scheduling of a constant workload?

### ISSUE THREAD

**Issue by seybi87** [brianfrankcooper/YCSB#1015]
Hi YCSB guys,

I would like to issue a constant workload against a DB over a specific time, e.g.:
Execute READ every N seconds (per  client thread)

Is this feature already supported?
I checked the documentation and had a look at some code but I didn't find anything?

If this is not yet supported, could you give me some hints where to start to implement such a feature?

Thank you in advance!

**Comment by busbey** [comment]
you can effectively do this with the target throughput flag, provided that your datastore can sustain the target rate.

see [Section 4 on "running a workload" for the -target cli option](https://github.com/brianfrankcooper/YCSB/wiki/Running-a-Workload#step-4-choose-the-appropriate-runtime-parameters)

**Comment by seybi87** [comment]
Thanks, that was exactly what I am looking for.

**Comment by busbey** [comment]
happy to help!
