### ISSUE TITLE
MongoDB benchmark results puzzle 

### ISSUE THREAD

**Issue by adally** [brianfrankcooper/YCSB#1016]
I used two different machines(Machine A and machine B)  to benchmark .

And I got the following result:
machine A's one-node  had better performance than machine B's one node 
while machine B's two node had better performance than machine A's two node 
My question are:
what did cause this result?
Note :
one node benchmark (YCSB  and MongoDB run on one machine ).
two node benchmark (YCSB and MongoDB run on different machine ).
machine A's two node (MongoDB running on machine  A while YCSB running on machine B)
machine B's two node (MongoDB running on machine  B while YCSB running on machine A)

**Comment by busbey** [comment]
what are the respective machine stats?

**Comment by adally** [comment]
Machine A is a X86 machine and machine  B is an arm machine.Other congratulations are similar

**Comment by adally** [comment]
Machine  A is a X86 and machine B is ARM.Other configuration is similar

**Comment by busbey** [comment]
It's hard to say what would be the cause of the difference. I don't know of any specific optimizations in MongoDB for a particular CPU architecture. It's possible Machine A just does a better job dealing with the concurrent workload while Machine B does better when there's less contention.

**Comment by busbey** [comment]
closing as stale. if you're still facing the same issue please reopen.
