### ISSUE TITLE
Drop jdk7 support

### ISSUE THREAD

**Issue by busbey** [brianfrankcooper/YCSB#1033]
When should we do this? 0.13 is going to add jdk9 support, I think. Maybe that means 0.14? Or is that too soon?

**Comment by busbey** [comment]
Relates to #705

**Comment by allanbank** [comment]
I vote to drop it in 0.14. jdk7 is already 2 years past the last public update.

**Comment by risdenk** [comment]
+1 to drop in 0.14.

**Comment by busbey** [comment]
this will need a large notice on the 0.14 release notes.
