### ISSUE TITLE
YCSB client threads and CPU core usage

### ISSUE THREAD

**Issue by swaapnika-guntaka** [brianfrankcooper/YCSB#1035]
How are the YCSB client threads related to the CPU core usage on a cassandra cluster? I've seen  [#584](https://github.com/brianfrankcooper/YCSB/issues/584) which relates to this but I didnt get the complete picture on that. 

Also when I did a  `top -H <pid>` to see the core used for the ycsb process, while the ycsb load is happening. But it gave me CPU 0.0 and mem 0.0.

This is the load command I gave 
`bin/ycsb.sh load cassandra-cql -p hosts="node1","node2","node3" -threads 32 workloads/workloada -p recordcount=20000000000 -p requestdistribution=uniform`
 
Also is there a relation between YCSB client threads and the thread pool in cassandra?

**Comment by twblamer** [comment]
Setting `recordcount=20000000000` looks like a problem, YCSB won't handle a recordcount value > 2^31-1. See #824 

What's the output if you add `-s` to the command line?

**Comment by swaapnika-guntaka** [comment]
@twblamer  Yeah probably I could only do 20000000 record count.  

My question was more focused on -threads 32. When I run the load command with option -threads 32, it uses 32 client threads to load the records. Does it vary the number of cores used by the Cassandra node to load?

**Comment by twblamer** [comment]
It looks like `cassandra.coreconnections` and `cassandra.maxconnections` control the number of connections in the connection pool, and the YCSB threads all share the same connection pool.  So to get 32 active threads on the server, you can try passing  `-threads 32 -p cassandra.coreconnections=32`. That's all I can tell from looking at the code, hopefully someone knowledgeable about Cassandra can chime in.

**Comment by swaapnika-guntaka** [comment]
I think that's a fair answer. I was looking for the relation between the two if any. Thanks. I'll find out m ore on this.
