### ISSUE TITLE
No host found Exception 

### ISSUE THREAD

**Issue by swaapnika** [brianfrankcooper/YCSB#1037]
Hi I'm trying to run the below command to run benchmark my 3 node cassandra cluster.

`/bin/ycsb.sh load cassandra-cql -p host="node1","node2","node3" -threads 32 -p recordcount=10000000 -p requestdistribution=uniform -P workloads/workloada`

I did this repeatedly to test how much data it could take. But it ran fine for a few times which ran fine and then started erroring out saying 

>Error inserting, all hosts tried but failed. Nohostfound Exception

I still see cassandra still running on that node which said not available. Also it still had >50% disk space available in the data directory to load new data.

**Comment by busbey** [comment]
are `"node1","node2","node3"` placeholders or the literal node names?

**Comment by busbey** [comment]
and do the cassandra logs show anything from when the load command is running?

**Comment by swaapnika-guntaka** [comment]
The node1,node2,node3 are place holders. Please find the Cassandra server log while this threw error.
![cassandra_nohost](https://user-images.githubusercontent.com/18042968/30873043-cc80cad4-a2a0-11e7-9315-062d7af8e209.png)

**Comment by swaapnika-guntaka** [comment]
Here's more detail.
The command I'm trying to run is,
![ycsb_command](https://user-images.githubusercontent.com/18042968/30874662-e274848e-a2a5-11e7-853b-100ebf6d32b2.png)

The error I'm getting is,
![nohost_error](https://user-images.githubusercontent.com/18042968/30874692-f3ca191a-a2a5-11e7-910a-699cd4e762a0.png)

Please refer the above for teh cassandra server logs during the error.

**Comment by jixuan1989** [comment]
Maybe it is because Cassandra node is busy (because "But it ran fine for a few times")?
Have you tried to connect to Cassandra node with `cqlsh` script in Cassandra? and use `nodetool status` to check whether Cassandra cluster is healthy?
(The process is alive does not means Cassandra is fine sometimes....)

**Comment by busbey** [comment]
closing as stale. if you're still having issues please reopen and address questions above.
