### ISSUE TITLE
New Workload

### ISSUE THREAD

**Issue by Zaryab-Arif** [brianfrankcooper/YCSB#1055]
Is there any new workload has been introduced instead of core workloads?

**Comment by cricket007** [comment]
What did you have in mind? You're welcome to override the properties to suit your database testing needs

**Comment by Zaryab-Arif** [comment]
Is there any limitations for core workloads?

**Comment by cricket007** [comment]
What exactly are you concerned about?

**Comment by Zaryab-Arif** [comment]
Actually right now i am trying to find limitations of core workloads. Then will design a new workload which will overcome all limitations

**Comment by cricket007** [comment]
In my opinion, the limitation is the database you're testing. The core workloads are meant to implement common use cases - read heavy or write heavy, or some even combination of the two. 

You aren't limited to using any of the core workloads, so I don't don't think it's fair to assume there's a limitation to them

**Comment by Zaryab-Arif** [comment]
Then what should be the new idea for it?

**Comment by cricket007** [comment]
You are the one wanting to implement the workload, so why are you asking me? Again, it's not clear what database you are testing, what workloads you are trying to achieve, and what metrics you are trying to collect. 

Please read over the examples given by the [Core Workloads](https://github.com/brianfrankcooper/YCSB/wiki/Core-Workloads), and see if any of them apply to you. 

And I'll point out again, you can define your own workload - if you think it warrants a new Core Workload, create a Pull Request.

**Comment by Zaryab-Arif** [comment]
I can share my idea with you. Will you please share your email id?

**Comment by cricket007** [comment]
If your idea is beneficial enough to the YCSB community, you may share it publicly.

**Comment by keshavmr** [comment]
I'm trying to use and extend YCSB framework to test JSON databases.
At Couchbase, we've extended it and implemented the workload for Couchbase and MongoDB.

Please take a look at the Issue #1050 and opine. Thanks. 
https://github.com/brianfrankcooper/YCSB/issues/1050

**Comment by Zaryab-Arif** [comment]
It will be beneficial.

**Comment by busbey** [comment]
All the current workloads can be found in the core module: https://github.com/brianfrankcooper/YCSB/tree/master/core/src/main/java/com/yahoo/ycsb/workloads

Right now they're:

* Core
* REST
* TimeSeries
* ConstantOccupancyWorkload

Unfortunately, the only one with user facing docs on the wiki is [the Core Workloads](https://github.com/brianfrankcooper/YCSB/wiki/Core-Workloads). For the rest you have to look at class javadocs.

**Comment by busbey** [comment]
closing as stale
