### ISSUE TITLE
Neither Jetty ALPN nor OpenSSL via netty-tcnative were properly configured

### ISSUE THREAD

**Issue by Serapke** [brianfrankcooper/YCSB#1058]
I was trying to run the workload on Bigtable but got an error: "Neither Jetty ALPN nor OpenSSL via netty-tcnative were properly configured".

I'm using alpn-boot-8.1.11.v20170118-javadoc.jar with -jvm-args='-Xbootclasspath/p:/home/serapinas_m1/alpn-boot-8.1.11.v20170118-javadoc.jar'

I'm doing this on Compute Engine

**Comment by Serapke** [comment]
#861

**Comment by sduskis** [comment]
alpn-boot shouldn't be used.  It's tricky to set up, and less performant than the tcnative alternatives.  #1048 is one way to go.

FYI, it looks like you're using the -javadoc file, and not the proper binary jar.

**Comment by busbey** [comment]
@Serapke can you try again with the 0.14.0 release artifacts now that the #1048 is closed?

**Comment by busbey** [comment]
closing as stale. if you're still having issues please reopen and address the questions above.
