### ISSUE TITLE
YCSB transaction that updates 10 records

### ISSUE THREAD

**Issue by kunrenyale** [brianfrankcooper/YCSB#1064]
If I understand correctly, each transaction only reads or updates one record in default YCSB, is this correct? If so, Can I use YCSB with updating multiple records?  Can I just change the doTransaction function, say to add for loop to update multiple records? Thanks a lot.

**Comment by busbey** [comment]
closing as stale. If you'd like to work on providing a workload that can span records, please open a PR.
