### ISSUE TITLE
Regarding change in data which is being uploaded 

### ISSUE THREAD

**Issue by pankajdubey1992** [brianfrankcooper/YCSB#1071]
hi 
i was searching for the sample data which is generated and loaded inside all databases and in any case can it be changed if possible please let me know

**Comment by busbey** [comment]
what kind of changing are you looking for? the existing YCSB workloads generate random synthetic data.

**Comment by pankajdubey1992** [comment]
To change column name and data type for aerospike

**Comment by busbey** [comment]
Closing as stale. Please reopen if you're still having trouble.
