### ISSUE TITLE
YCSB for HBase Multinode Cluster 

### ISSUE THREAD

**Issue by cikarozie** [brianfrankcooper/YCSB#1080]
Hello, im cici.
Im a beginner in NoSQL HBase, i have a HBase cluster that consist of 5 nodes. I have a question. What the process of loading and running ycsb on hbase does take a long time? I tried to load data 1 GB and spent 1 hour (worklaodA). Then I tried to load 2 GB into different table and spent 3 hours. What is the cause of the long time of load or run ycsb? Does load or run ycsb need a stable internet connection? I store each data load and run each data size variation into different tables. Does it also affect the length of the load and run process?

please help me to solve this problem, thankyou so much:)

**Comment by busbey** [comment]
where is the ycsb client running? is it just the one client instance? how many threads did you give the ycsb client? Are you using client side buffering?

**Comment by busbey** [comment]
closing as stale. if you're still having trouble please reopen.
