### ISSUE TITLE
95thPercentileLatency(us)

### ISSUE THREAD

**Issue by cgara** [brianfrankcooper/YCSB#1086]
Hi,
What it mean 95thPercentileLatency(us)?
What is exactly? example: "[READ], 95thPercentileLatency(us), 46527.0 " 
Mean 46ms average in 95% of operations fastest?

Thanks so much for your time!

**Comment by busbey** [comment]
the unit `us` is `microseconds`, or 10<sup>-6</sup> seconds. So your example there is ~46 milliseconds.

The line there specifically gives the 95th percentile for read operations. So 95% of all read latencies were less than or equal to ~46 milliseconds.

**Comment by cgara** [comment]
Thanks
