### ISSUE TITLE
YCSB Client for MongoDB

### ISSUE THREAD

**Issue by SantoshKumarL** [brianfrankcooper/YCSB#110]
Hi,

I have been running few benchmark tests on MongoDB in linux environment and using YCSB for data insertion and execution of workloads provided by YCSB.
Execution of workloads a, b & c is fine. When it came to exectution of workloads d & e, I'm facing issue of duplicate key exception. 
When I tried again after specifying variable "recordcount" and insertstart" in the workloadd file I got same exception for few seconds and then later execution is successful and .out file is generated with the execution stats.
.out file stats show that 253000 records have been inserted as workloadd has 5% insert operations. But when I checked the record count in the mongodb using the db.<collection>.count() command, the record count is same as before this execution.
Can you please elaborate why this has happend? If 5% records are inserted as part of workloadd execution in the MongoDB database then the record count also has to increase accordingly??

**Comment by busbey** [comment]
closing as stale. If you can reproduce this problem with the current MongoDB client, please include logs.
