### ISSUE TITLE
Cassandra Latency 

### ISSUE THREAD

**Issue by dipietro-salvatore** [brianfrankcooper/YCSB#1106]
Hello everyone,
I am benchmarking a Cassandra installation on Azure composed of 4 nodes (Standard_D2S_V3 - 2vCPU and 8GB ram) with a replication factor of 2. 
To benchmark this testbed, I am using a single YCSB instance with the workload C (100% read request), a Consistency level ONE and only 10 clients (so very low load).

However, I founded that the average latency gathered by YCSB is much different from the one obtained from the JMX (org.apache.cassandra.metrics:type=ClientRequest,scope=Read,name=Latency)
I ran the workload for over an hour and:
- YCSB returns around 4000 us as average latency
- JMX returns around 780 us as average latency

It is a quite an important difference in performance that I don't know how to justify. 
Do you have any idea from where this difference comes from?

Regarding the throughput, the value is the same across both the reading (~2400ops/sec)

Thank in advance

**Comment by busbey** [comment]
where is the YCSB client running?

**Comment by Nachiket90** [comment]
@dipietro-salvatore, ycsb client reported latency is addition of network latency + cassandra latency (which is available through JMX metrics). Please validate your network latency.

**Comment by busbey** [comment]
closing as stale. if you're still having issues please reopen and address the questions above.
