### ISSUE TITLE
Read Timeout when load dataset in redis cluster used ycsb benchmark

### ISSUE THREAD

**Issue by cikarozie** [brianfrankcooper/YCSB#1107]
Hello, im cici.
Im a beginner in NoSQL Redis, i have a redis cluster that consist of 4 nodes, when i used YCSB for benchmarking in Redis with this command:
![image](https://user-images.githubusercontent.com/35841859/37266316-0907feea-25ec-11e8-89fb-33b04afd5012.png)
i got this error : 
![error load](https://user-images.githubusercontent.com/35841859/37266395-6d4e7bb8-25ec-11e8-9613-33e9d6acf8ed.png)
please help me to solve this problem, thankyou so much!!

**Comment by yunhaom94** [comment]
I don't think it's supported yet, there is a potential fix #1072 but haven't been merged yet.

**Comment by busbey** [comment]
please try again with the 0.14.0 artifacts? #1072 has merged and is in that release.

**Comment by busbey** [comment]
closing as stale. if you're still having issues please try using 0.14.0 with the connectivity options added by #1072.
