### ISSUE TITLE
PR for RocksDB being ignored :-(

### ISSUE THREAD

**Issue by adamretter** [brianfrankcooper/YCSB#1120]
Can someone please please take a look at https://github.com/brianfrankcooper/YCSB/pull/1052

**Comment by Vogel612** [comment]
https://github.com/brianfrankcooper/YCSB/pull/1051#issuecomment-376290805

**Comment by Vogel612** [comment]
That said I added a quick "braindump" review 👍  I encourage you to do the same for other PRs to ease the burden on manolama and busbey

**Comment by busbey** [comment]
as soon as I get a staging branch cut for 0.14.0 I'll start working in merges for new stuff.  right now I see three PRs for RocksDB: #876, #1052, and #1075. if the three authors could come to a consensus position on what to include it'll make things go much faster.

**Comment by adamretter** [comment]
@busbey PR #1052 should replace #876. I had a quick look at #1075 and it seems to be for several things - MongoDB, LevelDB and RocksDB. The RocksDB stuff in #1075 seems to be okay but doesn't account for column families or have support for ensuring a single instance.

**Comment by busbey** [comment]
fixed by #1052
