### ISSUE TITLE
How to Define specific DataSets sizes such as 64GB, 128GB

### ISSUE THREAD

**Issue by Anugnu** [brianfrankcooper/YCSB#1121]
Am trying to test MonogDB, CassandraDB using YCSB. Where I have to test on different datasets sizes 32GB, 64GB, 128GB. But I can't figure out how to calculate it from available parameters. Please respond with any clue on that. Any help is highly appreciated.

Thanks and Regards
Anugnu Veeravathni

**Comment by Anugnu** [comment]
As per the xml file of workloads, I came to know one recordcount is 1kb. That means (1kb*1024*1024) is 1GB. But I wanted to try 1TB load, where Recordcount will be more than the limit suggested. I even read that changing field length will increase load, Is this accurate? If yes, can anyone help me in the equation please.
And one more thing, I need some idea on usage of element name 'target'.
Please help me out  guys. @busbey @twblamer @levaphenyl
Thanks in Advance

**Comment by levaphenyl** [comment]
If the total size is all what matters, then yes, changing `fieldlength` and `filedcount` will help.
Basically, the formula are:
```
row_size = fieldcount * fieldlength
load_size = recordcount * row_size
```

Please see the [workload template](https://github.com/brianfrankcooper/YCSB/blob/master/workloads/workload_template) and the [parallel workload documentation](https://github.com/brianfrankcooper/YCSB/wiki/Running-a-Workload-in-Parallel) for more info.

Please notice that YCSB is a tool and as such, *you* are responsible for designing the test case :wink:. I suggest closing the issue.

**Comment by Anugnu** [comment]
Thanks a lot @levaphenyl 
Sorry for pinging my question in Issues.
