### ISSUE TITLE
Use Another DataSheet On YCSB

### ISSUE THREAD

**Issue by adam034** [brianfrankcooper/YCSB#1126]
Hello, im Adam Kukuh Kurniawan.
Now, Im working on thesis that involves ycsb as tools to used. My thesis about comparing nosql database. I have a datasheet like this, that was collected from my sensor.
Datasheet:
524,%,20,mqtt,8456747,192.168.42.245,dht22,esp8266,celcius,30,pudge
577,%,20,mqtt,8456747,192.168.42.245,dht22,esp8266,celcius,30,pudge
911,%,20,mqtt,8456747,192.168.42.245,dht22,esp8266,celcius,30,pudge
153,%,20,mqtt,8456747,192.168.42.245,dht22,esp8266,celcius,30,pudge
509,%,20,mqtt,8456747,192.168.42.245,dht22,esp8266,celcius,30,pudge
694,%,20,mqtt,8456747,192.168.42.245,dht22,esp8266,celcius,30,pudge

When im tested this datasheet using ycsb on nosql cassandra, I got this error:
[WARN]  The 'cassandra2-cql' client has been deprecated. It has been renamed to                                                                                         simply 'cassandra-cql'. This alias will be removed in the next YCSB release.
/usr/lib/jvm/java-8-oracle/bin/java -cp /home/ubuntu/ycsb-0.12.0/cassandra-bindi                                                                                        ng/conf:/home/ubuntu/ycsb-0.12.0/conf:/home/ubuntu/ycsb-0.12.0/lib/core-0.12.0.j                                                                                        ar:/home/ubuntu/ycsb-0.12.0/lib/jackson-mapper-asl-1.9.4.jar:/home/ubuntu/ycsb-0                                                                                        .12.0/lib/jackson-core-asl-1.9.4.jar:/home/ubuntu/ycsb-0.12.0/lib/HdrHistogram-2                                                                                        .1.4.jar:/home/ubuntu/ycsb-0.12.0/lib/htrace-core4-4.1.0-incubating.jar:/home/ub                                                                                        untu/ycsb-0.12.0/cassandra-binding/lib/netty-buffer-4.0.33.Final.jar:/home/ubunt                                                                                        u/ycsb-0.12.0/cassandra-binding/lib/metrics-core-3.1.2.jar:/home/ubuntu/ycsb-0.1                                                                                        2.0/cassandra-binding/lib/guava-16.0.1.jar:/home/ubuntu/ycsb-0.12.0/cassandra-bi                                                                                        nding/lib/netty-handler-4.0.33.Final.jar:/home/ubuntu/ycsb-0.12.0/cassandra-bind                                                                                        ing/lib/cassandra-driver-core-3.0.0.jar:/home/ubuntu/ycsb-0.12.0/cassandra-bindi                                                                                        ng/lib/netty-codec-4.0.33.Final.jar:/home/ubuntu/ycsb-0.12.0/cassandra-binding/l                                                                                        ib/slf4j-api-1.7.7.jar:/home/ubuntu/ycsb-0.12.0/cassandra-binding/lib/netty-tran                                                                                        sport-4.0.33.Final.jar:/home/ubuntu/ycsb-0.12.0/cassandra-binding/lib/cassandra-                                                                                        binding-0.12.0.jar:/home/ubuntu/ycsb-0.12.0/cassandra-binding/lib/slf4j-api-1.6.                                                                                        4.jar:/home/ubuntu/ycsb-0.12.0/cassandra-binding/lib/slf4j-simple-1.7.7.jar:/hom                                                                                        e/ubuntu/ycsb-0.12.0/cassandra-binding/lib/netty-common-4.0.33.Final.jar com.yah                                                                                        oo.ycsb.Client -db com.yahoo.ycsb.db.CassandraCQLClient -p hosts=10.34.0.33 -P w                                                                                        orkloads/workloadc -s -t
YCSB Client 0.12.0
Command line: -db com.yahoo.ycsb.db.CassandraCQLClient -p hosts=10.34.0.33 -P wo                                                                                        rkloads/workloadc -s -t
Loading workload...
Starting test.
2018-04-07 04:06:26:069 0 sec: 0 operations; est completion in 0 seconds
[Thread-3] INFO com.datastax.driver.core.NettyUtil - Did not find Netty's native                                                                                         epoll transport in the classpath, defaulting to NIO.
[Thread-3] INFO com.datastax.driver.core.policies.DCAwareRoundRobinPolicy - Usin                                                                                        g data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorre                                                                                        ct, please provide the correct datacenter name with DCAwareRoundRobinPolicy cons                                                                                        tructor)
[Thread-3] INFO com.datastax.driver.core.Cluster - New Cassandra host /10.34.0.3                                                                                        3:9042 added
Connected to cluster: Test Cluster
DBWrapper: report latency for each error is false and specific error codes to tr                                                                                        ack for latency are: []
2018-04-07 04:06:29:922 3 sec: 101 operations; 25.63 current ops/sec; [READ: Cou                                                                                        nt=0, Max=0, Min=9223372036854775807, Avg=�, 90=0, 99=0, 99.9=0, 99.99=0] [CLEAN                                                                                        UP: Count=1, Max=2246655, Min=2244608, Avg=2245632, 90=2246655, 99=2246655, 99.9                                                                                        =2246655, 99.99=2246655] [READ-FAILED: Count=101, Max=51007, Min=1490, Avg=3192.                                                                                        56, 90=4763, 99=14695, 99.9=51007, 99.99=51007]

this is my ycsb comman on cassandra: ./bin/ycsb run cassandra2-cql -p hosts=10.34.0.33 -P w                                                                                      orkloads/workloadc -s> hasil_cassandra/cas.txt

My question is, is it possible to use another datasheet on ycsb?
please help me to solve this problem,thankyou so much.

**Comment by Anugnu** [comment]
Hi adam, even am new here but I guess I can help you.
By the way, What do you mean by datasheet in here? loading another workload.

**Comment by adam034** [comment]
@Anugnu hello Mr.Anugnu..
Yes sir, i mean loading another workload.

**Comment by Anugnu** [comment]
The error you got above is due to new changes done in the ycsb repo, even I got the same error just today, change cassandra2-cql to cassandra-cql and try again as it mentioned in the error itself.
Am not sure about your case as it says datasheet instead of pushing load in my case. But In general, you can load as many workloads has you can until you are out of storage.
If am not wrong, you should change the file name at the end of the command, bcs it will override the previous file.
Excuse me if I totally got it wrong.
Hope it helps.

**Comment by wuxiaobing1993** [comment]
i don't konw what you were told about !!!

**Comment by adam034** [comment]
@Anugnu thanks sir, i will try your suggestion in my case

**Comment by busbey** [comment]
what was the command you used to load?

**Comment by busbey** [comment]
closing as stale. if you're still having trouble please reopen.
