### ISSUE TITLE
Can YCSB perform a full table scan on HBase?

### ISSUE THREAD

**Issue by cjxqhhh** [brianfrankcooper/YCSB#1127]
I want to analyze the full table scan performance of HBase, can YCSB do that? Thanks~

**Comment by busbey** [comment]
there's no short-hand way to tell YCSB to do full table scans. if your table is a single column family, you could mess with the scan length and record count to always get from the start key to the end of the table.

**Comment by busbey** [comment]
Closing as stale. Feel free to reopen if you'd like to discuss more.
