### ISSUE TITLE
How do we define Sequential and Random Reads in our workloads

### ISSUE THREAD

**Issue by Anugnu** [brianfrankcooper/YCSB#1130]
Hi Guys, am Benchmarking Cassandra Database with YCSB.
My test is against (4kb transfersize, 32Queuedepth, 100% sequential Reads).
I took a look into workloads file, am thinking 'Fieldlength' is similar to 'transfersize' in my case, workloadc is 100%reads, but how to specify sequential reads, is "fieldlengthdistribution=uniform" is for sequential reads. Do the above assumptions correct or do we have any other element to satisfy my requirement? @busbey @levaphenyl

**Comment by twblamer** [comment]
As an experiment, you could try `insertorder=ordered` and `requestdistribution=uniform`. In that case, both load and run phase should operate on the keys in sequential order.

See: https://github.com/brianfrankcooper/YCSB/wiki/Core-Properties

Note that is not really the same as doing sequential block I/O. When you are testing a DB server, the actual layout of data on disk is always going to be controlled by the DB server and the underlying filesystem. Using `insertorder=ordered` will probably encourage the DB to use more sequential I/O, but I would ask what you're really trying to learn from this test.

**Comment by Anugnu** [comment]
Thanks for that suggestion.
In general, any SSD drive can have a greater number of sequential read operations than random read operations, so I would like to showcase my drives with higher IOps, that what I need to try.
Anyways, I will try that and compare the results with the other tests.

And one more thing, while loading workload data, is there any difference in loading workloada, workloadb or any other workload to another, or every workload acts similar as some random data. I mean does that really make difference to load one workload and testing different workloads on the same workload compare to going with that particular workload load with that particular workload run.

Thanks in Advance.
Anugnu

**Comment by busbey** [comment]
> And one more thing, while loading workload data, is there any difference in loading workloada, workloadb or any other workload to another, or every workload acts similar as some random data. I mean does that really make difference to load one workload and testing different workloads on the same workload compare to going with that particular workload load with that particular workload run.


The "Core Workloads", aka Workload A-F, all handle the load phase the same. So for those 6 specific workloads it doesn't matter which you use. (let me know if I should make this clearer in [the wiki page on running the core workloads](https://github.com/brianfrankcooper/YCSB/wiki/Core-Workloads#running-the-workloads))

**Comment by Anugnu** [comment]
Sooo Thanks @busbey @twblamer
