### ISSUE TITLE
[hbase12,hbase14,hbase20] Setting clientbuffering=true causes NoClassDefFoundError: com/google/common/base/Preconditions

### ISSUE THREAD

**Issue by saintstack** [brianfrankcooper/YCSB#1136]
I set clientbuffering=true (this enables clientSideBuffering) on the command line. The job fails to launch because no guava on CLASSPATH providing Precondition (clientSideBuffering goes a slightly different codepath which has a Precondition check).

It works in hbase10 and there is a guava jar in the bindings lib dir for hbase10. There is no such guava in the hbase12 bindings lib dir.

Workaround is to copy the guava from hbase10 bindings to hbase12 for now.

It looks like guava comes in transitively. In hbase12, the client is shaded so we do not (intentionally) have a transitive include. Could add explicit dependency mention in the hbase12 pom.

**Comment by busbey** [comment]
lemme take a look at repro so I can get a stacktrace. hbase12 is supposed to be using hbase's shaded client, which ought to have guava if it needs it.

**Comment by busbey** [comment]
oh! it's in the client code for ycsb. wow, I am surprised this loads at all. Let me just purge guava.

**Comment by busbey** [comment]
this almost certainly means hbase14 and hbase20 also are broken.
