### ISSUE TITLE
[UPDATE_FAILED - INSERT_FAILED] - Using memcached

### ISSUE THREAD

**Issue by thzois** [brianfrankcooper/YCSB#1141]
Hello,

I am running YCSB on memcached and I get some UPDATE-FAILED and INSERT-FAILED messages. I start memcached with: usr/local/bin/memcached -d -m 512 -p 11211 -l localhost

and for YCSB: ./bin/ycsb run memcached -s -P workloads/workloada -p "memcached.hosts=localhost"

I didn't change at workloada. 
recordcount=1000000
operationcount=1000000
workload=com.yahoo.ycsb.workloads.CoreWorkload

#readallfields=true

readproportion=0.34
updateproportion=0.33
scanproportion=0
insertproportion=0.33

requestdistribution=zipfian

Is this normal? 
Thank you!

**Comment by busbey** [comment]
failure messages generally mean either something is misconfigured between load/run or that the destination datastore is overloaded. what do the memcached logs show?

**Comment by busbey** [comment]
closing as stale. if you're still having trouble please reopen.
