### ISSUE TITLE
Multiple database endpoints

### ISSUE THREAD

**Issue by matjazmav** [brianfrankcooper/YCSB#1142]
Hey, I am testing CockroachDB, this database can use all nodes to interact with database and in production you would normally run haproxy in front of cluster. But for testing purposes it would be enough to pass multiple connection strings (one for each node in cluster) and YCSB tool should rounrobin this connections.

Is something like that available in YCSB or do I need to use proxy?

**Comment by busbey** [comment]
I don't think we have cockroachDB support currently. what version are you trying to use?

**Comment by busbey** [comment]
closing as stale. if you're still having trouble please reopen.
