### ISSUE TITLE
INSERT-FAILED], When using YCSB for riak Benachmarking

### ISSUE THREAD

**Issue by burakcemkara** [brianfrankcooper/YCSB#1145]
hi all

I just started using ycsb and riak  a i have some problem 

I am running below command:
burak@burak-VirtualBox:~/ycsb-0.12.0$ bin/ycsb load riak -P workloads/workloada

The results are as below:

java -cp /home/burak/ycsb-0.12.0/riak-binding/conf:/home/burak/ycsb-0.12.0/conf:/home/burak/ycsb-0.12.0/lib/jackson-mapper-asl-1.9.4.jar:/home/burak/ycsb-0.12.0/lib/HdrHistogram-2.1.4.jar:/home/burak/ycsb-0.12.0/lib/core-0.12.0.jar:/home/burak/ycsb-0.12.0/lib/htrace-core4-4.1.0-incubating.jar:/home/burak/ycsb-0.12.0/lib/jackson-core-asl-1.9.4.jar:/home/burak/ycsb-0.12.0/riak-binding/lib/google-collections-1.0.jar:/home/burak/ycsb-0.12.0/riak-binding/lib/netty-all-4.0.33.Final.jar:/home/burak/ycsb-0.12.0/riak-binding/lib/riak-client-2.0.5.jar:/home/burak/ycsb-0.12.0/riak-binding/lib/jackson-core-2.2.2.jar:/home/burak/ycsb-0.12.0/riak-binding/lib/jackson-annotations-2.2.2.jar:/home/burak/ycsb-0.12.0/riak-binding/lib/riak-binding-0.12.0.jar:/home/burak/ycsb-0.12.0/riak-binding/lib/jackson-databind-2.2.2.jar:/home/burak/ycsb-0.12.0/riak-binding/lib/slf4j-api-1.6.4.jar:/home/burak/ycsb-0.12.0/riak-binding/lib/joda-time-2.1.jar:/home/burak/ycsb-0.12.0/riak-binding/lib/jackson-datatype-joda-2.2.2.jar com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.riak.RiakKVClient -P workloads/workloadb -p recordcount=10001 -load
YCSB Client 0.12.0
Command line: -db com.yahoo.ycsb.db.riak.RiakKVClient -P workloads/workloadb -p recordcount=10001 -load
Loading workload...
Starting test.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Error inserting, not retrying any more. number of attempts: 1Insertion Retry Limit: 0
[OVERALL], RunTime(ms), 680.0
[OVERALL], Throughput(ops/sec), 0.0
[TOTAL_GCS_Copy], Count, 1.0
[TOTAL_GC_TIME_Copy], Time(ms), 6.0
[TOTAL_GC_TIME_%_Copy], Time(%), 0.8823529411764706
[TOTAL_GCS_MarkSweepCompact], Count, 0.0
[TOTAL_GC_TIME_MarkSweepCompact], Time(ms), 0.0
[TOTAL_GC_TIME_%_MarkSweepCompact], Time(%), 0.0
[TOTAL_GCs], Count, 1.0
[TOTAL_GC_TIME], Time(ms), 6.0
[TOTAL_GC_TIME_%], Time(%), 0.8823529411764706
[CLEANUP], Operations, 1.0
[CLEANUP], AverageLatency(us), 506.0
[CLEANUP], MinLatency(us), 506.0
[CLEANUP], MaxLatency(us), 506.0
[CLEANUP], 95thPercentileLatency(us), 506.0
[CLEANUP], 99thPercentileLatency(us), 506.0
[INSERT], Operations, 0.0
[INSERT], AverageLatency(us), NaN
[INSERT], MinLatency(us), 9.223372036854776E18
[INSERT], MaxLatency(us), 0.0
[INSERT], 95thPercentileLatency(us), 0.0
[INSERT], 99thPercentileLatency(us), 0.0
[INSERT], Return=ERROR, 1
[INSERT-FAILED], Operations, 1.0
[INSERT-FAILED], AverageLatency(us), 203072.0
[INSERT-FAILED], MinLatency(us), 203008.0
[INSERT-FAILED], MaxLatency(us), 203135.0
[INSERT-FAILED], 95thPercentileLatency(us), 203135.0
[INSERT-FAILED], 99thPercentileLatency(us), 203135.0

I am also using the below workload config file
recordcount=1000
operationcount=1000
workload=com.yahoo.ycsb.workloads.CoreWorkload

readallfields=true

readproportion=0.5
updateproportion=0
scanproportion=0
insertproportion=0
readmodifywriteproportion=0.5

requestdistribution=zipfian

WHAT CAN I FIX THIS PROBLEM? what i must add my  code for correctly load?
i am beginner user so pelease help me

**Comment by busbey** [comment]
Hi!

Can you confirm via something other than ycsb that your riak instance is working correctly?

It looks like there's no logging set up, so we should try to correct that. It'll take me a bit to come up with what to copy / paste.

**Comment by burakcemkara** [comment]
i think riak is working correctly?
burak@burak-VirtualBox:~$ sudo riak-admin test 
Successfully completed 1 read/write cycle to 'riak@127.0.0.1'
and also i am sure about correctly load ycsb file because I applied the same procedure for the cassandra and it is correctly work

**Comment by diogojfernandes** [comment]
Do you have **slf4j-simple** and **slf4j-api** files on the ycsb\lib folder?

**Comment by busbey** [comment]
@burakcemkara did you get a chance to try out the slf suggestion?

**Comment by busbey** [comment]
Closing as stale. Please reopen if you're still having trouble.
