### ISSUE TITLE
Memcached udp

### ISSUE THREAD

**Issue by hyh-hit2010** [brianfrankcooper/YCSB#1151]
I want to know how to use udp protocol to test memcached

**Comment by busbey** [comment]
I don't see any setting on our end for telling the memcachd client to use udp vs tcp.

If you're interested, you'll have to check on the library we use and then add a new property to set things accordingly.

**Comment by hyh-hit2010** [comment]
From the source code,I find nothing about how to set the udp .Now I want to test the memcacached ability with udp protocal and from some article they said they use ycsb test the memcached in udp ,so i think there are some ways to achieve it

**Comment by busbey** [comment]
What article specifically? If it doesn't mention a YCSB version used in the testing, it's possible they just worked off of a fork that never made it back to us.

**Comment by busbey** [comment]
Closing as stale. If you're interested in picking this back up, please submit a PR.
