### ISSUE TITLE
[Memcached] misbehavior when readallfields/writeallfields are false 

### ISSUE THREAD

**Issue by rizlik** [brianfrankcooper/YCSB#1153]
I think there are two issues here:

- When writeallfields is false ycsb-memcached replaces the object with one with just a single field (the one updated):
I don't see an easy fix here: to selectively update a single field we need to get the full object first and then store the updated one. This way we no longer measure updates but read+updates. 

- When readallfields is false the code return all but the requested fields:
https://github.com/brianfrankcooper/YCSB/blob/b7704ce4b6b453d15bf6ca55a9404ef45912d341/memcached/src/main/java/com/yahoo/ycsb/db/MemcachedClient.java#L270-L288
should  line L280 negate the check? (!fields.contain(value)).

This issue doesn't show up when dataintegrity is true: the verify code doesn't check that the fields returned are the ones requested:
https://github.com/brianfrankcooper/YCSB/blob/b7704ce4b6b453d15bf6ca55a9404ef45912d341/core/src/main/java/com/yahoo/ycsb/workloads/CoreWorkload.java#L682-L686

**Comment by busbey** [comment]
Sounds like we should fix the verification as a first step.

**Comment by busbey** [comment]
> should line L280 negate the check? (!fields.contain(value)).

Yeah I think so.

**Comment by busbey** [comment]
> When writeallfields is false ycsb-memcached replaces the object with one with just a single field (the one updated):
I don't see an easy fix here: to selectively update a single field we need to get the full object first and then store the updated one. This way we no longer measure updates but read+updates.

That's a consequence of the limitation around implementing storage as one big blob, right? If so, I think it's okay. If there's an alternate way to organize things so single field updates are less costly we could add that. It would help to show the trade-off involved.
