### ISSUE TITLE
YCSB load error

### ISSUE THREAD

**Issue by diogojfernandes** [brianfrankcooper/YCSB#1154]
Hello. 
I get this error when loading ArangoDB. Can anybody help me? 
Thanks in advance.

![image](https://user-images.githubusercontent.com/39376608/40421846-2b408fb4-5e85-11e8-84ff-972c9da649b4.png)

**Comment by busbey** [comment]
That looks like #908.

Please try running from a binary install.

**Comment by diogojfernandes** [comment]
How can I do that? Sorry, first time using YCSB and Git

**Comment by diogojfernandes** [comment]
Works on binaries.
