### ISSUE TITLE
Failed to create database and collection on running workload [duplicate name]

### ISSUE THREAD

**Issue by diogojfernandes** [brianfrankcooper/YCSB#1158]
After loading the workloada successfully, I tried to run it and got the errors:
"`failed to create database: ycsb`" and "`failed to create collection: usertable`" due to duplicate name.

![image](https://user-images.githubusercontent.com/39376608/40663020-b960bf66-634f-11e8-9698-335a7c3e4726.png)

Why does ycsb try to recreate a ycsb database and a usertable collection? Is it a normal message or does it affect the tests?

**Comment by busbey** [comment]
We generally leave it up to client bindings on how to handle collection / table / store creation. Usually I favor keeping all of that external to running YCSB.

Is this the ArangoDB client? If it reported successful read operations for workloada, I'd guess that the failure message about creation is benign. I agree that it'd be better to not have it.

**Comment by diogojfernandes** [comment]
Yes, it reported successful read operations. However, once we have to first load and then run the workload, I don't know why the run command also create the database/table.

**Comment by busbey** [comment]
it sounds like an error in our client binding for arangodb. any interest in putting together a PR to fix it? I think the ideal approach would be just removing the creation entirely in favor of instructions in the README about making it via ArangoDB tooling.

**Comment by diogojfernandes** [comment]
On README there's only the instruction to remove the usertable. However, that code does'nt work on command line with the error message "Unexpected token near 'usertable'". I have to manually delete the collection on ArangoDB interface.

**Comment by busbey** [comment]
you have to remove the usertable before you can do the "run" part of a workload?

**Comment by busbey** [comment]
As a part of the almost done 0.15.0 release the `arangodb` binding was updated and retested. Can you see if this is still an issue?

**Comment by busbey** [comment]
Closing as stale. Please reopen if you're still having trouble.
