### ISSUE TITLE
Just fill one byte in bytes buffer

### ISSUE THREAD

**Issue by liukun4515** [brianfrankcooper/YCSB#1159]
I'm confused in the class `RandomByteIterator`.
https://github.com/brianfrankcooper/YCSB/blob/master/core/src/main/java/com/yahoo/ycsb/RandomByteIterator.java#L35
In the constructor, we initialize the `buf` using the `fillBytesImpl` method, but the method of `fillBytesImpl` just fill one byte in the `buffer`.

```
  private void fillBytesImpl(byte[] buffer, int base) {
    int bytes = ThreadLocalRandom.current().nextInt();

    switch (buffer.length - base) {
    default:
      buffer[base + 5] = (byte) (((bytes >> 25) & 95) + ' ');
    case 5:
      buffer[base + 4] = (byte) (((bytes >> 20) & 63) + ' ');
    case 4:
      buffer[base + 3] = (byte) (((bytes >> 15) & 31) + ' ');
    case 3:
      buffer[base + 2] = (byte) (((bytes >> 10) & 95) + ' ');
    case 2:
      buffer[base + 1] = (byte) (((bytes >> 5) & 63) + ' ');
    case 1:
      buffer[base + 0] = (byte) (((bytes) & 31) + ' ');
    case 0:
      break;
    }
  }
```

**Comment by liukun4515** [comment]
@busbey

**Comment by busbey** [comment]
it relies on Java's case statement supporting fall-through.  so in the default case it fills in the bytes from base to base+5. If the space left in the buffer is less than 6 bytes, then it fills in up to that much.

**Comment by busbey** [comment]
hurm. actually there should probably be a guard in there to ensure base doesn't come in > buffer.length. or atleast a javadoc warning.

**Comment by busbey** [comment]
I guess a javadoc warning on the method would be enough since it'll already fail with `ArrayOutOfBoundsException` which is pretty clear. the side effect of consuming an int from ThreadLocalRandom is okay.

**Comment by liukun4515** [comment]
thanks for your reply.
I made a mistake and thought that echo case have **a break** in the end.
