### ISSUE TITLE
Please review Apache Ignite Client 

### ISSUE THREAD

**Issue by isuntsov-gridgain** [brianfrankcooper/YCSB#1165]
Guys,

I've created https://github.com/brianfrankcooper/YCSB/pull/1118 with [Apache Ignite](https://ignite.apache.org) Client on 29th of March. 
Could you please take a look at this PR?

**Comment by busbey** [comment]
hi!

At the moment all my YCSB time is going towards getting a 0.14.0 release out (#1117). Any help folks can provide in testing for that release will get me reviewing other contributions sooner.

That said, at the moment there are two different PRs for ignite support, #1118 and #1081. I've already started reviewing #1081 a few months ago, but it looks like things stalled out. It would substantially simplify the review process (and thus speed it up) if you and the author of that PR could come to a consensus on what should end up in YCSB.

**Comment by isuntsov-gridgain** [comment]
Thanks for your response!
You suggested a great plan. I've written a comment in https://github.com/brianfrankcooper/YCSB/pull/1081.

**Comment by isuntsov-gridgain** [comment]
@busbey 

Please take a look at this comment https://github.com/brianfrankcooper/YCSB/pull/1081#issuecomment-394735216
Let's continue with https://github.com/brianfrankcooper/YCSB/pull/1118

How can help you with 0.14.0?

**Comment by busbey** [comment]
great to hear!

The 0.14.0 release tracking issue #1117 has a link to the current Release Candidate as well as a recent (as of yesterday) list of things left to be tested. From that list I think any additional datastore binding tests will be nice-to-have and the windows testing will be need-to-have.

**Comment by isuntsov-gridgain** [comment]
@busbey I've finished work with the PR https://github.com/brianfrankcooper/YCSB/pull/1118. Please take a look.

**Comment by busbey** [comment]
thanks! I'll take a look later this coming weekend.

**Comment by isuntsov-gridgain** [comment]
Great! Thanks!

**Comment by isuntsov-gridgain** [comment]
@busbey did you have a chance to look at #1118? Maybe I can help you with current contribution testing?

**Comment by busbey** [comment]
Sadly not yet. Busy with the holiday week and day job. Should have time today or tomorrow.

**Comment by isuntsov-gridgain** [comment]
Got it. Thank you!

**Comment by busbey** [comment]
thanks for your patience!
