### ISSUE TITLE
[redis] There's no histogram in output file

### ISSUE THREAD

**Issue by hbstella92** [brianfrankcooper/YCSB#1170]
![screenshot from 2018-06-11 23-55-42](https://user-images.githubusercontent.com/31087197/41239673-a6c85a38-6dd3-11e8-9ffa-d1c00592319d.png)

I try to benchmark RocksDB with YCSB, but there's no binding code for RocksDB.
So, I attached ARDB(which uses redis protocol) on RocksDB.
And then, I use "mvn -pl com.yahoo.ycsb:redis-binding -am clean package" command to bind redis with YCSB.

But, when I do load/run with it, there's no histogram like
[UPDATE], 0, 464
[UPDATE], 1, 27
[UPDATE], 2, 0
[UPDATE], 3, 0
[UPDATE], 4, 0
...

What do I miss for binding RocksDB indirectly with YCSB??

**Comment by busbey** [comment]
Closing as stale. Please reopen if you're still having trouble.

**Comment by royforu** [comment]
add the following description in pom.xml in rocksdb  
<dependency>
      <groupId>org.apache.htrace</groupId>
      <artifactId>htrace-core4</artifactId>
      <version>4.1.0-incubating</version>
</dependency>
<dependency>
      <groupId>org.hdrhistogram</groupId>
      <artifactId>HdrHistogram</artifactId>
      <version>2.1.4</version>
</dependency>
it make it work
