### ISSUE TITLE
[hbase20] no slf4j implementation; hbase client doesn't log

### ISSUE THREAD

**Issue by busbey** [brianfrankcooper/YCSB#1173]
running through testing the `hbase20` binding, there's no logs from the client library (as there are in the earlier bindings).

```
Loading workload...
Starting test.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
```

Looks like the hbase 1.2 and hbase 1.4 shaded jars incorrectly included a dependency on the `slf4j-log4j12` bridge. so to have the same logging on the hbase 2.0 client we'll need to add it.

**Comment by sanxiago** [comment]
`curl -L -O 'https://search.maven.org/remotecontent?filepath=org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25.jar'`

Looks like the maven.org has a redirect, using -L gets to the actual jar.
