### ISSUE TITLE
Document behavior when operation count is not specified

### ISSUE THREAD

**Issue by awleblang** [brianfrankcooper/YCSB#1175]
When the operation count is not specified, ycsb runs until timeout. https://github.com/brianfrankcooper/YCSB/blob/0.13.0/core/src/main/java/com/yahoo/ycsb/Client.java#L452

This feels like something that should be documented here on the core properties wikipage for the operation count parameter https://github.com/brianfrankcooper/YCSB/wiki/Core-Properties

**Comment by busbey** [comment]
I've updated the core properties page to clarify the handling of 0 for operation count.
