### ISSUE TITLE
New to this forum

### ISSUE THREAD

**Issue by phemoski** [brianfrankcooper/YCSB#1180]
Please help, I need a guide on how to use any of the measuring metrics(histogram or time series) and where to get or print or see the metric after it has been issue at the command line. Pls it is urgent. Thanks

**Comment by lovengulu** [comment]
Start here: [Getting-Started](https://github.com/brianfrankcooper/YCSB/wiki/Getting-Started)

**Comment by busbey** [comment]
After that, the README for the mongodb support is particularly detailed:

https://github.com/brianfrankcooper/YCSB/blob/0.14.0/mongodb/README.md

**Comment by phemoski** [comment]
Txn so far, am able to unzip the ycsb and I tried to run it, but why do I have to run it with synchronous driver. Is this the next step after learning on getting started with ycsn. I ask this question bcos from the githup insrtuction, am able to start the mongod server and load the mongo client from the cmd line, but I don't no the next step to take, the aim of my project is to evaluate nosql datAbSes.

**Comment by busbey** [comment]
Please take a look at the [explanation of the core workloads that ship with YCSB](https://github.com/brianfrankcooper/YCSB/wiki/Core-Workloads)

**Comment by busbey** [comment]
Closing as stale. Please reopen if you're still having trouble.
