### ISSUE TITLE
ycsb load elasticsearch5-rest show error: argument database: invalid choice

### ISSUE THREAD

**Issue by aland-zhang** [brianfrankcooper/YCSB#1182]
ycsb version 0.14.0
According to this document: https://github.com/brianfrankcooper/YCSB/tree/master/elasticsearch5

./bin/ycsb load elasticsearch5-rest -P workloads/workloada ，
show error:
ycsb: error: argument database: invalid choice

**Comment by busbey** [comment]
it looks like maybe the python launcher is missing an entry for the rest version. can you try this instead:

`./bin/ycsb.sh load elasticsearch5-rest -P workloads/workloada`

**Comment by aland-zhang** [comment]
@busbey  thanks a lot !
