### ISSUE TITLE
[ignite, ignite-sql] clean up for apache ignite clients

### ISSUE THREAD

**Issue by busbey** [brianfrankcooper/YCSB#1183]
After the merge of #1118 here are some things to take care of in the Apache Ignite (incubating) clients, preferably before the next release.

Files missing a proper license header:

  * ignite/src/main/java/com/yahoo/ycsb/db/ignite/IgniteAbstractClient.java
  * ignite/src/main/resources/log4j2.xml
  * ignite/src/test/java/com/yahoo/ycsb/db/ignite/IgniteClientCommonTest.java

Files that still have \@author tags that need to be removed:

  * ignite/src/main/java/com/yahoo/ycsb/db/ignite/IgniteAbstractClient.java
  * ignite/src/main/java/com/yahoo/ycsb/db/ignite/IgniteClient.java
  * ignite/src/main/java/com/yahoo/ycsb/db/ignite/IgniteSqlClient.java

Need to confirm if copyright year is correct:

  * ignite/src/test/java/com/yahoo/ycsb/db/ignite/IgniteClientTest.java
  * ignite/src/test/java/com/yahoo/ycsb/db/ignite/IgniteSqlClientTest.java

from `ignite/README.md`
```
+### 2. Start Apache Ignite
+1.1 Download latest binary [Apache Ignite release](https://ignite.apache.org/download.cgi#binaries)
+
+1.2 Start ignite nodes using apache-ignite-fabric-2.5.0-bin/bin/**ignite.sh** ignite.xml
+
+1.3 Copy YCSB/ignite/target/ignite-binding-0.15.0-SNAPSHOT.jar to apache-ignite-fabric-2.5.0-bin/libs
+
```

Can we avoid copying things into the ignite installation?

```
+Run the workload test with IgniteClient:
...
+Run the workload test with IgniteSqlClient:
+
```

we should avoid referencing the internal classes and just use the binding names "ignite" and "ignite-sql".

from `ignite/pom.xml`
```
+  <repositories>
+    <repository>
+      <id>GridGain External Repository</id>
+      <url>http://www.gridgainsystems.com/nexus/content/repositories/external</url>
+    </repository>
+  </repositories>

```

I don't see any dependencies that specifically need this repository. Can we remove it?

from `ignite/src/main/java/com/yahoo/ycsb/db/ignite/IgniteClient.java`
```
+  @Override
+  public Status scan(String table, String startkey, int recordcount,
+                     Set<String> fields, Vector<HashMap<String, ByteIterator>> result) {
+    throw new UnsupportedOperationException("Scan method isn't implemented");
+  }
```

This should return `Status.NOT_IMPLEMENTED`

from `ignite/src/main/java/com/yahoo/ycsb/db/ignite/IgniteSqlClient.java`
```
+  /**
+      Unsupported operation.
+   */
+  @Override
+  public Status scan(String table, String startkey, int recordcount,
+                     Set<String> fields, Vector<HashMap<String, ByteIterator>> result) {
+    try {
+      return Status.OK;
+
+    } catch (Exception e) {
+      log.error(String.format("Error scanning with startkey: %s", startkey), e);
+
+      return Status.ERROR;
+    }
+
+  }
```

This should return `Status.NOT_IMPLEMENTED`

**Comment by busbey** [comment]
any chance you'd have time to work these things in the short term @isuntsov-gridgain ? I'd like to start the next release soon, but need these cleaned up first.

**Comment by isuntsov-gridgain** [comment]
Hi,

I'll take a look at this problem this evening.

сб, 14 июл. 2018 г., 8:34 Sean Busbey <notifications@github.com>:

**Comment by busbey** [comment]
awesome, thanks!

**Comment by isuntsov-gridgain** [comment]
@busbey please take a look at https://github.com/brianfrankcooper/YCSB/pull/1189
