### ISSUE TITLE
JDBC Binding does not support multiple host for failover

### ISSUE THREAD

**Issue by seybi87** [brianfrankcooper/YCSB#1184]
Hi guys,
I was trying to benchmark CockroachDB (using the JDBC binding and the PostgreSQL JDBC connector) with respect to node failures and I came across the following issue:

JDBC support multiple host in the connection String to enable failover, e.g.:
`jdbc:postgresql://host1:port1,host2:port2/database`

Yet, the current JDBC-binding epects multiple hosts only in the following form:  
`jdbc:postgresql://host1:port1/database,jdbc:postgresql://host2:port2/database`

And as the provided connection String is split by `","` to create multiple connections  (check the respsective line 198 [JDBC-Binding](https://github.com/brianfrankcooper/YCSB/blob/a9ad5b6f27c5b8cd9af7b97dc14d5fd4c4c98280/jdbc/src/main/java/com/yahoo/ycsb/db/JdbcDBClient.java#L198) ) this will result in an error for the failover connection String with multiple hosts.

Hence, the splitting identifier at line 198 should be changed to sth. which not conflicts with JDBC connection string chars.

I did a simple test by replacing `","` with `";"` and it worked without a problem for a failover connection String.

Would be great if you can apply this fix for upcoming releases

Cheers,
Daniel

**Comment by busbey** [comment]
Hi Daniel! do you have the time to put together a PR?

**Comment by seybi87** [comment]
Yes, I will try to do it within the next days.

**Comment by busbey** [comment]
Any progress?

**Comment by seybi87** [comment]
Sorry for coming back to this quite late.

Just submitted a [pull request](https://github.com/brianfrankcooper/YCSB/pull/1233)  to fix this issue

**Comment by busbey** [comment]
#1233 has been merged.
