### ISSUE TITLE
System error

### ISSUE THREAD

**Issue by phemoski** [brianfrankcooper/YCSB#1185]
pls help, I tried to use ycsb to load MongoDB to carry out the workloada andrecord count operation, I use the command; ycsb load mongodb -s -p workload/workloada -thread recordcount=10000000 -p
but I recieve the error message " the system cannot find the path mongodb". can you help please

**Comment by allanbank** [comment]
The command should look something like:

> ./bin/ycsb load mongodb -s -P workloads/workloada -threads 1 -p recordcount=10000000 

What was in your question was a little messed up.

**Comment by busbey** [comment]
@phemoski did this solve your issue?

**Comment by busbey** [comment]
Closing as stale. Please reopen if you're still having trouble.
