### ISSUE TITLE
"Could not initialize OrientDB connection pool for Loader"

### ISSUE THREAD

**Issue by diogojfernandes** [brianfrankcooper/YCSB#1190]
![image](https://user-images.githubusercontent.com/39376608/42755609-d4319f2e-88f0-11e8-808c-21a81b68c4ff.png)

**Comment by busbey** [comment]
It looks like the version of orientdb you're using no longer supports the "plocal" storage type.

Are you following a particular guide for running OrientDB? It should contain something about what URL you ought to use for connecting to the instance.

**Comment by busbey** [comment]
Closing as stale. Please reopen if you're still having trouble.
