### ISSUE TITLE
How can I debug YCSB source code?

### ISSUE THREAD

**Issue by meSmashsta** [brianfrankcooper/YCSB#1192]
How can I import YCSB to Eclipse or Intellij Community? Right now YCSB is opened in my Intellij and all I could see is jar files, any tips? It's using maven right?

**Comment by meSmashsta** [comment]
Ohhhhh, I might close this issue cause I just saw this [contributing guideline](https://github.com/brianfrankcooper/YCSB/blob/master/CONTRIBUTING.md). Will keep this open until I read the guidelines and got no further questions.

**Comment by busbey** [comment]
feel free to open additional issues with specific questions.

**Comment by busbey** [comment]
Please keep your new question on #1275
