### ISSUE TITLE
Issue in benchmarking graph databases.

### ISSUE THREAD

**Issue by Zaryab-Arif** [brianfrankcooper/YCSB#1194]
Hi,
I want to benhmark graph databases with YCSB. I am facing an issue to load the dataset. Is there anyone who can help me please? I am using Hypergraph, Infinitegraph and Infogrid.

**Comment by busbey** [comment]
As far as I can tell, we don't currently have supported bindings for any of those graph databases. What kind of issue are you having?

**Comment by Zaryab-Arif** [comment]
I have written java code for a client of hypergraphdb. Now what will be the
next step to perform benchmarking with YCSB?

**Comment by busbey** [comment]
Follow the guidelines for running the standard workload set using your client.

https://github.com/brianfrankcooper/YCSB/wiki/Core-Workloads

For help on running a particular workload:

https://github.com/brianfrankcooper/YCSB/wiki/Running-a-Workload

**Comment by Zaryab-Arif** [comment]
Okay :)

**Comment by busbey** [comment]
Did following the guides work?

**Comment by Zaryab-Arif** [comment]
Yes. I'll update in a couple of days.

On Aug 17, 2018 5:30 AM, "Sean Busbey" <notifications@github.com> wrote:

Did following the guides work?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/brianfrankcooper/YCSB/issues/1194#issuecomment-413723204>,
or mute the thread

**Comment by risdenk** [comment]
Closing due to no further update and sounds like it worked.

**Comment by biqar** [comment]
I don't think it worked. It is mentioned on the page: `"The goal of the YCSB project is to develop a framework and common set of workloads for evaluating the performance of different “key-value” and “cloud” serving stores."` How can a `key-value` database benchmark system possibly work on a Graph Database (GDB)?

However, benchmarking a GDB is still not very clear to me. Possibly running different graph analytics could be an option. Also, using YCSB to benchmark a GDB is still an open-ended question.
