### ISSUE TITLE
Issue in adding hypergraph db 

### ISSUE THREAD

**Issue by Zaryab-Arif** [brianfrankcooper/YCSB#1195]
Hi,

I want to benchmark hypergraph db with ycsb. But i am unable to understand how i can add in ycsb?

**Comment by busbey** [comment]
Please take a look at [our guide for adding a new database](https://github.com/brianfrankcooper/YCSB/wiki/Adding-a-Database). You will need to do some Java coding.

**Comment by busbey** [comment]
Closing as stale. Please reopen if you're still having trouble.
