### ISSUE TITLE
Error on running YCSB with SCAN operations on ArangoDB

### ISSUE THREAD

**Issue by diogojfernandes** [brianfrankcooper/YCSB#1197]
Everytime I run a workload with SCAN operations it crashes. For example on workload E, where is 95% SCAN and 5% INSERT, I tried with 100% SCAN and it crashed, I tried with 100% INSERT and it worked.

I can't run any workload with SCAN operations, being 1% or 100%.

Edit: I'm testing with ArangoDB and OrientDB and it just fails on ArangoDB.

**Comment by busbey** [comment]
Any ideas on what could be going wrong here @mpv1989?

**Comment by busbey** [comment]
Closing as stale. Please reopen if you're still having trouble.
