### ISSUE TITLE
How can I import YCSB in Eclipse?

### ISSUE THREAD

**Issue by meSmashsta** [brianfrankcooper/YCSB#1198]

**Comment by meSmashsta** [comment]
I got it working on IntelliJ, but man, it would really be nice if I could also make it work using Eclipse...

**Comment by busbey** [comment]
does using Eclipse's normal method of importing a maven project give a specific error?

**Comment by meSmashsta** [comment]
From what I remember 15 days ago, it does not have. But I will try again and report back here of my findings.

**Comment by busbey** [comment]
Closing as stale. Please reopen if you're still having trouble.

**Comment by akshat-khare** [comment]
> I got it working on IntelliJ, but man, it would really be nice if I could also make it work using Eclipse...

@meSmashsta how you made it work with intellij. I am not able to add a main class.
