### ISSUE TITLE
Difference between recordcount, operationcount and insertcount parametres

### ISSUE THREAD

**Issue by ssizmaster** [brianfrankcooper/YCSB#1206]
Hi,
Please, what is the difference between **recordcount**, **operationcount** and **insertcount** parametres.
Thanks in advance.

**Comment by busbey** [comment]
* record count  - how many records YCSB assumes are present or will be present in the backing data store
* operation count - how many workload operations YCSB should perform (scan / read / whatever according to the % breakdown in the workload)
* insert count - how many records a particular YCSB client ought to insert during a load phase.

**Comment by ssizmaster** [comment]
Thank you for you response.

**Comment by busbey** [comment]
happy to help! feel free to file another issue if you have more questions.

**Comment by Dhrumilsoni** [comment]
If operationcount is 0, does that mean no operations are performed altogether?

Also, is there any command-line argument that can change this value during the execution of ycsb client?
