### ISSUE TITLE
ycsb outputs values

### ISSUE THREAD

**Issue by burakcemkara** [brianfrankcooper/YCSB#1208]
I am reading a lot of theses used ycbs bencmarkig in comparing nosql database systems(mongo db cassandara,Hbase vs) but i still dont understand something

for example;
1)author of one's thesis , load 1000, 000 records into each system(mongo db cassandara,Hbase vs) and he writes his results on  "load phase" table but as you can see in the screenshot below,
he load records for each programs(mongo db cassandara, vs) and he also did this for each workloads(A,B,C,D,E,F) and finally he has 6 throughputs and 6 latency values for each workload but how and why only one  throughputs and latency values he writing tables?
This stiuation is not only about this thesis, i saw all of thesis

![load phase](https://user-images.githubusercontent.com/38786955/43477384-b84d67d8-9503-11e8-8851-fe2b3c856b61.PNG)

2)author in the same thesis,  load 1000, 000 records into each system(mongo db cassandara vs) and he took one load output text and one run output text for  workload A but he writes  5 throughputs and 5 latency values results on table but i think there must be only one avarage latency value, one throughput value for  worklad A inside output run text, so let me understand  ,how and where he find 5 latency value, 5 throughput value foe workload A  inside output run text?

![workload a update](https://user-images.githubusercontent.com/38786955/43480247-6a01092e-950b-11e8-9a67-4ec5bcc22851.PNG)

**Comment by busbey** [comment]
The core workloads all use the same shape of data, so many users will do a single load and then reuse it for multiple workloads. You can see our recommended practice for this in the ["running the workloads" section of the Core Workload documentation](https://github.com/brianfrankcooper/YCSB/wiki/Core-Workloads#running-the-workloads). In that set up you usually do two loads, but I wouldn't be surprised if folks just used the first one.

**Comment by busbey** [comment]
Closing as stale. If you have more questions feel free to reopen.
