### ISSUE TITLE
Parallel run for different Workloads

### ISSUE THREAD

**Issue by ssizmaster** [brianfrankcooper/YCSB#1209]
HI,

I would run different Workloads (A, C And G) parallel environment.
For load phase I have used this command:

1.  **First client**
bin/ycsb load hbase12 -P workloads/workloada  -p columnfamily=cf  -p table=usertable -p insertstart=0 -p insertcount=500 > workloada_res.txt

2. **Second client**
bin/ycsb load hbase12 -P workloads/workloada  -p columnfamily=cf  -p table=usertable -p insertstart=500 -p insertcount=500 > workloada_res.txt

It's worked nicely
Now we have 1000 records

For the run phase, how we can perform the run command in parallel clients for Workload A (50/50 reads and writes), Workload C(100% read) and Workload G(100% update)
I read this #674 but I don't understand how to do it.
Thank you in advance.

**Comment by busbey** [comment]
oof. it's too bad #674 didn't get a good write up in the 0.9.0 release notes or an update to the docs on parallel runs.

None of those workloads do inserts (I don't see Workload G in our definitions, but I'm presuming an update isn't an upsert). I think that means you can just run the two clients and tell each to do half of the total `operationcount` you want used.

**Comment by ssizmaster** [comment]
Thank you for this clarification.
For parallel run of MySQL workloads. I have installed MySQL servers in each node and then I have split the load and run phases into each node.
Is this method right for MySQL?

**Comment by busbey** [comment]
are the mysql servers in cluster mode or are they independent? in the simplest case you'd test MySQL in parallel by pointing the multiple clients at a single MySQL server.

**Comment by ssizmaster** [comment]
>  in the simplest case you'd test MySQL in parallel by pointing the multiple clients at a single MySQL server.
Thank you very much for your valuable response.

**Comment by busbey** [comment]
everything working now?

**Comment by ssizmaster** [comment]
Yes, thank you very much.
