### ISSUE TITLE
[READ-FAILED] during HBase YCSB Benchmarking

### ISSUE THREAD

**Issue by ssizmaster** [brianfrankcooper/YCSB#1210]
Hi,

I am using CDH 5.15.0 and through that installed HBase 1.2. I have made the load phase by using this command:

`bin/ycsb load hbase12 -P workloads/workloada  -p columnfamily=cf -p table=usertable100k  -p recordcount=100000 -p zeropadding=5 -p insertorder=ordered > workloada_load_100k_hbase.txt` 

but when i run the workload A by using this command :

`bin/ycsb run hbase12 -P workloads/workloada  -p columnfamily=cf -p table=usertable100k -p operationcount=10000 -p recordcount=100000 > run_workloadA_Op-10k_Rcr-100K_hbase.txt`

But its giving output as follows where near about 75% reads are failing :

[OVERALL], RunTime(ms), 11652
[OVERALL], Throughput(ops/sec), 858.2217645039478
[TOTAL_GCS_PS_Scavenge], Count, 3
[TOTAL_GC_TIME_PS_Scavenge], Time(ms), 50
[TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.4291108822519739
[TOTAL_GCS_PS_MarkSweep], Count, 0
[TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 0
[TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.0
[TOTAL_GCs], Count, 3
[TOTAL_GC_TIME], Time(ms), 50
[TOTAL_GC_TIME_%], Time(%), 0.4291108822519739
[READ], Operations, 1237
[READ], AverageLatency(us), 585.8108326596605
[READ], MinLatency(us), 245
[READ], MaxLatency(us), 9615
[READ], 95thPercentileLatency(us), 827
[READ], 99thPercentileLatency(us), 1150
[READ], Return=OK, 1237
[READ], Return=NOT_FOUND, 3790
[CLEANUP], Operations, 2
[CLEANUP], AverageLatency(us), 22896.5
[CLEANUP], MinLatency(us), 17
[CLEANUP], MaxLatency(us), 45791
[CLEANUP], 95thPercentileLatency(us), 45791
[CLEANUP], 99thPercentileLatency(us), 45791
[READ-FAILED], Operations, 3790
[READ-FAILED], AverageLatency(us), 525.877308707124
[READ-FAILED], MinLatency(us), 166
[READ-FAILED], MaxLatency(us), 134911
[READ-FAILED], 95thPercentileLatency(us), 739
[READ-FAILED], 99thPercentileLatency(us), 1029
[UPDATE], Operations, 4973
[UPDATE], AverageLatency(us), 1489.6780615322743
[UPDATE], MinLatency(us), 725
[UPDATE], MaxLatency(us), 71359
[UPDATE], 95thPercentileLatency(us), 2253
[UPDATE], 99thPercentileLatency(us), 2983
[UPDATE], Return=OK, 4973

But when I remove the   "zeropadding=5" and  "insertorder=ordered" parameters from the load phase everything works well.

Appreciate your help on this

Thanks,

**Comment by busbey** [comment]
how many rows / cells does the hbase shell show are in the table?

**Comment by ssizmaster** [comment]
hbase shell shows that the table has 100000 rows and 10 fields

**Comment by busbey** [comment]
in that case did the YCSB client log include any error information during the run? do the hbase region server logs show any issues during the run?

**Comment by busbey** [comment]
your run command has to also specify `-p insertorder=ordered` or else the keys generated for reading will get run through the hash funciton and thus pick keys that weren't in the original load.

**Comment by ssizmaster** [comment]
I have added the "insertorder=ordered" parameter in the run command and  its giving output as follows:

```
[OVERALL], RunTime(ms), 13370
[OVERALL], Throughput(ops/sec), 747.9431563201197
[TOTAL_GCS_PS_Scavenge], Count, 6
[TOTAL_GC_TIME_PS_Scavenge], Time(ms), 74
[TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.5534779356768885
[TOTAL_GCS_PS_MarkSweep], Count, 0
[TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 0
[TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.0
[TOTAL_GCs], Count, 6
[TOTAL_GC_TIME], Time(ms), 74
[TOTAL_GC_TIME_%], Time(%), 0.5534779356768885
[READ], Operations, 4649
[READ], AverageLatency(us), 712.2976984297699
[READ], MinLatency(us), 273
[READ], MaxLatency(us), 161023
[READ], 95thPercentileLatency(us), 1070
[READ], 99thPercentileLatency(us), 1496
[READ], Return=OK, 4649
[READ], Return=NOT_FOUND, 323
[CLEANUP], Operations, 2
[CLEANUP], AverageLatency(us), 30515.5
[CLEANUP], MinLatency(us), 23
[CLEANUP], MaxLatency(us), 61023
[CLEANUP], 95thPercentileLatency(us), 61023
[CLEANUP], 99thPercentileLatency(us), 61023
[UPDATE], Operations, 5028
[UPDATE], AverageLatency(us), 1647.5115354017503
[UPDATE], MinLatency(us), 630
[UPDATE], MaxLatency(us), 73471
[UPDATE], 95thPercentileLatency(us), 2253
[UPDATE], 99thPercentileLatency(us), 2937
[UPDATE], Return=OK, 5028
[READ-FAILED], Operations, 323
[READ-FAILED], AverageLatency(us), 553.0835913312693
[READ-FAILED], MinLatency(us), 241
[READ-FAILED], MaxLatency(us), 1923
[READ-FAILED], 95thPercentileLatency(us), 842
[READ-FAILED], 99thPercentileLatency(us), 1127
```

And this is  the output of the YCSB client when i execute the run command :

```
[WARN]  Running against a source checkout. In order to get our runtime dependencies we'll have to invoke Maven. Depending on the state of your system, this may take ~30-45 seconds
[DEBUG]  Running 'mvn -pl com.yahoo.ycsb:hbase12-binding -am package -DskipTests dependency:build-classpath -DincludeScope=compile -Dmdep.outputFilterFile=true'
/usr/lib/jvm/java-8-openjdk-amd64/bin/java -cp /home/researcher-m1/YCSB/hbase12/conf:/home/researcher-m1/YCSB/hbase12/target/hbase12-binding-0.16.0-SNAPSHOT.jar:/home/researcher-m1/.m2/repository/org/apache/htrace/htrace-core4/4.1.0-incubating/htrace-core4-4.1.0-incubating.jar:/home/researcher-m1/.m2/repository/com/github/stephenc/findbugs/findbugs-annotations/1.3.9-1/findbugs-annotations-1.3.9-1.jar:/home/researcher-m1/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.4/HdrHistogram-2.1.4.jar:/home/researcher-m1/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar:/home/researcher-m1/.m2/repository/org/apache/htrace/htrace-core/3.1.0-incubating/htrace-core-3.1.0-incubating.jar:/home/researcher-m1/.m2/repository/org/apache/hbase/hbase-shaded-client/1.2.5/hbase-shaded-client-1.2.5.jar:/home/researcher-m1/.m2/repository/org/slf4j/slf4j-log4j12/1.6.1/slf4j-log4j12-1.6.1.jar:/home/researcher-m1/YCSB/hbase10/target/hbase10-binding-0.16.0-SNAPSHOT.jar:/home/researcher-m1/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.4/jackson-core-asl-1.9.4.jar:/home/researcher-m1/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/home/researcher-m1/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar:/home/researcher-m1/YCSB/core/target/core-0.16.0-SNAPSHOT.jar:/home/researcher-m1/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.4/jackson-mapper-asl-1.9.4.jar com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.hbase12.HBaseClient12 -P workloads/workloada -p columnfamily=cf -p table=usertable100k -p insertorder=ordered -p operationcount=10000 -p recordcount=100000 -t
Command line: -db com.yahoo.ycsb.db.hbase12.HBaseClient12 -P workloads/workloada -p columnfamily=cf -p table=usertable100k -p insertorder=ordered -p operationcount=10000 -p recordcount=100000 -t
YCSB Client 0.16.0-SNAPSHOT

Loading workload...
log4j:WARN No appenders could be found for logger (org.apache.htrace.core.Tracer).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Starting test.
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []`
```

And this is the last operations in the log : /var/log/hbase/hbase-cmf-hbase-REGIONSERVER-master1.log.out

```
2018-08-12 04:22:33,984 INFO SecurityLogger.org.apache.hadoop.hbase.Server: Auth successful for hbase (auth:SIMPLE)
2018-08-12 04:22:33,985 INFO SecurityLogger.org.apache.hadoop.hbase.Server: Connection from 192.168.1.10 port: 37146 with version info: version: "1.2.0-cdh5.15.0" url: "file:///data/jenkins/workspace/generic-package-ubuntu64-14-04/CDH5.15.0-Packaging-HBase-2018-05-24_04-02-57/hbase-1.2.0+cdh5.15.0+461-1.cdh5.15.0.p0.52~trusty" revision: "Unknown" user: "jenkins" date: "Thu May 24 04:34:50 PDT 2018" src_checksum: "64eb1d7b2349843fda1e9617c9689e94"
2018-08-12 04:23:23,805 INFO SecurityLogger.org.apache.hadoop.hbase.Server: Auth successful for researcher-m1 (auth:SIMPLE)
2018-08-12 04:23:23,810 INFO SecurityLogger.org.apache.hadoop.hbase.Server: Connection from 192.168.1.10 port: 37234 with version info: version: "1.2.5" url: "git://asf-dev/home/busbey/projects/hbase" revision: "d7b05f79dee10e0ada614765bb354b93d615a157" user: "busbey" date: "Wed Mar  1 00:34:48 CST 2017" src_checksum: "5f0b6bf70e891eb3b315a1559f0a1c62"
```

**Comment by busbey** [comment]
could you run from a YCSB release instead of a source checkout? that'll make it easier to track what's going on back to source code.

**Comment by ssizmaster** [comment]
I have resolved the problem by adding  "zeropadding=5" parameter to the run command.
Thank you @busbey  for your assistance.

**Comment by busbey** [comment]
Happy to help!
