### ISSUE TITLE
run YCSB on redis with an error

### ISSUE THREAD

**Issue by kaiwu1121** [brianfrankcooper/YCSB#1218]
Hi, I am trying to run YCSB to redis. I test the connection with redis.
./bin/ycsb shell redis -p redis.host=localhost -p redis.port=6379
it shows connected.
But when I try to run command './bin/ycsb load redis -s -P workloads/workloada -p "redis.host=127.0.0.1" -p "redis.port=6379" > /home/cc/appResults/load.log'

I get an error as follow:
[WARN]  Running against a source checkout. In order to get our runtime dependencies we'll have to invoke Maven. Depending on the state of your system, this may take ~30-45 seconds
[DEBUG]  Running 'mvn -pl com.yahoo.ycsb:redis-binding -am package -DskipTests dependency:build-classpath -DincludeScope=compile -Dmdep.outputFilterFile=true'
/usr/lib/jvm/java-8-oracle/bin/java -cp /home/cc/YCSB/redis/conf:/home/cc/YCSB/redis/target/redis-binding-0.16.0-SNAPSHOT.jar:/home/cc/.m2/repository/org/apache/htrace/htrace-core4/4.1.0-incubating/htrace-core4-4.1.0-incubating.jar:/home/cc/YCSB/core/target/core-0.16.0-SNAPSHOT.jar:/home/cc/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.4/HdrHistogram-2.1.4.jar:/home/cc/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.4/jackson-mapper-asl-1.9.4.jar:/home/cc/.m2/repository/redis/clients/jedis/2.9.0/jedis-2.9.0.jar:/home/cc/.m2/repository/org/apache/commons/commons-pool2/2.4.2/commons-pool2-2.4.2.jar:/home/cc/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.4/jackson-core-asl-1.9.4.jar com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.RedisClient -s -P workloads/workloada -p redis.host=127.0.0.1 -p redis.port=6379 -load
Command line: -db com.yahoo.ycsb.db.RedisClient -s -P workloads/workloada -p redis.host=127.0.0.1 -p redis.port=6379 -load
YCSB Client 0.16.0-SNAPSHOT

Loading workload...
Starting test.
2018-08-19 22:59:12:295 0 sec: 0 operations; est completion in 0 second
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
redis.clients.jedis.exceptions.JedisDataException: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
        at redis.clients.jedis.Protocol.processError(Protocol.java:127)
        at redis.clients.jedis.Protocol.process(Protocol.java:161)
        at redis.clients.jedis.Protocol.read(Protocol.java:215)
        at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
        at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:239)
        at redis.clients.jedis.Jedis.hmset(Jedis.java:705)
        at com.yahoo.ycsb.db.RedisClient.insert(RedisClient.java:139)
        at com.yahoo.ycsb.DBWrapper.insert(DBWrapper.java:221)
        at com.yahoo.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:588)
        at com.yahoo.ycsb.ClientThread.run(Client.java:468)
        at java.lang.Thread.run(Thread.java:748)

Anyone knows why this happen? Thanks.

**Comment by busbey** [comment]
I believe that by default the shell doesn't do anything to connect to a datastore until you give it a command to run.

Could you try running from the 0.15.0 release so that we can eliminate the possibility of something going wrong with running from a source checkout?

The error mentions a redis log; what does it show?

**Comment by busbey** [comment]
Closing as stale. If you're still having an issue please reopen with some of the details previously mentioned.
