### ISSUE TITLE
JDBC binding does not support reWriteBatchedInserts

### ISSUE THREAD

**Issue by robert-s-lee** [brianfrankcooper/YCSB#1219]
Some JDBC drivers can transform batch inserts into significantly faster multi-insert statements using the following connection parameter:

- rewriteBatchedStatements for MySQL 
- reWriteBatchedInserts Postgres

However, using this technique returns `SUCCESS_NO_INFO` instead of `1` in `int[] results = insertStatement.executeBatch();` causing the insert to fail.

**Comment by busbey** [comment]
interesting. do you have time to put together a PR to modify as needed?

**Comment by robert-s-lee** [comment]
Sure.  Tested a patch on CockroachDB which uses Postgres JDBC driver and yielded 10x performance gain.  Will try a test on regular MySQL and Postgres and submit the PR.

**Comment by busbey** [comment]
closed by #1220
