### ISSUE TITLE
issue in YCSB

### ISSUE THREAD

**Issue by AhmadZia1991** [brianfrankcooper/YCSB#1221]
hello everyone, I am trying to compare 3 key-value NoSQL databases, I installed YCSB , but there is a code that I don't know. where to write this code please help me.

./bin/ycsb load redis -s -P workloads/workloada -p "redis.host=127.0.0.1" -p "redis.port=6379" > outputLoad.txt

**Comment by busbey** [comment]
Have you downloaded version 0.15.0 of YCSB or some other version?

Are you trying to run things on a Windows machine or Linux (or something else)?

Where is your Redis instance set up?

**Comment by AhmadZia1991** [comment]
dear sir,
thank you so much for your reply.
yes sir i have download version  0.15.0 of YCSB, and i am working on Linux
ubuntu18.04 , and i download and install Redis through terminal that is
it, after that its not clear to me what to do? please help me regarding
this.

thanks .

**Comment by busbey** [comment]
Once your Redis instance is set up, take a look at step 4 and 5 in the README for the YCSB client for Redis:

https://github.com/brianfrankcooper/YCSB/blob/0.15.0/redis/README.md

The example commands given there are all run from the directory you've installed YCSB into.

**Comment by busbey** [comment]
Did the above have enough information for you to be able to run against Redis?

**Comment by AhmadZia1991** [comment]
done tnx
