### ISSUE TITLE
adding hash key in dynamodb causes hot partition issue

### ISSUE THREAD

**Issue by flint-dominic** [brianfrankcooper/YCSB#1222]
If you use HASH_AND_RANGE as KeyType, it will cause the hot partition issue and not give you an accurate performance.  This is because every partition key ends up being the same.  To fix, 'hashKeyValue' needs to be randomized.  This needed to be randomized in inserts and updates.

**Comment by busbey** [comment]
Thanks for the report. Any interest in putting together a PR?

**Comment by flint-dominic** [comment]
Yes, I can, I've got some preliminary code working using Utils.

**Comment by flint-dominic** [comment]
this ended up being as designed, just not explained well.
