### ISSUE TITLE
running ycsb

### ISSUE THREAD

**Issue by AhmadZia1991** [brianfrankcooper/YCSB#1229]
while i m giving command ( mvn clean package ) i received the following error
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.yahoo.ycsb.db.accumulo.AccumuloTest
2018/09/11 13:31:19 WARN  org.apache.accumulo.core.client.impl.ServerClient  - There are no tablet servers: check that zookeeper and accumulo are running.

any knows how to solve that ?

**Comment by busbey** [comment]
What's your platform and what's your Maven version?

If you aren't customizing YCSB internals or adding a new data store binding then you shouldn't need to build things yourself. Download one of our convenience binary tarballs from the releases page instead.

https://github.com/brianfrankcooper/YCSB/releases/latest

i.e. the general purpose tarball for 0.15.0:

https://github.com/brianfrankcooper/YCSB/releases/download/0.15.0/ycsb-0.15.0.tar.gz

**Comment by meSmashsta** [comment]
What is your OS @AhmadZia1991 ? If you're using Windows and wants to build from source it's not a good idea, I suggest switching to Ubuntu like I did.

**Comment by AhmadZia1991** [comment]
Sir i am also using ubuntu i tried to run it without mvn package but still
i receiced the sam msg error of slf4g and i am not able to receive result.

**Comment by meSmashsta** [comment]
For the moment, here's the workaround:

mvn clean install -DskipTests
