### ISSUE TITLE
when  run workloade with hbase12 ,why does option '-p recordcount= ' have a big impact on result? 

### ISSUE THREAD

**Issue by adally** [brianfrankcooper/YCSB#1230]
It puzzled me to get the following result, why?
1.100% insert operation will not cause high CPU utilization.
2.100% scan operation will not cause high CPU utilization.
3.run workloade which has mixed insert/scan operation with adding option ‘-p recordcount= ’ will not cause high CPU utilization.
4.run workloade which has mixed insert/scan operation without adding option ‘-p recordcount= ’ will cause high CPU utilization.
5.When run workloade long time ，the CPU utilization will drop gradually and the performance came close to the one added option "-p recordcount".

Note:I run hadoop and hbase in a machine, and ycsb in another machine. It's that ycsb not hbase caused the cpu high. 
ycsb Version :0.14.0
Hbase version:1.2.6.1
Hadoop version:2.7.1
Distributed mode :pseudo-Distributed
Hbase and Hadoop configuration appended at the end.

 I got the above conclusions by  running the following commands 
1. 

./bin/ycsb run hbase12  -p operationcount=150000000 -P ./workloads/workloade -p table=test -p columnfamily=f1 -threads 128  -p  maxexecutiontime=60

[OVERALL], RunTime(ms), 60136
[OVERALL], Throughput(ops/sec), 598.6763336437408
[TOTAL_GCS_PS_Scavenge], Count, 60
[TOTAL_GC_TIME_PS_Scavenge], Time(ms), 198
[TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.3292536916323001
[TOTAL_GCS_PS_MarkSweep], Count, 1
[TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 84
[TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.13968338432885458
[TOTAL_GCs], Count, 61
[TOTAL_GC_TIME], Time(ms), 282
[TOTAL_GC_TIME_%], Time(%), 0.46893707596115475
[CLEANUP], Operations, 256
[CLEANUP], AverageLatency(us), 154.96875
[CLEANUP], MinLatency(us), 1
[CLEANUP], MaxLatency(us), 31183
[CLEANUP], 95thPercentileLatency(us), 26
[CLEANUP], 99thPercentileLatency(us), 306
[INSERT], Operations, 1889
[INSERT], AverageLatency(us), 54992.90100582319
[INSERT], MinLatency(us), 1104
[INSERT], MaxLatency(us), 511487
[INSERT], 95thPercentileLatency(us), 107967
[INSERT], 99thPercentileLatency(us), 149887
[INSERT], Return=OK, 1889
[SCAN], Operations, 34113
[SCAN], AverageLatency(us), 131474.4396857503
[SCAN], MinLatency(us), 810
[SCAN], MaxLatency(us), 1048575
[SCAN], 95thPercentileLatency(us), 239615
[SCAN], 99thPercentileLatency(us), 408319
[SCAN], Return=OK, 34113

2.workloade1 is modified according to workloade,just the operation ratio is different,which has 100% scan operation .
./bin/ycsb run hbase12  -p operationcount=150000000 -P ./workloads/workloade1 -p table=test -p columnfamily=f1 -threads 128  -p  maxexecutiontime=60

[OVERALL], RunTime(ms), 60059
[OVERALL], Throughput(ops/sec), 6309.012804075992
[TOTAL_GCS_PS_Scavenge], Count, 69
[TOTAL_GC_TIME_PS_Scavenge], Time(ms), 287
[TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.4778634342896152
[TOTAL_GCS_PS_MarkSweep], Count, 1
[TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 73
[TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.12154714530711466
[TOTAL_GCs], Count, 70
[TOTAL_GC_TIME], Time(ms), 360
[TOTAL_GC_TIME_%], Time(%), 0.5994105795967298
[CLEANUP], Operations, 256
[CLEANUP], AverageLatency(us), 98.125
[CLEANUP], MinLatency(us), 0
[CLEANUP], MaxLatency(us), 22543
[CLEANUP], 95thPercentileLatency(us), 15
[CLEANUP], 99thPercentileLatency(us), 49
[SCAN], Operations, 378913
[SCAN], AverageLatency(us), 19825.725285223783
[SCAN], MinLatency(us), 742
[SCAN], MaxLatency(us), 1458175
[SCAN], 95thPercentileLatency(us), 34623
[SCAN], 99thPercentileLatency(us), 43935
[SCAN], Return=OK, 378913
3.workloade2 is modified according to workloade,just the operation ratio is different,which has 100%  insert operation .

./bin/ycsb run hbase12  -p operationcount=150000000 -P ./workloads/workloade2 -p table=test -p columnfamily=f1 -threads 128  -p  maxexecutiontime=60

[OVERALL], RunTime(ms), 60728
[OVERALL], Throughput(ops/sec), 18321.416809379527
[TOTAL_GCS_PS_Scavenge], Count, 40
[TOTAL_GC_TIME_PS_Scavenge], Time(ms), 175
[TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.28817020155447237
[TOTAL_GCS_PS_MarkSweep], Count, 1
[TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 59
[TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.09715452509550784
[TOTAL_GCs], Count, 41
[TOTAL_GC_TIME], Time(ms), 234
[TOTAL_GC_TIME_%], Time(%), 0.38532472664998024
[CLEANUP], Operations, 256
[CLEANUP], AverageLatency(us), 2837.48046875
[CLEANUP], MinLatency(us), 1
[CLEANUP], MaxLatency(us), 684543
[CLEANUP], 95thPercentileLatency(us), 72
[CLEANUP], 99thPercentileLatency(us), 4931
[INSERT], Operations, 1112623
[INSERT], AverageLatency(us), 6744.665873346138
[INSERT], MinLatency(us), 443
[INSERT], MaxLatency(us), 750079
[INSERT], 95thPercentileLatency(us), 13599
[INSERT], 99thPercentileLatency(us), 18751
[INSERT], Return=OK, 1112623

4.When run Workloade  with option “-p recordcount=5000000” added , cpu utilization is get lower and the results is good.

./bin/ycsb run hbase12  -p operationcount=150000000 -P ./workloads/workloade   -p table=test -p columnfamily=f1 -threads 128  -p  maxexecutiontime=60 -p recordcount=5000000

OVERALL], Throughput(ops/sec), 6711.068200356233
[TOTAL_GCS_PS_Scavenge], Count, 83
[TOTAL_GC_TIME_PS_Scavenge], Time(ms), 331
[TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.5509962878497827
[TOTAL_GCS_PS_MarkSweep], Count, 1
[TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 117
[TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.19476303830339753
[TOTAL_GCs], Count, 84
[TOTAL_GC_TIME], Time(ms), 448
[TOTAL_GC_TIME_%], Time(%), 0.7457593261531803
[CLEANUP], Operations, 256
[CLEANUP], AverageLatency(us), 168.296875
[CLEANUP], MinLatency(us), 2
[CLEANUP], MaxLatency(us), 22271
[CLEANUP], 95thPercentileLatency(us), 39
[CLEANUP], 99thPercentileLatency(us), 5571
[INSERT], Operations, 20218
[INSERT], AverageLatency(us), 6515.05247798991
[INSERT], MinLatency(us), 515
[INSERT], MaxLatency(us), 383743
[INSERT], 95thPercentileLatency(us), 14287
[INSERT], 99thPercentileLatency(us), 17151
[INSERT], Return=OK, 20218
[SCAN], Operations, 382936
[SCAN], AverageLatency(us), 19260.245218522155
[SCAN], MinLatency(us), 692
[SCAN], MaxLatency(us), 419839
[SCAN], 95thPercentileLatency(us), 30671
[SCAN], 99thPercentileLatency(us), 42719
[SCAN], Return=OK, 382936

hbase-site.xml

<configuration>
   <property>
      <name>hbase.rootdir</name>
      <value>hdfs://node1:9000/hbase</value>
   </property>
   <property>
      <name>hbase.cluster.distributed</name>
      <value>true</value>
   </property>
   <property>
      <name>hbase.zookeeper.quorum</name>
      <value>node1</value>
   </property>
 <property>
   <name>hbase.zookeeper.property.clientPort</name>
      <value>2181</value>
   </property>
  <property>
   <name>hbase.tmp.dir</name>
      <value>/var/lib/hbase/hbase_tmp</value>
   </property>
</configuration> 

core-site.xml
<configuration>
 <property>
      <name>hadoop.tmp.dir</name>
      <value>file:/var/lib/hbase/hadoop/tmp</value>
   </property>
   <property>
      <name>fs.defaultFS</name>
      <value>hdfs://node1:9000</value>
   </property>
</configuration>

hdfs-site.xml

<configuration>
<property>
      <name>dfs.replication</name>
      <value>1</value>
   </property>
   <property>
      <name>dfs.namenode.name.dir</name>
      <value>file:/var/lib/hbase/hadoop/dfs/name</value>
   </property>
   <property>
      <name>dfs.datanode.data.dir</name>
      <value>file:/var/lib/hbase/hadoop/dfs/data</value>
   </property>
</configuration>

**Comment by busbey** [comment]
Is the issue that you're seeing a spike in CPU from the YCSB client itself?

Have you run a profiler against it to see where you're spending time?

**Comment by adally** [comment]
I run top to see that most of the cpu is occupied by ycsb. I run the commad :
./bin/ycsb run hbase12  -p operationcount=150000000 -P ./workloads/workloade   -p table=test -p columnfamily=f1 -threads 128  -p  maxexecutiontime=60
The CPU has 48 cores.
Get the following things:
   PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
136721 root      20   0   57.0g   4.1g  20260 R 38.2  2.2   0:16.10 java
136632 root      20   0   57.0g   4.1g  20260 S 37.9  2.2   0:16.80 java
136682 root      20   0   57.0g   4.1g  20260 R 37.5  2.2   0:17.23 java
136688 root      20   0   57.0g   4.1g  20260 S 37.5  2.2   0:17.44 java
136712 root      20   0   57.0g   4.1g  20260 S 37.5  2.2   0:16.15 java
136723 root      20   0   57.0g   4.1g  20260 S 37.5  2.2   0:17.00 java
136705 root      20   0   57.0g   4.1g  20260 S 37.2  2.2   0:16.79 java
136722 root      20   0   57.0g   4.1g  20260 R 37.2  2.2   0:16.06 java
136709 root      20   0   57.0g   4.1g  20260 S 36.5  2.2   0:16.64 java
136727 root      20   0   57.0g   4.1g  20260 R 35.9  2.2   0:17.04 java
136743 root      20   0   57.0g   4.1g  20260 R 35.2  2.2   0:16.80 java
136646 root      20   0   57.0g   4.1g  20260 S 34.9  2.2   0:17.47 java
136675 root      20   0   57.0g   4.1g  20260 S 34.9  2.2   0:16.84 java
136689 root      20   0   57.0g   4.1g  20260 R 34.9  2.2   0:16.84 java
136633 root      20   0   57.0g   4.1g  20260 R 34.6  2.2   0:16.72 java
136653 root      20   0   57.0g   4.1g  20260 S 33.9  2.2   0:16.83 java
136698 root      20   0   57.0g   4.1g  20260 R 33.9  2.2   0:16.98 java
136686 root      20   0   57.0g   4.1g  20260 R 33.6  2.2   0:16.56 java
136667 root      20   0   57.0g   4.1g  20260 S 33.2  2.2   0:17.09 java
136665 root      20   0   57.0g   4.1g  20260 R 32.9  2.2   0:16.52 java
136657 root      20   0   57.0g   4.1g  20260 S 32.6  2.2   0:16.72 java
[root@dell-004 ~]# jsta
jstack  jstat   jstatd
[root@dell-004 ~]# jstack 136565 > js.log
136565: No such process
[root@dell-004 ~]# clear
[root@dell-004 ~]# top
top - 22:44:54 up 1 day, 18:47,  3 users,  load average: 29.85, 17.79, 9.23
Tasks: 605 total,   1 running, 604 sleeping,   0 stopped,   0 zombie
%Cpu(s): 88.2 us,  1.0 sy,  0.0 ni, 10.6 id,  0.0 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem : 19650515+total, 18915864+free,  5958980 used,  1387524 buff/cache
KiB Swap:  4194300 total,  4194300 free,        0 used. 18958124+avail Mem

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
137260 root      20   0   57.0g   2.0g  20156 S  4489  1.1   4:30.99 java
137725 root      20   0  162512   2552   1532 R  16.7  0.0   0:00.06 top
137042 root      20   0       0      0      0 S   5.6  0.0   0:00.01 kworker/25:0
     1 root      20   0  194656   7632   2604 S   0.0  0.0   0:12.64 systemd
     2 root      20   0       0      0      0 S   0.0  0.0   0:00.04 kthreadd
     3 root      20   0       0      0      0 S   0.0  0.0   0:00.09 ksoftirqd/0
     4 root      20   0       0      0      0 S   0.0  0.0   0:00.11 kworker/0:0
     5 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/0:0H
     8 root      rt   0       0      0      0 S   0.0  0.0   0:00.38 migration/0
     9 root      20   0       0      0      0 S   0.0  0.0   0:00.00 rcu_bh
    10 root      20   0       0      0      0 S   0.0  0.0   0:15.27 rcu_sched
    11 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 lru-add-drain
    12 root      rt   0       0      0      0 S   0.0  0.0   0:00.11 watchdog/0
    13 root      rt   0       0      0      0 S   0.0  0.0   0:00.11 watchdog/1
    14 root      rt   0       0      0      0 S   0.0  0.0   0:00.36 migration/1
    15 root      20   0       0      0      0 S   0.0  0.0   0:08.38 ksoftirqd/1
    17 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/1:0H
    19 root      rt   0       0      0      0 S   0.0  0.0   0:00.10 watchdog/2
    20 root      rt   0       0      0      0 S   0.0  0.0   0:00.38 migration/2
    21 root      20   0       0      0      0 S   0.0  0.0   0:00.00 ksoftirqd/2
    22 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kworker/2:0
[root@dell-004 ~]# jps
137731 Jps
137260 Client
[root@dell-004 ~]# top -H -p 137260
top - 22:45:13 up 1 day, 18:48,  3 users,  load average: 56.16, 24.56, 11.64
Threads: 455 total, 129 running, 326 sleeping,   0 stopped,   0 zombie
%Cpu(s): 99.5 us,  0.5 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 19650515+total, 18789808+free,  7219324 used,  1387748 buff/cache
KiB Swap:  4194300 total,  4194300 free,        0 used. 18832089+avail Mem

   PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
137322 root      20   0   57.0g   3.3g  20248 R 47.6  1.7   0:08.63 java
137413 root      20   0   57.0g   3.3g  20248 R 47.6  1.7   0:08.99 java
137321 root      20   0   57.0g   3.3g  20248 R 42.9  1.7   0:09.76 java
137325 root      20   0   57.0g   3.3g  20248 R 42.9  1.7   0:08.92 java
137338 root      20   0   57.0g   3.3g  20248 R 42.9  1.7   0:08.93 java
137383 root      20   0   57.0g   3.3g  20248 R 42.9  1.7   0:08.87 java
137386 root      20   0   57.0g   3.3g  20248 R 42.9  1.7   0:09.13 java
137400 root      20   0   57.0g   3.3g  20248 R 42.9  1.7   0:08.94 java
137428 root      20   0   57.0g   3.3g  20248 R 42.9  1.7   0:08.77 java
137324 root      20   0   57.0g   3.3g  20248 R 38.1  1.7   0:09.17 java
137343 root      20   0   57.0g   3.3g  20248 R 38.1  1.7   0:09.23 java
137351 root      20   0   57.0g   3.3g  20248 R 38.1  1.7   0:08.86 java
137364 root      20   0   57.0g   3.3g  20248 R 38.1  1.7   0:08.63 java
137374 root      20   0   57.0g   3.3g  20248 R 38.1  1.7   0:08.54 java
137378 root      20   0   57.0g   3.3g  20248 R 38.1  1.7   0:09.67 java
137382 root      20   0   57.0g   3.3g  20248 R 38.1  1.7   0:08.80 java
137393 root      20   0   57.0g   3.3g  20248 R 38.1  1.7   0:08.87 java
137433 root      20   0   57.0g   3.3g  20248 R 38.1  1.7   0:09.52 java
137435 root      20   0   57.0g   3.3g  20248 R 38.1  1.7   0:09.04 java
137440 root      20   0   57.0g   3.3g  20248 R 38.1  1.7   0:08.70 java
137305 root      20   0   57.0g   3.3g  20248 R 33.3  1.7   0:01.11 java
[root@dell-004 ~]# jstack 137260 > js.log


[js.log](https://github.com/brianfrankcooper/YCSB/files/2377526/js.log)

**Comment by busbey** [comment]
It'll be hard to tell from a single jstack where time is getting spent as the client goes. You'll need a profiler.

Off the top of my head, one guess is that without a specified recordcount you get the workload default of ~1000. It's possible you're seeing contention between scans an inserts due to that hitting a small number of regions.

**Comment by adally** [comment]
Thanks.Could you tell me which tool can be used to perform a profiler ?

**Comment by adally** [comment]
Use this?
https://www.yourkit.com/download/YourKit-JavaProfiler-2018.04-b82.zip

**Comment by busbey** [comment]
sure, yourkit is a good profiler.

**Comment by busbey** [comment]
Looks like it's all in the HBase client code. Could be a form of #1108 .

**Comment by adally** [comment]
![image](https://user-images.githubusercontent.com/13135485/45524986-a8ba6280-b803-11e8-9838-520af645dedf.png)

Hi, you can have a look at the cpu utilization. It will take a drop in the long term.
2018-09-14 09:47:37

"Thread-95" - Thread t@119
   java.lang.Thread.State: TIMED_WAITING
	at java.lang.Object.wait(Native Method)
	- waiting on <18101499> (a org.apache.hadoop.hbase.ipc.Call)
	at org.apache.hadoop.hbase.ipc.RpcClientImpl.call(RpcClientImpl.java:1256)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callBlockingMethod(AbstractRpcClient.java:227)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$BlockingRpcChannelImplementation.callBlockingMethod(AbstractRpcClient.java:336)
	at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$BlockingStub.scan(ClientProtos.java:34094)
	at org.apache.hadoop.hbase.client.ScannerCallable.close(ScannerCallable.java:383)
	at org.apache.hadoop.hbase.client.ScannerCallable.call(ScannerCallable.java:200)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:145)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:60)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:210)
	at org.apache.hadoop.hbase.client.ClientScanner.call(ClientScanner.java:327)
	at org.apache.hadoop.hbase.client.ClientScanner.close(ClientScanner.java:748)
	at com.yahoo.ycsb.db.HBaseClient10.scan(HBaseClient10.java:387)
	at com.yahoo.ycsb.DBWrapper.scan(DBWrapper.java:159)
	at com.yahoo.ycsb.workloads.CoreWorkload.doTransactionScan(CoreWorkload.java:756)
	at com.yahoo.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:614)
	at com.yahoo.ycsb.ClientThread.run(Client.java:455)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- None

"hconnection-0x7648144-shared--pool1-t1" - Thread t@190
   java.lang.Thread.State: TIMED_WAITING
	at java.lang.Object.wait(Native Method)
	- waiting on <78dc8e96> (a org.apache.hadoop.hbase.ipc.Call)
	at org.apache.hadoop.hbase.ipc.RpcClientImpl.call(RpcClientImpl.java:1256)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callBlockingMethod(AbstractRpcClient.java:227)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$BlockingRpcChannelImplementation.callBlockingMethod(AbstractRpcClient.java:336)
	at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$BlockingStub.scan(ClientProtos.java:34094)
	at org.apache.hadoop.hbase.client.ScannerCallable.openScanner(ScannerCallable.java:400)
	at org.apache.hadoop.hbase.client.ScannerCallable.call(ScannerCallable.java:204)
	at org.apache.hadoop.hbase.client.ScannerCallable.call(ScannerCallable.java:65)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:210)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas$RetryingRPC.call(ScannerCallableWithReplicas.java:364)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas$RetryingRPC.call(ScannerCallableWithReplicas.java:338)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:136)
	at org.apache.hadoop.hbase.client.ResultBoundedCompletionService$QueueingFuture.run(ResultBoundedCompletionService.java:65)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- locked <4116f85d> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"main" - Thread t@1
   java.lang.Thread.State: WAITING
	at java.lang.Object.wait(Native Method)
	- waiting on <4148db48> (a java.lang.Thread)
	at java.lang.Thread.join(Thread.java:1252)
	at java.lang.Thread.join(Thread.java:1326)
	at com.yahoo.ycsb.Client.main(Client.java:802)

   Locked ownable synchronizers:
	- None

**Comment by adally** [comment]
Hi, I found that the requestdistribution had big effect on this. When I modifed workloade's  requestdistribution zipfian into uniform. Add or not add option recordcount ,the result is close. And when I read the source code, I found the following comment:
// it does this by generating a random "next key" in part by taking the modulus over the
      // number of keys.
      // If the number of keys changes, this would shift the modulus, and we don't want that to
      // change which keys are popular so we'll actually construct the scrambled zipfian generator
      // with a keyspace that is larger than exists at the beginning of the test. that is, we'll predict
      // the number of inserts, and tell the scrambled zipfian generator the number of existing keys
      // plus the number of predicted keys as the total keyspace. then, if the generator picks a key
      // that hasn't been inserted yet, will just ignore it and pick another key. this way, the size of
      // the keyspace doesn't change from the perspective of the scrambled zipfian generator
It seems that the predict cost a lot of cpu. But I still don't understand why mongodb don't have this problem when test in the same way.

**Comment by busbey** [comment]
are you still investigating this issue? Did you try reproducing it with the hbase14 or hbase20 bindings?

**Comment by adally** [comment]
Hi,I haven't worked on it for a long.
It always can be reproduced every time it doesn't have option " -p recordcount"
