### ISSUE TITLE
How can I benchmark my JSON dataset?

### ISSUE THREAD

**Issue by meSmashsta** [brianfrankcooper/YCSB#1234]
I am targeting to benchmark Redis, Cassandra, and MongoDB. The problem is that my JSON has inner / nested columns, second Redis and Cassandra has structure, I had to define the columns that I need, the problem is that I'm trying to benchmark a JSON which at any time can change. How would you benchmark a database that can't generate structure base on your JSON? At the moment I have two fields: id, details; At the moment I insert my json inside the details column as suggested by stackoverflow, but after benchmarking the throughput is off its mark, only MongoDB have the at least accuracy.

Off the marks, please help me 😢 

![41818780_742469566115108_357371949388660736_n](https://user-images.githubusercontent.com/12151336/45584505-2e730680-b907-11e8-87fc-d5645956fcb6.png)

**Comment by busbey** [comment]
YCSB doesn't generally offer guidance on how to implement particular use cases. that said, I believe the ease of using JSON is part of the feature set for things like MongoDB.

There's an open set of issues/PRs for adding a YCSB workload specific to JSON handling, but AFAIK it's stalled.

In the meantime your best bet is to look for guidance from the particular datastore you're interested in trying on how to handle JSON document storage and retrieval.

**Comment by meSmashsta** [comment]
I did, in my particular case, I made a column and insert the json as string there as suggested by the vendor. I think the problem is resolve at the moment because the graphs that I generated was from a throughput that was made by my outdated code.

**Comment by keshavmr** [comment]
See: https://github.com/brianfrankcooper/YCSB/issues/1050
We have implemented YCSB-JSON for MongoDB and Couchbase.
