### ISSUE TITLE
HBase batch load

### ISSUE THREAD

**Issue by ssizmaster** [brianfrankcooper/YCSB#1236]
Hi,
I have tested the batch load  in MySQL database by using the command bellow:

`bin/ycsb load jdbc -P workloads/workloada -P ~/YCSB/jdbc/src/main/conf/db.properties -p zeropadding=8 -p insertorder=ordered -p recordcount=100000 -p table=usertable100k  -threads 5 -p db.batchsize=1000 -p jdbc.fetchsize=1000 -p jdbc.autocommit=false -p jdbc.batchsize=1000 -p jdbc.batchupdateapi=true > workloada_load_100k_mysql.txt
`

Is there the same thing for HBase load command ?
Thank you

**Comment by risdenk** [comment]
What have you tried so far? What error message are you getting?

**Comment by ssizmaster** [comment]
I have not found a solution. is there a way to do the same thing in HBase?

**Comment by busbey** [comment]
the hbase loading has no equivalent. (In HBase terms this would be a bulk load option for YCSB)
