### ISSUE TITLE
YCSB command for running the load test for Cassandra 3.1

### ISSUE THREAD

**Issue by ssabnis** [brianfrankcooper/YCSB#1239]
Hello All,

I tried to run the load test for Cassandra 3.11. I am unable to get through.  Can you provide me a working sample command. Thanks in advance.

`./ycsb load cassandra -p hosts="172.x.x.x" -threads 128 -p fieldcount=20 -p operationcount=900000 -p recordcount=15000000 -p requestdistribution=zipfian -P workloads/workloada -s > workloada_load_res.txt`

**Comment by risdenk** [comment]
What error message are you getting?

**Comment by fbbfnc** [comment]
This one works for me:
`./bin/ycsb load cassandra-cql -s -P workloads/workloada -threads 100 -p recordcount=3000000000000000 -p hosts=************* 2>&1 | tee outputLoad.txt
`

**Comment by busbey** [comment]
closing as non-responsive. if you're still having issues please reopen.
