### ISSUE TITLE
TRAVIS CI failing for java 11 checks

### ISSUE THREAD

**Issue by 88sanjay** [brianfrankcooper/YCSB#1241]
I get the following message when I try running the CI pipeline . It looks like for some reason that the install of the jdk seems to fail.

Here is the snippet of result I see for this [PR](https://github.com/brianfrankcooper/YCSB/pull/1237)

```

Setting APT mirror in /etc/apt/sources.list: http://us-central1.gce.archive.ubuntu.com/ubuntu/
$ export JAVA_HOME=${TRAVIS_HOME}/oraclejdk11
$ bash install-jdk.sh -F 11 -L BCL --target $JAVA_HOME --workspace ${TRAVIS_HOME}/.cache/install-jdk
install-jdk.sh 2018-08-16
Couldn't determine a download url for 11-BCL on linux-x64
The command "bash install-jdk.sh -F 11 -L BCL --target $JAVA_HOME --workspace ${TRAVIS_HOME}/.cache/install-jdk" failed and exited with 1 during .

```

**Comment by busbey** [comment]
looking.

**Comment by busbey** [comment]
I restarted the oracle JDK11 build for #1237  and it looks like it's proceeding. Maybe just a transient failure?

**Comment by 88sanjay** [comment]
Yeah . It works for me now
