### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by kimiwukimi** [brianfrankcooper/YCSB#1246]
https://github.com/brianfrankcooper/YCSB/blob/3f39cac8bec52db6ac14fe95f4ce2f39c03be9c2/bin/ycsb#L224

I might be wrong, but I believe "," should be replaced with "as".

**Comment by risdenk** [comment]
The comma is from python 2.x days. Python 3.x requires the use of as. Here is an reference: https://stackoverflow.com/questions/2535760/python-try-except-comma-vs-as-in-except
