### ISSUE TITLE
How to configure MaxDirectMemorySize JVM option is not set or has invalid value (OrientDB) in UBUNTU 16.04

### ISSUE THREAD

**Issue by wahyualikram** [brianfrankcooper/YCSB#1252]
Hello Everyone, i try load & run data orientdb using ubuntu 16.04, but i have problem how to configure MaxDirectMemorySize JVM option is not set or has invalid value. and latency error to please help me @laa @brianfrankcooper @busbey 
Code : 
./bin/ycsb load orientdb -s -P workloads/workloada

INFO: OrientDB auto-config DISKCACHE=852MB (heap=852MB direct=852MB os=3,831MB), assuming maximum direct memory size equals to maximum JVM heap size
Nov 04, 2018 7:32:19 PM com.orientechnologies.common.log.OLogManager log
WARNING: MaxDirectMemorySize JVM option is not set or has invalid value, that may cause out of memory errors. Please set the -XX:MaxDirectMemorySize=3831m option when you start the JVM.
2018-11-04 19:32:19 INFO  OrientDBClient:115 - OrientDB database not found, creating fresh db
2018-11-04 19:32:28:665 10 sec: 0 operations; est completion in 106751991167300 days 15 hours
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
2018-11-04 19:32:30:469 11 sec: 1000 operations; 554.32 current ops/sec; [CLEANUP: Count=1, Max=99, Min=99, Avg=99, 90=99, 99=99, 99.9=99, 99.99=99] [INSERT: Count=1000, Max=49055, Min=116, Avg=641.69, 90=445, 99=4651, 99.9=41471, 99.99=49055]
[OVERALL], RunTime(ms), 11804
[OVERALL], Throughput(ops/sec), 84.71704506946797
[TOTAL_GCS_PS_Scavenge], Count, 11
[TOTAL_GC_TIME_PS_Scavenge], Time(ms), 25
[TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.21179261267366992
[TOTAL_GCS_PS_MarkSweep], Count, 1
[TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 23
[TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.19484920365977634
[TOTAL_GCs], Count, 12
[TOTAL_GC_TIME], Time(ms), 48
[TOTAL_GC_TIME_%], Time(%), 0.40664181633344626
[CLEANUP], Operations, 1
[CLEANUP], AverageLatency(us), 99.0
[CLEANUP], MinLatency(us), 99
[CLEANUP], MaxLatency(us), 99
INFO: OrientDB auto-config DISKCACHE=852MB (heap=852MB direct=852MB os=3,831MB), assuming maximum direct memory size equals to maximum JVM heap size
Nov 04, 2018 7:32:19 PM com.orientechnologies.common.log.OLogManager log
WARNING: MaxDirectMemorySize JVM option is not set or has invalid value, that may cause out of memory errors. Please set the -XX:MaxDirectMemorySize=3831m option when you start the JVM.
2018-11-04 19:32:19 INFO  OrientDBClient:115 - OrientDB database not found, creating fresh db
2018-11-04 19:32:28:665 10 sec: 0 operations; est completion in 106751991167300 days 15 hours
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
2018-11-04 19:32:30:469 11 sec: 1000 operations; 554.32 current ops/sec; [CLEANUP: Count=1, Max=99, Min=99, Avg=99, 90=99, 99=99, 99.9=99, 99.99=99] [INSERT: Count=1000, Max=49055, Min=116, Avg=641.69, 90=445, 99=4651, 99.9=41471, 99.99=49055]
[OVERALL], RunTime(ms), 11804
[OVERALL], Throughput(ops/sec), 84.71704506946797
[TOTAL_GCS_PS_Scavenge], Count, 11
[TOTAL_GC_TIME_PS_Scavenge], Time(ms), 25
[TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.21179261267366992
[TOTAL_GCS_PS_MarkSweep], Count, 1
[TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 23
[TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.19484920365977634
[TOTAL_GCs], Count, 12
[TOTAL_GC_TIME], Time(ms), 48
[TOTAL_GC_TIME_%], Time(%), 0.40664181633344626
[CLEANUP], Operations, 1
[CLEANUP], AverageLatency(us), 99.0
[CLEANUP], MinLatency(us), 99
[CLEANUP], MaxLatency(us), 99
[CLEANUP], 95thPercentileLatency(us), 99
[CLEANUP], 99thPercentileLatency(us), 99
[INSERT], Operations, 1000
[INSERT], AverageLatency(us), 641.691
[INSERT], MinLatency(us), 116
[INSERT], MaxLatency(us), 49055
[INSERT], 95thPercentileLatency(us), 551
[INSERT], 99thPercentileLatency(us), 4651
[INSERT], Return=OK, 1000

**Comment by wahyualikram** [comment]
where is the location of JVM configuration in ubuntu 16.04?

**Comment by busbey** [comment]
OS specific JVM tuning is out of scope for the kind of help the YCSB project generally provides. What are you trying to solve?

**Comment by wahyualikram** [comment]
i try to load data ycsb to orientdb but This notification always appears and info **latency** is always an error

INFO: OrientDB auto-config DISKCACHE=852MB (heap=852MB direct=852MB os=3,831MB), assuming maximum direct memory size equals to maximum JVM heap size
Nov 04, 2018 7:32:19 PM com.orientechnologies.common.log.OLogManager log
WARNING: MaxDirectMemorySize JVM option is not set or has invalid value, that may cause out of memory errors. Please set the -XX:MaxDirectMemorySize=3831m option when you start the JVM.

**Comment by busbey** [comment]
In my first comment I show an example of how to use the correct YCSB option to solve the warning.

If latency shows just error results, check to see if you can successfully connect to the orientdb instance via something that isn't YCSB.

**Comment by wahyualikram** [comment]
hello @busbey, what is the difference between orientdb enterprise and community edition?
I want to load and run data from YCSB, what version of orientdb should I use? version of community or enterprise ?

Orientdb Enterprise : https://orientdb.com/orientdb-enterprise/ => OrientDB Enterprise Edition-3.0.8 
Orientdb Community : wget -O orientdb-community-2.2.20.tar.gz http://orientdb.com/download.php?file=orientdb-community-2.2.20.tar.gz&os=linux => OrientDB Community

**Comment by risdenk** [comment]
@wahyualikram We don't support the underlying databases only YCSB. You will have to ask the OrientDB community or company for more details. The current YCSB orientdb client is 2.2.10 which is found here https://github.com/brianfrankcooper/YCSB/blob/master/pom.xml#L99

**Comment by busbey** [comment]
Closing as nonresponsive. Please reopen if you have more details.
