### ISSUE TITLE
Dynamodb: Missing primary key attribute name, cannot continue

### ISSUE THREAD

**Issue by iperica** [brianfrankcooper/YCSB#1257]
I was running load workload to dynamodb to existing new table 'usertable' with 'firstname' as primary key (string). Any idea why it complains missing primary key attribute name in output?

----/opt/YCSB/dynamodb/conf/dynamodb.properties
dynamodb.awsCredentialsFile = $DYNAMODB_HOME/conf/AWSCredentials.properties
dynamodb.primaryKey= firstname
dynamodb.endpoint = http://dynamodb.us-east-1.amazonaws.com

----sudo ./bin/ycsb load dynamodb -P workloads/workloada -P dynamodb.props
`Command line: -db com.yahoo.ycsb.db.DynamoDBClient -P workloads/workloada -P dynamodb.props -load
YCSB Client 0.16.0-SNAPSHOT

Loading workload...
Starting test.
com.yahoo.ycsb.DBException: Missing primary key attribute name, cannot continue
	at com.yahoo.ycsb.db.DynamoDBClient.init(DynamoDBClient.java:100)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:86)
	at com.yahoo.ycsb.ClientThread.run(Client.java:424)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.yahoo.ycsb.DBException: Missing primary key attribute name, cannot continue
	at com.yahoo.ycsb.db.DynamoDBClient.init(DynamoDBClient.java:100)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:86)
	at com.yahoo.ycsb.ClientThread.run(Client.java:424)
	at java.base/java.lang.Thread.run(Thread.java:834)
[OVERALL], RunTime(ms), 11
[OVERALL], Throughput(ops/sec), 0.0
[TOTAL_GCS_Copy], Count, 0
[TOTAL_GC_TIME_Copy], Time(ms), 0
[TOTAL_GC_TIME_%_Copy], Time(%), 0.0
[TOTAL_GCS_MarkSweepCompact], Count, 0
[TOTAL_GC_TIME_MarkSweepCompact], Time(ms), 0
[TOTAL_GC_TIME_%_MarkSweepCompact], Time(%), 0.0
[TOTAL_GCs], Count, 0
[TOTAL_GC_TIME], Time(ms), 0
[TOTAL_GC_TIME_%], Time(%), 0.0`

**Comment by risdenk** [comment]
It might be because you specified your properties as `dynamodb.props` when the properties file is actually `dynamodb.properties`? You may also need a full path to the properties file.

**Comment by busbey** [comment]
Closing as nonresponsive. Please reopen if you have more details.
