### ISSUE TITLE
Where is the orientdb data storage location after load and run ycsb?

### ISSUE THREAD

**Issue by wahyualikram** [brianfrankcooper/YCSB#1259]
hi all i read this how to load and run the ycsb in orientdb https://github.com/brianfrankcooper/YCSB/blob/master/orientdb/README.md

./bin/ycsb load orientdb -s -P workloads/workloada -> load
./bin/ycsb run orientdb -s -P workloads/workloada -> run
 if I do load and run data where is the location of the data I have loaded seen?

can you give me a way to properly do it load and run data?, please help me. @busbey @risdenk

**Comment by risdenk** [comment]
Depends if you are using local then it would be the path you specify. If you specify in memory it would be in memory only. If you specify remote, it would be where OrientDB is running.
