### ISSUE TITLE
Endless loop when opcount is less than threadcount

### ISSUE THREAD

**Issue by melhindi** [brianfrankcooper/YCSB#1268]
Hi,
I came this by accident (forgot to change threadcount):
When opcount is set to 1 and threadcount to e.g. 2, it causes the first thread to stop after 1 operation, but the second thread runs endlessly.
This is due to the threadopcount calculation in the following lines: https://github.com/brianfrankcooper/YCSB/blob/2f03a2f83a713e86fb66e067be3da98fd5871f0c/core/src/main/java/com/yahoo/ycsb/Client.java#L432-L437

When threadopcount is 0 the loop in ClientThread will run endlessly https://github.com/brianfrankcooper/YCSB/blob/2f03a2f83a713e86fb66e067be3da98fd5871f0c/core/src/main/java/com/yahoo/ycsb/ClientThread.java#L116

I am not sure what the intended behaviour is, but I would suggest to either throw an exception (when opcount < threadcount) or alter the calculation to pass e.g. a negative opcount to those ClientThreads that will not need to issue operations.

**Comment by busbey** [comment]
Good find! Would you mind putting together a PR?

**Comment by busbey** [comment]
this was fixed in #1323
