### ISSUE TITLE
Remove deprecated product Azure DocumentDB

### ISSUE THREAD

**Issue by voellm** [brianfrankcooper/YCSB#1269]
I've reached out to https://www.linkedin.com/in/kirill-vlasov-48451427/ who did the Azure Document DB driver and asked if he was ok if it was removed.  Document DB stopped being a production ~2017.

He approved the removal.

I'll take this bug and submit a PR for it.

**Comment by busbey** [comment]
sounds good. we'll put in a release note into whatever release the PR ends up landing on.

**Comment by busbey** [comment]
done in #1295
