### ISSUE TITLE
Cassandra YCBS

### ISSUE THREAD

**Issue by pajus7** [brianfrankcooper/YCSB#1279]
Hi, I have a problem with inserting data into Cassandra DB using YCBS. I got error 

`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2019-02-11 14:30:16:992 0 sec: 0 operations; est completion in 0 second 
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Error inserting, not retrying any more. number of attempts: 1Insertion Retry Limit: 0`

I created a keyspace in Cassandra called 'ycbs' and I have also right connection between docker containers. How Can I resolve this problem ?

**Comment by fbbfnc** [comment]
Are you also creating the usertable? 
`create keyspace IF NOT EXISTS ycsb
    WITH REPLICATION = {'class' : 'SimpleStrategy', 'replication_factor': 3 };
USE ycsb;
create table IF NOT EXISTS usertable (
    y_id varchar primary key,
    field0 varchar,
    field1 varchar,
    field2 varchar,
    field3 varchar,
    field4 varchar,
    field5 varchar,
    field6 varchar,
    field7 varchar,
    field8 varchar,
    field9 varchar);
`

**Comment by busbey** [comment]
Did the above suggestion help?

**Comment by busbey** [comment]
Closing as nonresponsive. Please reopen if you have more details

**Comment by MichaelFree1993** [comment]
I create table usertable, but still have some problem.
