### ISSUE TITLE
How can I use YCSB to evaluate Oracle's performance?

### ISSUE THREAD

**Issue by KaimingWan** [brianfrankcooper/YCSB#128]
I have set the classpath included with 'ojdbc14' and I also move it to the directory ~/ycsb-0.1.4/jdbc-binding/lib.

I have create a table called 'usertable' in oracle.When use the command 
 ./ycsb load jdbc -P ../workloads/workloada -p threads=1 -p columnfamily=f1 -p recordcount=10000 -s > load.dat

issues appeared as below:

Loading workload...
Starting test.
 0 sec: 0 operations; 
Error in database operation: java.sql.SQLException: No suitable driver found for 
com.yahoo.ycsb.DBException: java.sql.SQLException: No suitable driver found for 
        at com.yahoo.ycsb.db.JdbcDBClient.init(JdbcDBClient.java:203)
        at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:63)
        at com.yahoo.ycsb.ClientThread.run(Client.java:189)
Caused by: java.sql.SQLException: No suitable driver found for 
        at java.sql.DriverManager.getConnection(DriverManager.java:602)
        at java.sql.DriverManager.getConnection(DriverManager.java:185)
        at com.yahoo.ycsb.db.JdbcDBClient.init(JdbcDBClient.java:187)
        ... 2 more
 0 sec: 0 operations; 

my conf file under /jdbc-binding:
[hadoopcdh@mastersrv conf]$ cat db.properties 
#Properties file that contains database connection information.

jdbc.driver=oracle.jdbc.driver.OracleDriver
db.url=jdbc:oracle:thin:@192.168.1.65:1521:kakou
db.user=kakou
db.passwd=kakou
[hadoopcdh@mastersrv conf]$ cat h2.properties 
#Properties file that contains database connection information.

jdbc.driver=oracle.jdbc.driver.OracleDriver
db.url=jdbc:oracle:thin:@192.168.1.65:1521:kakou
db.user=kakou
db.passwd=kakou

**Comment by busbey** [comment]
restating the problems above:

* Need to verify the README of the JDBC driver explains how to get appropriate jdbc drivers on the classpath
* Need to update the JDBC driver to not rely on semi-colons since that breaks some oracle bindings.
