### ISSUE TITLE
YCSB not loading data apart from “usertable” cassandra column family

### ISSUE THREAD

**Issue by nm0916** [brianfrankcooper/YCSB#1280]
I am using YCSB 0.14.0 and Cassandra 3.11.3

If I use YCSB load command to load the data to the default "usertable" column family, the data gets loaded to the table properly. I use "select * from usertable" in cql to verify that the data has been loaded.

But if the same is tried for any other Cassandra table, YCSB tool just runs for a few seconds and I also get a few load statistics, but there is no actual loading of the data in the table. The select command just displays the table without any data.

The command I use for loading is as below:
`./bin/ycsb load cassandra-cql -P workloads/workloada -p hosts=<ip-address> -p columnfamily=<name of the table> -p recordcount=10000
`
What is the problem here with loading data to other column families apart from "usertable"?

**Comment by fbbfnc** [comment]
I use the following file to create the table and the keyspace. 
`create keyspace IF NOT EXISTS ycsb
    WITH REPLICATION = {'class' : 'SimpleStrategy', 'replication_factor': 3 };
USE ycsb;
create table IF NOT EXISTS usertable (
    y_id varchar primary key,
    field0 varchar,
    field1 varchar,
    field2 varchar,
    field3 varchar,
    field4 varchar,
    field5 varchar,
    field6 varchar,
    field7 varchar,
    field8 varchar,
    field9 varchar);
`

**Comment by nm0916** [comment]
But YCSB does not load any data if you change the data type from varchar to anything else. Also, you need to provide the same names, like y_id, field0, field1.. 
If you define the variable in some other way, data won't get loaded to the table.

**Comment by fbbfnc** [comment]
I just followed the documentation [here](https://github.com/brianfrankcooper/YCSB/tree/master/cassandra)

**Comment by nm0916** [comment]
Yes, I know that. But is it to be understood that YCSB takes only that format of data types and variable names and nothing else?

**Comment by fbbfnc** [comment]
I'm in the same situation as you, unfortunately. I think that it's to be understood like that. 
Why do you need to change the datatypes and variable names? Are you using it for benchmarking purposes?

**Comment by nm0916** [comment]
Yes. I do not need the varchar data type for my experimentations. I wanted to try out with ints, but YCSB doesn't load data if any change is made and I am stuck with that problem for a while.

**Comment by fbbfnc** [comment]
What about writing your own custom workload that behave as expected by you? 
[Here](https://github.com/brianfrankcooper/YCSB/wiki/Implementing-New-Workloads)

**Comment by busbey** [comment]
To use data types other than text you would need a custom workload as @fbbfnc described.

**Comment by busbey** [comment]
Let us know if the docs on making a custom workload need help.
