### ISSUE TITLE
Testing HBase 2.0.0 (working on top of Hadoop 2.7.1)

### ISSUE THREAD

**Issue by oylumalatli** [brianfrankcooper/YCSB#1284]
Hello,

I try to test HBase 2.0.0 with YCSB 0.15. Hbase can create tables and works fine. However, when I run the command "./bin/ycsb load hbase20 -P workloads/workloada -p columnfamily=family" I get the following warnings and errors (a bit long- excuse me please):
log4j:WARN No appenders could be found for logger (org.apache.htrace.core.Tracer).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Starting test.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
com.yahoo.ycsb.DBException: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=16, exceptions:
Wed Mar 20 10:57:29 EET 2019, RpcRetryingCaller{globalStartTime=1553068615964, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.MasterNotRunningException: java.io.IOException: org.apache.hadoop.hbase.shaded.org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/master
Wed Mar 20 10:58:04 EET 2019, RpcRetryingCaller{globalStartTime=1553068615964, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.MasterNotRunningException: java.io.IOException: org.apache.hadoop.hbase.shaded.org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/master
Wed Mar 20 10:58:38 EET 2019, RpcRetryingCaller{globalStartTime=1553068615964, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.MasterNotRunningException: java.io.IOException: org.apache.hadoop.hbase.shaded.org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/master
Wed Mar 20 10:59:12 EET 2019, RpcRetryingCaller{globalStartTime=1553068615964, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.MasterNotRunningException: java.io.IOException: org.apache.hadoop.hbase.shaded.org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/master
Wed Mar 20 10:59:46 EET 2019, RpcRetryingCaller{globalStartTime=1553068615964, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.MasterNotRunningException: java.io.IOException: org.apache.hadoop.hbase.shaded.org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/master
Wed Mar 20 11:00:20 EET 2019, RpcRetryingCaller{globalStartTime=1553068615964, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.MasterNotRunningException: java.io.IOException: org.apache.hadoop.hbase.shaded.org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/master
Wed Mar 20 11:00:55 EET 2019, RpcRetryingCaller{globalStartTime=1553068615964, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.MasterNotRunningException: java.io.IOException: org.apache.hadoop.hbase.shaded.org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/master
Wed Mar 20 11:01:33 EET 2019, RpcRetryingCaller{globalStartTime=1553068615964, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.MasterNotRunningException: java.io.IOException: org.apache.hadoop.hbase.shaded.org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/master
Wed Mar 20 11:02:17 EET 2019, RpcRetryingCaller{globalStartTime=1553068615964, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.MasterNotRunningException: java.io.IOException: org.apache.hadoop.hbase.shaded.org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/master
Wed Mar 20 11:03:01 EET 2019, RpcRetryingCaller{globalStartTime=1553068615964, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.MasterNotRunningException: java.io.IOException: org.apache.hadoop.hbase.shaded.org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/master
Wed Mar 20 11:03:45 EET 2019, RpcRetryingCaller{globalStartTime=1553068615964, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.MasterNotRunningException: java.io.IOException: org.apache.hadoop.hbase.shaded.org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/master
Wed Mar 20 11:04:29 EET 2019, RpcRetryingCaller{globalStartTime=1553068615964, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.MasterNotRunningException: java.io.IOException: org.apache.hadoop.hbase.shaded.org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/master
Wed Mar 20 11:05:23 EET 2019, RpcRetryingCaller{globalStartTime=1553068615964, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.MasterNotRunningException: java.io.IOException: org.apache.hadoop.hbase.shaded.org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/master
Wed Mar 20 11:06:17 EET 2019, RpcRetryingCaller{globalStartTime=1553068615964, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.MasterNotRunningException: java.io.IOException: org.apache.hadoop.hbase.shaded.org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/master
Wed Mar 20 11:07:11 EET 2019, RpcRetryingCaller{globalStartTime=1553068615964, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.MasterNotRunningException: java.io.IOException: org.apache.hadoop.hbase.shaded.org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/master
Wed Mar 20 11:08:05 EET 2019, RpcRetryingCaller{globalStartTime=1553068615964, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.MasterNotRunningException: java.io.IOException: org.apache.hadoop.hbase.shaded.org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/master

	at com.yahoo.ycsb.db.HBaseClient10.init(HBaseClient10.java:159)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:86)
	at com.yahoo.ycsb.ClientThread.run(ClientThread.java:74)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=16, exceptions:

Could you please help? Thanks a lot.

Oylum

**Comment by busbey** [comment]
That looks like YCSB couldn't find you HBase instance. Did you include pointing it at your local hbase configs?

**Comment by busbey** [comment]
Closing as nonresponsive. Please reopen if you have more details.
