### ISSUE TITLE
Could not find or load main class com.yahoo.ycsb.CommandLine

### ISSUE THREAD

**Issue by AliYns** [brianfrankcooper/YCSB#1285]
Hello
I'm new to maven,I have done mvn clean install
I m running on windows10 with maven3.6 and get this:

G:\GitHub\YCSB\bin>ycsb shell basic
G:\GitHub\YCSB\bin>"C:\Program Files\Java\jdk1.8.0_181\bin\java.exe"  -classpath "G:\GitHub\YCSB\bin\conf" com.yahoo.ycsb.CommandLine  -db com.yahoo.ycsb.BasicDB
Error: Could not find or load main class com.yahoo.ycsb.CommandLine

**Comment by busbey** [comment]
Can you use the binary artifacts from the 0.15.0 release instead of trying to build from source?

**Comment by AliYns** [comment]
I have tried  ycsb-0.15.0.tar.gz from https://github.com/brianfrankcooper/YCSB/releases
first i get
G:\ycsb-0.15.0\bin>ycsb shell basic
FINDSTR: Cannot open G:\ycsb-0.15.0\bin\bin\bindings.properties
[ERROR] The specified binding 'basic' was not found.  Exiting.

after copying bindings.properties from ycsb-0.15.0\bin to ycsb-0.15.0\bin\bin 
G:\ycsb-0.15.0\bin>ycsb shell basic

G:\ycsb-0.15.0\bin>"C:\Program Files\Java\jdk1.8.0_181\bin\java.exe"  -classpath "G:\ycsb-0.15.0\bin\conf" com.yahoo.ycsb.CommandLine  -db com.yahoo.ycsb.BasicDB
Error: Could not find or load main class com.yahoo.ycsb.CommandLine

**Comment by busbey** [comment]
You shouldn't need to copy files around places from the given installation.

Have you already walked through our windows specific instructions for "running from a release"?



https://github.com/brianfrankcooper/YCSB/wiki/Prerequisites-for-Windows

**Comment by AliYns** [comment]
Thanks a lot, I have tried to run it directly without python.exe before my commands, now it works
