### ISSUE TITLE
why does the total OPS differ from the target number ?

### ISSUE THREAD

**Issue by baiwfg2** [brianfrankcooper/YCSB#1287]
Hi. I met with a strange situation in redis benchmarking. My YCSB commandline is ：
> ./bin/ycsb load redis -s -P workloads/workloada -p "redis.host=10.110.36.139" -p "redis.port=6379" -p recordcount=10000000 -target 10000 -threads 4

With redis_exporter, I can see the total OPS is 20000 from grafana dashboard including `hmset` and `zadd`
![image](https://user-images.githubusercontent.com/5157680/55138959-9c7a6f00-516f-11e9-8fe0-33d61b6b4ef2.png)

Why is that ? I had thought the `target` meant the total OPS, not the one of single command. Does the same thing happen in other databases ?

**Comment by baiwfg2** [comment]
What if I just want to send `set`, how should I do that ？

**Comment by busbey** [comment]
The ycsb target parameter is talking about YCSB record operations, so it'll map to a different number of operations in different datastores depending on how the client binding maps things.

For example, in the binding for HBase we write each record and a series of cells in the same row, one cell per YCSB field. That means with defualts usually the HBase monitoring stuff will show an operation rate ~10x that of YCSB.

**Comment by baiwfg2** [comment]
Got that. Thanks.
