### ISSUE TITLE
How to get fluctuating connections

### ISSUE THREAD

**Issue by baiwfg2** [brianfrankcooper/YCSB#1289]
When I do benchmarking with some kind of database, I want to make the number of tcp connections with database server fluctuate around some avergae value, just like what I saw on production servers. Would YCSB be able to do that now ?

**Comment by busbey** [comment]
That's going to depend on which YCSB client binding you're using specifically. YCSB itself uses two fixed-at-start configs (number of YCSB clients you run and number of threads you tell YCSB to use on each of those) to drive how much parallel load it will place on the client binding. The client bindings either directly map that number to connections to the data store or they do some kind of pooling (usually in the client library for whatever datastore).
