### ISSUE TITLE
ycsb on hbase fails with java.io.EOFException

### ISSUE THREAD

**Issue by manojsundaram** [brianfrankcooper/YCSB#129]
Hi,

I am trying to install ycsb for benchmarking hbase.

#  ./bin/ycsb load hbase -p columnfamily=family -P workloads/workloada > /tmp/loaddata.tmp

Loading workload...
Starting test.
SLF4J: The requested version 1.5.8 by your slf4j binding is not compatible with [1.6]
SLF4J: See http://www.slf4j.org/codes.html#version_mismatch for further details.
13/05/15 11:31:50 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.3-1240972, built on 02/06/2012 10:48 GMT
13/05/15 11:31:50 INFO zookeeper.ZooKeeper: Client environment:host.name=<..hostname..>
13/05/15 11:31:50 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_24
13/05/15 11:31:50 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
13/05/15 11:31:50 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.0.x86_64/jre
13/05/15 11:31:50 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/<..path..>/ycsb-0.1.4/hbase-binding/conf:/<..path..>/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/<..path..>/ycsb-0.1.4/core/lib/core-0.1.4.jar:/<..path..>/ycsb-0.1.4/voldemort-binding/conf:/<..path..>/ycsb-0.1.4/jdbc-binding/conf:/<..path..>/ycsb-0.1.4/infinispan-binding/conf
13/05/15 11:31:50 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.0.x86_64/jre/lib/amd64/server:/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.0.x86_64/jre/lib/amd64:/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.0.x86_64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
13/05/15 11:31:50 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
13/05/15 11:31:50 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
13/05/15 11:31:50 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
13/05/15 11:31:50 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
13/05/15 11:31:50 INFO zookeeper.ZooKeeper: Client environment:os.version=2.6.32-279.el6.x86_64
13/05/15 11:31:50 INFO zookeeper.ZooKeeper: Client environment:user.name=hbase
13/05/15 11:31:50 INFO zookeeper.ZooKeeper: Client environment:user.home=/var/run/hbase
13/05/15 11:31:50 INFO zookeeper.ZooKeeper: Client environment:user.dir=/<..path..>/ycsb-0.1.4
13/05/15 11:31:50 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=<..hostname..>:2181 sessionTimeout=180000 watcher=hconnection
13/05/15 11:31:50 INFO zookeeper.RecoverableZooKeeper: The identifier of this process is 24314@<..hostname..>
13/05/15 11:31:50 INFO zookeeper.ClientCnxn: Opening socket connection to server /<IP>:2181
13/05/15 11:31:50 INFO client.ZooKeeperSaslClient: Client will not SASL-authenticate because the default JAAS configuration section 'Client' could not be found. If you are not using SASL, you may ignore this. On the other hand, if you expected SASL to work, please fix your JAAS configuration.
13/05/15 11:31:50 INFO zookeeper.ClientCnxn: Socket connection established to <..hostname..>/<..IP..>:2181, initiating session
13/05/15 11:31:50 INFO zookeeper.ClientCnxn: Session establishment complete on server <..hostname..>/<..IP..>:2181, sessionid = 0x3ea192c11c1bff, negotiated timeout = 180000
 
Error accessing HBase table: java.io.IOException: Call to <..hostname..>/<..IP..>:60020 failed on local exception: java.io.EOFException

My HBase+Zookeeper is running fine and i am able to perform all operations on it. The problem arises only when i use YCSB.

Some background info:

# netstat -ntpl | grep 60020
tcp        0      0 ::ffff: <IP>:60020  :::*                        LISTEN      115262/java

# created user table with,
# hbase org.apache.hadoop.hbase.util.RegionSplitter usertable UniformSplit -c 200 -f family

Can someone point me in the right direction?

Thanks in advance for the help!

-Manoj

**Comment by busbey** [comment]
closing as stale. @manojsundaram if you're still running into this problem, reopen and we'll work through things.
