### ISSUE TITLE
Request to be a contributor / approver

### ISSUE THREAD

**Issue by voellm** [brianfrankcooper/YCSB#1296]
It looks like there are a number of changes looking for approvers / contributors.  Can you please add me as an approver.  i'm the original owner of the https://github.com/GoogleCloudPlatform/PerfKitBenchmarker and grew that community on GitHub.  I very much open value opensource and the community behind it.

**Comment by busbey** [comment]
That's great! Start picking up reviews and participate in the next release vote. Those are the two things we usually look for to invite additional maintainers.

**Comment by voellm** [comment]
Sean,

In terms on picking up review should I just leave feedback for submitters?
How does it get completed?  Is there some @done or something to add in the
comments so you know its reviewed?

Just looking for your process.

  Thanks,
      Tony

**Comment by busbey** [comment]
Yeah just start leaving feedback and requesting changes where needed.

I usually go through open PRs in updated order, so it should be easy to find those that have a sign-off.
