### ISSUE TITLE
Cassandra - FamilyColumn="data"'

### ISSUE THREAD

**Issue by nicolasdegroodt** [brianfrankcooper/YCSB#13]
in your files for running the db cassandra, you force to have only one familycolumn seted to "data". We can't work with more columnfamily. What a pitty. I'm working on extending it for my tests !

**Comment by busbey** [comment]
In Cassandra, "column family" is what they used to call tables in CQL. Since we allow setting this like the other bindings within the cassandra2 binding (the only non-deprecated Cassandra binding), I'm closing this out.
