### ISSUE TITLE
Getting bad response for Solr

### ISSUE THREAD

**Issue by pm-adnan** [brianfrankcooper/YCSB#1302]
Hello eevryone

 I set up different NoSQL databases on my laptop such as Elasticsearch, Solr, OrientDB and MongoDB and wanted to measure the performance of these databases using YCSB.

The problem is Solr takes too much time for each workload as shown below

[OVERALL], RunTime(ms), 98412
[OVERALL], Throughput(ops/sec), 101.61362435475348
[TOTAL_GCS_PS_Scavenge], Count, 16
[TOTAL_GC_TIME_PS_Scavenge], Time(ms), 47
[TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.04775840344673414
[TOTAL_GCS_PS_MarkSweep], Count, 0
[TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 0
[TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.0
[TOTAL_GCs], Count, 16
[TOTAL_GC_TIME], Time(ms), 47
[TOTAL_GC_TIME_%], Time(%), 0.04775840344673414
[READ], Operations, 4959
[READ], AverageLatency(us), 1867.9526114135915
[READ], MinLatency(us), 1288
[READ], MaxLatency(us), 19551
[READ], 95thPercentileLatency(us), 2217
[READ], 99thPercentileLatency(us), 4299
[READ], Return=OK, 4959
[CLEANUP], Operations, 1
[CLEANUP], AverageLatency(us), 1672.0
[CLEANUP], MinLatency(us), 1672
[CLEANUP], MaxLatency(us), 1672
[CLEANUP], 95thPercentileLatency(us), 1672
[CLEANUP], 99thPercentileLatency(us), 1672
[UPDATE], Operations, 5041
[UPDATE], AverageLatency(us), 17593.302916088076
[UPDATE], MinLatency(us), 9520
[UPDATE], MaxLatency(us), 183167
[UPDATE], 95thPercentileLatency(us), 30591
[UPDATE], 99thPercentileLatency(us), 40287
[UPDATE], Return=OK, 5041

Plus I don't know how to make a graph throughput vs latency?

 is it possible that we can make changes (or define) to the throughput like 3k or 5k or 6k  per sec. if yes then how is it possible. I read that we can define the throughput using the target parameter but I am unsuccessful while applying  this tag
-p  target 300 

I am very thankful to you if you can help me regarding these issues.

Best Wishes,
Adnan

**Comment by busbey** [comment]
> is it possible that we can make changes (or define) to the throughput like 3k or 5k or 6k per sec. if yes then how is it possible. I read that we can define the throughput using the target parameter but I am unsuccessful while applying this tag
-p target 300

The target throughput rate is specified on the cli with `-target 300`

**Comment by busbey** [comment]
> Plus I don't know how to make a graph throughput vs latency?

Use one of the exporters to get machine parsable metrics and thrn use the charting mechanism of your choice.

They're covered a bit on the docs page for core properties:

https://github.com/brianfrankcooper/YCSB/wiki/Core-Properties

**Comment by busbey** [comment]
Closing as stale, feel free to reopen if you have more details.
