### ISSUE TITLE
mongodb results I'm getting seems incorrect

### ISSUE THREAD

**Issue by lovengulu** [brianfrankcooper/YCSB#1303]
I'm trying to test relation between RAM availability size and Mongodb performance. 
I tried testing the extremes as follows: 

I'm using MongoDB 4.0.6 on a linux server + linux server to run ycsb-0.15.0 client.

Using YCSB, I built ''ycsb"  database with 1,200,000,000 objects. 
The storage size I found was ~1.4TB Which is what I expected (as each document is slightly more than 1KB).
mongo's db.stats() reported in addition that the index size is ~80GB. 

Using this database I performed two 30 minutes tests of workload-c (read-only workload). The first test was using server occupied with 768GB or RAM, and the other test and same hardware, but with only 64GB of RAM.

I expected that the throughput using 768GB would be much faster. 
I got very similar results:
768GB RAM: throughput: 320,626 TPS  
 64GB RAM: throughput: 326,313 TPS 
This is very unreasonable. I verified that that all read actions had Return=OK. 

I changed in workload-c definition "requestdistribution" from "zipfian" to "uniform" to avoid reading the same documents already in RAM over and over again. 

It looks to me that somehow that there's something wrong in the test and I'm using in both tests small set of values already in RAM. 

The command line I used:
`# bin/ycsb run mongodb -s -P /opt/MongoDB-Benchmark/ycsb-0.15.0/workloads/workloadc -threads 72 -p operationcount=1000000000 -p maxexecutiontime=1800 -p mongodb.url=mongodb://dl380g10-0:27017/ycsb?w=1`

Is there something I do wrong in the way I use the test? 
Or anything else I should have configured?

**Comment by twblamer** [comment]
You need to pass `-p recordcount=1200000000` on the command line. If you don't tell YCSB what the recordcount is, it's going to use the workload default (1000).

**Comment by lovengulu** [comment]
Thanks! This can explain. I'll test it.

**Comment by busbey** [comment]
added both. thanks for the feedback!
