### ISSUE TITLE
Use YCSB programatically for benchmarking NoSQL stores

### ISSUE THREAD

**Issue by bnzishan** [brianfrankcooper/YCSB#1307]
Is it possible to use YCSB API with java code for benchmarking? I want to benchmark HBase, MongoDB, and Cassandra for datasets that I have, while using workloads of YCSB. Is there anyway I can send my datasets from my java code to YCSB running in a docker container which will benchmark Hbase cluster running in separate docker containers? All examples I have seen until now, are using YCSB via command line. Thanks.

**Comment by busbey** [comment]
YCSB is designed to be run from the command line.

You should be able to run said command line in a docker container, but afaik we have no docs or examples of doing so.
