### ISSUE TITLE
Error in bin/bindings.properties

### ISSUE THREAD

**Issue by sneceesay77** [brianfrankcooper/YCSB#1325]
There is a trivial error in the bin/bindings.properties file for hbase20 property. At line number 57 

This line 
`hbase20:com.yahoo.ycsb.db.hbase14.HBaseClient20`

should have been

`hbase20:com.yahoo.ycsb.db.hbase20.HBaseClient20`

The error lead to `java.lang.ClassNotFoundException:com.yahoo.ycsb.db.hbase14.HBaseClient20`

**Comment by busbey** [comment]
Thanks for the report!

This got fixed in #1524 and should be in the next release.
