### ISSUE TITLE
how to disable cleanup phase

### ISSUE THREAD

**Issue by XiaochenCui** [brianfrankcooper/YCSB#1333]
What should I do if I don't want the cleanup execute?

**Comment by busbey** [comment]
I don't think we currently have a way to disable cleanup phase. Some datastore bindings use that e.g. to ensure changes are all committed when they're operating in client-batching mode.

Why are you looking to skip it?

**Comment by XiaochenCui** [comment]
@busbey Cause I'm testing the insert performance of my hbase, and I don't want the test data be deleted.

**Comment by XiaochenCui** [comment]
@busbey In the way the region split could be retained after test.

**Comment by busbey** [comment]
The cleanup phase for YCSB just cleans up client side session state, it shouldn't impact stuff that's been persisted by the datastore.

Some of the workloads do alter the table state, but we have a recommended ordering of workloads aimed at minimizing the number of data set loads needed:

https://github.com/brianfrankcooper/YCSB/wiki/Core-Workloads#running-the-workloads

**Comment by busbey** [comment]
closing as stale, feel free to reopen if you have more questions.
