### ISSUE TITLE
The estimation for finishing Run Workload E too long Arangodb

### ISSUE THREAD

**Issue by RezaTri** [brianfrankcooper/YCSB#1337]
I want to ask, what is the problem with arangodb when running Workload E Scan 95% and insert 5%. the estimation is so long to finish the run of Workload E.
Can't someone help with this?
I'm running on arangodb ver. 3.4.4
![Screenshot from 2019-08-03 22-12-01](https://user-images.githubusercontent.com/33218606/62413680-e7cfed00-b63b-11e9-9f00-4e330560d46e.png)

**Comment by busbey** [comment]
wow that looks really bad. I don't personally have any experience with tuning ArangoDB specifically.

how does the same instance do with other workloads?

any ideas @mpv1989?

**Comment by RezaTri** [comment]
The other workload are just fine and running well. Just workload E that running so slow. I am running on ubuntu 16.04 with spec intel core i7 and ram 4gb. is it the hardware fault>

**Comment by busbey** [comment]
I don't think I know enough about Arangodb to know if the hardware is the issue, but 4GiB of memory is not very much for most of the things YCSB can be run against.

Your best bet is probably to reach out the the Arangodb community about optimization options.

Let us know if you find a way to make it go faster.
