### ISSUE TITLE
error of can't find new added database client class

### ISSUE THREAD

**Issue by Meizhen** [brianfrankcooper/YCSB#134]
I am trying to add a new database to YCSB to benchmark. I've extended the DB abstract class and implemented the init, cleanup, read ... methods. I add the new class in the same file of the HBaseClient. And I add all the path I need to run the new class. But it shows that class can not be found. I can successfully ran the default databases by command and in eclipse, but I don't know how can I ran the new added database interface. I tried the following commands:
java -cp /home/meizhen/workspace/YCSB/core/target/core-0.1.4.jar:/home/meizhen/workspace/YCSB/jdbc/src/main/conf:/home/meizhen/workspace/YCSB/hbase/target/hbase-binding-0.1.4.jar:/home/meizhen/workspace/YCSB/hbase/target/archive-tmp/hbase-binding-0.1.4.jar:/home/meizhen/workspace/YCSB/hbase/src/main/conf com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.MyDatabaseClient -P workloads/MyProperties -s -t
Could you shed me some light on this? Thank you!

**Comment by busbey** [comment]
you added the new client as an additional class in the same jar as HBaseClient or in the HBaseClient.java file?

generally, you should add new DB drivers as independent artifacts.

**Comment by busbey** [comment]
please use the changes in #261 to add the jar for your new datastore binding to the classpath
