### ISSUE TITLE
Publish YCSB on Maven Central

### ISSUE THREAD

**Issue by sneceesay77** [brianfrankcooper/YCSB#1340]
I included YCSB as a dependency in my project. In my pom.xml file I have the entry below.

```
<dependency>
      <groupId>com.yahoo.ycsb</groupId>
      <artifactId>core</artifactId>
      <version>0.1.4</version>
</dependency>
```

However when I run 

`mvn clean install`

 I always get the error below. 

[ERROR] Failed to execute goal on project xyz-benchmark: Could not resolve dependencies for project org.apache.xyz:xyz-benchmark:jar:0.9-SNAPSHOT: Could not find artifact com.yahoo.ycsb:core:jar:0.1.4 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

Any ideas.

**Comment by busbey** [comment]
I don't believe we publish to maven central. Have you loaded artifacts into a local maven repo?

**Comment by busbey** [comment]
Also 0.1.4 is very very old. You should use our latest release, 0.15.0

**Comment by sneceesay77** [comment]
> I don't believe we publish to maven central. Have you loaded artifacts into a local maven repo?

What about https://mvnrepository.com/artifact/com.yahoo.ycsb/core/0.1.4. 

It only works when I manually download and add the jar file into my local maven repo.

**Comment by sneceesay77** [comment]
> Also 0.1.4 is very very old. You should use our latest release, 0.15.0

Okay, so even the latest version is not available on maven central?

**Comment by busbey** [comment]
That's some third party jar analysis site. I can't speak for how they decide what to index.

Also 0.1.4 was released in 2012; for all I know the project did publish to maven central then.

**Comment by busbey** [comment]
> Okay, so even the latest version is not available on maven central?

Correct, we don't publish to maven central. That would make it easier for folks to build datastore bindings outside of the project.

Instead of copying jars you could also grab the source version of the release a d use maven to do a local maven install.

**Comment by sneceesay77** [comment]
> > Okay, so even the latest version is not available on maven central?
> 
> Correct, we don't publish to maven central. That would make it easier for folks to build datastore bindings outside of the project. (Which is a good argument for starting to publish there now that I think about it)
Yes, this is exactly what we are doing and struggling with at the moment. Would this entail a lot of time?
> 
> Instead of copying jars you could also grab the source version of the release a d use maven to do a local maven install.

Okay, I have never tried this approach but I will give it a try and keep this space posted.

**Comment by busbey** [comment]
> Would this entail a lot of time?

Publishing to Maven Central? I dunno. Haven't tried as an independent open source project.

**Comment by sneceesay77** [comment]
> > Would this entail a lot of time?
> 
> Publishing to Maven Central? I dunno. Haven't tried as an independent open source project.

Yes, to maven central. Oh okay, can you please update this space when you have an idea.

**Comment by lewismc** [comment]
Hi @busbey thanks for the reply and @sneceesay77 thanks for registering the issue. 

@busbey as you can see @sneceesay77 has been working very well on a GSoC project over on the [Apache Gora](https://gora.apache.org) and is nearing the completion of his contribution.

I've got a lot of experience publishing artifacts to Maven Central and would be happy to take this work on. I will bring @sneceesay77 along for the journey. Please let me know.

**Comment by busbey** [comment]
Any pointers are welcome. All of my experience publishing to central is via mirroring there out of ASF's nexus repo. I'm reading Sonatype's guide now on project set up and we'll see how much I can get queued up while I have the time.

**Comment by busbey** [comment]
Okay, I'm following [Sonatype's OSSRH Guide](https://central.sonatype.org/pages/ossrh-guide.html) and have thus far gotten through making an account on sonatype's jira and [filing an issue to get a repo (OSSRH-50690)](https://issues.sonatype.org/browse/OSSRH-50690)

**Comment by sneceesay77** [comment]
Okay, this looks promising, hopefully, we should get somewhere before mid next week.

**Comment by busbey** [comment]
FYI, currently blocked on getting someone from Yahoo! to verify that we should be allowed to deploy to the group id "com.yahoo.ycsb". I'm following up with the other maintainers via email.

**Comment by lewismc** [comment]
@busbey thanks for the update. I am happy to provide the Maven configuration if you can clarify the groupId issue.

**Comment by lewismc** [comment]
@busbey did you get any word back? Thanks

**Comment by busbey** [comment]
internal discussion among the maintainers still ongoing. might be a bit of time still.

**Comment by sneceesay77** [comment]
@busbey, thanks for the update.

**Comment by sneceesay77** [comment]
@busbey do we have any updates on this? Are we still blocked on the internal discussions among the maintainers?

**Comment by busbey** [comment]
we've been going back and forth amongst us and the sonatype folks on OSSRH-50690. I think we have consensus now, just waiting for me to get some free time. should move forward this weekend.

**Comment by sneceesay77** [comment]
@busbey thanks for the update, glad that there is some progress. By the way if you need some help I think @lewismc had mentioned that he will be happy to do so. Please keep us posted.

**Comment by lewismc** [comment]
ack, the Maven configuration is trivial.

**Comment by sneceesay77** [comment]
@busbey just a gentle ping to see if you were able to find time to have a look at this in the past weekend?

**Comment by busbey** [comment]
I've got a domain registered. now I need to update our coordinates and make a call on updating our packages now vs later.

**Comment by busbey** [comment]
2 of the 3 needed PRs are up now: #1351 (docs) and #1352 (group ids)

**Comment by sneceesay77** [comment]
Awesome @busbey, thanks for the update.

**Comment by lewismc** [comment]
Brilliant @busbey

**Comment by busbey** [comment]
YCSB is review-then-commit and we take reviews from all contributors as binding. so if y'all have time to check correctness on those PRs it'll help things go faster, fyi.

**Comment by lewismc** [comment]
ack

**Comment by busbey** [comment]
#1352 has been updated for recent changes on the master branch and now #1354 (change java packages) has also been posted.

still looking for reviews.

**Comment by lewismc** [comment]
@sneceesay77 can you check out those tickets? Thanks

**Comment by sneceesay77** [comment]
Okay, I will have a look at this.

**Comment by sneceesay77** [comment]
+1 both tested locally and successful. @busbey

**Comment by busbey** [comment]
we now have the ability to publish to central. I'll close out the 0.16.0 release as untested and start a 0.17.0 release with the new coordinates so we can publish it.

Anyone have strong opinions about which jars we ought to publish? (i.e. just those needed to implement a new client binding vs all the jars we make)

**Comment by lewismc** [comment]
We're really interested in former e.g. just those needed to implement a new client binding
You can see specifically at [GoraBenchmarkClient.java](https://github.com/apache/gora/blob/a354b35c5d77c0e67d4c2d01ca0306dd5f91e3d8/gora-benchmark/src/main/java/org/apache/gora/benchmark/GoraBenchmarkClient.java)

**Comment by sneceesay77** [comment]
Great!, I think for a start, I would suggest the former option of publishing those needed to implement a new binding.

**Comment by busbey** [comment]
@lewismc can you take a look at #1361 ? AFAICT it should pass all of the sonatype checks (I have a staged repo that gets a ✅) and it only deploys the artifacts mentioned above.

**Comment by busbey** [comment]
The [YCSB 0.17.0 release is on maven central now](https://search.maven.org/search?q=site.ycsb%200.17.0).

**Comment by sneceesay77** [comment]
thanks, I will update test this in Gora and will keep you all posted.

**Comment by lewismc** [comment]
Sorry @busbey I had a terrible week. We have a [PR open over at Gora](https://github.com/apache/gora/pull/197) for this. Excellent job. Thank you for accommodating this.
