### ISSUE TITLE
how abount I can get  Elasticsearch-7.2.0 QPS

### ISSUE THREAD

**Issue by madonhe** [brianfrankcooper/YCSB#1348]
I know  Elasticsearch-7.x remove type,How do I test QPS？

WARNING: request [GET http://172.18.3.116:9200/es.test003/usertable/_search] returned 1 warnings: [299 Elasticsearch-7.2.0-508c38a "[types removal] Specifying types in search requests is deprecated."]
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.lang.Integer

**Comment by busbey** [comment]
As far as I know, no one has done the work to have YCSB function correctly with Elastic Search 7 yet. So unless there's some kind of compatibility mode available (and I don't know of one) then you're stuck until someone does the work of adding the needed binding code.

**Comment by madonhe** [comment]
==this Elasticsearch-7.2.0
[root@dba-test2 YCSB-master]# curl -X GET "172.18.3.163:9200/customer1/usertable/_search"
{"took":118,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}}[root@dba-test2 YCSB-master]# 
[root@dba-test2 YCSB-master]# 
[root@dba-test2 YCSB-master]# curl -X GET "172.18.3.163:9200/customer1/_search"          
{"took":61,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":3,"max_score":1.0,"hits":[{"_index":"customer1","_type":"external","_id":"1","_score":1.0,"_source":{"name": "John Doe"}},{"_index":"customer1","_type":"external","_id":"AW0eXVcSiUPEHmwxXM1I","_score":1.0,"_source":{"name": "Green Doe"}},{"_index":"customer1","_type":"external","_id":"AW0eZmI4iUPEHmwxXM1J","_score":1.0,"_source":{"name": "Green Doe888"}}]}}[root@dba-test2 YCSB-master]# 

==this Elasticsearch-5.5.0
[root@dba-test2 YCSB-master]# curl -X GET "172.18.3.121:9200/customer1/**usertable**/_search"
{"took":2,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":87,"relation":"eq"},"max_score":1.0,"hits":[{"_index":"customer1","_type":"usertable","_id":"3-zjHm0BA7s15hLJfX8y","_score":1.0,"_source"

if YCSB mode remove "usertable"  we can do test QPS

**Comment by madonhe** [comment]
> ==this Elasticsearch-7.2.0
> [root@dba-test2 YCSB-master]# curl -X GET "172.18.3.163:9200/customer1/usertable/_search"
> {"took":118,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}}[root@dba-test2 YCSB-master]#
> [root@dba-test2 YCSB-master]#
> [root@dba-test2 YCSB-master]# curl -X GET "172.18.3.163:9200/customer1/_search"
> {"took":61,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":3,"max_score":1.0,"hits":[{"_index":"customer1","_type":"external","_id":"1","_score":1.0,"_source":{"name": "John Doe"}},{"_index":"customer1","_type":"external","_id":"AW0eXVcSiUPEHmwxXM1I","_score":1.0,"_source":{"name": "Green Doe"}},{"_index":"customer1","_type":"external","_id":"AW0eZmI4iUPEHmwxXM1J","_score":1.0,"_source":{"name": "Green Doe888"}}]}}[root@dba-test2 YCSB-master]#
> 
> ==this Elasticsearch-5.5.0
> [root@dba-test2 YCSB-master]# curl -X GET "172.18.3.121:9200/customer1/**usertable**/_search"
> {"took":2,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":87,"relation":"eq"},"max_score":1.0,"hits":[{"_index":"customer1","_type":"usertable","_id":"3-zjHm0BA7s15hLJfX8y","_score":1.0,"_source"
> 
> if YCSB mode remove "usertable" we can do test QPS
