### ISSUE TITLE
ycsb redis 

### ISSUE THREAD

**Issue by madonhe** [brianfrankcooper/YCSB#1349]
nohup ./bin/ycsb run redis -P workloads/workloada -p redis.host=172.18.3.163 -p redis.port=6379 -p redis.password=test123 -p operationcount=30000000 -threads 800 &
SocketTimeoutException: Read timed out

**Comment by busbey** [comment]
can you connect to that redis instance from something other than YCSB?

**Comment by madonhe** [comment]
> nohup ./bin/ycsb run redis -P workloads/workloada -p redis.host=172.18.3.163 -p redis.port=6379 -p redis.password=test123 -p operationcount=30000000 -threads 800 &
> SocketTimeoutException: Read timed out
