### ISSUE TITLE
Error while loading Workload

### ISSUE THREAD

**Issue by andrehgdias** [brianfrankcooper/YCSB#1368]
I recently begin use YCSB in my research but I'm getting an error that I don't have a clue how to fix.

I'm kinda newbie using git issues, MongoDB and YCSB, so any help is appreciated!
Output form my terminal:

root@lsncs3:/home/andredias/Workarea/YCSB/ycsb-0.17.0# ./bin/ycsb load mongodb-async -s -P workloads/workloada > outputLoad.txt

/usr/lib/jvm/java-11-openjdk-amd64/bin/java/bin/java -cp /home/andredias/Workarea/YCSB/ycsb-0.17.0/mongodb-binding/conf:/home/andredias/Workarea/YCSB/ycsb-0.17.0/conf:/home/andredias/Workarea/YCSB/ycsb-0.17.0/lib/htrace-core4-4.1.0-incubating.jar:/home/andredias/Workarea/YCSB/ycsb-0.17.0/lib/core-0.17.0.jar:/home/andredias/Workarea/YCSB/ycsb-0.17.0/lib/jackson-core-asl-1.9.4.jar:/home/andredias/Workarea/YCSB/ycsb-0.17.0/lib/jackson-mapper-asl-1.9.4.jar:/home/andredias/Workarea/YCSB/ycsb-0.17.0/lib/HdrHistogram-2.1.4.jar:/home/andredias/Workarea/YCSB/ycsb-0.17.0/mongodb-binding/lib/logback-core-1.1.2.jar:/home/andredias/Workarea/YCSB/ycsb-0.17.0/mongodb-binding/lib/snappy-java-1.1.7.1.jar:/home/andredias/Workarea/YCSB/ycsb-0.17.0/mongodb-binding/lib/mongodb-binding-0.17.0.jar:/home/andredias/Workarea/YCSB/ycsb-0.17.0/mongodb-binding/lib/logback-classic-1.1.2.jar:/home/andredias/Workarea/YCSB/ycsb-0.17.0/mongodb-binding/lib/mongodb-async-driver-2.0.1.jar:/home/andredias/Workarea/YCSB/ycsb-0.17.0/mongodb-binding/lib/mongo-java-driver-3.8.0.jar:/home/andredias/Workarea/YCSB/ycsb-0.17.0/mongodb-binding/lib/slf4j-api-1.7.25.jar site.ycsb.Client -db site.ycsb.db.AsyncMongoDbClient -s -P workloads/workloada -load
Traceback (most recent call last):
  File "./bin/ycsb", line 347, in <module>
    sys.exit(main())
  File "./bin/ycsb", line 338, in main
    return subprocess.call(ycsb_command)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 20] Not a directory

**Comment by busbey** [comment]
What's the output of `/usr/lib/jvm/java-11-openjdk-amd64/bin/java/bin/java -version`

**Comment by andrehgdias** [comment]
> /usr/lib/jvm/java-11-openjdk-amd64/bin/java/bin/java -version

root@lsncs3:/home/andredias# /usr/lib/jvm/java-11-openjdk-amd64/bin/java/bin/java -version
bash: /usr/lib/jvm/java-11-openjdk-amd64/bin/java/bin/java: Not a directory
root@lsncs3:/home/andredias# /usr/lib/jvm/java-11-openjdk-amd64/bin/java -version
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)

**Comment by busbey** [comment]
Can you do an ls of the ycsb 0.17.0 install directory?

**Comment by andrehgdias** [comment]
Fun fact? Now if I try running the command above from my ycsb directory
./bin/ycsb load mongodb-async -s -P workloads/workloada > outputLoad.txt

it gives me this error:
/usr/lib/jvm/java-11-openjdk-amd64/bin/bin/java -cp /home/andredias/Workarea/YCSB/ycsb-0.17.0/mongodb-binding/conf:/home/andredias/Workarea/YCSB/ycsb-0.17.0/conf:/home/andredias/Workarea/YCSB/ycsb-0.17.0/lib/htrace-core4-4.1.0-incubating.jar:/home/andredias/Workarea/YCSB/ycsb-0.17.0/lib/core-0.17.0.jar:/home/andredias/Workarea/YCSB/ycsb-0.17.0/lib/jackson-core-asl-1.9.4.jar:/home/andredias/Workarea/YCSB/ycsb-0.17.0/lib/jackson-mapper-asl-1.9.4.jar:/home/andredias/Workarea/YCSB/ycsb-0.17.0/lib/HdrHistogram-2.1.4.jar:/home/andredias/Workarea/YCSB/ycsb-0.17.0/mongodb-binding/lib/logback-core-1.1.2.jar:/home/andredias/Workarea/YCSB/ycsb-0.17.0/mongodb-binding/lib/snappy-java-1.1.7.1.jar:/home/andredias/Workarea/YCSB/ycsb-0.17.0/mongodb-binding/lib/mongodb-binding-0.17.0.jar:/home/andredias/Workarea/YCSB/ycsb-0.17.0/mongodb-binding/lib/logback-classic-1.1.2.jar:/home/andredias/Workarea/YCSB/ycsb-0.17.0/mongodb-binding/lib/mongodb-async-driver-2.0.1.jar:/home/andredias/Workarea/YCSB/ycsb-0.17.0/mongodb-binding/lib/mongo-java-driver-3.8.0.jar:/home/andredias/Workarea/YCSB/ycsb-0.17.0/mongodb-binding/lib/slf4j-api-1.7.25.jar site.ycsb.Client -db site.ycsb.db.AsyncMongoDbClient -s -P workloads/workloada -load
[ERROR]  Command failed. Is java installed and on your PATH?

But if i try echo $JAVA_HOME i get my path:
/usr/lib/jvm/java-11-openjdk-amd64/bin/

**Comment by andrehgdias** [comment]
> Can you do an ls of the ycsb 0.17.0 install directory?

sure:
accumulo1.6-binding        googlebigtable-binding   nosqldb-binding
accumulo1.7-binding        googledatastore-binding  NOTICE.txt
accumulo1.8-binding        griddb-binding           orientdb-binding
aerospike-binding          hbase098-binding         outputLoad.txt
arangodb-binding           hbase10-binding          outputRun.txt
asynchbase-binding         hbase12-binding          postgrenosql-binding
azurecosmos-binding        hbase14-binding          rados-binding
azuretablestorage-binding  hbase20-binding          redis-binding
bin                        hypertable-binding       rest-binding
cassandra-binding          ignite-binding           riak-binding
cloudspanner-binding       infinispan-binding       rocksdb-binding
couchbase2-binding         jdbc-binding             s3-binding
couchbase-binding          kudu-binding             solr6-binding
crail-binding              lib                      solr-binding
dynamodb-binding           LICENSE.txt              tablestore-binding
elasticsearch5-binding     maprdb-binding           tarantool-binding
elasticsearch-binding      maprjsondb-binding       voltdb-binding
foundationdb-binding       memcached-binding        workloads
geode-binding              mongodb-binding

btw: outputLoad and outputRun is empty.

**Comment by andrehgdias** [comment]
It worked!!
I reset my environmental variables and tried again now both output's txt has a log from the operations.

**Comment by busbey** [comment]
happy to help as a sounding board. :)
