### ISSUE TITLE
 Role of SLF4J in YCSB

### ISSUE THREAD

**Issue by jake914** [brianfrankcooper/YCSB#1370]
- I'm curious what role SLF4J plays in benchmarking YCSB.
- If SLF4J error occurs, does the simulation not work properly?
This error occurred during benchmarking. 

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

**Comment by busbey** [comment]
slf4j is a logging framework that we use in the ycsb core and some of the datastore bindings. It works by having dividing things into an API layer that's always present and then user configurable implementations that take care of formatting and actually writing logs to the console or files or whatever.

That message just means it couldn't find a configured implementation for logging. Everything else will work fine.

Out of curiosity which datastore binding were you using? I'm wondering if this is #1173 or something new.

**Comment by busbey** [comment]
closing as non-responsive. feel free to reopen if you can follow up.

**Comment by genghenggao** [comment]
My problem is solved, please refer to https://github.com/brianfrankcooper/YCSB/issues/1612#issuecomment-1663158429 , hope it can help you.
