### ISSUE TITLE
Potential Null Pointer Dereference in jdbcDBClient

### ISSUE THREAD

**Issue by JulyChen728** [brianfrankcooper/YCSB#1371]
Hi all,

 Our bug scanner has reported a null pointer dereference issue at [JdbcDBClient.java#L187](https://github.com/brianfrankcooper/YCSB/tree/master/jdbc/src/main/java/site/ycsb/db/JdbcDBClient.java#L187).

 since the variable `driver` is checked for whether being null or not at [JdbcDBClient.java#L198](https://github.com/brianfrankcooper/YCSB/tree/master/jdbc/src/main/java/site/ycsb/db/JdbcDBClient.java#L198), 

 it may be null when it was initialized, at [JdbcDBClient.java#L185](https://github.com/brianfrankcooper/YCSB/tree/master/jdbc/src/main/java/site/ycsb/db/JdbcDBClient.java#L185). 

 When `dirver` invokes its function `contains` , the program may crash.

 
```
public void init() throws DBException {
    ...
    String driver = props.getProperty(DRIVER_CLASS);
    ...
    if (driver.contains("sqlserver")) {
      sqlserver = true;
    }
    ...
    try {
      if (driver != null) {
        Class.forName(driver);
      }
      ...
    }
    ...
  }

```
Thanks

**Comment by busbey** [comment]
Makes sense. Interested in putting together a PR?

**Comment by JulyChen728** [comment]
I have create a PR at #1372

**Comment by JulyChen728** [comment]
> Makes sense. Interested in putting together a PR?

I have created a PR at #1372 .
