### ISSUE TITLE
Bring back the maxtime option

### ISSUE THREAD

**Issue by rodrigonascimento** [brianfrankcooper/YCSB#1377]
I remember using "-p maxtime=3600" to make sure my tests wouldn't run for more than 1 hour. It looks like the "maxtime" option got ripped out from YCSB.

**Comment by busbey** [comment]
Perhaps you're thinking of `maxexecutiontime`, which gives a max time in seconds for the benchmark to run?

Note that there is a known issue still wrt honoring the parameter:

> Datastore drivers that lack timeouts may result in YCSB failing to honor the maxexecutiontime parameter. (see #618)

**Comment by busbey** [comment]
If there's still and issue with the referenced parameter please reopen.
