### ISSUE TITLE
not possible to use zero operation count

### ISSUE THREAD

**Issue by symat** [brianfrankcooper/YCSB#1382]
Previously, if you defined `maxexecutiontime` and not defined `operationcount` parameter (or set `operationcount=0`), then you were able to run YCSB for a given period of time and measure the number of operations you get during the load test.

Since https://github.com/brianfrankcooper/YCSB/pull/1323 was merged, it it not possible to use `operationcount=0`, as the thread count will be set to 0 in this case and no client thread will be created:

https://github.com/brianfrankcooper/YCSB/blob/4b19340e3bab5e4c88eda75ad56e83dc4d5cc503/core/src/main/java/site/ycsb/Client.java#L421-L424

The solution would be to change the is statement to: `if (threadcount > opcount && opcount > 0)`

What do you think?
(should I create a PR?)

**Comment by busbey** [comment]
Yes please, that solution sounds great.
