### ISSUE TITLE
very low throughputs of sharded mysql with YCSB

### ISSUE THREAD

**Issue by prashant23** [brianfrankcooper/YCSB#139]
am using ycsb for sharded mysql n was following your idea but of using sharded client,
am using follwing clients for doing benchmarking

https://github.com/Altoros/YCSB/tree/6b5c6720de693ae6bb4f802ebce3d43cb6c13d75/src/jdbc/src/main/java/com/yahoo/ycsb/jdbc

i have updated the core-ycsb jar and jdbc jar accordingly but facing following issue

Exception in thread "Thread-1" java.lang.NoSuchMethodError: com.yahoo.ycsb.Utils.parseInt(Ljava/lang/String;I)I
at com.yahoo.ycsb.jdbc.BaseJdbcClient.init(BaseJdbcClient.java:41)
at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:63)
at com.yahoo.ycsb.ClientThread.run(Client.java:189)

and when am using the jdbc client which is provided by YCSB there the workloads are running properly but the throughputs are coming very low as am increasing the records in the table for 1 million rows its giving through put only 5-6 op/sec for workloada

please guide me with any configuration issue of mysql or any thing else where am going wrong

thanks

prashant

**Comment by busbey** [comment]
Please refer to mysql docs on how to optimize table creations.

The error you gave above sounds like the classpath is wrong in your rebuilt jar. Either the fork you started from has some incompatible change that can't be mixed with the main repo or the build is incorrect.

**Comment by kruthar** [comment]
Hi @prashant23, very late time gap, but want to help solve your issue if possible. When you use the jdbc module provided in YCSB and are successful with workloads, are you doing any proportion of scans in your workload? We identified an issue with jdbc scan operations that would cause longer and longer latencies with increased record counts. You can see the discussion of that at #171, could that be your issue?

**Comment by kruthar** [comment]
closing as stale, and possibly resolved with #468
