### ISSUE TITLE
Doubt with property "hosts" (YCSB)

### ISSUE THREAD

**Issue by man12** [brianfrankcooper/YCSB#140]
I'd like to resolve one doubt that I have about the "host" property of YCSB benchmark. I just have a quick look at the code but I couldn't solve anything.
I'm trying out YCSB with Cassandra and here (https://github.com/brianfrankcooper/YCSB/wiki/Using-the-Database-Libraries) says "... the client can load balance its connections among all of the servers".

In my own test case, I have a multinode cluster with 4 nodes. I'm defining the property like that: hosts=compute0,compute1... and even so. According to the previous link, I suppose all petitions would be balanced, similar to Round Robin, with one thread.

But my doubt is with multiple client threads, i.e., what's the behaviour of the benchmark in that case? Is it like Round Robin or there is a mapping between threads and nodes? I asked this because I wanna know if the database performance or efficiency may be affected for this parameter for several clients. I don't know if each thread "goes" to a different machine (node) or not. If so, it is obviously that performance would be better.

Moreover, related with the previous questions and as finally, is it possible on YCSB each client knows where the data can be? So, they could make requests where they wanted. Am I wrong on this?

Thank you very much for your attention.

Manuel

**Comment by busbey** [comment]
closing as stale. if you are still having issues please check with the current Cassandra bindings.

**Comment by i-refugee** [comment]
Hallo,
when I am running a ycsb script on a cassandra cluster should I run it only in the master/seed node or at all nodes simultaneously?
Thus, cause when I run it on the master/seed node then when i check from ganglia I see more movment to this node than to the other nodes of the cluster. Why is that?
Should not all request be balanced among the nodes?

Thanks and regards,
Konstantinos
