### ISSUE TITLE
Inconsistent library versions notice.

### ISSUE THREAD

**Issue by calvinhkf** [brianfrankcooper/YCSB#1411]
Hi. I have implemented a tool to detect library version inconsistencies. Your project have 13 inconsistent libraries and 2 false consistent libraries.

Take net.java.dev.jna:jna for example, this library is declared as version 4.2.2 in rados, 4.1.0 in elasticsearch and etc... Such version inconsistencies may cause unnecessary maintenance effort in the long run. For example, if two modules become inter-dependent, library version conflict may happen. It has already become a common issue and hinders development progress. Thus a version harmonization is necessary.

Provided we applied a version harmonization, I calculated the cost it may have to harmonize to all upper versions including an up-to-date one. The cost refers to POM config changes and API invocation changes. Take net.java.dev.jna:jna for example, if we harmonize all the library versions into 4.2.2. The concern is, how much should the project code adapt to the newer library version. We list an effort table to quantify the harmonization cost. 

The effort table shows the overall harmonization cost on APIs. It seems your project have no API invokes on this library, which could be safely upgrade to 4.2.2

|Index|Module|NA(NAC)|NDA(NDAC)|NMA(NMAC)|
|-|-|-|-|-|
|1|rados|0(0)|0(0)|0(0)|
|2|elasticsearch|0(0)|0(0)|0(0)|

Also we provided another table to show the potential files that may be affected due to library API change, which could help to spot the concerned API usage and rerun the test cases. 

As for false consistency, take org.apache.httpcomponents httpclient jar for example. The library is declared in version 4.5.1 in all modules. However they are declared differently.  As components are developed in parallel, if one single library version is updated, which could become inconsistent as mentioned above, may cause above-mentioned inconsistency issues

If you are interested, you can have a more complete and detailed report in the attached PDF file.
[brianfrankcooper YCSB.pdf](https://github.com/brianfrankcooper/YCSB/files/4270513/brianfrankcooper.YCSB.pdf)

**Comment by busbey** [comment]
Feel free to file PRs where you can verify getting a consistent library works. But most of our modules are for dealing with different data storage systems and they often need their own specific versions . That's why we keep them separate.

**Comment by calvinhkf** [comment]
Ok. I'll check to see if I could align some libraries that are not purposely in different versions.  Thanks!

**Comment by calvinhkf** [comment]
BTW, how do you think of an automatic tool that could align versions into a unified one(first of all, it should not report false positives), and automatically create a PRs? Would that be convenient in helping developers in not having to messing with version conflicts.
