### ISSUE TITLE
Unable to redirect output from ycsb to a log file

### ISSUE THREAD

**Issue by Prudhvi-pln** [brianfrankcooper/YCSB#1416]
I'm running the following code on ycsb 0.15 (on CentOS) :
./bin/ycsb load mongodb -s -P workloads/workloada -threads 10 -p recordcount=10000 -p mongodb.url=mongodb://testuser:testuser@<ip addresses>/ycsb?w=1&authSource=admin&authMechanism=SCRAM-SHA-1 > results/gen_ycsb.log
Here the results are not getting logged into the gen_ycsb.log file, but I was able to view the output on the terminal.

Any idea why it is not getting stored in log file and how to solve it?

--Thank you in advance

**Comment by busbey** [comment]
The URL isn't getting properly escaped so the shell never sees the file redirect. Put it in single quotes

**Comment by Prudhvi-pln** [comment]
Now it's getting stored in log file. But now there is "Caused by: com.mongodb.MongoCommandException: Command failed with error 18 (AuthenticationFailed)" error, which was not happening previously. Any idea why this is happening?

**Comment by busbey** [comment]
Your URL contains authentication parameters. Previously they were not getting included due to the shell thinking the `&` was part of the shell command. I would guess that they are incorrect.

**Comment by busbey** [comment]
Did updating the authentication parameters work?

**Comment by Prudhvi-pln** [comment]
Yes, it worked. Thank you @busbey
