### ISSUE TITLE
ycsb presplit strategy for hbase

### ISSUE THREAD

**Issue by aiyoh79** [brianfrankcooper/YCSB#142]
Hi,

Do you guys do any presplit when doing data loading? i tried using the regionsplitter with uniformsplit (firstrow = user000 and last row =user999) to create 100 regions but i noticed the load is not balance across all the regions.

There is this Jira mentioning of using ycsbsplit algorithm but is this something already implemented or we have to do our own implementation?

https://issues.apache.org/jira/browse/HBASE-4163

Any good suggestion for this?

aiyoh79

**Comment by busbey** [comment]
You can use the hbase shell as described in that issue to presplit. for example, with 200 splits:

    create 'usertable', 'family', {SPLITS => (1..200).map {|i| "user#{1000+i*(9999-1000)/200}"}, MAX_FILESIZE => 4*1024**3}
