### ISSUE TITLE
Enable reading all fields of a table by column name

### ISSUE THREAD

**Issue by justinuang** [brianfrankcooper/YCSB#1426]
I have observed that for certain databases (google bigtable), it can be faster to read all the columns by passing in all the field names, vs forcing the client to do a wildcard filter .* on the columns. This is especially true when there is only 1 column, where I have observed an also 50% increase in performance when reading by column name. One way to force the client to pass in all the names is to enable dataintegrity:

https://github.com/brianfrankcooper/YCSB/blob/cd1589ce6f5abf96e17aa8ab80c78a4348fdf29a/core/src/main/java/site/ycsb/workloads/CoreWorkload.java#L718

However, dataintegrity incurs the CPU cost of verifyRow, which I would rather not have. Can we create a new flag called readallfieldsbyname? I'm happy to create the PR for it.

**Comment by busbey** [comment]
Sure that sounds reasonable. Default to doing things by the explicit list of all expected fields I'd say.

**Comment by justinuang** [comment]
I linked a PR with what I was thinking. Regarding

> Default to doing things by the explicit list of all expected fields I'd say.

Do you mean that readallfieldsbyname should default to true? I'm a bit wary of that because I don't want to change the benchmark behavior for existing ones. For example, it is slower to readallfieldsbyname if there are many columns in googlebigtable, but faster if there are only a few columns.

**Comment by justinuang** [comment]
Friendly ping =)

**Comment by busbey** [comment]
i'm in the middle of a household move, gonna be a bit for me. If any other maintainers have a chance I don't need to personally be the one to sign off.

**Comment by justinuang** [comment]
Ah I understand, yea I'm moving too. Good luck!

**Comment by busbey** [comment]
fixed by #1427
