### ISSUE TITLE
Can't output load and run operations results to a txt file in cassandra

### ISSUE THREAD

**Issue by andrehgdias** [brianfrankcooper/YCSB#1431]
I can't output any load and run operations results to a txt file in Cassandra.
**Load Command:** ./bin/ycsb load cassandra-cql -p hosts=localhost -s -P workloads/workloada > outputLoad.txt

**Load terminal output:**
```
Loading workload...
Starting test.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2020-06-02 13:40:21:440 0 sec: 0 operations; est completion in 0 second 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.PlatformDependent0 (file:/home/andre/Documentos/Files/UNESP/Iniciacao%20Cientifica/ycsb-0.17.0/cassandra-binding/lib/netty-common-4.0.33.Final.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.PlatformDependent0
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
jun 02, 2020 1:40:23 PM io.netty.util.internal.PlatformDependent <clinit>
INFORMAÇÕES: Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system unstability.
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
2020-06-02 13:40:31:139 10 sec: 1000 operations; 99,99 current ops/sec; [INSERT: Count=1000, Max=60447, Min=751, Avg=2169,45, 90=3133, 99=10063, 99.9=56191, 99.99=60447] 
2020-06-02 13:40:31:533 10 sec: 1000 operations; 0 current ops/sec; [CLEANUP: Count=1, Max=2254847, Min=2252800, Avg=2253824, 90=2254847, 99=2254847, 99.9=2254847, 99.99=2254847] [INSERT: Count=0, Max=0, Min=9223372036854775807, Avg=NaN, 90=0, 99=0, 99.9=0, 99.99=0] 
```

**Comment by andrehgdias** [comment]
Actually It looks like its loading, but I don't know if it's running the workloads because it's not printing out its logs in any file I set....

**Comment by busbey** [comment]
What's the ycsb version

**Comment by andrehgdias** [comment]
Hey, it's the latest 0.17.0

**Comment by busbey** [comment]
can you list out the contents of the lib directory for core and for the cassandra binding?

**Comment by andrehgdias** [comment]
Sure:
**Lib Core**
- core-0.17.0.jar
- HdrHistogram-2.1.4.jar
- htrace-core4-4.1.0-incubating.jar
- jackson-core-asl-1.9.4.jar
- jackson-mapper-asl-1.9.4.jar

**Lib Casandra**
- cassandra-binding-0.17.0.jar
- cassandra-driver-core-3.0.0.jar
- guava-16.0.1.jar
- metrics-core-3.1.2.jar
- netty-buffer-4.0.33.Final.jar
- netty-codec-4.0.33.Final.jar
- netty-common-4.0.33.Final.jar
- netty-handler-4.0.33.Final.jar
- netty-transport-4.0.33.Final.jar
- slf4j-api-1.7.25.jar

**Comment by busbey** [comment]
okay looks like Cassandra has an equivalent to #1173. the same workaround should get you moving again.

**Comment by andrehgdias** [comment]
Ok, I'll try later on and post the result here.

**Comment by andrehgdias** [comment]
well, looks like it worked, that SLF4J error isn't showing up anymore(don't know what caused that exactly since I already had SLF4J api) and now I'm getting some "Infos" messages, I'm outputting the results correctly, thanks a lot!

**Comment by busbey** [comment]
glad to hear it worked. if anyone has time to but together a PR, the gap is that the cassandra binding needs to include a slf4j binding (e.g. the eventual resolution of #1173 happened by including `slf4j-log4j12`, but that's because we already had log4j configs for the hbase bindings)

**Comment by genghenggao** [comment]
My problem is solved, please refer to https://github.com/brianfrankcooper/YCSB/issues/1612#issuecomment-1663158429 , hope it can help you.
