### ISSUE TITLE
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project dynamodb-binding: Compilation failure

### ISSUE THREAD

**Issue by Lforlinux** [brianfrankcooper/YCSB#1438]
Hello, 

The AWS credentials are right. And I can put the data into Dynomodb via CLI from the same terminal. But still, I cannot establish the DB binding. Can you please let me know what is wrong in here. 

Creds placed here  ~/YCSB/dynamodb/conf$ ls AWSCredentials.properties

Dynamodb configuration details: 

~/YCSB/dynamodb/conf$ grep -v '^#' dynamodb.properties
dynamodb.awsCredentialsFile = /home/ubuntu/YCSB/dynamodb/conf/AWSCredentials.properties
dynamodb.primaryKey = "firstname"
dynamodb.hashKeyName = firstname
dynamodb.endpoint = http://dynamodb.us-east-1.amazonaws.com
requestdistribution = uniform

:~/YCSB$ ./bin/ycsb shell dynamodb

[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/ubuntu/YCSB/dynamodb/src/main/java/site/ycsb/db/DynamoDBClient.java:[82,25] cannot find symbol
  symbol:   variable firstname
  location: class site.ycsb.db.DynamoDBClient
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for YCSB Root 0.18.0-SNAPSHOT:
[INFO]
[INFO] YCSB Root .......................................... SUCCESS [  1.946 s]
[INFO] Core YCSB .......................................... SUCCESS [  3.120 s]
[INFO] Per Datastore Binding descriptor ................... SUCCESS [  0.275 s]
[INFO] YCSB Datastore Binding Parent ...................... SUCCESS [  0.568 s]
[INFO] DynamoDB DB Binding ................................ FAILURE [  0.642 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.996 s
[INFO] Finished at: 2020-06-22T07:58:10Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project dynamodb-binding: Compilation failure
[ERROR] /home/ubuntu/YCSB/dynamodb/src/main/java/site/ycsb/db/DynamoDBClient.java:[82,25] cannot find symbol
[ERROR]   symbol:   variable firstname
[ERROR]   location: class site.ycsb.db.DynamoDBClient

**Comment by busbey** [comment]
please use the binary artifacts from our most recent release. i.e. [the dynamodb specific tarball](https://github.com/brianfrankcooper/YCSB/releases/download/0.17.0/ycsb-dynamodb-binding-0.17.0.tar.gz)

**Comment by busbey** [comment]
Did using the binary artifact work for you?
