### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by t2adhikary** [brianfrankcooper/YCSB#1439]
Recent version from github produces the following error. Don't know why?

sudo ./bin/ycsb load cassandra-cql -p hosts="127.0.0.1" -s -P workloads/workloada
[WARN]  Running against a source checkout. In order to get our runtime dependencies we'll have to invoke Maven. Depending on the state of your system, this may take ~30-45 seconds
[DEBUG]  Running 'mvn -pl site.ycsb:cassandra-binding -am package -DskipTests dependency:build-classpath -DincludeScope=compile -Dmdep.outputFilterFile=true'
Traceback (most recent call last):
  File "./bin/ycsb", line 325, in <module>
    sys.exit(main())
  File "./bin/ycsb", line 298, in main
    maven_says = get_classpath_from_maven(project)
  File "./bin/ycsb", line 218, in get_classpath_from_maven
    "-Dmdep.outputFilterFile=true"])
  File "./bin/ycsb", line 167, in check_output
    process = subprocess.Popen(stdout=subprocess.PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by xuclachina** [comment]
you should install openjdk at first

**Comment by busbey** [comment]
probably you are also missing a maven install. you should run from our latest release artifacts instead of building if you can.

you also should not run ycsb as root, but I do not think that is causing your current problem.

**Comment by busbey** [comment]
Did using the binaries from the latest ycsb release work for you?
