### ISSUE TITLE
DynamoDB: improve endpoint and region config

### ISSUE THREAD

**Issue by ahachete** [brianfrankcooper/YCSB#1441]
I have found some limitations on current DynamoDB code, mostly when using a proxy as an endpoint. I have just submitted an initial PR with some minor code improvements to address this limitation, including an upgrade of the AWS client that was quite outdated. The main benefits of this patch are:

* Simplify region configuration with a new parameter, dynamodb.region, which avoids needing to set dynamodb.endpoint if using an standard one.

* Enable using a non-standard endpoint, which would fail with a signature error unless the proxy's upstream is a us-east-1 endpoint.

Please see [PR's commit message](https://github.com/brianfrankcooper/YCSB/pull/1440) for more details.

**Comment by busbey** [comment]
This was merged
