### ISSUE TITLE
Cannot load Arangodb workload

### ISSUE THREAD

**Issue by giannisgrigorakos** [brianfrankcooper/YCSB#1450]
I have chosen to download the .tar YCSB. I have managed to successfully load keys to both redis and aerospike. But when I try to load the workloads in arangodb i get the following message : 
`Loading workload...`
 `Starting test.`
 `SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".`
` SLF4J: Defaulting to no-operation (NOP) logger implementation`
` SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.`
 
I can see the **slf4j-api-1.7.13.jar** under ycsb-0.17.0/arangodb-binding/lib/ 
What can I do to load the keys properly?

**Comment by busbey** [comment]
Looks like the arangodb binding is missing a slf4j binding, so you won't see any logs. We have notes on working around this issue from when we didn't properly include things for the hbase 2 binding as well. Lemme see if I can find a link

**Comment by busbey** [comment]
The workaround is described in #1173

**Comment by busbey** [comment]
What does the output look like now?

**Comment by giannisgrigorakos** [comment]
Still the same as before. I just needed to ` (cd lib/ && curl -O 'https://search.maven.org/remotecontent?filepath=org/slf4j/slf4j-api/1.7.13/slf4j-api-1.7.13.jar')` right? Is there a step that I am missing?

**Comment by giannisgrigorakos** [comment]
Ok so I managed to make it run with this command `curl -L -O 'https://search.maven.org/remotecontent?filepath=org/slf4j/slf4j-simple/1.7.13/slf4j-simple-1.7.13.jar'`. It needs the -L, too. This issue can close from my side. Thank you for your time.
