### ISSUE TITLE
Can someone kindly tell me how to use YCSB to access the HBase cluster with Kerberos authentication enabled

### ISSUE THREAD

**Issue by mlbzssk** [brianfrankcooper/YCSB#1453]
Can someone kindly tell me how to use YCSB to access the HBase cluster with Kerberos authentication enabled.
I tried many methods, but nothing worked.
Such as :
./ycsb run hbase20 -P /data0/backup/ycsb/ycsb-hbase20-binding-0.16.0-SNAPSHOT/workloads/workloada -p table=acceptanceTestTable -p columnfamily=cf1 -p recordcount=1000 -p operationcount=1500 -p fieldcount=1 -p fieldlength=3 -p kerberos=true -p kerberoskeytab=/etc/security/keytabs/spnego.service.keytab -p kerberosprincipal=HTTP/_HOST@TEST.123.RETURN.NET -p debug=true
But i got is ：
Tue Sep 15 17:40:45 CST 2020, RpcRetryingCaller{globalStartTime=1600162716959, pause=100, maxAttempts=16}, javax.security.sasl.SaslException: Call to /172.169.21.67:16020 failed on local exception: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Server not found in Kerberos database (7) - LOOKING_UP_SERVER)] [Caused by javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Server not found in Kerberos database (7) - LOOKING_UP_SERVER)]]

**Comment by busbey** [comment]
you need to let the hbase client know what your hbase configuration is. usually this happens by adding an appropriate hbase configuration directory via the classpath. with that you can just kinit before running ycsb.

e.g. `./bin/ycsb run hbase20 -cp /etc/hbase/conf -p columnfamily=family -s -P workloads/workloada`

**Comment by mlbzssk** [comment]
Thank you very much for your reply.I solved this problem by adding the attribute: 
    -p keytab=/etc/security/keytabs/hbase.headless.keytab -p principal=xx
Of course hbase configuration  of YCSB  is the same as HBase cluster configuration.
I am new to ycsb, thank you very much for resolving my problem.
`
    <property>
      <name>hbase.security.authentication</name>
      <value>kerberos</value>
    </property>

    <property>
      <name>hbase.security.authentication.spnego.kerberos.keytab</name>
      <value>/etc/security/keytabs/spnego.service.keytab</value>
    </property>

    <property>
      <name>hbase.security.authentication.spnego.kerberos.principal</name>
      <value>xxx</value>
    </property>

    <property>
      <name>hbase.security.authorization</name>
      <value>true</value>
    </property>

`

**Comment by busbey** [comment]
happy to help.
