### ISSUE TITLE
ycsb with phoenix 

### ISSUE THREAD

**Issue by cc-a100** [brianfrankcooper/YCSB#1454]
The following error occurs when I tested ycsb for phoenix 
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Error in processing insert to table: USERTABLEorg.apache.phoenix.exception.PhoenixParserException: ERROR 601 (42P00): Syntax error. Encountered "INSERT" at line 1, column 1.
Error inserting, not retrying any more. number of attempts: 1Insertion Retry Limit: 0
2020-09-16 16:35:45:846 2 sec: 0 operations; est completion in 106751991167300 days 15 hours [CLEANUP: Count=1, Max=52, Min=52, Avg=52, 90=52, 99=52, 99.9=52, 99.99=52] [INSERT: Count=0, Max=0, Min=9223372036854775807, Avg=�, 90=0, 99=0, 99.9=0, 99.99=0] [INSERT-FAILED: Count=1, Max=3581, Min=3580, Avg=3581, 90=3581, 99=3581, 99.9=3581, 99.99=3581]

**Comment by cc-a100** [comment]
![QQ图片20200916170957](https://user-images.githubusercontent.com/71377079/93316993-7a7f1b80-f83f-11ea-9512-71570ac1715b.png)

**Comment by cc-a100** [comment]
![2](https://user-images.githubusercontent.com/71377079/93317128-aac6ba00-f83f-11ea-89bc-85ad840cd81e.png)
This is my configuration file

**Comment by cc-a100** [comment]
This is the command line I executed
ycsb load jdbc -s -P workloads/workloada -P phoenix.properties -p table=USERTABLE -p recordcount=1000 > workloada_jdbc_load.log

**Comment by busbey** [comment]
hi! probably the most effective path forward will be to ask on the [Apache Phoenix user mailing list](http://phoenix.apache.org/mailing_list.html) if there are special considerations needed when using the JDBC driver. Specifically let them know that you're trying to use YCSB with their jdbc driver. If there's something we can make work that'd be great. This would not be the first time we had to customize things for a particular jdbc implementation.

**Comment by busbey** [comment]
Any progress getting help from the phoenix folks?
