### ISSUE TITLE
Error with ./bin/ycsb file

### ISSUE THREAD

**Issue by andrehgdias** [brianfrankcooper/YCSB#1456]
Hello againg, this time I'm getting a new error, just changed my test enviroment(now I'm using docker).
I've deleted bindings for unused databases, so I don't know if this is the cause...

My terminal looks like this:
```
root@a6e7297ad94e:/ycsb-0.17.0# ./bin/ycsb load mongodb-async -s -P workloads/workloada -p mongodb.url=mongodb://172.18.0.3:27017 > 'logs/load/wa1k.txt'
  File "./bin/ycsb", line 228
    except subprocess.CalledProcessError, err:
                                        ^
SyntaxError: invalid syntax
```

**Comment by busbey** [comment]
if you just need the mongodb binding, please use the mongodb specific binary tarball rather than modifying the "here's everything" binary tarball.

**Comment by andrehgdias** [comment]
actually I need other bindings but even with new tarball with nothing modified, I'm geting that error. It's YCSB 0.17.0 on ubuntu 18.04, Java 11 and Maven 3.6

**Comment by busbey** [comment]
What version of python is in your docker image

**Comment by andrehgdias** [comment]
Python 3.6.9, should I downgrade?

**Comment by andrehgdias** [comment]
Now I can't run a workload with specified 'recordcount', even though I **did** load that same amount. It's always doing 1k operations instead of what I specified.

Command:
`
./bin/ycsb.sh run mongodb-async -P workloads/workloada -p mongodb.url=mongodb://172.18.0.3:27017/ycsb?w=1 -p recordcount=100000 -s > 'logs/running-workloadA.txt'
`

**Comment by busbey** [comment]
Changing the extension switched you from the python launcher to the bash launcher.

The python launcher requires python 2. Please ensure you have python 2 in the docker image and use the Python launcher

**Comment by andrehgdias** [comment]
True, after purging Python3, installing Python 2.7 via apt and setting the alternatives, the python script works just fine.
But I'm still having the second issue where running workloads just ignore my parameters and always execute 1k operations.

**Comment by busbey** [comment]
Please open a dedicated issue with details for that, since it is a different problem.

**Comment by andrehgdias** [comment]
Ok thanks
