### ISSUE TITLE
very low throughputs of Cassandra for YCSB workload for large amount of data

### ISSUE THREAD

**Issue by prashant23** [brianfrankcooper/YCSB#148]
Hi all 
Am benchmarking cassandra cluster using YCSB tool. When am using 1 gb data it is giving me fair results (throughput around 20K op/sec) but when am using the 1TB data then it is coming 200 to 300 op/sec. it is having very high read latency can any body tell me that what can be done to improve the throughput.
Thanks

**Comment by busbey** [comment]
closing as stale. if you are still having this issue please reopen.
