### ISSUE TITLE
command mvn package

### ISSUE THREAD

**Issue by linguere** [brianfrankcooper/YCSB#1492]
I have this problem want I run this command mvn package

fter one minute; proceeding with shutdown
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for YCSB Root 0.18.0-SNAPSHOT:
[INFO]
[INFO] YCSB Root .......................................... SUCCESS [ 17.212 s]
[INFO] Core YCSB .......................................... SUCCESS [ 28.957 s]
[INFO] Per Datastore Binding descriptor ................... SUCCESS [  0.543 s]
[INFO] YCSB Datastore Binding Parent ...................... SUCCESS [  3.394 s]
[INFO] Accumulo 1.9 DB Binding ............................ SUCCESS [10:38 min]
[INFO] Aerospike DB Binding ............................... SUCCESS [01:14 min]
[INFO] ArangoDB Binding ................................... SUCCESS [01:19 min]
[INFO] AsyncHBase Client Binding for Apache HBase ......... SUCCESS [27:31 min]
[INFO] Cassandra 2.1+ DB Binding .......................... FAILURE [28:44 min]
[INFO] Cloud Spanner DB Binding ........................... SKIPPED
[INFO] Couchbase Binding .................................. SKIPPED
[INFO] Couchbase Java SDK 2.x Binding ..................... SKIPPED
[INFO] Crail DB Binding ................................... SKIPPED
[INFO] Azure Cosmos Binding ............................... SKIPPED
[INFO] Azure table storage Binding ........................ SKIPPED
[INFO] DynamoDB DB Binding ................................ SKIPPED
[INFO] Elasticsearch Binding .............................. SKIPPED
[INFO] Elasticsearch 5.x Binding .......................... SKIPPED
[INFO] FoundationDB Binding ............................... SKIPPED
[INFO] Geode DB Binding ................................... SKIPPED
[INFO] Google Cloud Datastore Binding ..................... SKIPPED
[INFO] Google Cloud Bigtable Binding ...................... SKIPPED
[INFO] GridDB Binding ..................................... SKIPPED
[INFO] HBase 1.y DB Binding ............................... SKIPPED
[INFO] HBase 2.y DB Binding ............................... SKIPPED
[INFO] Hypertable DB Binding .............................. SKIPPED
[INFO] Apache Ignite ...................................... SKIPPED
[INFO] Infinispan DB Binding .............................. SKIPPED
[INFO] JDBC DB Binding .................................... SKIPPED
[INFO] Kudu DB Binding .................................... SKIPPED
[INFO] memcached binding .................................. SKIPPED
[INFO] MapRDB Binding ..................................... SKIPPED
[INFO] MapR JSON DB Binding ............................... SKIPPED
[INFO] MongoDB Binding .................................... SKIPPED
[INFO] Oracle NoSQL Database Binding ...................... SKIPPED
[INFO] OrientDB Binding ................................... SKIPPED
[INFO] PostgreNoSQL Binding ............................... SKIPPED
[INFO] rados of Ceph FS binding ........................... SKIPPED
[INFO] Redis DB Binding ................................... SKIPPED
[INFO] Rest Client Binding ................................ SKIPPED
[INFO] Riak KV Binding .................................... SKIPPED
[INFO] RocksDB Java Binding ............................... SKIPPED
[INFO] S3 Storage Binding ................................. SKIPPED
[INFO] SeaweedFS Storage Binding .......................... SKIPPED
[INFO] Solr Binding ....................................... SKIPPED
[INFO] Solr 6 Binding ..................................... SKIPPED
[INFO] Solr 7 Binding ..................................... SKIPPED
[INFO] Tarantool DB Binding ............................... SKIPPED
[INFO] TableStore DB Binding .............................. SKIPPED
[INFO] VoltDB Binding ..................................... SKIPPED
[INFO] YCSB Release Distribution Builder .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:10 h
[INFO] Finished at: 2020-12-09T22:08:07Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.8:test (default-test) on project cassandra-binding: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\birane\eclipse-workspace-these\YCSB-masterBK\cassandra\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :cassandra-binding

**Comment by busbey** [comment]
please use the precompiled binaries from our last release.
