### ISSUE TITLE
Could not resolve dependencies for project com.yahoo.ycsb:mapkeeper-binding:jar

### ISSUE THREAD

**Issue by mnikhil-git** [brianfrankcooper/YCSB#150]
Hi,

I am trying to build the package on my mac and I am getting these errors.

[ERROR] Failed to execute goal on project mapkeeper-binding: Could not resolve dependencies for project com.yahoo.ycsb:mapkeeper-binding:jar:0.1.4: Failure to find com.yahoo.mapkeeper:mapkeeper:jar:1.0 in http://nexus.rfiserve.net/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of nexus-hq has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :mapkeeper-binding

----

Am I missing anything in m2 settings? Thanks for the help.

Nikhil

**Comment by busbey** [comment]
current build failures fixed by #210. getting things working again for leveldb will stay in #181.
