### ISSUE TITLE
DNS Seed List Connection Format not accepted for "mongodb" URI

### ISSUE THREAD

**Issue by SteveH-US** [brianfrankcooper/YCSB#1501]
Version 0.17 of ycsb explicitly rejects MongoDB URI that is in ["DNS Seed List Connection Format"](https://docs.mongodb.com/manual/reference/connection-string/#dns-seed-list-connection-format). 

```java
 if (!url.startsWith("mongodb://")) {
        System.err.println("ERROR: Invalid URL: '" + url
            + "'. Must be of the form "
            + "'mongodb://<host1>:<port1>,<host2>:<port2>/database?options'. "
            + "http://docs.mongodb.org/manual/reference/connection-string/");
        System.exit(1);
      }
```

The "DNS Seed List Connection Format" should be [supported by "mongo-java-driver-3.8.0.jar"](https://mongodb.github.io/mongo-java-driver/3.8/whats-new/) since that driver support v3.6 and this feature was new to v3.6

MongoDB Atlas prefers the use of the "DNS Seed List Connection Format". So testing Atlas clusters with ycsb is troublesome with this limitation. 

There's probably no need to even check the URI because the MongoDB driver validates the URI as well.

**Comment by busbey** [comment]
Sounds reasonable. Could you put up a PR?

**Comment by SteveH-US** [comment]
I found this bug in 0.17, but the issue appears to have been fixed in master. It appears that you just need to produce a new release.

**Comment by morcelicaio** [comment]
Hi, @SteveH-US and @busbey .

I'm trying to run ycsb on mongodb atlas cluster but not having success.

I'm using the following connection string in the 'mongodb.url' parameter:

**-p mongodb.url=mongodb+srv://clusterycsb.oyia8.mongodb.net/ycsb**

And I'm getting the error:
**ERROR: Invalid URL: 'mongodb+srv://clusterycsb.oyia8.mongodb.net/ycsb'.**

**Must be of the form 'mongodb://<host1>:<port1>,<host2>:<port2>/database?options'.**

See http://docs.mongodb.org/manual/reference/connection-string/.
Command execution failed.

Do you have any idea how I can run YCSB on MongoDB Atlas?

**Comment by morcelicaio** [comment]
![image](https://user-images.githubusercontent.com/21083525/162086925-76a1085d-5768-4d96-a878-102b45192a0f.png)
