### ISSUE TITLE
The "org.apache.maven.plugins" source and target version need to be updated from "1.6" to "1.8"

### ISSUE THREAD

**Issue by SteveH-US** [brianfrankcooper/YCSB#1502]
Version "1.6" is no longer supported. 

The following error is currently produced when compiling:
```
error: Source option 6 is no longer supported. Use 7 or later.
```
This version needs to updated in "pom.xml" to "1.8"

**Comment by busbey** [comment]
What version of the jdk are you using to build?

**Comment by busbey** [comment]
And what version of ycsb are you trying to build?

**Comment by busbey** [comment]
We should already be using a source and target version of 1.8. please provide the full details of the failure

**Comment by SteveH-US** [comment]
Sorry, I was looking at the wrong  stanza.
