### ISSUE TITLE
Low throughput while benchmarking DynamoDB using YCSB

### ISSUE THREAD

**Issue by rohannarde** [brianfrankcooper/YCSB#151]
Hello,

I created a DyanamoDB table as instructed using a hash for "firstname" and assigned a read throughput of 1000 and a write throughput of 750. In the dynamodb.properties file in YCSB/dynamodb/conf I defaulted most of the settings including consistentReads as false.

I ran dynamoDB with varying recordcounts of 1000, 10000 and 50,000 and was surprised when I could achieve throughputs of 15-50 ops/sec on most of the workloads. I followed the workload sequence specified in "CoreWorkloads" page.

https://github.com/brianfrankcooper/YCSB/wiki/Core-Workloads

I ran the following command to load,

bin/ycsb load dynamodb -P dynamodb/conf/dynamodb.properties -p recordcount=1000 -p debug=true -P workloads/workloada -s > workloada_load.txt

To run the workload,

bin/ycsb run dynamodb -P dynamodb/conf/dynamodb.properties  -p operationcount=1000 -p debug=true -P workloads/workloada -t -s > workloada_run.txt

 Could there be something that I missed while configuring? Should I change the number of threads from the default value of 1?

Any help would be welcome.

--Rohan

**Comment by busbey** [comment]
closing as stale. If you are still working on this issue, please reopen.

(the record count / operation count observation above sounds like contention in the datastore over access to the smaller number of records)
