### ISSUE TITLE
"mvn clean package" failed when binding MapKeeper.

### ISSUE THREAD

**Issue by amber-zhang** [brianfrankcooper/YCSB#152]
Hi,

When I ran "mvn clean package" to create project, I got this error when binding MapKeeper. Although I manually downloaded MapKeeper.jar and put it ./YCSB-master/mapkeeper/target, the error still occur. How can I fix the problem? thank you!

[INFO] YCSB Root ......................................... SUCCESS [0.689s]
[INFO] Core YCSB ......................................... SUCCESS [4.593s]
[INFO] Cassandra DB Binding .............................. SUCCESS [5.774s]
[INFO] HBase DB Binding .................................. SUCCESS [15.647s]
[INFO] Hypertable DB Binding ............................. SUCCESS [4.104s]
[INFO] DynamoDB DB Binding ............................... SUCCESS [5.083s]
[INFO] ElasticSearch Binding ............................. SUCCESS [7.186s]
[INFO] Infinispan DB Binding ............................. SUCCESS [29.247s]
[INFO] JDBC DB Binding ................................... SUCCESS [4.041s]
[INFO] Mapkeeper DB Binding .............................. FAILURE [1.477s]
[INFO] Mongo DB Binding .................................. SKIPPED
[INFO] OrientDB Binding .................................. SKIPPED
[INFO] Redis DB Binding .................................. SKIPPED
[INFO] Voldemort DB Binding .............................. SKIPPED
[INFO] YCSB Release Distribution Builder ................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:18.023s
[INFO] Finished at: Thu Dec 05 05:17:52 EST 2013
[INFO] Final Memory: 125M/304M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project mapkeeper-binding: Could not resolve dependencies for project com.yahoo.ycsb:mapkeeper-binding:jar:0.1.4: Failed to collect dependencies at com.yahoo.mapkeeper:mapkeeper:jar:1.0: Failed to read artifact descriptor for com.yahoo.mapkeeper:mapkeeper:jar:1.0: Could not transfer artifact com.yahoo.mapkeeper:mapkeeper:pom:1.0 from/to mapkeeper-releases (https://raw.github.com/m1ch1/m1ch1-mvn-repo/master/releases): TransferFailedException: ClientProtocolException: The server failed to respond with a valid HTTP response -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :mapkeeper-binding

**Comment by busbey** [comment]
current build failures fixed by #210. getting things working again for leveldb will stay in #181.
