### ISSUE TITLE
Couchdb

### ISSUE THREAD

**Issue by andrecalcada** [brianfrankcooper/YCSB#1524]
Hi I'm trying to test couch db bust there's no data for couchdb in this version. I found one in version 0.1.4 but it doesn't work can you help please?

**Comment by andrecalcada** [comment]
in version 0.1.4 when try to load a workload it gives an error
![image](https://user-images.githubusercontent.com/52075321/112855426-af99df80-90a6-11eb-8442-f73a9c85218c.png)

**Comment by busbey** [comment]
you must be on a fork. YCSB has never had couchdb support AFAICT.

Here's is the 0.1.4 version of the set of support datastores in our repo, which lacks couchdb:

https://github.com/brianfrankcooper/YCSB/blob/0.1.4/bin/ycsb#L26
