### ISSUE TITLE
load redis error

### ISSUE THREAD

**Issue by Muktikanta0123** [brianfrankcooper/YCSB#1529]
While loading redis I am getting this error:
./bin/ycsb load redis -s -P workloads/workloada -p "redis.host=127.0.0.1" -p "redis.port=6379"
  File "./bin/ycsb", line 223
    except subprocess.CalledProcessError, err:
                                        ^
SyntaxError: invalid syntax

Anyone please help me to fix it.

**Comment by busbey** [comment]
what version of YCSB are you attempting to use?

**Comment by Mukti0123** [comment]
I have just cloned the latest version 0.17.0. I think the problem with the python version. Now it is working, as I am using ./bin/ycsb.sh instead of ./bin/ycsb. Thanks.
