### ISSUE TITLE
  except subprocess.CalledProcessError, err:

### ISSUE THREAD

**Issue by Muktikanta0123** [brianfrankcooper/YCSB#1530]
While loading redis I am getting this error:

./bin/ycsb load redis -s -P workloads/workloada -p "redis.host=127.0.0.1" -p "redis.port=6379"
  File "./bin/ycsb", line 223
    except subprocess.CalledProcessError, err:
                                        ^
SyntaxError: invalid syntax

Can anyone help me to fix?

I am using Python 3.8.5 and javac 11.0.10

**Comment by outloudvi** [comment]
YCSB is not updated for Python 3. Please use Python 2 or apply fixes such as #1421 (I personally haven't tested it yet).
