### ISSUE TITLE
Maven 3 

### ISSUE THREAD

**Issue by Srija2000** [brianfrankcooper/YCSB#1537]
If I use maven3 also I am finding the same issue 
Build failure
![Screenshot (262)](https://user-images.githubusercontent.com/60351574/116838615-97a90480-abec-11eb-839c-94b81288f0de.png)

**Comment by stefanocereda** [comment]
I am getting the exact same error on my pc, where I have arch with maven 3.8.1.
However, running it on ubuntu with maven 3.6.3 works perfectly.

**Comment by busbey** [comment]
marking this as a duplicate of #1557 because there's a good explanation there of what's going on.
