### ISSUE TITLE
Retrying a failed thread

### ISSUE THREAD

**Issue by liujiongxin** [brianfrankcooper/YCSB#1551]
My understanding:
- A thread is allocated a fixed number of operations
- If the thread encounters problem (e.g., due to server being unavailable), the thread will exit immediately, and never come back.

My thought:
I think it's more reasonable for the thread to at least make the target number of attempts. For example, If it targets 100 operations, but fails in the first operation and dies, it should try to start the remaining 99 operations before giving up completely.

If my understanding or thoughts are wrong, please correct me.

Thanks!

**Comment by busbey** [comment]
So long as the datastore specific binding properly implements returning operation Status, YCSB handles failures by measuring the number and latency of failures. If you have a specific case where the datastore-binding allows a failure to propagate to the test framework please file an issue or PR with specific details.
