### ISSUE TITLE
404 error on summary slides

### ISSUE THREAD

**Issue by CES-dengzeyuan** [brianfrankcooper/YCSB#1565]
Hi, I can not reach the summary slides because of the 404 error.

![F15D13BD-6DF8-4761-B3E0-2100A693DD6A](https://user-images.githubusercontent.com/46039524/136697727-fb1b4f78-437d-4dfb-8981-4f75fb62caf0.png)

https://www.brianfrankcooper.net/home/publications/ycsb-v4.pdf

Anyone knows why? Thanks.

**Comment by busbey** [comment]
Looks like the link to the presentation slides has gone dead. I updated the link to the paper to point at a archive.org copy and the ACM digital library.
