### ISSUE TITLE
Old RocksDB version/custom RocksDB build

### ISSUE THREAD

**Issue by dmytroye** [brianfrankcooper/YCSB#1570]
Hi, after some time of using YCSB as benchmarking tool for RocksDB I found that YCSB uses an old precompiled RocksDB (5.11.3) version from maven repo. 

How it could be changed? How we can build our custom builds of RocksDB to test it with YCSB client?

Kind regards,
Dmytro

**Comment by seybi87** [comment]
Hi @dmytroye 
I assume you are using the latest release 0.17.0 ? 

The current master already support `6.2.2`.

In case you need a more up to date version you need to set the version in the maven dependency of the RocksDB client in the [pom.xml](https://github.com/brianfrankcooper/YCSB/blob/master/pom.xml#L143)

As long as the new client version does not break with the current code in the [RockDBClient](https://github.com/brianfrankcooper/YCSB/blob/master/rocksdb/src/main/java/site/ycsb/db/rocksdb/RocksDBClient.java) you can easily update the version.

However you will need to build your own release until the 0.18.0 version is released.

**Comment by dmytroye** [comment]
Hi @seybi87

Thank you for response, now I understand what I was doing not in the best way.

Yes, I use 0.17.0 at the moment. With your tip it works good with the latest 6.25.3.

I have a few more question:

1) maven build is successful without any warnings but after starting load/run some warnings appear (OS Ubuntu 20.04.3): 
![image](https://user-images.githubusercontent.com/87181095/140484927-f8d6629b-6d9d-40b5-ad98-1e900be54d8a.png)
Also there is no warnings when I download prebuild YCSB from:

`curl -O --location https://github.com/brianfrankcooper/YCSB/releases/download/0.17.0/ycsb-0.17.0.tar.gz`

2) Where I can find RocksDB binding after run: `mvn -pl site.ycsb:rocksdb-binding -am clean package`?
3) Can I replace .jar with RocksDB to my own build?

**Comment by seybi87** [comment]
Hi @dmytroye ,

happy that my answers were useful.

> maven build is successful without any warnings but after starting load/run some warnings appear (OS Ubuntu 20.04.3):

Did you build the RocksDB binding `.jar` with the updated version or did you run the code directly via your IDE (or command line)?

If you build the binding via `mvn -pl site.ycsb:rocksdb-binding -am clean package`, the warning at the first line should not appear. 

> Where I can find RocksDB binding after run: mvn -pl site.ycsb:rocksdb-binding -am clean package

You will find a target folder within the `rocksdb-binding-0.17.0` 

> Can I replace .jar with RocksDB to my own build?

Yes, this should work without problems.
