### ISSUE TITLE
How do I generate logs?

### ISSUE THREAD

**Issue by deokershesh** [brianfrankcooper/YCSB#1572]
How do I generate logs, while running any workloads? For example: I am running "workloadc", I want to see what's going on behind the scene, what all SQL/NOSQL queries being generated and executed.

**Comment by deokershesh** [comment]
Just to add, I am not talking about log which it creates while "redirecting" into the file during the run. Basically, more of internal logging of the operations YCSB is performing like generating the SQL/NOSQL queries to be run in the underlying database.

**Comment by andrehgdias** [comment]
I think YCSB doesn't have this feature, it would be really nice to have, but would probably increase the time to perform the tests by a lot. Imagine printing out 1KK of operations and its returns.

**Comment by busbey** [comment]
YCSB doesn't currently generate a fine grain log of operations. Please see duplicate #1143
