### ISSUE TITLE
Issues running YCSB client on another machine

### ISSUE THREAD

**Issue by sneha1012** [brianfrankcooper/YCSB#158]
Hello am running data-serving benchmark..am running cassandra on one machine & YCSB on another machine.i ve done client-server setup with SSH..i could able to tranfer the files between two system...when i run YCSB,its not getting connect with server...
could anybody help me to reslove this issue...what settings i should change inside YCSB?????

**Comment by busbey** [comment]
Please include a copy of the error you're getting.

Please ensure the host running Cassandra is not running a firewall (or that said firewall is configured to allow connections to Cassandra from the YCSB client machine)

**Comment by busbey** [comment]
closing as stale. if you are still having this problem please reopen.
