### ISSUE TITLE
How to calculate RAM required by YCSB Client Host

### ISSUE THREAD

**Issue by ashwinivsh** [brianfrankcooper/YCSB#1598]
Hello YCSB Experts,

I'm trying to understand how to calculate RAM required by a YCSB Client Host e.g. I would like to load/insert 1 billion documents in a database using YCSB and each document is of 1KB (10 fields of 100 bytes each). The batch size I'd like to select is 5000 and I'd like to use a thread count of 16 when doing this load/insert operation. How much RAM would I need for my YCSB Client Host?

Another question related to the same load/insert operation of 1 billion docs - how to calculate the time it might take to complete this load/insert test? On a slightly lower number of insert operations I was initially seeing very good throughput which progressively declines and so e.g. initially the YCSB monitor thread log shows estimated completion time of 1 hour but eventually it ended up taking more than 2 hours to complete the load/insert test. Is this kind of progressive slowness while inserting large number of documents a common thing? I'm using the latest checked out code from master branch of https://github.com/brianfrankcooper/YCSB

Thanks,
Ashwini

**Comment by busbey** [comment]
You should use a released version of YCSB.

the time to load will depend on the rate of operations your chosen datastore can sustain. the status output is just a best guess from recent throughput levels.

the amount of memory needed by the client will depend on if the client driver you are using has been configured to do client side caching. The default is supposed to be no client side caching , which should mean you need relatively little memory for the client.

**Comment by seybi87** [comment]
Hi @ashwinivsh 

recently, we were facing the same challenges by benchmarking a DBaaS instance, long story short:

In case you run into `out of heap space` errors you can increase the heap space size of the YCSB with the `-jvm-args=`, e.g. `-jvm-args=-XX:MaxRAMPercentage=85.0`. This solved the issue for our benchmarking case.

**Comment by ashwinivsh** [comment]
> Hi @ashwinivsh
> 
> recently, we were facing the same challenges by benchmarking a DBaaS instance, long story short:
> 
> In case you run into `out of heap space` errors you can increase the heap space size of the YCSB with the `-jvm-args=`, e.g. `-jvm-args=-XX:MaxRAMPercentage=85.0`. This solved the issue for our benchmarking case.

Thanks @seybi87. I too had run into the "out of heap space" problem and fixed it using "-jvm-args=" parameter.

My query was mainly from the perspective of "how to calculate the RAM" required, which got answered by @busbey's response.

**Comment by ashwinivsh** [comment]
> You should use a released version of YCSB.
> 
> the time to load will depend on the rate of operations your chosen datastore can sustain. the status output is just a best guess from recent throughput levels.
> 
> the amount of memory needed by the client will depend on if the client driver you are using has been configured to do client side caching. The default is supposed to be no client side caching , which should mean you need relatively little memory for the client.

Thanks a lot.

Has anyone in your experience seen or reported the kind of progressive slowing down of the YCSB client's document insertion speed, while inserting large number of documents, as I reported above? If yes, in those instances, did the issue turn out to be due to the database server itself? If no one has reported or observed such an issue, any suggestions on how to debug it? Thanks

**Comment by seybi87** [comment]
> Has anyone in your experience seen or reported the kind of progressive slowing down of the YCSB client's document insertion speed, while inserting large number of documents, as I reported above? If yes, in those instances, did the issue turn out to be due to the database server itself? If no one has reported or observed such an issue, any suggestions on how to debug it? Thanks

We have run a lot of benchmarks against different database with a full monitoring stack in place (i.e. monitoring the YCSB instance and the database instances) and based on the system metrics we did not see any reason for a "performance decrease" of the YCSB instance.

However, on the database side, we see a clear decrease in performance over time if a large number of records is inserted (especially when using batched inserts). 

The performance decrease occurs because the database becomes overloaded with the applied workload, i.e. the database internal processes such as indexing, compaction, buffer handling, ... are overloaded with the applied workload. System and database monitoring data show this clearly.   

Of course this is not a general affect but highly depends on the target database, the applied resources to run the database and the applied workload.
