### ISSUE TITLE
How stupid ycsb for hbase

### ISSUE THREAD

**Issue by dryangkun** [brianfrankcooper/YCSB#161]
The first error：package org.apache.hadoop.conf does not exist
The second error：org.slf4j.impl.StaticLoggerBinder.getSingleton()Lorg/slf4j/impl/StaticLoggerBinder;

I just make benchmark for hbase, but it spend my a whole of morning.

**Comment by busbey** [comment]
closed as stale. @dryangkun if you're still having problems reopen and we'll figure out what's wrong with your deployment.
