### ISSUE TITLE
ArangoDB YCSB 0.17.0 slf4j Bug

### ISSUE THREAD

**Issue by masterElmar** [brianfrankcooper/YCSB#1634]
When starting a load or run benchmark, it always returns this error.

```bash
Loading workload...
Starting test.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022-08-24 13:55:09:561 0 sec: 0 operations; est completion in 0 second
```

I build the binding with MVN by my self and downloaded the latest release, both won't work.

That the bash command that I used:

`./bin/ycsb.sh load arangodb -s -P workloads/workloada -p arangodb.ip=46.101.229.237 -p arangodb.port=8529`

Hope this bug could be fixed.
With kind regards
Elmar

**Comment by Varagos** [comment]
It looks like you are missing a jar. Navigate into your ycsb/lib folder and add it 
`curl -L -O 'https://search.maven.org/remotecontent?filepath=org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25.jar'`
