### ISSUE TITLE
Can I get the result of 99th-latency for entire workload?

### ISSUE THREAD

**Issue by Ychanho** [brianfrankcooper/YCSB#1637]
What should I do if I want to see the result of 99th-latency for my '**entire**' workload?

for example, 
when the workload setting is 
readproprtion=0.95, updateproportion=0.05

then the results are maybe like as follows ('@@@', '###', '$$$' are something constant value)

[READ], 99thPercentileLatency(us), '@@@'
[UPDATE], 99thPercentileLatency(us), '###'

but I want to see 99th-latency for the **'entire workload'**, like

[OVERALL], 99thPercentileLatency(us), '$$$'

not latency for each of READ or UPDATE or other.

Is there any command for this?

**Comment by busbey** [comment]
we don't currently measure things across operations, so there's no option to output it.

**Comment by DELAB-Y** [comment]
Thank you for your answer!
