### ISSUE TITLE
Running YCSB Workload

### ISSUE THREAD

**Issue by VinaySheth** [brianfrankcooper/YCSB#1640]
Whenever we are setting the operation count property, is it for a particular thread or for all the threads (as defined using the threadcount property)? 

If it is collectively used for all the threads, how can I specify the number of operations each thread should perform?

**Comment by busbey** [comment]
it's across all client threads. the operations are always uniformly distributed.

**Comment by VinaySheth** [comment]
Thank you for your reply @busbey !
