### ISSUE TITLE
Core Property: request distribution

### ISSUE THREAD

**Issue by VinaySheth** [brianfrankcooper/YCSB#1642]
Could you please explain the various types of distributions (uniform, zipfian, hotspot, sequential, exponential, latest) in detail?

**Comment by VinaySheth** [comment]
> Could you please explain the various types of distributions (uniform, zipfian, hotspot, sequential, exponential, latest) in detail?

@brianfrankcooper Is there any documentation available for this?

**Comment by busbey** [comment]
please do not ping individual maintainers.

If you want details on request distributions you'll have to look at source:

https://github.com/brianfrankcooper/YCSB/blob/0.17.0/core/src/main/java/site/ycsb/workloads/CoreWorkload.java#L459

the various generators that create the distributions are all in here, most have a class level doc with an explanation:

https://github.com/brianfrankcooper/YCSB/tree/0.17.0/core/src/main/java/site/ycsb/generator

**Comment by VinaySheth** [comment]
> please do not ping individual maintainers.
> 
> If you want details on request distributions you'll have to look at source:
> 
> https://github.com/brianfrankcooper/YCSB/blob/0.17.0/core/src/main/java/site/ycsb/workloads/CoreWorkload.java#L459
> 
> the various generators that create the distributions are all in here, most have a class level doc with an explanation:
> 
> https://github.com/brianfrankcooper/YCSB/tree/0.17.0/core/src/main/java/site/ycsb/generator

Thank You very much for your response!
