### ISSUE TITLE
ycsb: error: argument database: invalid choice: 'scylla'

### ISSUE THREAD

**Issue by qiuxinyidian** [brianfrankcooper/YCSB#1659]
ycsb version 0.17.0
centos 7
scylla version: scylla-server-5.1.2

`[root@node1 ycsb-0.17.0]# ./scylla/ycsb-0.17.0/bin/ycsb load scylla -s  -P workloads/workloada -p scylla.username=cassandra -p scylla.password=cassandra -p cassandra.cluster=192.168.167.67:9042,192.168.167.68:9042,192.168.167.122:9042  -p  cassandra.connections=3 -p threadcount=96 -p recordcount=100000000 -p insertstart=0 -p insertcount=33000000 
-bash: ./scylla/ycsb-0.17.0/bin/ycsb: No such file or directory
[root@node1 ycsb-0.17.0]# bin/ycsb load scylla -s  -P workloads/workloada -p scylla.username=cassandra -p scylla.password=cassandra -p cassandra.cluster=192.168.167.67:9042,192.168.167.68:9042,192.168.167.122:9042  -p  cassandra.connections=3 -p threadcount=96 -p recordcount=100000000 -p insertstart=0 -p insertcount=33000000 
usage: bin/ycsb command database [options]

Commands:
    load           Execute the load phase
    run            Execute the transaction phase
    shell          Interactive mode

Databases:
    accumulo       https://github.com/brianfrankcooper/YCSB/tree/master/accumulo
    accumulo1.6    https://github.com/brianfrankcooper/YCSB/tree/master/accumulo1.6
    accumulo1.7    https://github.com/brianfrankcooper/YCSB/tree/master/accumulo1.7
    accumulo1.8    https://github.com/brianfrankcooper/YCSB/tree/master/accumulo1.8
    aerospike      https://github.com/brianfrankcooper/YCSB/tree/master/aerospike
    arangodb       https://github.com/brianfrankcooper/YCSB/tree/master/arangodb
    arangodb3      https://github.com/brianfrankcooper/YCSB/tree/master/arangodb3
    asynchbase     https://github.com/brianfrankcooper/YCSB/tree/master/asynchbase
    azurecosmos    https://github.com/brianfrankcooper/YCSB/tree/master/azurecosmos
    azuretablestorage https://github.com/brianfrankcooper/YCSB/tree/master/azuretablestorage
    basic          https://github.com/brianfrankcooper/YCSB/tree/master/basic
    basicts        https://github.com/brianfrankcooper/YCSB/tree/master/basicts
    cassandra-cql  https://github.com/brianfrankcooper/YCSB/tree/master/cassandra
    cassandra2-cql https://github.com/brianfrankcooper/YCSB/tree/master/cassandra2
    cloudspanner   https://github.com/brianfrankcooper/YCSB/tree/master/cloudspanner
    couchbase      https://github.com/brianfrankcooper/YCSB/tree/master/couchbase
    couchbase2     https://github.com/brianfrankcooper/YCSB/tree/master/couchbase2
    crail          https://github.com/brianfrankcooper/YCSB/tree/master/crail
    dynamodb       https://github.com/brianfrankcooper/YCSB/tree/master/dynamodb
    elasticsearch  https://github.com/brianfrankcooper/YCSB/tree/master/elasticsearch
    elasticsearch5 https://github.com/brianfrankcooper/YCSB/tree/master/elasticsearch5
    elasticsearch5-rest https://github.com/brianfrankcooper/YCSB/tree/master/elasticsearch5
    foundationdb   https://github.com/brianfrankcooper/YCSB/tree/master/foundationdb
    geode          https://github.com/brianfrankcooper/YCSB/tree/master/geode
    googlebigtable https://github.com/brianfrankcooper/YCSB/tree/master/googlebigtable
    googledatastore https://github.com/brianfrankcooper/YCSB/tree/master/googledatastore
    griddb         https://github.com/brianfrankcooper/YCSB/tree/master/griddb
    hbase098       https://github.com/brianfrankcooper/YCSB/tree/master/hbase098
    hbase10        https://github.com/brianfrankcooper/YCSB/tree/master/hbase10
    hbase12        https://github.com/brianfrankcooper/YCSB/tree/master/hbase12
    hbase14        https://github.com/brianfrankcooper/YCSB/tree/master/hbase14
    hbase20        https://github.com/brianfrankcooper/YCSB/tree/master/hbase20
    hypertable     https://github.com/brianfrankcooper/YCSB/tree/master/hypertable
    ignite         https://github.com/brianfrankcooper/YCSB/tree/master/ignite
    ignite-sql     https://github.com/brianfrankcooper/YCSB/tree/master/ignite
    infinispan     https://github.com/brianfrankcooper/YCSB/tree/master/infinispan
    infinispan-cs  https://github.com/brianfrankcooper/YCSB/tree/master/infinispan
    jdbc           https://github.com/brianfrankcooper/YCSB/tree/master/jdbc
    kudu           https://github.com/brianfrankcooper/YCSB/tree/master/kudu
    maprdb         https://github.com/brianfrankcooper/YCSB/tree/master/maprdb
    maprjsondb     https://github.com/brianfrankcooper/YCSB/tree/master/maprjsondb
    memcached      https://github.com/brianfrankcooper/YCSB/tree/master/memcached
    mongodb        https://github.com/brianfrankcooper/YCSB/tree/master/mongodb
    mongodb-async  https://github.com/brianfrankcooper/YCSB/tree/master/mongodb
    nosqldb        https://github.com/brianfrankcooper/YCSB/tree/master/nosqldb
    orientdb       https://github.com/brianfrankcooper/YCSB/tree/master/orientdb
    postgrenosql   https://github.com/brianfrankcooper/YCSB/tree/master/postgrenosql
    rados          https://github.com/brianfrankcooper/YCSB/tree/master/rados
    redis          https://github.com/brianfrankcooper/YCSB/tree/master/redis
    rest           https://github.com/brianfrankcooper/YCSB/tree/master/rest
    riak           https://github.com/brianfrankcooper/YCSB/tree/master/riak
    rocksdb        https://github.com/brianfrankcooper/YCSB/tree/master/rocksdb
    s3             https://github.com/brianfrankcooper/YCSB/tree/master/s3
    solr           https://github.com/brianfrankcooper/YCSB/tree/master/solr
    solr6          https://github.com/brianfrankcooper/YCSB/tree/master/solr6
    tablestore     https://github.com/brianfrankcooper/YCSB/tree/master/tablestore
    tarantool      https://github.com/brianfrankcooper/YCSB/tree/master/tarantool

Options:
    -P file        Specify workload file
    -cp path       Additional Java classpath entries
    -jvm-args args Additional arguments to the JVM
    -p key=value   Override workload property
    -s             Print status to stderr
    -target n      Target ops/sec (default: unthrottled)
    -threads n     Number of client threads (default: 1)

Workload Files:
    There are various predefined workloads under workloads/ directory.
    See https://github.com/brianfrankcooper/YCSB/wiki/Core-Properties
    for the list of workload properties.
ycsb: error: argument database: invalid choice: 'scylla' (choose from 'accumulo', 'accumulo1.6', 'accumulo1.7', 'accumulo1.8', 'aerospike', 'arangodb', 'arangodb3', 'asynchbase', 'azurecosmos', 'azuretablestorage', 'basic', 'basicts', 'cassandra-cql', 'cassandra2-cql', 'cloudspanner', 'couchbase', 'couchbase2', 'crail', 'dynamodb', 'elasticsearch', 'elasticsearch5', 'elasticsearch5-rest', 'foundationdb', 'geode', 'googlebigtable', 'googledatastore', 'griddb', 'hbase098', 'hbase10', 'hbase12', 'hbase14', 'hbase20', 'hypertable', 'ignite', 'ignite-sql', 'infinispan', 'infinispan-cs', 'jdbc', 'kudu', 'maprdb', 'maprjsondb', 'memcached', 'mongodb', 'mongodb-async', 'nosqldb', 'orientdb', 'postgrenosql', 'rados', 'redis', 'rest', 'riak', 'rocksdb', 's3', 'solr', 'solr6', 'tablestore', 'tarantool')
`

**Comment by seybi87** [comment]
Hi @qiuxinyidian 

the release `0.17.0` does not contain the ScyllaDB binding, it is included with the `0.18.0` which currently needs to be built by yourself. 

With the `0.18.0` it works without problems, we used it to run large scale benchmark studies against ScyllaDB.

**Comment by qiuxinyidian** [comment]
@seybi87 how to get 0.18.0 ? clone master branch ?

**Comment by seybi87** [comment]
Yes, clone and build it with maven, see: https://github.com/brianfrankcooper/YCSB#building-from-source
