### ISSUE TITLE
Error in using YCSB with Gemfire

### ISSUE THREAD

**Issue by prashant23** [brianfrankcooper/YCSB#168]
Hii Am Using YCSB for Benchmarking Pivotal Gemfire My Gemfire server is running properly and by using following command am running the benchmarking test.

bin/ycsb load gemfire -P workloads/workloada -p gemfire.serverhost=x.x.x.x -P gemfire-binding/conf/cache.xml -p gemfire.serverport=40404 -s > load.txt

Loading workload... Starting test. 0 sec: 0 operations; Exception in thread "Thread-1" java.lang.IllegalStateException: You must use client-cache in the cache.xml when ClientCacheFactory is used. at com.gemstone.gemfire.internal.cache.xmlcache.CacheCreation.create(CacheCreation.java:316) at com.gemstone.gemfire.internal.cache.xmlcache.CacheXmlParser.create(CacheXmlParser.java:274) at com.gemstone.gemfire.internal.cache.GemFireCacheImpl.loadCacheXml(GemFireCacheImpl.java:3495) at com.gemstone.gemfire.internal.cache.GemFireCacheImpl.initializeDeclarativeCache(GemFireCacheImpl.java:926) at com.gemstone.gemfire.internal.cache.GemFireCacheImpl.init(GemFireCacheImpl.java:708) at com.gemstone.gemfire.internal.cache.GemFireCacheImpl.create(GemFireCacheImpl.java:533) at com.gemstone.gemfire.cache.client.ClientCacheFactory.basicCreate(ClientCacheFactory.java:207) at com.gemstone.gemfire.cache.client.ClientCacheFactory.create(ClientCacheFactory.java:161) at com.yahoo.ycsb.db.GemFireClient.init(GemFireClient.java:125) at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:63) at com.yahoo.ycsb.ClientThread.run(Client.java:189) 0 sec: 0 operations;

Please anybody tell can tell me where am going wrong

Thanks in advance

**Comment by busbey** [comment]
hi @prashant23! are you still able to try solutions to this? could you see if the changes in #268 solves your issue?

**Comment by busbey** [comment]
Closing as stale. If someone else runs into this and can work with us to troubleshoot, please reopen.
