### ISSUE TITLE
mongodb appear READ-FAILED and UPDATE-FAILED 

### ISSUE THREAD

**Issue by 2310652493** [brianfrankcooper/YCSB#1703]
![image](https://github.com/brianfrankcooper/YCSB/assets/88769942/8ed1961a-6684-407d-923b-a1038fb0aa8e)
![image](https://github.com/brianfrankcooper/YCSB/assets/88769942/364c3d68-2df7-430d-a7aa-4a89f6689ac6)
I encountered an issue while testing mongo, with READ-FAILED and UPDATE-FAILED appearing. How can I handle it
 This is the command to run
./bin/ycsbrun mongodb - s - p workload=site. ycsb.workloads CoreWorkload - p recordcount=100- p operationcount=50- p insertpromotion=0 - p readpromotion=50 -p updatepromotion=50- p requestdistribution=zipfan - p mongodb. URL=“ mongodb://abc:wecon123 @192.168.0.74:27017/test "- threads 8

**Comment by seybi87** [comment]
Hi @2310652493 did you run the `load` command before running the `run` command?

Looks like no records to update or read are found in the database, so you might have not successfully loaded the database via the `load` command.
