### ISSUE TITLE
Central problem

### ISSUE THREAD

**Issue by aviadzuc** [brianfrankcooper/YCSB#174]
I'm trying to compile the code as is (on Ubuntu machine), but keep getting an error 
"Failed to execute goal on project cassandra-binding: Could not resolve dependencies for project com.yahoo.ycsb:cassandra-binding:jar:0.1.4: Could not find artifact com.yahoo.ycsb:core:jar:0.1.4 in central (http://repo.maven.apache.org/maven2)"

Core compiles fine. I'm a newbie to Java and Maven etc, but this seems to indicate there's a problem in the central repository that YCSB is trying to access. Looking at it I dont find the relevant jar file
http://search.maven.org/#browse|-2026234819

Am I doing something wrong, or has something changed?
Thank you

**Comment by haishmg** [comment]
Were you able to fix this. I am facing same issues

**Comment by pgaref** [comment]
Check that you are actually using the central maven repo, you can try adding to you pom file this:
<repository>              
          <id>central</id>
          <name>Central</name>
          <url>http://repo1.maven.org/maven2</url>
</repository>

I also know for sure some dependencies like mapkeeper is not deleted from the central maven repo so you could comment it out from the pom file until it is fixed.

**Comment by busbey** [comment]
@haishmg  can you give more details on what command you're running? building top level currently works from master AFAICT.

**Comment by busbey** [comment]
closing as stale. if you are still facing this issue with the current master branch, please reopen.
