### ISSUE TITLE
YCSB shouldn't build a tar.gz when you run clean install -DskipTests

### ISSUE THREAD

**Issue by posix4e** [brianfrankcooper/YCSB#177]
Generally people expect a mvn package command will be run if you want to build a tar.gz

**Comment by busbey** [comment]
the maven "install" lifecycle phase implies the "package" one ([ref the maven lifecycle intro](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#Lifecycle_Reference))
