### ISSUE TITLE
error when using workloade for mongodb test

### ISSUE THREAD

**Issue by ylouis83** [brianfrankcooper/YCSB#184]
when I use workloade mode for scan range query:

[root@mysqlstd ycsb-0.1.4]#  ./bin/ycsb run  mongodb -P workloads/workloade  -P large.dat -p mongodb.url=mongodb://127.0.0.1:27017 -p mongodb.database=newdb2 -p mongodb.writeConcern=normal  -s  >data
Loading workload...
Starting test.
 0 sec: 0 operations; 
java.lang.ClassCastException: [B cannot be cast to java.lang.String
java.lang.ClassCastException: [B cannot be cast to java.lang.String
java.lang.ClassCastException: [B cannot be cast to java.lang.String
java.lang.ClassCastException: [B cannot be cast to java.lang.String
java.lang.ClassCastException: [B cannot be cast to java.lang.String

but workloadc is right:

[root@mysqlstd ycsb-0.1.4]#  ./bin/ycsb run  mongodb -P workloads/workloadc  -P large.dat -p mongodb.url=mongodb://127.0.0.1:27017 -p mongodb.database=newdb2 -p mongodb.writeConcern=normal  -s  >data
Loading workload...
Starting test.
 0 sec: 0 operations; 
 10 sec: 43764 operations; 4358.1 current ops/sec; [READ AverageLatency(us)=217.29] 
 20 sec: 98842 operations; 5506.15 current ops/sec; [READ AverageLatency(us)=178.14] 
 20 sec: 100000 operations; 4559.06 current ops/sec; [READ AverageLatency(us)=215.32]

**Comment by benjaminbrent** [comment]
I think this bug is fixed in 87c8e1f05fd472df53f23348938a5af32ddea77e. You could try running the workload again after making that change. Let me know the outcome if you do this.

**Comment by busbey** [comment]
closing as stale. please reopen if you are still having this problem after the change mentioned above.
