### ISSUE TITLE
standalone hbase, ycsb doesn't load the data... [question]

### ISSUE THREAD

**Issue by arapov** [brianfrankcooper/YCSB#186]
Hello,

I've followed the guide available here(wiki/github) ... 
1. I have running standalone hbase, which I actually using for development projects (iow, it works).
2. I created 'usertable','family'
3. When I run '# bin/ycsb load hbase -P workloads/workloada -p columnfamily=family -s' it doesn't load anyting, see the output below. 
Please, give me a hint where is the problem could be... (I don't see anything suspicious in hbase logs too)

oading workload...
Starting test.
 0 sec: 0 operations;
14/08/04 14:43:21 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.3.2-1031432, built on 11/05/2010 05:32 GMT
14/08/04 14:43:21 INFO zookeeper.ZooKeeper: Client environment:host.name=opentdsb-ams.troglodyte.com
14/08/04 14:43:21 INFO zookeeper.ZooKeeper: Client environment:java.version=1.8.0_11
14/08/04 14:43:21 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Oracle Corporation
14/08/04 14:43:21 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/java/jre1.8.0_11
14/08/04 14:43:21 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/opt/ycsb-0.1.4/core/lib/core-0.1.4.jar:/opt/ycsb-0.1.4/hbase-binding/conf:/opt/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/opt/ycsb-0.1.4/gemfire-binding/conf:/opt/ycsb-0.1.4/infinispan-binding/conf:/opt/ycsb-0.1.4/jdbc-binding/conf:/opt/ycsb-0.1.4/nosqldb-binding/conf:/opt/ycsb-0.1.4/voldemort-binding/conf
14/08/04 14:43:21 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
14/08/04 14:43:21 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/08/04 14:43:21 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/08/04 14:43:21 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/08/04 14:43:21 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/08/04 14:43:21 INFO zookeeper.ZooKeeper: Client environment:os.version=3.10.0-123.4.4.el7.x86_64
14/08/04 14:43:21 INFO zookeeper.ZooKeeper: Client environment:user.name=anton
14/08/04 14:43:21 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/anton
14/08/04 14:43:21 INFO zookeeper.ZooKeeper: Client environment:user.dir=/opt/ycsb-0.1.4
14/08/04 14:43:21 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=localhost:2181 sessionTimeout=180000 watcher=hconnection
14/08/04 14:43:21 INFO zookeeper.ClientCnxn: Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181
14/08/04 14:43:21 INFO zookeeper.ClientCnxn: Socket connection established to localhost/0:0:0:0:0:0:0:1:2181, initiating session
14/08/04 14:43:21 INFO zookeeper.ClientCnxn: Session establishment complete on server localhost/0:0:0:0:0:0:0:1:2181, sessionid = 0x147a0f438d70012, negotiated timeout = 40000
 10 sec: 0 operations;
 20 sec: 0 operations;
...

**Comment by busbey** [comment]
Can you retry with the current HBase bindings? This should work now.

**Comment by risdenk** [comment]
Closing since no update in 6 months.
