### ISSUE TITLE
How to use YCSB to test LevelDB?

### ISSUE THREAD

**Issue by panfengfeng** [brianfrankcooper/YCSB#194]
Hi, 
    is there any ways or stepsof using YCSB to test the performance of LevelDB?

**Comment by cld378632668** [comment]
I will push a module for LevelDB.

**Comment by LiujiaHuan** [comment]
> 

Thanks , I am looking forward to it

**Comment by Nana-nn** [comment]
Seems like the module for leveldb still not exists.
