### ISSUE TITLE
YCSB java out of memory error with mysql jdbc scan

### ISSUE THREAD

**Issue by renep123** [brianfrankcooper/YCSB#196]
Hi,
I have setup a 10GB mysql database using ycsb (0.1.4). When I am running the workloade (scan test) against my database, I end up in java out of memory error "Exception in thread "Thread-1" java.lang.OutOfMemoryError: Java heap space".

I can see some commits back in 2012 to fix some scan issue with jdbc in the git repo that adds a fetch size parameter. I am using the following command to run workloade, still I get the error:-

./bin/ycsb run jdbc -P workloads/workloade -p db.driver=com.mysql.jdbc.Driver -p db.url=jdbc:mysql://localhost:3306/testycsbWA -p db.user=username -p jdbc.fetchsize=1 -p recordcount=10 -p operationcount=10 -p maxexecutiontime=1800

I am not sure if the fix works for mysql or if I need to use any more parameters. Could someone help me out to identify/fix the error? 

Thanks!

**Comment by busbey** [comment]
you can now pass a command line arg to give the YCSB client more java heap, see #261

**Comment by kruthar** [comment]
OOM errors with the JDBC module doing scan operations initially found in #171, known issue.

**Comment by kruthar** [comment]
@renep123 - #171 was fixed with #468, does this fix you issue?
