### ISSUE TITLE
benchmark couchdb [solved]

### ISSUE THREAD

**Issue by laphory** [brianfrankcooper/YCSB#200]
I've added a new interface layer for couchdb and the command "mvn clean package" worked fine. When i try to start ycsb with the command "./bin/ycsb load couchdb -P workloads/workloada" it says, the database "couchdb" doesnt exit. I've installed couchdb and it works, also the interface layer worked fine when i resolved the dependencies.
(I've got the folder couchdb in the folder YCSB. the folder couchdb contains the folder YCSB-couchdb-binding-master from arnaud123, the folder "org.ektorp" and a pom.xml)
Can someone help me? Thanks

Solved: see github/arnaud123

**Comment by busbey** [comment]
closing for now. please reopen if you are still having problems.
