### ISSUE TITLE
how can i use YCSB to test hbase with java 

### ISSUE THREAD

**Issue by HubSKY** [brianfrankcooper/YCSB#201]
i want to write a program like a web client to test hbase with YCSB,but  how can i use the YCSB in my own java program

**Comment by busbey** [comment]
YCSB isn't really made to be programmatically driven. You can take a look at the core/src/main/java/com/yahoo/ycsb/Client.java file to see what it invokes when run from the command line.

**Comment by busbey** [comment]
closing as stale. If you still are trying to get this working, please let us know!
