### ISSUE TITLE
when i compile YCSB ,bug appear as follow

### ISSUE THREAD

**Issue by HubSKY** [brianfrankcooper/YCSB#202]
Failed to execute goal on project hbase-binding: Could not resolve dependencies for project com.yahoo.ycsb:hbase-binding:jar:0.1.4: Failure to find org.apache.hbase:hbase:jar:0.98.5 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Comment by busbey** [comment]
this is a problem from the hbase artifact refactoring from 0.94 -> 0.98. the hbase jar changed to hbase-client. The new hbase-1.0 binding *should* work for it, but I'll confirm with 0.98 before closing.

**Comment by risdenk** [comment]
@HubSKY is this still an issue with the latest YCSB release? This most likely changed with splitting of HBase bindings with PR #392

**Comment by busbey** [comment]
Confirmed that this is no longer an issue.
