### ISSUE TITLE
Problems when i testing for Hbase

### ISSUE THREAD

**Issue by xuxc** [brianfrankcooper/YCSB#203]
Hi:
How to show progress every 5 sec?
It just show time once,and run test is useless.
code as follows:
----------------------------------------------------------------------------------

hadoop@namenode:~/ycsb-0.1.4/bin$ ./ycsb load hbase -P ../workloads/workloadc -p threads=10 -p columnfamily=f1 -p recordcount=10000 -s > load.dat
Loading workload...
Starting test.
 0 sec: 0 operations; 
14/12/28 21:48:39 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.5-1392090, built on 09/30/2012 17:52 GMT
14/12/28 21:48:39 INFO zookeeper.ZooKeeper: Client environment:host.name=namenode
14/12/28 21:48:39 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_45
14/12/28 21:48:39 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/12/28 21:48:39 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/jdk1.6.0_45/jre
14/12/28 21:48:39 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/voldemort-binding/conf:/home/hadoop/ycsb-0.1.4/gemfire-binding/conf:/home/hadoop/ycsb-0.1.4/nosqldb-binding/conf:/home/hadoop/ycsb-0.1.4/infinispan-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/asm-3.2.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hadoop-tools-1.0.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hsqldb-1.8.0.10.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/jettison-1.1.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/commons-codec-1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/zookeeper-3.4.5.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/high-scale-lib-1.1.1.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/httpcore-4.1.3.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/jsp-2.1-6.1.14.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hadoop-client-1.0.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/jsp-api-2.1-6.1.14.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/commons-logging-1.1.1.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/commons-math-2.1.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/jasper-runtime-5.5.23.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/jsch-0.1.42.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/junit-4.5.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/commons-net-1.4.1.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/jersey-json-1.8.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/commons-io-2.1.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/commons-el-1.0.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/jackson-mapper-asl-1.8.8.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/jackson-core-asl-1.8.8.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/jsr305-1.3.9.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/jersey-core-1.8.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/guava-11.0.2.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/mockito-all-1.8.5.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/servlet-api-2.5-6.1.14.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/commons-configuration-1.6.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/jets3t-0.6.1.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/libthrift-0.8.0.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/jetty-6.1.26.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/protobuf-java-2.4.0a.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/avro-1.5.3.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/asm-3.1.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hadoop-ant-1.0.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/commons-collections-3.2.1.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/oro-2.0.8.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/commons-beanutils-1.7.0.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/avro-ipc-1.5.3.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hadoop-minicluster-1.0.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-0.94.8.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/jamon-runtime-2.3.1.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/aspectjtools-1.6.5.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/jackson-xc-1.8.8.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/slf4j-api-1.4.3.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/commons-httpclient-3.1.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/commons-lang-2.5.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/commons-httpclient-3.0.1.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/commons-logging-api-1.0.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hadoop-thriftfs-1.0.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/jersey-server-1.8.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/kfs-0.2.2.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/aspectjrt-1.6.5.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/jaxb-api-2.1.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hadoop-capacity-scheduler-1.0.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hadoop-fairscheduler-1.0.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/junit-4.10-HBASE-1.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/commons-digester-1.8.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/jetty-util-6.1.26.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/jackson-jaxrs-1.8.8.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/jaxb-impl-2.2.3-1.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/jruby-complete-1.6.5.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/commons-cli-1.2.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/log4j-1.2.16.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/log4j-1.2.15.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/jasper-compiler-5.5.12.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/activation-1.1.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/core-3.1.1.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/commons-lang-2.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/httpclient-4.1.2.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/slf4j-log4j12-1.4.3.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/servlet-api-2.5-20081211.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/metrics-core-2.1.2.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/jasper-runtime-5.5.12.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hadoop-core-1.0.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/netty-3.2.4.Final.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/jasper-compiler-5.5.23.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/commons-daemon-1.0.1.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/jdeb-0.8.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/lib/commons-beanutils-core-1.8.0.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf
14/12/28 21:48:39 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/jdk1.6.0_45/jre/lib/i386/server:/usr/lib/jvm/jdk1.6.0_45/jre/lib/i386:/usr/lib/jvm/jdk1.6.0_45/jre/../lib/i386:/usr/java/packages/lib/i386:/lib:/usr/lib
14/12/28 21:48:39 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/12/28 21:48:39 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/12/28 21:48:39 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/12/28 21:48:39 INFO zookeeper.ZooKeeper: Client environment:os.arch=i386
14/12/28 21:48:39 INFO zookeeper.ZooKeeper: Client environment:os.version=3.8.0-29-generic
14/12/28 21:48:39 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/12/28 21:48:39 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/12/28 21:48:39 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4/bin
14/12/28 21:48:39 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=datanode1:2181,namenode:2181,datanode2:2181 sessionTimeout=180000 watcher=hconnection
14/12/28 21:48:39 INFO zookeeper.RecoverableZooKeeper: The identifier of this process is 6098@namenode
14/12/28 21:48:39 INFO zookeeper.ClientCnxn: Opening socket connection to server datanode2/192.168.0.202:2181. Will not attempt to authenticate using SASL (无法定位登录配置)
14/12/28 21:48:39 INFO zookeeper.ClientCnxn: Socket connection established to datanode2/192.168.0.202:2181, initiating session
14/12/28 21:48:39 INFO zookeeper.ClientCnxn: Session establishment complete on server datanode2/192.168.0.202:2181, sessionid = 0x24a910d47700003, negotiated timeout = 180000
 5 sec: 10000 operations; 1946.28 current ops/sec; [INSERT AverageLatency(us)=333.86] 
hadoop@namenode:~/ycsb-0.1.4/bin$ ./ycsb run basic -P workloads/workloada -P large.dat -s > transactions.dat
hadoop@namenode:~/ycsb-0.1.4/bin$ 

-------------------------------------------------------------------------------------------

thank you!

**Comment by busbey** [comment]
closing as stale (I believe the advice above is correct), please reopen if still an issue.
