### ISSUE TITLE
hellow,how to use ycsb on hbase-0.98 ??

### ISSUE THREAD

**Issue by zhao777ying** [brianfrankcooper/YCSB#211]
It can correct run with hbase-0.94, but when i use ycsb wiht  hbase-0.98,it seems something wrong.

like this:
15/02/04 16:37:04 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.3-1240972, built on 02/06/2012 10:48 GMT
15/02/04 16:37:04 INFO zookeeper.ZooKeeper: Client environment:host.name=clientsingle
15/02/04 16:37:04 INFO zookeeper.ZooKeeper: Client environment:java.version=1.8.0_25
15/02/04 16:37:04 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Oracle Corporation
15/02/04 16:37:04 INFO zookeeper.ZooKeeper: Client environment:java.home=/opt/jdk1.8.0_25/jre
15/02/04 16:37:04 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/opt/ycsb-0.1.4/infinispan-binding/conf:/opt/ycsb-0.1.4/nosqldb-binding/conf:/opt/ycsb-0.1.4/riak-binding/lib/riak-client-1.1.1-jar-with-dependencies.jar:/opt/ycsb-0.1.4/core/lib/core-0.1.4.jar:/opt/ycsb-0.1.4/jdbc-binding/conf:/opt/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/opt/ycsb-0.1.4/hbase-binding/conf:/opt/ycsb-0.1.4/gemfire-binding/conf:/opt/ycsb-0.1.4/voldemort-binding/conf
15/02/04 16:37:04 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/java/packages/lib/i386:/lib:/usr/lib
15/02/04 16:37:04 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
15/02/04 16:37:04 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
15/02/04 16:37:04 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
15/02/04 16:37:04 INFO zookeeper.ZooKeeper: Client environment:os.arch=i386
15/02/04 16:37:04 INFO zookeeper.ZooKeeper: Client environment:os.version=3.2.0-4-amd64
15/02/04 16:37:04 INFO zookeeper.ZooKeeper: Client environment:user.name=root
15/02/04 16:37:04 INFO zookeeper.ZooKeeper: Client environment:user.home=/root
15/02/04 16:37:04 INFO zookeeper.ZooKeeper: Client environment:user.dir=/opt/ycsb-0.1.4
15/02/04 16:37:04 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=192.168.1.53:2181,192.168.1.27:2181 sessionTimeout=180000 watcher=hconnection
15/02/04 16:37:04 INFO zookeeper.ClientCnxn: Opening socket connection to server /192.168.1.53:2181
15/02/04 16:37:04 INFO zookeeper.RecoverableZooKeeper: The identifier of this process is 13587@clientsingle
15/02/04 16:37:04 INFO client.ZooKeeperSaslClient: Client will not SASL-authenticate because the default JAAS configuration section 'Client' could not be found. If you are not using SASL, you may ignore this. On the other hand, if you expected SASL to work, please fix your JAAS configuration.
15/02/04 16:37:05 INFO zookeeper.ClientCnxn: Socket connection established to slave02/192.168.1.53:2181, initiating session
15/02/04 16:37:05 INFO zookeeper.ClientCnxn: Session establishment complete on server slave02/192.168.1.53:2181, sessionid = 0x24b526583ce0010, negotiated timeout = 90000
 10 sec: 0 operations;
 20 sec: 0 operations;
 30 sec: 0 operations;
 40 sec: 0 operations;
 50 sec: 0 operations;
 60 sec: 0 operations;
 70 sec: 0 operations;
 80 sec: 0 operations;

the operations always is 0 !
please help me,what can i do for using ycsb with hbase-0.98???????
thank you !!!!

**Comment by alexmc6** [comment]
I have just had exactly the same problem. I am using Hortonworks HDP 2.2 which includes HBase 0.98.4
I can see the file with the ZooKeeper Client JAAS info and it does have a Client section. 


$ cat  /etc/zookeeper/conf/zookeeper_client_jaas.conf

Client {
com.sun.security.auth.module.Krb5LoginModule required
useKeyTab=false
useTicketCache=true;
};

Is there anything else I can do to help diagnose the problem?

**Comment by alexmc6** [comment]
PS I am using a Kerberized cluster

**Comment by zhao777ying** [comment]
maybe the problem is occured when you maven the ycsb.

**Comment by zhao777ying** [comment]
how did you install the tool ?

**Comment by alexmc6** [comment]
I just untarred the package from Github, ran  mvn clean package
I then copied the whole directory tree to my hadoop cluster before running the ./bin/ycsb commands. Was that wrong?

**Comment by zhao777ying** [comment]
before you run mvn clean package , you should change the pom.xml that make it 
matching with your hadoop and hbase version.

**Comment by busbey** [comment]
HBase 0.94 clients can't talk to a 0.98 server.  you'll need to build YCSB against 0.98 to talk to a 0.98 server.

**Comment by cmccoy** [comment]
Closing as stale - there's now a separate 0.98 binding.
