### ISSUE TITLE
Cassandra 2.0.12

### ISSUE THREAD

**Issue by ManiKrishnamurthy** [brianfrankcooper/YCSB#216]
Can some one provide a connector class for Cassandra 2.0.12?
Can i also get detailed steps for running ycsb client?

**Comment by cmatser** [comment]
Try out this pull request: #145 

Start with the documentation on running the client and then post with specific questions: https://github.com/brianfrankcooper/YCSB/wiki/Running-a-Workload

Chrisjan

**Comment by busbey** [comment]
this should work now that #145 has been merged. use the [instructions in the CQL client for setting up the table](https://github.com/brianfrankcooper/YCSB/blob/master/cassandra/src/main/java/com/yahoo/ycsb/db/CassandraCQLClient.java#L35) and then the page cmaster referenced above.

**Comment by busbey** [comment]
Closing as stale. Please reopen if the updated instructions don't work.
