### ISSUE TITLE
mvn package failed

### ISSUE THREAD

**Issue by zjiekai** [brianfrankcooper/YCSB#217]
Inspiron-3847:~/dev/github/YCSB$ mvn clean package

[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Hypertable DB Binding 0.1.4
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.hypertable:hypertable:jar:0.9.5.6 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] YCSB Root .......................................... SUCCESS [  1.500 s]
[INFO] Core YCSB .......................................... SUCCESS [  6.918 s]
[INFO] Cassandra DB Binding ............................... SUCCESS [  4.666 s]
[INFO] HBase DB Binding ................................... SUCCESS [ 11.863 s]
[INFO] Hypertable DB Binding .............................. FAILURE [  0.663 s]
[INFO] Accumulo DB Binding ................................ SKIPPED
[INFO] DynamoDB DB Binding ................................ SKIPPED
[INFO] ElasticSearch Binding .............................. SKIPPED
[INFO] Infinispan DB Binding .............................. SKIPPED
[INFO] JDBC DB Binding .................................... SKIPPED
[INFO] Mapkeeper DB Binding ............................... SKIPPED
[INFO] Mongo DB Binding ................................... SKIPPED
[INFO] OrientDB Binding ................................... SKIPPED
[INFO] Redis DB Binding ................................... SKIPPED
[INFO] Voldemort DB Binding ............................... SKIPPED
[INFO] YCSB Release Distribution Builder .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 25.832 s
[INFO] Finished at: 2015-03-18T10:19:15+08:00
[INFO] Final Memory: 58M/776M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project hypertable-binding: Could not resolve dependencies for project com.yahoo.ycsb:hypertable-binding:jar:0.1.4: Failure to find org.hypertable:hypertable:jar:0.9.5.6 in http://172.16.1.22:8081/artifactory/libs-release was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :hypertable-binding

**Comment by cmatser** [comment]
It's unfortunate that some of the modules don't build, but that has been the case.  If you don't need hypertable, you can comment it out of the module from the main pom.xml:



Otherwise, you'll have to fix hypertable.  Looks like it's missing the hypertable.jar.

Good luck.

Chrisjan

**Comment by ABIDD** [comment]
HELLO zjiekai
I install HBase 0.94.14 with hadoop1.0.4 but whenever compiles YCSB (mvn clean package) poses a mistake despite that change pom.xml, please help me

[INFO] HBase DB Binding.............................. FAILURE [ 0.663 s]

**Comment by busbey** [comment]
closed as stale. hypertable currently builds. @ABIDD  please file a new issue for hbase 0.94 not working.
