### ISSUE TITLE
Infinite loop while benchmarrking Hbase

### ISSUE THREAD

**Issue by shek007** [brianfrankcooper/YCSB#219]
I pulled your code, modified the code to show log for every second, compiled it and change configuration to hadoop 2.6 & hbase 0.98 and then I executed following command,
`bin/ycsb load hbase -P workloads/workloada -p columnfamily=f1 -p recordcount=100 -p threadcount=10 -s`

I waited for more than 20 mins, and still I don't see any stats (See screenshot). The logging on console it going on and on! Is it a code issue or I'm missing something?
![capture](https://cloud.githubusercontent.com/assets/11553521/6796049/3ebb1590-d211-11e4-9924-3b93c81989cd.PNG)

Can somebody help me in resolving the issue?

If required, I'm using horton works 2.2.

**Comment by lambdaupb** [comment]
have a look at: https://github.com/brianfrankcooper/YCSB/issues/186

**Comment by shek007** [comment]
I've made those changes like adding 0.98.4-hadoop2 in pm.xml and other stuff, but still I see same error. :|

**Comment by busbey** [comment]
what shows up in your hbase server logs? can you get a jstack of the client while it's waiting?

**Comment by shek007** [comment]
How do I get habse server logs? What is jstack?

**Comment by busbey** [comment]
Getting the hbase server logs will depend on how you deployed hbase. What are you setting for your hbase connection information?

Jstack is a tool that comes with the JDK that will give you information about threads in a java process. It's usually in the same directory as the 'java' command.

**Comment by busbey** [comment]
Closing as stale. If you are still experiencing this issue with our latest release, please reopen.
