### ISSUE TITLE
additional stuff and thinking

### ISSUE THREAD

**Issue by mikaelsitruk** [brianfrankcooper/YCSB#22]
Hi
I begun to work with ycsb and it is very nice, so first thanks.
While playing around a little to evaluate Cassandra, i noticed the following
1. There is no support for batch - that is instead of sending values for a certain key it should be possible to send several keys at once. 
2. There is no support for consistency level and replication factor setup
3. The setup of the db can usually be performed by the benchmark, instead of manually (i know that in the document it was especially written as design purpose, but i think it is still possible to allow a db manager to be invoked at the beginning if the db support it)
4. It think that the latency bound used is not exact, since there is an extra time used to convert the data created by the workload, to the appropriate structure used by the db and this time is counted as the db operation.
5. The keys generated by the different threads are the same (for insert), in fact i think that the range of values should be spread among the threads. 
I plan to add support for the above items (1,2,3 and 5), if so are you interested in patches? 
1 - db interface and workload change,
2 - for cassandra db
3 - in db interface 
5 - workload interface changes

**Comment by busbey** [comment]
sorry for the long lag. Are you still interested in working on this?

numbers 1 and 5 will require more review, so it'd be best if you did any of these you are interested in with independent PRs.

**Comment by manolama** [comment]
I'm looking at using YCSB for time series database measuring and while poking around I noticed a number of DBs with asynchronous support. 
One way to address #1 would be to a ``flush()`` abstract method that DBs can implement before the ``cleanup()`` method to make sure all outstanding values are written to the DB. This would interfere with reads though so that part would be tricky to sync.

#4 doesn't seem to be a big issue as YCSB is primarily useful for comparisons between DBs.

#5 is pretty useful so I'd be happy to take a stab at that.

**Comment by cmatser** [comment]
@manolama Would you mind posting a new issue for this?  This is such an old thread, we probably should have closed it.  Plus, I think it's is a great new topic.  I'd like to hear more about how you'd accomplish this time series measuring.  Doesn't this depend on the DB's implementation of "eventual consistency".  That too may be a good reason to have it... for DB comparison.  Please discuss in a new thread.  Thanks!  -Chrisjan

**Comment by risdenk** [comment]
Closing this since some of the items have been addressed and its very old at this point (some of the items have been addressed)
