### ISSUE TITLE
ycsb error

### ISSUE THREAD

**Issue by amneet456** [brianfrankcooper/YCSB#223]
i tried to run command 
python ycsb shell basic 
 to check wether ycsb is properly configured. but it is giving me error. could not find or load main class com.yahoo.ycsb.commndLine.
can anyone tell me solution?

**Comment by cmatser** [comment]
Sounds like the classpath isn't being setup correctly.  I usually ran ycsb straight from the shell of my linux platform, but I also ran it from the top-level directory like:
bin/ycsb shell basic

That being said, I know that I ran the development install which can be slightly different from production distribution.  Hopefully, you can see more than just "could not find or load main class".  You should see the classpath output as well, something like "-cp core/target/core-0.1.4.jar" .  If that directory path is not valid to the core jar file, then that's usually when you get the error message you are seeing.

Chrisjan

**Comment by amneet456** [comment]
i am able to load the data.. bu is showing me some infinite results.. i am sending a screenshot. can you please tell reson behind this.
![capture1](https://cloud.githubusercontent.com/assets/11829568/7214431/8667a612-e5c9-11e4-986a-c3a7585027bf.JPG)

**Comment by cmatser** [comment]
You might try adding the slf4j-simple-1.7.12.jar.  You can find it here: http://mvnrepository.com/artifact/org.slf4j/slf4j-simple/1.7.12

You might need an older version of this jar.  If so, just browse up on that link and try an older version.

If you place it in the same location as the core-0.1.4.jar and the python script should find it and add it automatically to the classpath.  You should also have a file called simplelogger.properties in the same location, with the contents: org.slf4j.simpleLogger.defaultLogLevel=debug

This may give you some extra debug information that could point you to the problem you're experiencing.

The second thing I would suggest you look at is the version of cassandra server you are running against.  You're using the client for Cassandra 1.0.6, which is a bit dated.

I wrote a binding for cassandra v2 call the CassandraCQLClient which is also dated now, but I think it works with v3 too.  I created a merge request for it, but it failed for some reason and I haven't had the time to track it down.

Chrisjan

**Comment by busbey** [comment]
@amneet456 are you still pursuing this? the CQL client has now been merged.

**Comment by amneet456** [comment]
no. i have obtained my results
