### ISSUE TITLE
OSError while trying to run workload on redis-server

### ISSUE THREAD

**Issue by nielsdevos** [brianfrankcooper/YCSB#226]
I'm trying to setup the YCSB for Redis but i keep getting the same error.

I just use 

sudo apt-get install -y python-software-propert
sudo -E add-apt-repository -y ppa:rwky/redis
sudo apt-get update
sudo apt-get install redis-server

to install the redis-server and use

./bin/ycsb load redis -P workloads/workloada -p redis.host=localhost

to load the workload. And i get the following error.

Traceback (most recent call last):
  File "./bin/ycsb", line 116, in <module>
    subprocess.call(ycsb_command)
  File "/usr/lib/python2.7/subprocess.py", line 493, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

I get the same error when i'm running 2 connected nodes with each an instance of a mongodbserver. I have no problems with the first node but the 2nd node also gives this error. I don't know if the 2 are related.

**Comment by busbey** [comment]
what OS is this on?

**Comment by busbey** [comment]
Closing as stale. If you're still having this issue with our most recent release and you'd like help troubleshooting, please reopen.
