### ISSUE TITLE
hbase 0.94.4 with ycsb

### ISSUE THREAD

**Issue by ABIDD** [brianfrankcooper/YCSB#231]
I install HBase 0.94.14 with hadoop1.0.4 but whenever compiles YCSB poses a mistake despite that change pom.xml, please help me with detailed

[INFO] Reactor Summary:
[INFO]
[INFO] YCSB Root ......................................... SUCCESS [1.942s]
[INFO] Core YCSB ......................................... SUCCESS [8:12.657s]
[INFO] Cassandra DB Binding .............................. SUCCESS [14.509s]
[INFO] HBase DB Binding .................................. FAILURE [4.001s]
[INFO] Hypertable DB Binding ............................. SKIPPED
[INFO] Accumulo DB Binding ............................... SKIPPED
[INFO] DynamoDB DB Binding ............................... SKIPPED
[INFO] ElasticSearch Binding ............................. SKIPPED
[INFO] Infinispan DB Binding ............................. SKIPPED
[INFO] JDBC DB Binding ................................... SKIPPED
[INFO] Mongo DB Binding .................................. SKIPPED
[INFO] OrientDB Binding .................................. SKIPPED
[INFO] Redis DB Binding .................................. SKIPPED
[INFO] Voldemort DB Binding .............................. SKIPPED
[INFO] YCSB Release Distribution Builder ................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8:34.225s
[INFO] Finished at: Sat May 02 11:42:33 CET 2015
[INFO] Final Memory: 37M/89M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project hbase-binding: Compilation failure: Compilation failure:
[ERROR] /home/hduser/YCSB/hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient.java:[34,29] package org.apache.hadoop.conf does not exist
[ERROR] /home/hduser/YCSB/hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient.java:[56,25] cannot find symbol
[ERROR] symbol  : class Configuration
[ERROR] location: class com.yahoo.ycsb.db.HBaseClient
[ERROR] /home/hduser/YCSB/hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java:[26,29] package org.apache.hadoop.conf does not exist
[ERROR] /home/hduser/YCSB/hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java:[27,30] cannot find symbol
[ERROR] symbol  : class Cell
[ERROR] location: package org.apache.hadoop.hbase
[ERROR] /home/hduser/YCSB/hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java:[28,30] cannot find symbol
[ERROR] symbol  : class CellUtil
[ERROR] location: package org.apache.hadoop.hbase
[ERROR] /home/hduser/YCSB/hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java:[31,30] cannot find symbol
[ERROR] symbol  : class TableName
[ERROR] location: package org.apache.hadoop.hbase
[ERROR] /home/hduser/YCSB/hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java:[32,37] cannot find symbol
[ERROR] symbol  : class BufferedMutator
[ERROR] location: package org.apache.hadoop.hbase.client
[ERROR] /home/hduser/YCSB/hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java:[33,37] cannot find symbol
[ERROR] symbol  : class BufferedMutatorParams
[ERROR] location: package org.apache.hadoop.hbase.client
[ERROR] /home/hduser/YCSB/hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java:[34,37] cannot find symbol
[ERROR] symbol  : class Connection
[ERROR] location: package org.apache.hadoop.hbase.client
[ERROR] /home/hduser/YCSB/hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java:[35,37] cannot find symbol
[ERROR] symbol  : class ConnectionFactory
[ERROR] location: package org.apache.hadoop.hbase.client
[ERROR] /home/hduser/YCSB/hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java:[43,37] cannot find symbol
[ERROR] symbol  : class Table
[ERROR] location: package org.apache.hadoop.hbase.client
[ERROR] /home/hduser/YCSB/hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java:[66,25] cannot find symbol
[ERROR] symbol  : class Configuration
[ERROR] location: class com.yahoo.ycsb.db.HBaseClient10
[ERROR] /home/hduser/YCSB/hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java:[71,11] cannot find symbol
[ERROR] symbol  : class Connection
[ERROR] location: class com.yahoo.ycsb.db.HBaseClient10
[ERROR] /home/hduser/YCSB/hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java:[75,11] cannot find symbol
[ERROR] symbol  : class Table
[ERROR] location: class com.yahoo.ycsb.db.HBaseClient10
[ERROR] /home/hduser/YCSB/hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java:[76,11] cannot find symbol
[ERROR] symbol  : class BufferedMutator
[ERROR] location: class com.yahoo.ycsb.db.HBaseClient10
[ERROR] /home/hduser/YCSB/hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient.java:[168,23] cannot access org.apache.hadoop.io.Writable
[ERROR] class file for org.apache.hadoop.io.Writable not found
[ERROR] r = _hTable.get(g);
[ERROR] /home/hduser/YCSB/hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient.java:[328,19] cannot access org.apache.hadoop.io.WritableComparable
[ERROR] class file for org.apache.hadoop.io.WritableComparable not found
[ERROR] _hTable.put(p);
[ERROR] /home/hduser/YCSB/hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java:[114,26] cannot find symbol
[ERROR] symbol  : variable ConnectionFactory
[ERROR] location: class com.yahoo.ycsb.db.HBaseClient10
[ERROR] /home/hduser/YCSB/hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java:[164,14] cannot find symbol
[ERROR] symbol  : class TableName
[ERROR] location: class com.yahoo.ycsb.db.HBaseClient10
[ERROR] /home/hduser/YCSB/hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java:[164,36] cannot find symbol
[ERROR] symbol  : variable TableName
[ERROR] location: class com.yahoo.ycsb.db.HBaseClient10
[ERROR] /home/hduser/YCSB/hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java:[168,18] cannot find symbol
[ERROR] symbol  : class BufferedMutatorParams
[ERROR] location: class com.yahoo.ycsb.db.HBaseClient10
[ERROR] /home/hduser/YCSB/hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java:[168,48] cannot find symbol
[ERROR] symbol  : class BufferedMutatorParams
[ERROR] location: class com.yahoo.ycsb.db.HBaseClient10
[ERROR] /home/hduser/YCSB/hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java:[233,13] cannot find symbol
[ERROR] symbol  : class Cell
[ERROR] location: class com.yahoo.ycsb.db.HBaseClient10
[ERROR] /home/hduser/YCSB/hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java:[233,23] cannot find symbol
[ERROR] symbol  : method listCells()
[ERROR] location: class org.apache.hadoop.hbase.client.Result
[ERROR] /home/hduser/YCSB/hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java:[234,38] cannot find symbol
[ERROR] symbol  : variable CellUtil
[ERROR] location: class com.yahoo.ycsb.db.HBaseClient10
[ERROR] /home/hduser/YCSB/hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java:[235,46] cannot find symbol
[ERROR] symbol  : variable CellUtil
[ERROR] location: class com.yahoo.ycsb.db.HBaseClient10
[ERROR] /home/hduser/YCSB/hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java:[237,71] cannot find symbol
[ERROR] symbol  : variable CellUtil
[ERROR] location: class com.yahoo.ycsb.db.HBaseClient10
[ERROR] /home/hduser/YCSB/hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java:[238,47] cannot find symbol
[ERROR] symbol  : variable CellUtil
[ERROR] location: class com.yahoo.ycsb.db.HBaseClient10
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :hbase-binding

thanks

**Comment by cmatser** [comment]
Maven does not seem to have downloaded the hadoop jars needed to compile.  Not sure why...

I'm not a maven expert.  But, you might try manually adding the hadoop jars to your maven repository or trying to figure out why maven can't seem to get the hadoop jars that the hbase project needs.

Chrisjan.

**Comment by busbey** [comment]
this looks like an error in handling both 0.94 and the new client for hbase 1.0. I'll take a look at better providing hbase client profiles.

**Comment by risdenk** [comment]
@ABIDD is this still an issue? The HBase bindings were split in PR #392 to support 0.94, 0.98, and 1.0.

**Comment by busbey** [comment]
closing as stale. please open a new ticket if the current HBase 0.94 binding isn't working.
