### ISSUE TITLE
hbase shell command not working 

### ISSUE THREAD

**Issue by amneet456** [brianfrankcooper/YCSB#234]
while ruuning hbase shell. i am getting following error..
Invalid maximum heap size: -Xmx1000m "
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
ERROR: Could not determine the startup mode.

**Comment by busbey** [comment]
Could you paste your exact command and hbase version?

**Comment by amneet456** [comment]
![capture](https://cloud.githubusercontent.com/assets/11829568/7664475/876fc89e-fba6-11e4-8016-b75eed82481e.JPG)
i am running hbase on windows.
version1.0.0

**Comment by busbey** [comment]
It will be easiest for you to get help with your underlying hbase problem via [the hbase user mailing list](http://hbase.apache.org/mail-lists.html). You should provide all of this information for them there, as well as your jvm version. Once you have that working, we'd be glad to help get YCSB going against it (though I believe I have to find the fork that has modern HBase support still).

Just to set your expectations, note that the [HBase reference guide calls out running on windows as "not recommended"](http://hbase.apache.org/book.html#basic.prerequisites).

**Comment by amneet456** [comment]
okk ill check. 
thanks for your help :)
