### ISSUE TITLE
versioning YCSB

### ISSUE THREAD

**Issue by busbey** [brianfrankcooper/YCSB#236]
Our last release was ~3 years ago. Before working towards the next one, I'd like to document what we convey to others with our version numbers.

Given version numbers that look like x.y.z I'd like to define compatibility with

* _Major_ version x: incremented when pre-existing custom Workloads or Database bindings would break.
* _Minor_ version y: incremented when new Workloads or Database bindings are added.
* _Patch_ version z: just bug fixes

One thing I'm not sure about is improvements to the Client or changes in statistics gathered. These things can change how comparable results are for YCSB runs, but I'm not sure tests that run on different hardware set ups are comparable anyways.

Once we have some consensus I'll put together a new wiki page.

**Comment by cmccoy** [comment]
Sounds good to me.

> One thing I'm not sure about is improvements to the Client or changes in statistics gathered.

I'd consider statistic changes at least to be breaking changes. Client improvements I'm not as sure about.

**Comment by busbey** [comment]
Okay, so what's our next version going to be? I haven't done an exhaustive comparison to 0.1.4. I know we should at least be at 0.2.0, but given the length of time I'd be surprised if we had no incompatible changes.

I could do an automated check for API changes pretty easy. I'll try to do that this weekend. I'll do it over everything since we haven't defined an API yet.

**Comment by cmccoy** [comment]
0.2 sounds good to me. I'd expect pre-1.0 minor releases to break
compatibility.

**Comment by gkamat** [comment]
I would relax the compatibility requirement for minor version numbers to permit output format or statistics changes, for now at least.  Admittedly, any changes would be rare, but since it looks like development is restarting after a hiatus, it would be good not to commit to that, at least initially.

**Comment by busbey** [comment]
Here's a gist for the proposed new wiki page (until we get #258 together): https://gist.github.com/busbey/f02f429b859574a109ea

How does that look?

**Comment by busbey** [comment]
I pushed an initial version to [Version Numbers and Compatibility](https://github.com/brianfrankcooper/YCSB/wiki/Version-Numbers-and-Compatibility) since the PR updates the version according to that guidance. If we need to discuss further, just let me know.
