### ISSUE TITLE
verify status of running on windows

### ISSUE THREAD

**Issue by busbey** [brianfrankcooper/YCSB#246]
We need to verify the current usability on windows and make sure we have documentation that calls out how to run properly there.

**Comment by busbey** [comment]
Proposed new wiki page in this gist:

https://gist.github.com/busbey/572ebc8c4e592055e505

Verified on Windows 7.

**Comment by allanbank** [comment]
Your wiki page looks good to me.

**Comment by busbey** [comment]
Posted to [wiki as 'Prerequisites for Windows'](https://github.com/brianfrankcooper/YCSB/wiki/Prerequisites-for-Windows)
