### ISSUE TITLE
Workload D through null pointer exception

### ISSUE THREAD

**Issue by pratap5469** [brianfrankcooper/YCSB#263]
To Load the data i am using below script fro workloadd and it working fine -
./bin/ycsb load cassandra-cql -s -threads 10 -p "hosts=IP1 IP2 IP3" -P workloads/workloadd >>/Output/workloadd.txt.

To run the opration i am using below script fro workloadd and it working fine -
 ./bin/ycsb run cassandra-cql -s -threads 10 -p "hosts=IP1 IP2 IP3" -P workloads/workloadd >>/Output/workloadd.txt.

During the run the test for workload D i am experiencing below error- 

Starting test.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/xyz/New_YCSB/YCSB/cassandra/target/slf4j-log4j12-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/xyz/New_YCSB/YCSB/cassandra/target/cassandra-binding-0.1.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
log4j:WARN No appenders could be found for logger (com.datastax.driver.core.Cluster).
log4j:WARN No appenders could be found for logger (com.datastax.driver.core.Cluster).
log4j:WARN No appenders could be found for logger (com.datastax.driver.core.Cluster).
log4j:WARN No appenders could be found for logger (com.datastax.driver.core.Cluster).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
log4j:WARN Please initialize the log4j system properly.
log4j:WARN No appenders could be found for logger (com.datastax.driver.core.Cluster).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
log4j:WARN No appenders could be found for logger (com.datastax.driver.core.Cluster).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
log4j:WARN Please initialize the log4j system properly.
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
java.lang.NullPointerException
        at com.yahoo.ycsb.db.CassandraCQLClient.read(CassandraCQLClient.java:285)
        at com.yahoo.ycsb.db.CassandraCQLClient.readAll(CassandraCQLClient.java:255)
        at com.yahoo.ycsb.DBWrapper$1.go(DBWrapper.java:124)
        at com.yahoo.ycsb.DBWrapper.operation(DBWrapper.java:283)
        at com.yahoo.ycsb.DBWrapper.readAll(DBWrapper.java:111)
        at com.yahoo.ycsb.workloads.CoreWorkload.doTransactionRead(CoreWorkload.java:535)
        at com.yahoo.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:482)
        at com.yahoo.ycsb.ClientThread$1.doOperation(Client.java:349)
        at com.yahoo.ycsb.ClientThread.run(Client.java:405)
        at com.yahoo.ycsb.ClientThread.run(Client.java:346)

could any one please help me resolve this issue. if any one has experienced the same issue please share the solution.

**Comment by busbey** [comment]
Hi! I don't see the class "CassandraCQLClient" in the source tree. Are you using a customized fork downloaded from somewhere? Or perhaps one of the open pull requests?

**Comment by nitendragautam** [comment]
Hello Busbey ,
CassandraCQLClient is the new cassandra java client created for Cassandra 2.x testing .Its a customized fork {https://github.com/joshwilliams/YCSB,https://github.com/jbellis/YCSB } .
Perhaps its a good idea to merge this fork into the master ,as it supports latest Cassandra 2.x.

**Comment by busbey** [comment]
My goal is to eventually merge all the forks. That's considerably easier when folks put up PRs that work with current master, which is a bit of a moving target right now. :)

**Comment by busbey** [comment]
@pratap5469 please try to make use of the patch on #270, since that is the version of CassandraCQLClient that is likely going to live in the repo short term.

**Comment by busbey** [comment]
Still trying to do this? the current release candidate should work with Cassandra 2.0.

**Comment by nitendragautam** [comment]
Thanks  fir the info .But I left the Cassandra project now working on Hadoop related project .i will use next time when I work in a Cassandra   Related Project .

**Comment by satybald** [comment]
I do experience the same problem. Looks like CassandraCQL driver cannot initialize cluster object.

```
Command line: -db com.yahoo.ycsb.db.CassandraCQLClient -P workloads/workloada -p debug=true -s -p host=127.0.0.1 -p threadcount=10 -p port=9042 -load
Loading workload...
Starting test.
2015-07-13 16:30:36:725 0 sec: 0 operations; 
16:30:36.820 [Thread-1] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.NEW_NODE_DELAY_SECONDS is undefined, using default value 1
16:30:36.824 [Thread-1] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.NON_BLOCKING_EXECUTOR_SIZE is undefined, using default value 4
16:30:36.828 [Thread-1] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.NOTIF_LOCK_TIMEOUT_SECONDS is undefined, using default value 60
16:30:36.875 [Thread-1] DEBUG com.datastax.driver.core.Cluster - Starting new cluster with contact points [/127.0.0.1:9042]
16:30:36.903 [Thread-1] DEBUG i.n.u.i.l.InternalLoggerFactory - Using SLF4J as the default logging framework
16:30:36.922 [Thread-1] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
16:30:36.922 [Thread-1] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
16:30:36.923 [Thread-1] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
16:30:36.924 [Thread-1] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: true
16:30:37.008 [Thread-1] DEBUG i.n.util.internal.PlatformDependent - UID: 501
16:30:37.008 [Thread-1] DEBUG i.n.util.internal.PlatformDependent - Java version: 8
16:30:37.008 [Thread-1] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noUnsafe: false
16:30:37.008 [Thread-1] DEBUG i.n.util.internal.PlatformDependent - sun.misc.Unsafe: available
16:30:37.009 [Thread-1] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noJavassist: false
16:30:37.010 [Thread-1] DEBUG i.n.util.internal.PlatformDependent - Javassist: unavailable
16:30:37.010 [Thread-1] DEBUG i.n.util.internal.PlatformDependent - You don't have Javassist in your class path or you don't have enough permission to load dynamically generated classes.  Please check the configuration for better performance.
16:30:37.010 [Thread-1] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.tmpdir: /var/folders/z7/t6xvj0fs4wzfwhjtpj94921c0000gn/T (java.io.tmpdir)
16:30:37.010 [Thread-1] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
16:30:37.011 [Thread-1] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
16:30:37.019 [Thread-1] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.FORCE_NIO is undefined, using default value false
16:30:37.021 [Thread-1] WARN  com.datastax.driver.core.NettyUtil - Found Netty's native epoll transport, but not running on linux-based operating system. Using NIO instead.
16:30:37.025 [Thread-1] DEBUG i.n.c.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 8
16:30:37.033 [Thread-1] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
16:30:37.033 [Thread-1] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
16:30:37.053 [Thread-1] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetectionLevel: simple
16:30:37.200 [Thread-1] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.DISABLE_COALESCING is undefined, using default value false
Exception in thread "Thread-1" java.lang.NoSuchMethodError: io.netty.util.UniqueName.<init>(Ljava/lang/String;)V
	at io.netty.channel.ChannelOption.<init>(ChannelOption.java:136)
	at io.netty.channel.ChannelOption.valueOf(ChannelOption.java:99)
	at io.netty.channel.ChannelOption.<clinit>(ChannelOption.java:42)
	at com.datastax.driver.core.Connection$Factory.newBootstrap(Connection.java:796)
	at com.datastax.driver.core.Connection$Factory.access$100(Connection.java:669)
	at com.datastax.driver.core.Connection.initAsync(Connection.java:129)
	at com.datastax.driver.core.Connection$Factory.open(Connection.java:724)
	at com.datastax.driver.core.ControlConnection.tryConnect(ControlConnection.java:248)
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:194)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:82)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1265)
	at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:337)
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:145)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:63)
	at com.yahoo.ycsb.ClientThread.run(Client.java:195)
INSERT INTO usertable(y_id,field1,field0,field7,field6,field9,field8,field3,field2,field5,field4) VALUES ('user6873002678636213555','''=j6Gu;U+8Fm1+8(=x7D71Ni?1v+J57^k''Ws!C54Ia!=(<^!#\?,C9$P}7/|"W!,*b4.8%''6&&>-Oy/9<87&'']};Yy!Xc?J3=<n+',':7|?Y#/Xk+#|16`+&>!^;%Qa/&~6Z5*M1 O%5749C99905Di79:8R+;W3,:v"%x*V=8E7<X1,#h; j?Ck232<)2-S3#"d>F#,!(0','.G#4O=1R+$Ag60n+?&/Vk;-~ >f6.$(&"(Xo(>84+"<L=05~2Gi+6`9:~&-l-]%=Nc7B78Vg)(,0A- "v? 6;Sa>Rq> z7286Jw7',',Q3(X!/9x.1d4;l78f<C= A/=#<)Xg1)f;M#><49T%/9b&Zg/Uc/ .6%p/^!-Yo/)~>Ii6-|0X#<Z5%K=$Zc<."-482V)-809%p>','<9|&!l;,"-Gg7Oe:M?;%6,Fa5M''=/n+''.-N+<"<-7&7T#!:r$Iu#34,3z2By6*&<3v4?b''D/"S/<>r4-h*@!*A)1>|+<(=1</%x7','!Ki3Lg+T>]-%; (F)4N/=]{1Sg7A9![/-X5(R5,N3($2%#f0&640v+Ng+_a.#"5 b4H7,Ra2)>0Vk''C50Hk8;()<49!h"$("Ao3','0F=,I#"M}#_m1"z>9";2d*I!([;8#p6!~#M33E%1626Rk7_y6:t>L;%**%((<Z=1D;$Y55Qm26"<W=5D38Go*F-<6 =Ce/K!?\e''','5^q''5z+Qo>P''8 "!^;9>$$P77P#4<,7-r.W-<!b''O707>,A!>S3$Zo9J{:!n6\s3Lu4W"+`61v?!:4\/1,4-R5-- 2P{#V;$M}/','$5h6Ea3"j&36>B{"8z>&b&1p#Og6=v>Gs;Tg2N!9#n=:x7?l.+z./ 6>$()p6Dw67h1Wa&1z( d*\!0561Pm!\= ;$4Ok.V9>9r&',';''h#\a?F}.^c"&`''Oc*N?<#x9B?!=r4Ki+,t(Sk.-6<!|;5`13p6H)!>45\+:Dw"Z;6>,<+:#@68.%<.!D*7h/E+8]3(_/<I}7');

```

**Comment by satybald** [comment]
```
INSERT INTO usertable(y_id,field1,field0,field7,field6,field9,field8,field3,field2,field5,field4) VALUES ('user4052466453699787802','8F51<2>C=%K%<10$Y#*^30#8<U{?S/4D''-/~- `./ >Go+&|<Cm+Py*5j3Zy*B3%G{7]%1_55-v2/6#K-(>b4_{:58;W!,*h8Uu3','.@;-Xa$W}:^?47"1?4!U=0M;+Ic/< <Oo"3|8(p;0n(5l;V/-)p?Re?$,<<$)Tq3B76U{?0v!L70&,"+z#'' =Ew''C7;9:![s.>t.','#0*0Vs!C-,4$>!  &`>+4-#t9Tw''(4:3`*;:5M=87t=;4 G5- (1+p->p>H)6H#)T-!2,=>.(.z**~!4t;]#-!d&Us)0:,* -U=0','"0l7 d0)>,&:(;h''\#)*~>!p''I-9Rq0 "4>&$ p#Z3):(-_o64x+(h1(646`;\;0B#,!,8]3'';n:P5<$4(*b''*$-Gk9Yy*Y?'' 29','3"<,G-"Hy&(v2%r:$,>Zc>6&&+z3.`++4%N}(26((|4Aw2_9$! 4 h).p#&n2V18\y0F=41.4Fe+9n0"x7O!9Iq"7n"''*5+~&Ny?','#%,8?r75><-0"-6(."$U7%/2:T3<B+ Bs3:v8!84^9-("-]3$J5<1`?94-P9>R}''Bm#3<,0(/1l#\7%,z/B{#J!8Nw$7f.Yi&''z&','>#`? &2U7P7/05Qa:5"%50%]m&,$3C)1I;(>(,?t%Vy3_a9Qy*O/1/x2\;6@?5,l+Q-(_o0Ac"U=<@g2;6+2x.X=#%2 Nu,Sw>','0<f3X'',64,@)5I=9Nq,1x:[''6G=!%:2,>=!6%:49L{%>r6\k*=$5,69/d+,8/^;Sc0D%-6~>4r7S=8^{3Kg37<$Os&A?5=p=[#,','1Na:&l4-j3V/*&z+Ti3@q>=t)G/86<_))Qi&965Va+/,5H?:*,)!<#We3R):):=:h9Ag''?6''%*!Oa09 9A51D=85j:?")=.1G5!','? `.P;5]c?:t92.)Ze),n;:t$3,!J%$W1=#x4Jo.7*&F1)5|/[a. (# p6Uc?4v;He78<)Uy2G''%K}2N9<#~(Fi7(>;Z#4Pw?Dg:');java.lang.NullPointerException

	at com.yahoo.ycsb.db.CassandraCQLClient.insert(CassandraCQLClient.java:377)
	at com.yahoo.ycsb.DBWrapper.insert(DBWrapper.java:158)
	at com.yahoo.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:548)
	at com.yahoo.ycsb.ClientThread.run(Client.java:252)
java.lang.NullPointerException
	at com.yahoo.ycsb.db.CassandraCQLClient.insert(CassandraCQLClient.java:377)
	at com.yahoo.ycsb.DBWrapper.insert(DBWrapper.java:158)
	at com.yahoo.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:548)
	at com.yahoo.ycsb.ClientThread.run(Client.java:252)

```

**Comment by satybald** [comment]
I found the reason for this exception. I was using new C* libraries, which gives this error. Using an older version eliminated this problem.
Normal:
```
<cassandra.version>2.0.16</cassandra.version>
<cassandra.cql.version>2.2.0-rc1</cassandra.cql.version>
```
Buggy one:
```
    <cassandra.version>2.1.7</cassandra.version>
    <cassandra.cql.version>2.2.0-rc1</cassandra.cql.version>
```

**Comment by busbey** [comment]
ah, so this is #293 then. thanks for chasing it down! this should help us update things to work with Cassandra 2.1.
