### ISSUE TITLE
Handling incompatible API versions

### ISSUE THREAD

**Issue by cmccoy** [brianfrankcooper/YCSB#272]
We should decide how to structure code handling incompatible API changes for different database versions. I've seen:
- Backwards-incompatible API changes (e.g., HBase 0.9x to 1.x, see #225).
- New APIs (e.g., Cassandra CQL, see #270).

Currently we're including multiple clients within a single module, but I think it would be cleaner to have a separate module for incompatible versions. The HBase client, for example, now needs to be compiled against HBase 1.0.x. I think having an `hbase-10` module and `hbase-09` module might be better.

**Comment by busbey** [comment]
yes, definitely. in the case of HBase it should probably be hbase-94 and hbase-1.0 (and if the hbase-1.0 client doesn't work properly with a 0.98 cluster, we'll also need an hbase-98).

In addition to making the transition across versions clearer to downstream folks, this also makes it easier to deal with conflicting runtime needs.

**Comment by cmccoy** [comment]
This is done for HBase.

**Comment by risdenk** [comment]
Closing since this has been implemented with HBase and other bindings.
