### ISSUE TITLE
YCSB does not throw error if there is no table created

### ISSUE THREAD

**Issue by ramkrish86** [brianfrankcooper/YCSB#278]
If we run the ycsb tool without creating the table the tool does not throw any error. It just runs and infact displays some statistics also. But internally nothing actually works.

**Comment by busbey** [comment]
which data store binding are you running against? which version of YCSB? could you include the command line invocation?

**Comment by ramkrish86** [comment]
I have a YCSB version pulled out of this
https://github.com/apurtell/YCSB/tree/new_hbase_client and it is running against 0.98.120hadoop2.

Am running hbase store. 
the command line invocation is this
./ycsb load hbase -P ../workloads/workloada -p columnfamily=f1 -p recordcount=5000000 -p threadcount=20 -s | tee -a workloada.dat

**Comment by busbey** [comment]
please try to recreate the problem with the current hbase client.

    bin/ycsb -jvm-args='-Xmx1024m' -cp "${HBASE_CONF_DIR}" load hbase -P workloads/workloada -p columnfamily=f1 -p recordcount=5000000 -p threadcount=20 -s

Or if you prefer the new API:

    bin/ycsb -jvm-args='-Xmx1024m' -cp "${HBASE_CONF_DIR}" load hbase-10 -P workloads/workloada -p columnfamily=f1 -p recordcount=5000000 -p threadcount=20 -s

**Comment by gkamat** [comment]
The TableNotFound exception is indeed reported; however, the problem is that an error status reported by a transaction in the client stub is not propagated upstream to the core module.  Therefore, YCSB will continue to attempt the specified number of transactions rather than terminating.

Will create a category of errors on encountering which YCSB should terminate; that should fix this issue.

**Comment by busbey** [comment]
How about instead we tell datastore bindings that they should check for things like this in their init call? At that point the binding can throw a DBException to indicate the problem and things ought to terminate.

**Comment by gkamat** [comment]
Submitted pull request #298.

**Comment by busbey** [comment]
closed by #304
