### ISSUE TITLE
Repo for async mongo client failing

### ISSUE THREAD

**Issue by busbey** [brianfrankcooper/YCSB#282]
PR check are currently failing because they can't get dependencies for the new async mongo client

    [ERROR] Failed to execute goal on project mongodb-binding: Could not resolve dependencies for 
    project com.yahoo.ycsb:mongodb-binding:jar:0.2.0-SNAPSHOT: Failed to collect dependencies at 
    com.allanbank:mongodb-async-driver:jar:2.0.1: Failed to read artifact descriptor for 
    com.allanbank:mongodb-async-driver:jar:2.0.1: Could not transfer artifact com.allanbank:mongodb-
    async-driver:pom:2.0.1 from/to allanbank (http://www.allanbank.com/repo/): Connect to 
    www.allanbank.com:80 [www.allanbank.com/66.159.80.130] failed: Connection timed out -> [Help 1]

ping @allanbank

**Comment by allanbank** [comment]
@busbey - The hosting provider did an emergency migration of the site that did not complete successfully. The repo should be back up but the DNS change may take up to a hour to propagate.

**Comment by busbey** [comment]
Thanks for the quick clean up. At the least travis-ci sees it now.
