### ISSUE TITLE
The result only show [CLEANUP] data , no [OVERALL] data

### ISSUE THREAD

**Issue by deadjoe** [brianfrankcooper/YCSB#290]
I tried the latest ycsb from github and tried to run it against couchbase cluster and hazelcast cluster. The test launched without problem and after it finished. Only [CLEANUP] data reported. 

Does the latest ycsb code remove [OVERALL] or there might be a bug?

=OutPut like below=

[READ], 322700, 750.887323943662
[READ], 322800, 970.5576923076923
[READ], 322900, 701.1944444444445
[READ], 323000, 735.2166666666667
[READ], 323100, 718.9384615384615
[READ], 323200, 704.5079365079365
[READ], 323300, 700.5076923076923
[READ], 323400, 698.6578947368421
[READ], 323500, 727.6268656716418
[READ], 323600, 594.6279069767442
[READ], 323700, 557.2658227848101
[READ], 323800, 560.072463768116
[CLEANUP], Operations, 1
[CLEANUP], AverageLatency(us), 7250.0
[CLEANUP], MinLatency(us), 7250
[CLEANUP], MaxLatency(us), 7250
[CLEANUP], 0, 7250.0

**Comment by deadjoe** [comment]
back to 0.1.4, everything looks fine.

**Comment by busbey** [comment]
Sounds like a bug. Someone else have time to dig in?

**Comment by cmccoy** [comment]
I just tried against HBase with 076b8024ba4abee6bef2afc88c5f309564eaf31c, and get an OVERALL section:
```
YCSB Client 0.1
Command line: -db com.yahoo.ycsb.db.HBaseClient -P workloads/workloada -p columnfamily=cf -t
[OVERALL], RunTime(ms), 2533.0
[OVERALL], Throughput(ops/sec), 394.78878799842084
[OVERALL], RunTime(ms), 2487.0
[OVERALL], Throughput(ops/sec), 402.09087253719343
[UPDATE], Operations, 500
[UPDATE], AverageLatency(us), 3354.724
[UPDATE], MinLatency(us), 14
[UPDATE], MaxLatency(us), 830579
[UPDATE], 95thPercentileLatency(ms), 2
[UPDATE], 99thPercentileLatency(ms), 2
[UPDATE], Return=0, 499
```

I don't have any experience with couchbase or hazelcast. @deadjoe: what YCSB revision are you using?

**Comment by deadjoe** [comment]
@cmccoy I used the current version that checked out from the github.(0.2.0-SNAPSHOT).

Couchbase is couchbase-server-3.0.3-1716.x86_64
Hazelcast is hazelcast-3.4.2 

Thanks,

**Comment by busbey** [comment]
I thought we didn't have hazelcast support?

Can you upload logs from the couchbase run somewhere and post a link here?

**Comment by busbey** [comment]
Any update here? Can we get logs from the couchbase run?

**Comment by busbey** [comment]
Closing as stale. If you are still having this issue with our latest release and would like help troubleshooting, please reopen.
