### ISSUE TITLE
cannot load data in cassandra

### ISSUE THREAD

**Issue by bikashbanjara** [brianfrankcooper/YCSB#311]
i m using windows 8.1 where the required sw i m using java 1.7.0_79, apache maven 3.3.3, python 2.7.10, git version 1.9.5.msysgit.1, apache cassandra 2.1.6 and ycsb 0.1.4

and the path of ycsb C:\YCSB\workloads\workloada

i have edited the workload file by assinging the hosts=127.0.0.1

the error was "the system cannot find the file specified"
![document](https://cloud.githubusercontent.com/assets/7991748/8265777/afd848d0-1729-11e5-8390-12e3f11bdd64.jpg)

**Comment by bikashbanjara** [comment]
Hello busbey
Thank you for your reply.
i m trying to get "md5 sum of the ycsb tarball used for 0.1.4" using cygwin but i cannot get...please can u tell me how can i get md5 sum of the ycsb tarball...

**Comment by busbey** [comment]
I don't have a cygwin instance handy, but [this blog post](http://www.codejacked.com/using-md5sum-to-validate-the-integrity-of-downloaded-files/) claims that the md5 utility on cygwin is named "md5sum"

**Comment by cmatser** [comment]
I ran ycsb under cygwin and never tried under window's CMD which it appears you are doing.  Based on your output, to me, it looks like the ycsb core code is being called correctly.  It's just having trouble locating the file which you've specified on the command line.  I'm guessing it might be a windows path thing for the program arguments.  Try this:

-P C:\\YCSB\\workloads\\workloada

with cygwin, my argument looked like -P /cygdrive/c/ycsb/workloads/workloada

**Comment by cmatser** [comment]
I'm not sure that last comment of mine came through correctly.  I just noticed my double slashes didn't show up.  It looks like double slashes are escaped here on the site.  So, I updated the comment and quadruple slashed it.  Just to be clear, try using two slashes in your windows cmd argument for the path to the workloada.

**Comment by busbey** [comment]
Hi!

We now have substantially better documentation on running on windows

https://github.com/brianfrankcooper/YCSB/wiki/Prerequisites-for-Windows

Unfortunately, we don't currently work against Cassandra 2.1+. If you have some time to try working out the problem let us know. Otherwise please follow issue #293
