### ISSUE TITLE
Race condition in workload D?

### ISSUE THREAD

**Issue by tlopatic** [brianfrankcooper/YCSB#327]
There seems to be a race condition in workload D.

The client threads generate keys for the records to be inserted and there is a small time window between the thread generating the key and it actually inserting the record. However, as soon as the key has been generated, that key is considered to be available for other threads to read. (Because transactioninsertkeysequence.lastInt() now returns that key.) That results in the other threads potentially trying to read records that don't yet exist.

**Comment by tlopatic** [comment]
Proposed fix in pull request #364.

**Comment by allanbank** [comment]
Not sure why it re-openned. Closing again.
