### ISSUE TITLE
"./bin/ycsb load mongodb-async -s -P workloads/workloada > outputLoad.txt" fails

### ISSUE THREAD

**Issue by pbgalvin** [brianfrankcooper/YCSB#337]
Hi, trying to run YCSB against mongodb 3.0 on Centos 2.6.32-504.el6.x86_64
Followed the steps to install and run Mongodb, then install and run ycsb. But this step fails for me:
----------
4. Run YCSB

Now you are ready to run! First, use the asynchronous driver to load the data:

./bin/ycsb load mongodb-async -s -P workloads/workloada > outputLoad.txt
----------
First it failed this way:
[root@r2601-d5-us02 YCSB]# ./bin/ycsb load mongodb-async -s -P workloads/workloada > outputLoad.txt
Traceback (most recent call last):
  File "./bin/ycsb", line 3, in <module>
    import argparse
ImportError: No module named argparse

And I solved that via 
# easy_install argparse

But then it fails via:
[root@r2601-d5-us02 YCSB]# ./bin/ycsb load mongodb-async -s -P workloads/workloada > outputLoad.txt
[WARN]  Running against a source checkout. In order to get our runtime dependencies we'll have to invoke Maven. Depending on the state of your system, this may take ~30-45 seconds
[DEBUG]  Running 'mvn -pl com.yahoo.ycsb:mongodb-binding -am package -DskipTests dependency:build-classpath -DincludeScope=compile -Dmdep.outputFilterFile=true'
Traceback (most recent call last):
  File "./bin/ycsb", line 208, in <module>
    sys.exit(main())
  File "./bin/ycsb", line 187, in main
    maven_says = get_classpath_from_maven(binding)
  File "./bin/ycsb", line 127, in get_classpath_from_maven
    mvn_output = subprocess.check_output(["mvn", "-pl", "com.yahoo.ycsb:"+database+"-binding",
AttributeError: 'module' object has no attribute 'check_output'

Thoughts appreciated!

--Peter

**Comment by bigbes** [comment]
What's your python version? It seems to me that's 2.6, but `check_output` appeared only in 2.7.
I suppose this part is needed to be rewrited with `check_call` or `Popen`..
For you i recommend using Python with version 2.7 (using e.g. [pythonz](https://github.com/saghul/pythonz) project)

**Comment by pbgalvin** [comment]
Thanks. I'm on centos and apparently can't just replace python 2.6 with 2.7, so installed 2.7 as well called python2.7.  But how do I get ycsb et al to use it?

**Comment by bigbes** [comment]
Simply as `python2.7 bin/ycsb` (or another alias for python binary).

**Comment by pbgalvin** [comment]
Hah of course thanks.
Possibly more challenging question :-) - I want to run ycsb against a big database (to be sure I'm doing I/O to storage, which is what I want to test, not server cpus or memory which I presume has a bigger performance impact if the database is small). Any thoughts on how to build a big DB in mongodb and then have ycsb test against it?
Appreciate all the help...

**Comment by bigbes** [comment]
For example:
```
python2.7 bin/ycsb load mongodb --p recordcount=25000000
```
read about properties [here](https://github.com/brianfrankcooper/YCSB/wiki/Core-Properties)

**Comment by busbey** [comment]
All set @pbgalvin?

**Comment by pbgalvin** [comment]
Yes have it working, thanks for all the help.
