### ISSUE TITLE
Improve experience running on CentOS 6

### ISSUE THREAD

**Issue by busbey** [brianfrankcooper/YCSB#341]
CentOS 6 comes with Python 2.6, which *almost* works with our python bindings but not quite.

Possible solutions, in decreasing order of short-term preference:
* make the script work with python 2.6 (but keep working with 2.7)
* make a "what you need" section similar to #246 
* move off of python in favor of linux and windows specific shell glue

**Comment by risdenk** [comment]
Closing this since this seems to be addressed by the above and addition of bin/yscb.sh script.
