### ISSUE TITLE
YCSB key size

### ISSUE THREAD

**Issue by patiner** [brianfrankcooper/YCSB#352]
Hi, 

I'm trying to use YCSB with memcached. Could anyone tell me the default key size of YCSB and how to change the length of the key?

Thanks very much.

**Comment by busbey** [comment]
Hi!

Keys are a string made up of the concatenation of "user" and (right now) the toString of a long. Unfortunately, right now that means its the decimal representation with no leading 0s. So presently between 5 and 23 characters.

Unfortunately, that also means there's currently no way to control the key length.

What are you using for talking to Memcached?

**Comment by patiner** [comment]
Hi,

Thanks for your clarification. I'm using spymemcached-2.7.3 as the
memcached client in YCSB. One problem with spymemcached is that although I
can set fieldcount=1 and fieldlength=20 in YCSB configuration file to have
20B value size, the value size that memcached server receives becomes more
than 100B! Spymemcached might have done something which increases the value
size.

**Comment by busbey** [comment]
Keep in mind that the key is just the record identifier. there's also the field identifier, though I don't know how the binding you're using encodes records.

I don't think we have a spymemcached datastore binding yet, so we'd love a contribution. :)

**Comment by patiner** [comment]
I just did some modification based on this one
https://github.com/leverich/ycsb-memcached/blob/master/db/memcached/src/com/yahoo/ycsb/db/Memcached.java

**Comment by busbey** [comment]
Anything else can help with on key sizes?

**Comment by cmatser** [comment]
Regarding field sizes, setting "fieldlength=20" should have done the trick.  Are you sure you've spelled it correctly @patiner ?  The default is 100.  So if you say, you're getting 100, then it sounds like the default hasn't changed.

Regarding key sizes, it is as @busbey stated.

**Comment by patiner** [comment]
Thanks for your help. For the value size, finally I find that the culprit is spymemcached which I use to connect to memcached. From the source code of spymemcached, it seems that spymemcached's MemcachedClient will add extra bytes to the items before sending to memcached server, but I don't know the reason. Maybe I need to find another java-based memcached client which do not add extra bytes.




patiner

From: Chrisjan Matser
Date: 2015-07-16 14:38
To: brianfrankcooper/YCSB
CC: patiner
Subject: Re: [YCSB] YCSB key size (#352)
Regarding field sizes, setting "fieldlength=20" should have done the trick. Are you sure you've spelled it correctly @patiner ? The default is 100. So if you say, you're getting 100, then it sounds like the default hasn't changed.
Regarding key sizes, it is as @busbey stated.
