### ISSUE TITLE
Release version 0.3.0

### ISSUE THREAD

**Issue by gkamat** [brianfrankcooper/YCSB#358]
I'll be managing the release of the next version of YCSB, 0.3.0.

Sean B. has done a terrific job driving the 0.2.0 release -- the first version after a rather long gap -- and the intention now is to establish a more regular release cadence going forward.

My plan is to put this version out in about a couple of weeks.  I will create the release branch off master this Friday and then cherry-pick additional features into it as appropriate.  Enhancements in this release will include the following:

* New binding: aerospike
* Updated bindings: cassandra, infinispan, orientdb
* Fixes to the HBase binding to be better compatible with earlier versions of HBase

As before, it would be really helpful for folks to volunteer to test the release, especially the updated bindings.

**Comment by busbey** [comment]
I'll take care of testing on windows again, unless someone else wants to jump in.


I'd like to see us get the jdbc driver tested this time.

Thanks for driving this Govind!

**Comment by cmccoy** [comment]
I can do HBase / Cassandra 2.0 again.
Thanks, Govind!

**Comment by allanbank** [comment]
I can do MongoDB again and hope to get some time to look at the jdbc binding.

**Comment by gkamat** [comment]
Thanks very much for volunteering, folks!  Release candidate [0.3.0-RC1](https://github.com/brianfrankcooper/YCSB/releases/tag/0.3.0-RC1) is now available.

* Testers should build and use either the distribution artifact (ycsb-0.3.0-RC1.tar.gz) or a binding specific distribution (e.g. ycsb-hbase-0.3.0-RC1.tar.gz).  Please file issues for problems found.
* Fixes for issues should go into master. I will pull changes back into the release staging branch. 
* As issues come up, I will periodically cut new release candidates off the 0.3.0-staging branch.  After the final release is published, the staging branch will be deleted.  The tag can be used to track the branch or to generate patch releases.
* Successful testing of a datastore binding should be noted in this issue.  Please include the following:
    * Datastore binding name (e.g. hbase)
    * Version of datastore tested against (e.g. hbase 1.0.0 cluster)
    * If the datastore has distinct single node and clustered modes, indicate which was used (e.g. hbase standalone)
    * OS for client
    * Packaging used (either the distribution artifact or a datastore-specific artifact)
    * Workload used
    * Any other options used

I will note any additional tasks and testing we need to get done in this issue.  The final release artifacts will be similar to those in release 0.2.0.  I will write up the release notes as we get close to publishing the release.

**Comment by allanbank** [comment]
MongoDB Testing:
* Bindings mongodb-async and mongodb
* Testing against single mongod instance for version 3.0.4, 2.6.10, 2.4.14, 2.2.7, 2.0.9, and 1.8.5
* OS - Linux Fedora 22
    * Linux kanga 4.0.8-300.fc22.x86_64 #1 SMP Fri Jul 10 21:04:56 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
* Using the src distribution and then running from the src directory.
* Packaged workloads a-f.
* Adjusted threads and connection counts.

Still seeing these issues (as expected):
* #344 - 'mongodb' client throws timeout exceptions with scan workloads.
    * I would really like to get #344 in 0.3.0. Can someone review #362 so I can merge it to master and then we can get it in RC2?
* #316 -  StatusThread should wake up when the test has completed and exit.
    * Already on master. Not sure it is worth the effort to cherry pick.
* #327 - Race condition in workload D?
    * No work done yet.

Question:  I am building up a fairly big script for automating the testing. Any interest in putting it in the repo somewhere?

**Comment by allanbank** [comment]
I would like to see #353 / 2d6185e in 0.3.0.

**Comment by gkamat** [comment]
@allanbank, thanks for finishing the MongoDB testing quite so promptly!

With regard to testing, any automation would definitely be helpful.  Ideally, the script would work with all or most bindings we have.  The list of workloads and bindings being tested should be configurable and it should provide a good status summary at completion.

I will merge in #353 shortly into 0.3.0.

**Comment by busbey** [comment]
I have a script I use for running through the workloads for Accumulo and
HBase. I'd be glad to use a followup to your initial script to make sure I
don't need to maintain my own. :)

**Comment by allanbank** [comment]
My test script does lots of MongoDB specific things like pull the distributions from the MongoDB web site, start/stop MongoDB and clear the collections between test runs. Most of the port test analysis is me doing greps across the stdout/stderr files generated. Let me finish adding the testing on clusters and then I'll post in a gist for all of you to tear apart.

Rob

P.S. Can someone give #362  a +1? It is jump a bump of the driver version...

**Comment by gkamat** [comment]
Merged #353 into 0.3.0 and checked #362 into master.

**Comment by busbey** [comment]
I've been too overwhelmed with other responsibilities this week to make progress on testing the current RC. I think I'm going to get some time tomorrow.

What's timing look like for RC2? I want to make the Accumulo binding a little more usable and I can probably get a first cut up by tomorrow morning.

**Comment by gkamat** [comment]
I will cut a RC2 tomorrow.  Other testers: if you could wrap up testing your modules over the weekend and have results by Tuesday next week, that would be really helpful so as to get out 0.3.0 before the end of next week.  Thanks!

**Comment by gkamat** [comment]
Release candidate [0.3.0-RC2](https://github.com/brianfrankcooper/YCSB/releases/tag/0.3.0-RC2) is now available.

**Comment by cmccoy** [comment]
I'm having trouble compiling 0.3.0-RC2. It looks like 2d6185ee331d65ac514127aa6eb7d00aef16ee6a is included, which is missing an import for `java.util.concurrent.atomic.AtomicInteger`, but a9bc84c46e272fc6d83c21e1de7f760b27baa341, which resolves the problem, is not.

**Comment by cmccoy** [comment]
With a9bc84c46e272fc6d83c21e1de7f760b27baa341, HBase looks good.

**Comment by bigbes** [comment]
@cmccoy yes, it's broken. It's my fault, I didn't write that in my commit message :(

**Comment by gkamat** [comment]
I will cut a new RC shortly.  I should have checked the build after the merge.

**Comment by gkamat** [comment]
Release candidate [0.3.0-RC3](https://github.com/brianfrankcooper/YCSB/releases/tag/0.3.0-RC3) is now available.  Please use this candidate for any further testing.

@cmccoy, thanks for catching the issue with the previous RC and for testing HBase.  We should be able to treat the HBase binding as verified at this point, given that RC3 is essentially what you used in your testing.

**Comment by busbey** [comment]
FYI, still haven't had time to test on windows or check Accumulo. I'm tentatively blocking out some time this evening, but recent history has been full of life getting in the way.

**Comment by busbey** [comment]
I'd like to make sure we don't regress on which databases are in the "tested & supported" category. Looks like our current gaps are:

* accumulo: I should be able to knock this out this evening.
* tarantool: @bigbes do you have time to do a check again?
* cassandra: still have time @cmccoy ?

It'd also be nice if some of our updated bindings could make the transition.

* aerospike: could you check one of the RCs to confirm your additions work as expected @tlopatic ?
* infinispan: @mylesjao could you try out the infinispan specific artifact on the latest RC?
* orientdb: anyone have contacts in this community?

**Comment by busbey** [comment]
@gkamat could you recap which gates you want to see done before the release?

**Comment by bigbes** [comment]
@busbey i'll be AFK for next few days, but we use 0.3.0-RC* for testing/benchmarking Tarantool, so i suppose that connector is OK.

**Comment by busbey** [comment]
> @busbey i'll be AFK for next few days, but we use 0.3.0-RC* for testing/benchmarking Tarantool, so i suppose that connector is OK.

that sounds sufficient to me if it's sufficient for @gkamat

**Comment by gkamat** [comment]
At this point, we have the following bindings tested:
* MongoDB
* HBase
* Tarantool ( @bigbes 's use of the binding should ensure it works at least as well as in 0.2.0)

If we have one other binding done, I think we should be able to wrap up the release.  If @cmccoy can do Cassandra by mid-week, that will be great; otherwise, we can go with Accumulo.

I will run the licensing check and write up the release notes tomorrow, so we can cut the release Wednesday.

**Comment by tlopatic** [comment]
@busbey Yep, the RCs all worked with Aerospike and I just double-checked with RC3. (Sorry I didn't notice this ticket earlier.)

**Comment by busbey** [comment]
Confirmed windows works with RC3 following the instructions in the docs.

**Comment by busbey** [comment]
confirmed Accumulo works with 1.6 APIs, though I skipped workload e. ran into #340 again.

**Comment by busbey** [comment]
FYI, [this is the script I use to run the core workloads against hbase and accumulo](https://gist.github.com/busbey/c26ad8856d4a9434665b). Haven't figured out yet how to integrate it into the code base.

**Comment by cmccoy** [comment]
Sorry for the delay; I've been traveling. I can test Cassandra tonight.

**Comment by cmccoy** [comment]
@gkamat: cassandra-10 looks good.

@busbey: thanks for the test script.

One little thing:
core/src/main/java/com/yahoo/ycsb/Client.java:646 prints "YCSB Client 0.1"

**Comment by busbey** [comment]
the version at start up is #320

**Comment by busbey** [comment]
how's the draft of release notes coming @gkamat ?

**Comment by gkamat** [comment]
Sorry about the delay, was backlogged with other tasks.

Here are the [proposed release notes](https://gist.github.com/gkamat/c326403cfb7f0c764023).

**Comment by busbey** [comment]
minor nits:

* I would leave off the note about the licensing headers.
* I'd call out the Aerospike support as new via the emoticon: :new:
* Need issue numbers for the misc fixes
* Need issue #228 listed for the improvements to Infinispan

**Comment by busbey** [comment]
besides those couple of things, looks good to me.

**Comment by gkamat** [comment]
Updated the release notes.  However, with regard to the misc fixes, unless I've missed it, there is only a pull request, no issue for:
* Execute correct number of operations, even if not a multiple of thread count. (PR #338).

Are PR's acceptable in the Release Notes, or should an issue be created for this?

**Comment by gkamat** [comment]
[Release 0.3.0](https://github.com/brianfrankcooper/YCSB/releases/tag/0.3.0) published.  Will send out announcements shortly.
