### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: com.yahoo.ycsb.Client

### ISSUE THREAD

**Issue by pbgalvin** [brianfrankcooper/YCSB#361]
Hi, mighty confused.
After using YCSB successfully for a while on this host, it's now giving me an error. Started after I tried to write a script to automate some work.  Seems that I've lost track of some Java components, but I've changed nothing about Java. Thought it might be something I changed in my environment but logging out and back in did not clear the problem.  Don't know much about Java...  Thanks for any ideas.

[root@r2601-d5-us03 YCSB]# python2.7 ./bin/ycsb load mongodb-async -s -P workloads/workloadb
[WARN]  Running against a source checkout. In order to get our runtime dependencies we'll have to invoke Maven. Depending on the state of your system, this may take ~30-45 seconds
[DEBUG]  Running 'mvn -pl com.yahoo.ycsb:mongodb-binding -am package -DskipTests dependency:build-classpath -DincludeScope=compile -Dmdep.outputFilterFile=true'
java -cp /usr/local/YCSB/mongodb/conf:/usr/local/YCSB/mongodb/target/mongodb-binding-0.3.0-SNAPSHOT.jar:/root/.m2/repository/com/allanbank/mongodb-async-driver/2.0.1/mongodb-async-driver-2.0.1.jar:/usr/local/YCSB/core/target/core-0.3.0-SNAPSHOT.jar:/root/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.4/jackson-core-asl-1.9.4.jar:/root/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.4/HdrHistogram-2.1.4.jar:/root/.m2/repository/org/mongodb/mongo-java-driver/3.0.2/mongo-java-driver-3.0.2.jar:/root/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.4/jackson-mapper-asl-1.9.4.jar com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.AsyncMongoDbClient -s -P workloads/workloadb -load
Exception in thread "main" java.lang.NoClassDefFoundError: com/yahoo/ycsb/Client
Caused by: java.lang.ClassNotFoundException: com.yahoo.ycsb.Client
	at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
Could not find the main class: com.yahoo.ycsb.Client. Program will exit.

**Comment by allanbank** [comment]
Does this file exist: ```/usr/local/YCSB/core/target/core-0.3.0-SNAPSHOT.jar```?

If not make sure you do a ```mvn clean package``` before running ycsb.

If you are running automated scripts I recommend using the distribution that is generated by the ```package```.  It is located in the distribution/target/ directory as a ```ycsb-<version>.tar.gz``` file. If you unpack that file somewhere it will then have a directory with the bin/ycsb script and all of the dependencies for each binding in well know locations.

**Comment by pbgalvin** [comment]
Hi,

Yes the file exists: -rw-r--r--. 1 root root 1103269 Jul 16 11:56 /usr/local/YCSB/core/target/core-0.3.0-SNAPSHOT.jar

I used this method to install YCSB:
git clone git://github.com/brianfrankcooper/YCSB.git
cd YCSB
mvn -pl com.yahoo.ycsb:mongodb-binding -am clean package

I then do my work in /usr/local/YCSB.
It’s very odd that one script works fine, but if I run my new script it not only doesn’t work but also causes the first script to stop working...

—Peter

**Comment by pbgalvin** [comment]
Just tried reinstalling with 
git clone git://github.com/brianfrankcooper/YCSB.git <git://github.com/brianfrankcooper/YCSB.git>
cd YCSB
mvn -pl com.yahoo.ycsb:mongodb-binding -am clean package

That seemed to fix the problem (probably until I run my new script again)…

—Peter

**Comment by allanbank** [comment]
Any chance you can post the new script in a gist?

**Comment by busbey** [comment]
Peter could you try using the 0.2.0 binary release instead of the working repo?

With the binary release you can run your tests without having to build.

**Comment by pbgalvin** [comment]
That seems to have fixed the problem. Thanks!

—Peter
