### ISSUE TITLE
Document release process

### ISSUE THREAD

**Issue by busbey** [brianfrankcooper/YCSB#363]
We should document how to do a release so that we can get more folks acting as release manager.

**Comment by busbey** [comment]
WIP guide : https://gist.github.com/busbey/5d977d38a6237bd603c4

**Comment by gkamat** [comment]
Excellent writeup. I'll update as needed based upon any observations during the 0.3.0 release. Will also add a note on signing release and adding checksum information as in [issue 347](https://github.com/brianfrankcooper/YCSB/issues/347).

**Comment by gkamat** [comment]
Made some changes to this doc on my fork; feel free to pull and merge as desired.

**Comment by busbey** [comment]
[wiki page "Managing a Release"](https://github.com/brianfrankcooper/YCSB/wiki/Managing-a-Release) has the work so far. putting together an update now.

**Comment by busbey** [comment]
by the way, @technmsg thanks for the commit!

**Comment by busbey** [comment]
the [WIP gist](https://gist.github.com/busbey/5d977d38a6237bd603c4) has now been updated to fill in the rest of the process and fix some whitespace errors.

**Comment by busbey** [comment]
bump. can someone take a look at the gist so I can close this out?

**Comment by allanbank** [comment]
Looks good to me.

**Comment by busbey** [comment]
pushed to wiki

**Comment by gkamat** [comment]
The gist and wiki look good.  The material was very helpful for the 0.3.0 release.  Have a few small updates based on that, will add that to the wiki directly.
