### ISSUE TITLE
Make checkstyle enforcing for the MongoDB client.

### ISSUE THREAD

**Issue by allanbank** [brianfrankcooper/YCSB#365]
I have been getting annoyed with the multiple formats rolling around so I have started with my own yard and made the checkstyle enforcing for the MongoDB client.

To get the build to pass most of the changes were done via automated formatters/cleanup. The rest where variable name changes.

The bad part of doing this kind of thing is it creates a patch horizon that it is extremely difficult to move patches across (in either direction). I think the consistency is worth the one time pain.

**Comment by gkamat** [comment]
I agree it's a good idea to get it over with.  We should do this for the other modules too when we get a chance.

**Comment by busbey** [comment]
I want to see this enforcing long term, but please hold off on cassandra, hbase, and core until after I manage to get #98 merged.

**Comment by gkamat** [comment]
+1
