### ISSUE TITLE
CCLA agreement for Pull requests

### ISSUE THREAD

**Issue by ivanB1975** [brianfrankcooper/YCSB#367]
Hi guys,

I would like to make a small pull request with a new binding. My company requires a CCLA agreement (CCLA - Corporate Contribution Licence Agreement) from you to be able to approve my pull request.
Is it possible this? Where can I get it. 
Bests
Ivan

**Comment by gkamat** [comment]
YCSB is distributed under the Apache license and any code contributed should conform to it.  This is an open-source project facilitated by maintainers, so there is no "organization" as such that would supply a license agreement to you (apart from the Apache license).

**Comment by busbey** [comment]
I'll see what we can come up with. How long of a timeline is okay for you
Ivan?

**Comment by ivanB1975** [comment]
Hi, thanks, 
yes off course I would use the same license of YCSB, we fully support it. I need a CCLA to get the approval from my department. If you can provide me with some sort of CCLA I can also wait. @busbey how long do you think it will take?
Many thanks
Ivan

**Comment by ivanB1975** [comment]
Maybe an already existing CCLA can be used also in this case. For example here: https://developer.yahoo.com/cocktails/mojito/cla/ 
you already use a CCLA.
What do you think?
Bests
Ivan

**Comment by busbey** [comment]
Well, YCSB doesn't get run out of Yahoo!'s developer group. We don't have any established CLA process because we rely on ASLv2 licensing from all of the contributors.

Do you know what your department wants to make sure is covered in the CCLA?

**Comment by cmatser** [comment]
I saw this site that might help us: https://www.clahub.com/

**Comment by cmatser** [comment]
It has more information that you'd ever want to know about CLAs.  It may not be the site to go with, but there's a discussion on alternatives, if the site maintainer doesn't find a suitable replacement for himself.

**Comment by ivanB1975** [comment]
Thanks guys, I need to ask to my boss exactly the requirements. I will come back with these information ASAP.

**Comment by ivanB1975** [comment]
We submitted the request to the department and it could be we will not need any CCLA. Let's see. As soon I have new information I will post here.
Thanks
Ivan

**Comment by ivanB1975** [comment]
We can close the issue. I got the approval for the pull request. I will proceed so with it. Thanks for the support.
