### ISSUE TITLE
run YCSB for fixed duration

### ISSUE THREAD

**Issue by patiner** [brianfrankcooper/YCSB#377]
Hi,

Can I run YCSB with fixed duration, e.g., one hour? I mean is there any command line parameters for me to set this duration?

Thanks.

**Comment by busbey** [comment]
Yep! There's a "max execution time" parameter. At the moment there isn't an explicit "by time" mode, so I set the insert/operation count to max. At least so far none of the systems I've tested have been able to chew through things in an hour.

I'll post an example when I get to a computer.

**Comment by patiner** [comment]
Thanks so much, Sean :) I will try this "max execution time".

**Comment by busbey** [comment]
It's a bit more than you're looking for, but [the helper I use when running the core workloads against a YCSB RC](https://gist.github.com/busbey/c26ad8856d4a9434665b) has an example of setting the properties to do "run for an hour".

To run on a single host, you just leave out the host_offset.txt file or set it to contain the hostname mapped to offset 0.

**Comment by nitsanw** [comment]
This seems to be covered by max_execution_time, why not close it?

**Comment by JigarProjects** [comment]
It looks like there is problem in max execution time. 
I am running an experiment on virtual machine which has 256MB Ram with 3GB of Hard Disk. 
I installed mysql and configured YCSB with 1000 thread to load database. I set maxexecutiontime to 10 second and YCSB is not responding.

It repeatedly says that "Still waiting for thread Thread-XXX to complete. Workload status: true"

**Comment by antonis-papaioannou** [comment]
It seems that 1000 threads is overkill for your VM.
Try to set the numbers of threads equal to the number of your virtual cpus and play a little bit with this number while at the same time monitor the cpu utilizations

> It looks like there is problem in max execution time.
> I am running an experiment on virtual machine which has 256MB Ram with 3GB of Hard Disk.
> I installed mysql and configured YCSB with 1000 thread to load database. I set maxexecutiontime to 10 second and YCSB is not responding.
> 
> It repeatedly says that "Still waiting for thread Thread-XXX to complete. Workload status: true"

**Comment by pogobanane** [comment]
To summarize the discussion above:
the cli parameter goes like `-p max_execution_time=10` (in seconds)
