### ISSUE TITLE
YCSB HBaseclient does not compile with HBase-2.0

### ISSUE THREAD

**Issue by ramkrish86** [brianfrankcooper/YCSB#379]
Based on a discussion today raising this issue so that it can act as a placeholder. I can submit a patch too. 
The HBase-2.0 removes some of the deprcated API like KV.getValue(), kv.getRow() and the Result.raw() APIs.  We can modify the client code accordingly so that it compiles with HBase-2.0 and anyway it would work with HBase-1.0 also.
{code}
-                            Bytes.toString(kv.getQualifier()),
-                            new ByteArrayByteIterator(kv.getValue()));
+                            Bytes.toString(kv.getQualifierArray(), kv.getQualifierOffset(), kv.getQualifierLength()),
+                            new ByteArrayByteIterator(kv.getValueArray(), kv.getValueOffset(), kv.getValueLength()));
{code}

**Comment by busbey** [comment]
sounds like we should break the 0.94 binding out into a different module so this can go into the hbase-10 binding.

**Comment by cmccoy** [comment]
Updated #392 to remove the use of `KeyValue` in favor of Cell; it compiles without any deprecation warnings against HBase 1.1.1 as of 95e98d9604117685c2a41f09449d6d6e68228e3d.

**Comment by cmccoy** [comment]
@ramkrish86: Could you try again with latest master?

**Comment by ramkrish86** [comment]
Thanks for fixing this.  Will see if I can give a try on the latest checkin.
