### ISSUE TITLE
 -P (No such file or directory) Error while loading data

### ISSUE THREAD

**Issue by bharathstpi** [brianfrankcooper/YCSB#385]
Hello,

 I am executing basic load and am getting the below error.

 /opt/ycsb-0.1.4% ./bin/ycsb load basic -P workloads/workloada
 -P (No such file or directory)

 I am getting the same error when I am executing the load on MongoDB.

 Thanks for your support.

 Regards,
 Bharath

**Comment by cmccoy** [comment]
Hi Bharath,

Could you try with the most recent release ([v0.3.0](https://github.com/brianfrankcooper/YCSB/releases/tag/0.3.0))?

**Comment by bharathstpi** [comment]
Hello Connor,

Thanks for your reply. I tried it on the different server and it works. Can
you please let me know what are the pre-requisites for YCSB benchmark on
MongoDB? Looks like the benchmark is executing but I do not see on which
collections that data is inserted/read and updated. The DB name is
configurable but I am not sure about the collection name.


Regards,
Bharath Singh

**Comment by allanbank** [comment]
The collection name is the table name provided for each operation. It defaults to ```usertable``` and is configured by the [core workload package properties](https://github.com/brianfrankcooper/YCSB/wiki/Core-Properties#core-workload-package-properties).

Requirements are actually pretty minimal since MongoDB will automatically create the database and collection once you start inserting data into it.

Have you tried using the 'mongostat' tool to monitor the MongoDB Cluster while the YCSB client is running? It is a good way to verify that the operations are making it to the cluster. If you have a large cluster use the ```--discover``` option to see the entire cluster from one display.

**Comment by bharathstpi** [comment]
Thank You Sean. Will get back to you once I start the benchmarking the
MongoDB using YCSB.

-Bharath

**Comment by busbey** [comment]
sounds like the immediate issue is solved. please reopen if that's not the case. If you run into a problem in your benchmarking of mongodb, please open a new issue.

**Comment by bharathstpi** [comment]
Hello Sean,

When I am running the YCSB load command I am getting the below error.

/opt/ycsb-0.1.4% bin/ycsb load mongodb -s -P workloads/workloada -p
recordcount=10000000 -threads 16 -p  mongodb.url=
blrrnddbsm04.rnd.amadeus.net:61017/test > mongooutput/workloada_24.log
Loading workload...
Starting test.
 0 sec: 0 operations;
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
Aug 24, 2015 10:18:12 AM com.mongodb.DBPortPool$Holder get
WARNING: jmx registration error:
javax.management.InstanceAlreadyExistsException:
com.mongodb:type=ConnectionPool,host=blrrnddbsm04.rnd.amadeus.net,port=61017/test/null,instance=2058297015
continuing...
java.lang.NullPointerException
 0 sec: 0 operations; [INSERT AverageLatency(us)=202.62]

I presume that the YCSB should create the collection and insert the records
on its own. Can you tell me what am I missing here?

Regards,
Bharath Singh

**Comment by busbey** [comment]
Please open a new issue. Also, please ensure you are using the 0.3.0 release.
