### ISSUE TITLE
Release version 0.3.1

### ISSUE THREAD

**Issue by busbey** [brianfrankcooper/YCSB#391]
Hi folks, it's the middle of the month again! :)

I looked back through git history since 0.3.0 branched, and it looks like the following are in master and not 0.3.0:

* #359 (exit as soon as worker threads are done) and #239 (include est time remaining) via #316 
* #362 update mongo driver version to 3.0.3
* #366 enforce checkstyle for mongo
* #381 fix hdrhistogram recorder/logger initialization timing issue.
* #389 use the container based infrastructure for Travis Builds

The things I'd like to make sure get out in a timely manner are #362 and #381. None of these changes indicate a need for "0.4.0".

What do folks think about a quick turn around for 0.3.1? Since it'd be a patch release, I'd be fine only needing to test bindings that are actually touched (i.e. mongo) and leaving everyone else's "tested" status as in the 0.3.0 release.

**Comment by busbey** [comment]
Barring additional feedback, I'm going to spin up on a 0.3.1 release this evening.

**Comment by busbey** [comment]
[0.3.1 RC1](https://github.com/brianfrankcooper/YCSB/releases/tag/0.3.1-RC1) is available now.

Since this is a patch release, the only thing I'm concerned with verifying is the new driver used in the mongodb binding.

@allanbank got time to run this one through the MongoDB gauntlet? If not, could you post your test script and I'll take care of it?

I'd like to have things packaged and out the door early next week.

**Comment by allanbank** [comment]
MongoDB looks good. Ran through the standard suite with version 3.0.5, 2.6.11, 2.4.14, 2.2.7, 2.0.9, and 1.8.5. Everything looks good except the return=1 values for Workload D which is #327.

I need to get more testing time in on the fix @tlopatic started in #364 so I feel comfortable merging it. (not for 0.3.1)

Rob.

**Comment by busbey** [comment]
awesome. thanks for checking things out so fast Rob. barring other issues, I'll run through a rat check and then push the release tomorrow.

**Comment by busbey** [comment]
Proposed release notes: https://gist.github.com/busbey/1680c0133761263e595a

**Comment by allanbank** [comment]
> Proposed release notes:
> https://gist.github.com/busbey/1680c0133761263e595a
>

Looks good to me.

**Comment by cmatser** [comment]
:+1:  0.3.1 Release Notes

**Comment by busbey** [comment]
My apologies. I went on vacation and didn't realize I had forgotten to actually push the release tag and artifacts. :/

The release is live now: https://github.com/brianfrankcooper/YCSB/releases/tag/0.3.1
