### ISSUE TITLE
URL in the readme is a redirect

### ISSUE THREAD

**Issue by jdesfossez** [brianfrankcooper/YCSB#393]
The curl command provided in the Getting Started section of the readme actually downloads a HTML redirect page instead of the .tar.gz file and it seems that the link in the redirect file cannot be used as is with curl/wget. I am not sure if it is possible to have a direct link to the file, but if someone knows how, that would be really useful. Thanks !

**Comment by allanbank** [comment]
Looks like we need to add the ```--location``` option to the curl command.

**Comment by jdesfossez** [comment]
Indeed it works, thanks ! Do you want me to create a pull request with the update ?

**Comment by allanbank** [comment]
Thanks but I am already on it.
