### ISSUE TITLE
ycsb compiles but all tests/workloads fail with "AttributeError: 'module' object has no attribute 'check_output'"

### ISSUE THREAD

**Issue by duck-tape** [brianfrankcooper/YCSB#397]
I have downloaded (git) and compiled YCSB using java 1.7 as follows:

YCSB]$ javac -version
javac 1.7.0_85
YCSB]$ mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T09:29:23-08:00)
Maven home: /usr/share/apache-maven
Java version: 1.7.0_85, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.85.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "2.6.32-573.3.1.el6.x86_64", arch: "amd64", family: "unix"

Output of the mvn clean package

[INFO] Processing sources for module project: com.yahoo.ycsb:accumulo-binding:jar:0.4.0-SNAPSHOT
[INFO] Processing sources for module project: com.yahoo.ycsb:aerospike-binding:jar:0.4.0-SNAPSHOT
[INFO] Processing sources for module project: com.yahoo.ycsb:cassandra-binding:jar:0.4.0-SNAPSHOT
[INFO] Processing sources for module project: com.yahoo.ycsb:couchbase-binding:jar:0.4.0-SNAPSHOT
[INFO] Processing sources for module project: com.yahoo.ycsb:dynamodb-binding:jar:0.4.0-SNAPSHOT
[INFO] Processing sources for module project: com.yahoo.ycsb:elasticsearch-binding:jar:0.4.0-SNAPSHOT
[INFO] Processing sources for module project: com.yahoo.ycsb:gemfire-binding:jar:0.4.0-SNAPSHOT
[INFO] Processing sources for module project: com.yahoo.ycsb:hbase-binding:jar:0.4.0-SNAPSHOT
[INFO] Processing sources for module project: com.yahoo.ycsb:hypertable-binding:jar:0.4.0-SNAPSHOT
[INFO] Processing sources for module project: com.yahoo.ycsb:infinispan-binding:jar:0.4.0-SNAPSHOT
[INFO] Processing sources for module project: com.yahoo.ycsb:jdbc-binding:jar:0.4.0-SNAPSHOT
[INFO] Processing sources for module project: com.yahoo.ycsb:mongodb-binding:jar:0.4.0-SNAPSHOT
[INFO] Processing sources for module project: com.yahoo.ycsb:orientdb-binding:jar:0.4.0-SNAPSHOT
[INFO] Processing sources for module project: com.yahoo.ycsb:redis-binding:jar:0.4.0-SNAPSHOT
[INFO] Processing sources for module project: com.yahoo.ycsb:tarantool-binding:jar:0.4.0-SNAPSHOT
[INFO] Building tar: /home/aalurkar/YCSB/distribution/target/ycsb-0.4.0-SNAPSHOT.tar.gz
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] YCSB Root .......................................... SUCCESS [  1.169 s]
[INFO] Core YCSB .......................................... SUCCESS [  7.702 s]
[INFO] Per Datastore Binding descriptor ................... SUCCESS [  0.428 s]
[INFO] YCSB Datastore Binding Parent ...................... SUCCESS [  0.337 s]
[INFO] Accumulo DB Binding ................................ SUCCESS [  1.535 s]
[INFO] Aerospike DB Binding ............................... SUCCESS [  0.980 s]
[INFO] Cassandra DB Binding ............................... SUCCESS [  1.050 s]
[INFO] Couchbase Binding .................................. SUCCESS [  0.981 s]
[INFO] DynamoDB DB Binding ................................ SUCCESS [  0.536 s]
[INFO] ElasticSearch Binding .............................. SUCCESS [  4.065 s]
[INFO] Gemfire DB Binding ................................. SUCCESS [  0.613 s]
[INFO] HBase DB Binding ................................... SUCCESS [  4.000 s]
[INFO] Hypertable DB Binding .............................. SUCCESS [  0.451 s]
[INFO] Infinispan DB Binding .............................. SUCCESS [  1.205 s]
[INFO] JDBC DB Binding .................................... SUCCESS [  0.534 s]
[INFO] MongoDB Binding .................................... SUCCESS [  1.045 s]
[INFO] OrientDB Binding ................................... SUCCESS [  0.795 s]
[INFO] Redis DB Binding ................................... SUCCESS [  0.564 s]
[INFO] Tarantool DB Binding ............................... SUCCESS [  0.521 s]
[INFO] YCSB Release Distribution Builder .................. SUCCESS [  7.336 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 36.201 s
[INFO] Finished at: 2015-08-24T08:53:07-07:00
[INFO] Final Memory: 64M/279M
[INFO] ------------------------------------------------------------------------

But when I try and execute ycsb

YCSB]$ ./bin/ycsb shell basic
[WARN]  Running against a source checkout. In order to get our runtime dependencies we'll have to invoke Maven. Depending on the state of your system, this may take ~30-45 seconds
[DEBUG]  Running 'mvn -pl com.yahoo.ycsb:basic-binding -am package -DskipTests dependency:build-classpath -DincludeScope=compile -Dmdep.outputFilterFile=true'
Traceback (most recent call last):
  File "./bin/ycsb", line 225, in <module>
    sys.exit(main())
  File "./bin/ycsb", line 204, in main
    maven_says = get_classpath_from_maven(binding)
  File "./bin/ycsb", line 144, in get_classpath_from_maven
    mvn_output = subprocess.check_output(["mvn", "-pl", "com.yahoo.ycsb:"+database+"-binding",
AttributeError: 'module' object has no attribute 'check_output'

any ideas?

**Comment by cmccoy** [comment]
The YCSB runner requires python 2.7. Are you by any chance using 2.6?

**Comment by duck-tape** [comment]
Yes I am

**Comment by cmccoy** [comment]
You need at least 2.7 to run `bin/ycsb` - see #341.

**Comment by busbey** [comment]
did upgrading the python version fix things for you @duck-tape ?

**Comment by busbey** [comment]
Bump. Please let us know if this fixed things.

**Comment by nsabharwal** [comment]
Upgrading to Python 2.7 did fix the issue
