### ISSUE TITLE
Error while loading basic workload

### ISSUE THREAD

**Issue by bharathstpi** [brianfrankcooper/YCSB#399]
Hello,

I am getting the below error when I execute the load command 

/opt/ycsb-0.3.0% ./bin/ycsb load basic -P workloads/workloada
Traceback (most recent call last):
  File "./bin/ycsb", line 19, in <module>
    import argparse
ImportError: No module named argparse

I will be doing a benchmark on MongoDB. Can you please assist me here as I am getting the same error while executing MongoDB load?

bin/ycsb load mongodb -s -P workloads/workloada -p recordcount=10000000  -p  mongodb.url="blrrnddbsm04.rnd.amadeus.net:61017,blrrnddbsm05.rnd.amadeus.net:61018,blrrnddbsm06.rnd.amadeus.net:61019" -p mongodb.database=test  > mongooutput/workloada1.log
Traceback (most recent call last):
  File "bin/ycsb", line 19, in <module>
    import argparse
ImportError: No module named argparse

Regards,
Bharath Singh

**Comment by cmccoy** [comment]
Python 2.7 is required for the YCSB runner script (`bin/ycsb`) - I suspect that you're using 2.6.

**Comment by busbey** [comment]
Any update here? you can  check your python version like so:

```bash
busbey$ python --version
Python 2.7.2
```

**Comment by bharathstpi** [comment]
Hello Sean,

It worked with the python upgrade to 2.7. Please close the ticket. I will
open one if there are any other issues.

Regards,
Bharath Singh

**Comment by allanbank** [comment]
Closing per request.
