### ISSUE TITLE
YCSB MongoDB execute update instead of insert

### ISSUE THREAD

**Issue by Spectrumleeee** [brianfrankcooper/YCSB#400]
i tried to use YCSB-0.3.0 to test the write ops of mongodb, and i used mongostat to show the status of mongodb, i can't find the insert operation not matter during load phase or run phase with insert operations, it turns out YCSB use update operation to insert all the records. So, how can i use YCSB to test insert ops of mongodb?

**Comment by allanbank** [comment]
Yes - The MongoDB adapter uses upserts for the insert operations. Using upsert allows the operations to succeed in the case that the document is already present (re-running a load when the documents are already present is a common instance). 

It should not be that hard to update the adapter to add the ability to switch from upserts to inserts and I would  gladly accept a patch...

Rob.
