### ISSUE TITLE
Throughput per second not visible post after execution of a run

### ISSUE THREAD

**Issue by amar2000** [brianfrankcooper/YCSB#404]
In the previous version once we ran the load we used to get the throughput (overall throughput), however we are not seeing the same in the older version. Is there a flag or parameter to be used to get this in the o/p

**Comment by busbey** [comment]
What version are you using? Which binding?

There should still be total throughout at the end.

**Comment by amar2000** [comment]
I am using the latest version .

Can you please explain what do u mean by binding

**Comment by busbey** [comment]
Which datastore are you using YCSB with? e.g. hbase, MongoDB, Cassandra, etc...

**Comment by amar2000** [comment]
I am using Mongo

**Comment by allanbank** [comment]
Can you post a sample of what you saw before and what you are seeing now?

**Comment by busbey** [comment]
Can you try doing this again now that the default measurement system has changed from 'histogram' to 'hdrhistogram'?

The HDR Histogram implementation prints much less detail than the older one (most of which ended up being filler), so the throughput value should be easier to pick out.

**Comment by busbey** [comment]
any update here @amar2000 ?

**Comment by busbey** [comment]
Closing as stale. If you are still seeing this issue and would like help troubleshooting please reopen.
