### ISSUE TITLE
Mmodify YCSB request header to generate SSE and SSEC securities

### ISSUE THREAD

**Issue by ShreyasC** [brianfrankcooper/YCSB#413]
We are using YCSB to generate traffic to S3.

I am trying to generate YCSB load with SSE and SSEC encryption traffic through YCSB to know the impact of encryption.

To enable this traffic the request header would have to be modified. Here are 3 sample requests to put 1KB objects.

sample request inserting 1KB object with no encryption
./put.py -S amazon -b 1K f1

sample request inserting 1KB SSE object 
./put.py -S amazon -b 1K -H '{"x-amz-server-side-encryption":"AES256"}' f2

sample request inserting 1KB SSEC object 
./put.py -S amazon -b 1K -H '{"x-amz-server-side-encryption-customer-algorithm":"AES256","x-amz-server-side-encryption-customer-key":"U2CccCI40he2mZtg2aCEzofP7nQsfy4nP14VSYu6bFA=","x-amz-server-side-encryption-customer-key-MD5":"GVLmBQ1EQKAN2sE2FOlUMQ=="}' f3

How to modify YCSB request header to insert the about encryptions?

Further details about SSE and SSEC:
1. SSE
Need to add HTTP header to PUT Object request
x-amz-server-side-encryption : AES256 

2. SSEC
x-amz-server-side-encryption -customer-algorithm : AES256 
x-amz-server-side -encryption-customer-key: <Encryption key>
x-amz-server-side-encryption -customer-key-MD5: <MD5(Encryption key)>
http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html
Strong encryption jars for java 7
http://www.oracle.com/technetwork/java/javase/downloads/jce-7-download-432124.html

**Comment by busbey** [comment]
are you using the S3 binding over in #372 or something else?

**Comment by ivanB1975** [comment]
For both cases this can be implemented in the s3 binding. I have to go on this.

**Comment by ivanB1975** [comment]
I added the support for SSE for the insert operations. I will deploy the changes later. I will work on the SSEC. I have some limited time lately. Next weekend will be more productive.

**Comment by ivanB1975** [comment]
To use the SSE encryption with the s3-binding you have to set in the file s3.properties "s3.sse=true"
Doing that it will automatically select Server side encryption with AES256.

**Comment by ivanB1975** [comment]
I also added the support for SSE-C encryption. This can be used placing on the s3.properties file "s3.ssec=THE-KEY-TO-USE", if not present the encryption is not used.
It is not necessary to provide a MD5 since the sdk take care of this.

**Comment by ShreyasC** [comment]
Hi Ivan,
I added ssec header information in the workload file, pointed YCSB to 443(https port) and changed protocol to https in the workload file.

However YCSB still generates http traffic and not https. Does it require any other change in the workload file?

**Comment by ivanB1975** [comment]
Ah yes I see. I have to include many settings for the Client and one of this is the protocol. By default is http. I will do in some moments.

**Comment by ivanB1975** [comment]
I added the possibility to set the protocolo in the file s3.properties. If you set s3.protocol=HTTPS it should use the HTTPS one. Please try and let me know

**Comment by ivanB1975** [comment]
Did it work?

**Comment by ShreyasC** [comment]
I still trying few options. ycsb continues to create http request. Its due the mismatch in certificate in the client (ycsb box) and s3. So I would either need to copy the certificate key or disable it.

Thanks for asking
Shreyas

**Comment by ivanB1975** [comment]
Hi Shreyas,

I will look at this problem, it could be that I have to use the https option accept unauthorized. I will verify this tomorrow

Bests
Ivan

**Comment by ivanB1975** [comment]
Just checking the docs and it is written that by default the protocol is HTTPS. 
I will try to dump the traffic and test this.

**Comment by ShreyasC** [comment]
HI Ivan,
We don't seem to be using brainfrankcooper YCSB as there is no s3.properties file.

I am working on this. Will let you know the progress.

Thanks,
Shreyas

**Comment by busbey** [comment]
@ShreyasC note that Ivan is talking about his work-in-progress contribution on #372. it's not in the main bfc repo yet, though I believe it is close. If you need help pulling his changes so you can test them out locally, let me know (here or on #372)
