### ISSUE TITLE
support cockroachdb?

### ISSUE THREAD

**Issue by YuleiXiao** [brianfrankcooper/YCSB#417]
Does YCSB support cockroachdb?

**Comment by busbey** [comment]
I do not believe we currently have a cockroachdb specific client. A quick browse through [the cockroachdb git rep](https://github.com/cockroachdb/cockroach) shows that they support some subset of SQL, but didn't turn up a JDBC driver.

Interested in contributing one?

**Comment by bigbes** [comment]
Any UPD on this?

**Comment by risdenk** [comment]
Closing due to no response. If there is still interest please reopen.
