### ISSUE TITLE
Document commands to create tables in Cassandra bindings

### ISSUE THREAD

**Issue by busbey** [brianfrankcooper/YCSB#421]
over on #418, @Thomas-Yang has got the commands needed to properly initialize tables in both the old Cassandra thrift binding and the CQL one. We should make a README file and get them in there.

Here're his findings copied for convenience:

 ```cassandra-cli``` solves the problem. It seems the keyspace and table generated by ```cassandra-cli``` and ```cqlsh``` is not totally compatible. The commands I tried out are listed as follows:

 | cassandra-10 | cqlsh
------------ | ------------- | -------------
create keyspace | create keyspace **usertable** with placement_strategy = 'org.apache.cassandra.locator.SimpleStrategy' and strategy_options = {replication_factor:1}; | create keyspace **ycsb** with replication = {'class' : 'SimpleStrategy', 'replication_factor': 1 };
create table | create column family **data** with column_type = 'Standard' and comparator = 'UTF8Type'; | create table **usertable** (y_id text primary key,field0 varchar,field1 varchar,field2 varchar,field3 varchar,field4 varchar,field5 varchar,field6 varchar,field7 varchar,field8 varchar,field9 varchar);

Since the ```cassandra-cli``` (the Thrift API) will be removed soon (from v3.0 I guess), I am not sure it worths the effort to improve the consistency. Anyway, I do hope the above commands are useful for people still want to try out both bindings.

**Comment by cmccoy** [comment]
These are now documented in `cassandra/README.md` (Thrift) and `cassandra2/README.md` (CQL).
