### ISSUE TITLE
Benchmarking new DB with YCSB

### ISSUE THREAD

**Issue by shehbazj** [brianfrankcooper/YCSB#424]
Hi,

I am trying to benchmark my own linear key value store (called lkvs)
having PUT/GET/DEL API. I followed the instructions here:
https://github.com/brianfrankcooper/YCSB/wiki/Adding-a-Database

And created a new file that extends db class here:
```
YCSB/lkvs/src/main/java/com/yahoo/ycsb/db/LkvsClient.java
```
I tried compiling it using javac but it gave me the following error:
```
donjaffer@donjaffer-ASUS:~/research/YCSB/lkvs/src/main/java/com/yahoo/ycsb/db$
javac LkvsClient.java
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar
LkvsClient.java:12: error: cannot find symbol
import com.yahoo.ycsb.db;
                     ^
  symbol:   class db
  location: package com.yahoo.ycsb
LkvsClient.java:23: error: cannot find symbol
public class LkvsClient extends DB {
                                ^
  symbol: class DB
LkvsClient.java:27: error: cannot find symbol
    public void init() throws DBException
                              ^
 symbol:   class DBException
  location: class LkvsClient
3 errors
```

So I tried adding the lkvs tool to the maven build system like so:
```
diff --git a/pom.xml b/pom.xml
index cf5f5bc..231c27a 100644
--- a/pom.xml
+++ b/pom.xml
@@ -90,6 +90,7 @@ LICENSE file.
     <couchbase.version>1.1.8</couchbase.version>
     <tarantool.version>1.6.1</tarantool.version>
     <aerospike.version>3.1.2</aerospike.version>
+    <lkvs.version>0.0.1</lkvs.version>
   </properties>

   <modules>
@@ -110,6 +111,7 @@ LICENSE file.
     <module>hbase10</module>
     <module>hypertable</module>
     <module>infinispan</module>
+    <module>lkvs</module>
     <module>jdbc</module>
     <!--<module>mapkeeper</module>-->
     <module>mongodb</module>
```
I also created a pom.xml file in the lkvs folder (looking at
cassandra's pom.xml) here:
```
donjaffer@donjaffer-ASUS:~/research/YCSB$ diff cassandra/pom.xml lkvs/pom.xml
28,29c28,29
<   <artifactId>cassandra-binding</artifactId>
<   <name>Cassandra DB Binding</name>
---
>   <artifactId>lkvs-binding</artifactId>
>   <name>LKVS DB Binding</name>
34,36c34,36
<        <groupId>org.apache.cassandra</groupId>
<        <artifactId>cassandra-all</artifactId>
<        <version>${cassandra.version}</version>
---
>        <groupId>org.apache.lkvs</groupId>
>        <artifactId>lkvs-all</artifactId>
>        <version>${lkvs.version}</version>
38c38
<      <!-- CQL driver -->
---
>      <!-- CQL driver
40,43c40,43
<        <groupId>com.datastax.cassandra</groupId>
<        <artifactId>cassandra-driver-core</artifactId>
<        <version>${cassandra.cql.version}</version>
<      </dependency>
---
>        <groupId>com.datastax.lkvs</groupId>
>        <artifactId>lkvs-driver-core</artifactId>
>        <version>${lkvs.cql.version}</version>
>      </dependency> -->
```
But now running mvn like this:
```
mvn -pl com.yahoo.ycsb:lkvs-binding -am clean package -e
```
gives me the following build error:
```
[ERROR] Failed to execute goal on project lkvs-binding: Could not
resolve dependencies for project
com.yahoo.ycsb:lkvs-binding:jar:0.5.0-SNAPSHOT: Failure to find
org.apache.lkvs:lkvs-all:jar:0.0.1 in
https://repo.maven.apache.org/maven2 was cached in the local
repository, resolution will not be reattempted until the update
interval of central has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to
execute goal on project lkvs-binding: Could not resolve dependencies
for project com.yahoo.ycsb:lkvs-binding:jar:0.5.0-SNAPSHOT: Failure to
find org.apache.lkvs:lkvs-all:jar:0.0.1 in
https://repo.maven.apache.org/maven2 was cached in the local
repository, resolution will not be reattempted until the update
interval of central has elapsed or updates are forced
```
I am unable to understand how to add an interface so that I can use
YCSB for my new database. Could anyone please tell me what additional
steps would be required to correctly add a new database API to run
YCSB on it?

I would be happy to contribute to a generic API code, but I would
appreciate some guidance in this regard

Thanks!

**Comment by cmccoy** [comment]
It looks like your message formatting got jumbled a little here. Could you try bracketing code / console output with \`\`\`, as described [here](https://guides.github.com/features/mastering-markdown/)?

If you have all of your database binding code included in your `lkvs-binding`, you shouldn't need to add an external dependency for it - try removing the dependency on `org.apache.lkvs:lkvs-all`? I can't find any record of that artifact online.

**Comment by shehbazj** [comment]
@cmccoy Thank you for your reply. I have made appropriate changes in the previous comment. Hope this helps readability.
It is my own Key-Value store hence the bindings are not available online. Could you please point out code for other database bindings (eg-mongodb?) so that I can follow the code and write my own lkvs-binding tool? I am new to java so sorry if I am asking obvious questions. If I am able to benchmark my db with YCSB, I will definitely write a README describing how to write API interface for using YCSB.

Thank you for your help.

**Comment by cmccoy** [comment]
If your bindings aren't available online, you can either publish the jar to your local maven repository, or include the necessary code in your lkvs-binding source directory.

**Comment by busbey** [comment]
If your goal is to eventually contribute the binding, could you publish the bindings somewhere, e.g. maven central?

**Comment by shehbazj** [comment]
Hi,

I am still stuck on this! If someone has time could you please tell why am I not able to compile my code and create a binding here:

```
donjaffer@donjaffer-ASUS:~/research/YCSB$ javac -cp core/src/main/java/ lkvs/src/main/java/com/yahoo/ycsb/LkvsClient.java 
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
lkvs/src/main/java/com/yahoo/ycsb/LkvsClient.java:12: error: cannot find symbol
import com.yahoo.ycsb;
                ^
  symbol:   class ycsb
  location: package com.yahoo
lkvs/src/main/java/com/yahoo/ycsb/LkvsClient.java:23: error: cannot find symbol
public class LkvsClient extends DB {
                                ^
  symbol: class DB
lkvs/src/main/java/com/yahoo/ycsb/LkvsClient.java:27: error: cannot find symbol
	public void init() throws DBException
	                          ^
  symbol:   class DBException
  location: class LkvsClient
3 errors
donjaffer@donjaffer-ASUS:~/research/YCSB$
```
@busbey Yes, I plan to publish binding at OSSRH.

Thanks for your help in advance.

**Comment by busbey** [comment]
you need to use Maven 3+ to build, rather than attempt to find the correct classpath manually.

presuming your new binding is in a directory called 'lkvs', you need to add it as a submodule to the top-level maven pom like so:

````diff
diff --git a/pom.xml b/pom.xml
index cf5f5bc..c44f01c 100644
--- a/pom.xml
+++ b/pom.xml
@@ -111,6 +111,7 @@ LICENSE file.
     <module>hypertable</module>
     <module>infinispan</module>
     <module>jdbc</module>
+    <module>lkvs</module>
     <!--<module>mapkeeper</module>-->
     <module>mongodb</module>
     <!--module>nosqldb</module-->
````

then in the top of your new module, you need to add an appropriate pom file. You should be able to copy one of the other bindings and modify things to suite your situation.

**Comment by busbey** [comment]
all set @shehbazj ?

**Comment by kruthar** [comment]
@shehbazj I have seen your issue before when creating a new database. For me it was because my pom.xml was not setup properly. The crucial parts to getting things to compile (in terms of YCSB dependencies) is to make sure you have the parent block setup correctly: https://github.com/brianfrankcooper/YCSB/blob/master/couchbase/pom.xml#L21-L26 and to add the ycsb dependency: https://github.com/brianfrankcooper/YCSB/blob/master/couchbase/pom.xml#L38-L43.

**Comment by busbey** [comment]
Closing as stale. If you are still having problems @shehbazj please reopen.
