### ISSUE TITLE
Overall Runtime

### ISSUE THREAD

**Issue by cgara** [brianfrankcooper/YCSB#430]
Hi,

When start the overall runtime count and at what time it is completed.
I am studying using the runtime as the main parameter in my study, I found this reference on the website

Thank you

**Comment by cmatser** [comment]
When YCSB completes, the output report will give you the overall runtime.  This happens automatically.

**Comment by cgara** [comment]
The count starts when the method is called in ycsb and ends when a return to this method? or the count is held within the DBMS?

**Comment by cmatser** [comment]
A call to get current system time is done just before the first operation and then after the last operation is completed.  The difference between these two is the "overall runtime".  This is done similarly for each operation to measure performance for the operations: updates, inserts, adds, and deletes.  When YCSB completes the output report gives you all these statistics.  None of this statistical data is stored in the DB.  The bottom of this page discusses this: https://github.com/brianfrankcooper/YCSB/wiki/Running-a-Workload

**Comment by cgara** [comment]
Thank's
