### ISSUE TITLE
Feature Request: Distributed YCSB Capabilities

### ISSUE THREAD

**Issue by kruthar** [brianfrankcooper/YCSB#433]
I have used YCSB on a couple benchmarks so far, great tool. When it comes to generating a very large amount of throughput with low individual client latency I have run identical workload tests across multiple YCSB machines simultaneously.

That approach works, but not only do you have to keep multiple ssh sessions open and launch the workload one after another, but to gather up metrics you need to consolidate and reconfigure averages, percentiles, etc on your own.

So, I think it could be very interesting to have distributed functionality in which you could control multiple YCSB instances from a single location that would allow you to launch workloads, and also aggregate results into a single location. I took inspiration for this from JMeter which has a Master-Server model in which you launch a lightweight server on all your machines, then distribute a workload to each server. Each server would then run the workload and report back all output to the central location.

This  may not be the only way or best way to accomplish distributed functionality, but it is a good example. I would potentially be interested in helping implement this, but would also like to know others thoughts on the usefulness and acceptance of this new functionality.

**Comment by bigbes** [comment]
There are better ways to do it:
1) https://github.com/brianfrankcooper/YCSB/pull/122

**Comment by kruthar** [comment]
Hey @bigbes 

Yes, I ended up writing my own bash loops that SSH'd to all my YCSB clients and ran the same load, then another to pull down all the results. Although this worked, it still did not seem ideal, particularly around automated aggregating results IE recomputing the average latency etc. Then again, I could have made my aggregation script as complex as I wanted it to be.

Main point being it seemed like a good idea to have a generalized form of this so everyone isn't reinventing the distributed wheel, and it looks like the Fabric pull request might have accomplished that so I'll check it out. Thanks for the links.

**Comment by busbey** [comment]
take a look at #255 too. I think we're after the same sort of thing, but your write up is a little better. :)

I was planning to fold this into the "experiment" stuff I posted about on #398. Effectively have hooks for "change cluster config", "deploy client artifacts", "run clients", "cleanup". then provide some example implementations that use pssh, fabric, etc.

**Comment by kruthar** [comment]
Hey @busbey 

It definitely looks like we are after the same principles in #255, although I would argue that actually provisioning the client machines might be out of scope, who knows what type of machines people will want to use. But that discussion probably isn't for this thread.

I think we can close this thread as it is covered in #255. Any estimates on who/when that work is happening? As I said, it interests me so I have some thoughts on implementation of it.

**Comment by busbey** [comment]
I don't believe we currently have any estimates, mostly because we don't have a volunteer.

When I was thinking through how to do this, I planned to define the API in terms of command line options and return codes. I'll try to write up some notes over on #255 later this week.
