### ISSUE TITLE
Feature Request: Configurable Percentile Metric Printouts

### ISSUE THREAD

**Issue by kruthar** [brianfrankcooper/YCSB#437]
Currently OneMeasurementHdrHistogram prints out 95% and 99% Latency numbers. (Well sort of, 95% is labeled 95 but is actually printing the 90% value: https://github.com/brianfrankcooper/YCSB/blob/master/core/src/main/java/com/yahoo/ycsb/measurements/OneMeasurementHdrHistogram.java#L104). 

I recently needed the 80% and 95%. I was able to go into OneMeasurementHdrHistogram and put in the specific percentile values I wanted to see. This made me think that the output for percentile values should be configurable.

As far as I can see it should be pretty simple since the percentile calculation is nice abstracted into a function. All you should need is a new configuration property, possibly a comma delimited string of values (1-100). And then loop over that list to print out the percentile values in OneMeasurementHdrHistogram.

I'd be happy to work on this if others think this would be useful.

**Comment by cmccoy** [comment]
I think that would be great, if you're willing to put a pull-request together.
Opened #440 to track the 90/95th percentile issue - thanks for catching that.

**Comment by kruthar** [comment]
Is there a specific reason why getSummary() outputs the 90, 99, 99.9, and 99.99 percentiles here: https://github.com/brianfrankcooper/YCSB/blob/master/core/src/main/java/com/yahoo/ycsb/measurements/OneMeasurementHdrHistogram.java#L126-L131? 

Or does it make since to have this output conform to the same configuration I am proposing for this readout here: https://github.com/brianfrankcooper/YCSB/blob/master/core/src/main/java/com/yahoo/ycsb/measurements/OneMeasurementHdrHistogram.java#L126-L131?

**Comment by cmccoy** [comment]
Are those links correct? They both point to the same line range....

**Comment by kruthar** [comment]
So they do, looks like I don't know how to copy&paste. I edited the comment with correct line links.

**Comment by cmccoy** [comment]
I think it's reasonable to report a subset of the percentiles in `getSummary` - users might be interested in a large range of percentiles for the overall results, but reporting a small, consistent set will keep the status output a bit more digestible.

**Comment by cmccoy** [comment]
Closed by #442
