### ISSUE TITLE
Crate.io support

### ISSUE THREAD

**Issue by hwaastad** [brianfrankcooper/YCSB#443]
Hi,
would you consider having support for crate.io aswell?

**Comment by busbey** [comment]
We love adding new datastores. It looks like Crate's driver is licensed ASLv2, which means we can distirbute it. So long as the driver is available somewhere we can get from maven,things should go well.

Care to put together a pull request?

**Comment by hwaastad** [comment]
Hi,
yeah I can try to dig into the YCSB code to see if I can make it work with crate.
And yes, drivers are available from http://dl.bintray.com/crate/crate repo

**Comment by hwaastad** [comment]
Hi,
I've been looking into this and I think the jdbc module will work (just a few minor bugs in the code).

But what would be the preferable way?
-Adding a separate module or just adding correct deps, repositories, properties to existing jdbc module?

**Comment by busbey** [comment]
the difficulty with the existing jdbc module is that it hasn't been well tested for some time, so it will be hard to bound the impact on current downstream users.

what if you made a separate module to build on the current jdbc one, similar to how the hbase094 module builds on the hbase098 one?

**Comment by hwaastad** [comment]
Yeah,
https://github.com/hwaastad/YCSB.git

Made a simple module, but needed to patch the jdbc client (';' in p-statements not needed)
I need to make sure the crate.io config is optimal, but I'll check with the crate.io guys.

**Comment by busbey** [comment]
excellent progress! when you're ready, please submit a PR. github has some basic help, let us know if you get stuck: https://help.github.com/articles/creating-a-pull-request/

I believe the semicolons in prepared statements came up in #128, so if you can close out that issue in the balance that would be great.

**Comment by hwaastad** [comment]
Hi,
a little busy at the moment, but i've had some time to think about the implementation.
I'm not sure it's any point adding a separate module since its using jdbc.
I would recommend:
1. fix the ';' in existing jdbc module
2. Somewhere add implementation specific readme to tests. (ie, for crate, a modified db schema and jdbc config for using clustered environment)
3. Add a crate module using crate-client implemenation. performancewise i would see if i could benchmark requests to all nodes in a cluster.

Wdyt?

Br hw

**Comment by busbey** [comment]
TBH, I've been waiting to see how the Crate JDBC support pans out to see if modules for JDBC driven things are worth it. :)

I definitely would like to see the semicolon thing fixed. I believe getting that part of your PR in would also let @kruthar skip fixing it later. (they've been cleaning up JDBC stuff lately)

The main advantage I see to adding a module for the Crate JDBC testing is that it gives us an obvious place to put the implementation specific information.

We've just recently gained a README for the JDBC driver, maybe see if using it as is suffices?

**Comment by cmatser** [comment]
My preference is to see the native driver used for benchmarking.  However, I do feel the jdbc driver is useful to have for comparing jdbc vs native or for when the native driver is jdbc.

2 pennies

**Comment by hwaastad** [comment]
Hi,
i just figured out that crate.io already has made fork of the project and added a native implementation.

Would be cool they could make a pull request.

Br hw

**Comment by allanbank** [comment]
I assume you are referring to this branch?
  https://github.com/crate/YCSB/commits/r/crate-binding

It would be very cool. Have you considered adding a ticket on the crate.io side and reference this ticket? I think it will have more weight coming from an existing crate.io user.

**Comment by hwaastad** [comment]
Hi,
had a chat with crate.io and they will create a pull request when they have published benchmark results.

Thats good news so I think this issue should be closed.

br hw

**Comment by busbey** [comment]
Any update here on the crate benchmarking post?

**Comment by hwaastad** [comment]
Hi,
crate still have'nt "released" or made a PR on their YCSB fork.

I'll check with them one more tilme.

/hw

**Comment by busbey** [comment]
closing as stale.
