### ISSUE TITLE
Unable to Load Cassandra using YCSB - Connection refused exception

### ISSUE THREAD

**Issue by keerthibs** [brianfrankcooper/YCSB#453]
Hi,
rpc_address in cassandra.yaml set to 172.31.1.160 (which is my machine IP)

I am running the following command - 

./bin/ycsb load cassandra-10 -P workloads/workload_test10 -p hosts="172.31.1.160" -p port=9160 -p columnfamily=data -s > results_cassandra/load_10

and I am getting the following exception -
Unable to connect to 172.31.1.160 after 300 tries
com.yahoo.ycsb.DBException: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused
        at com.yahoo.ycsb.db.CassandraClient10.init(CassandraClient10.java:162)
        at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:63)
        at com.yahoo.ycsb.ClientThread.run(Client.java:195)
Caused by: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused
        at org.apache.thrift.transport.TSocket.open(TSocket.java:183)
        at org.apache.thrift.transport.TFramedTransport.open(TFramedTransport.java:81)
        at com.yahoo.ycsb.db.CassandraClient10.init(CassandraClient10.java:144)
        ... 2 more
Caused by: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at org.apache.thrift.transport.TSocket.open(TSocket.java:178)
        ... 4 more

Any inputs would be of much help to me. Thanks in advance.

**Comment by cmccoy** [comment]
Are you able to telnet to that ip/port? Or run cassandra-cli connecting to the same?

**Comment by keerthibs** [comment]
Hi cmccoy, thanks for the reply.
I tried cassandra -cli locahost - and I get this -

root@ip-172-31-1-160:/usr/local/cassandra/apache-cassandra-2.2.3/bin# /usr/local/cassandra/apache-cassandra-2.2.3/bin/cassandra -cli localhost
getopt: invalid option -- 'c'
getopt: invalid option -- 'l'
getopt: invalid option -- 'i'
root@ip-172-31-1-160:/usr/local/cassandra/apache-cassandra-2.2.3/bin# Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000e2200000, 415236096, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 415236096 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /usr/local/cassandra/apache-cassandra-2.2.3/bin/hs_err_pid7306.log

**Comment by keerthibs** [comment]
and this is my telnet output:

 telnet 172.31.1.160
Trying 172.31.1.160...
telnet: Unable to connect to remote host: Connection refused

**Comment by cmccoy** [comment]
What about `telnet 172.31.1.160 9160`?
not sure what to do about the OOM, but if you can't connect on the IP/port specified, there's some problem outside of YCSB. Are you sure cassandra is running?

**Comment by keerthibs** [comment]
Same output for this as well. How do I ensure if cassandra is running?
Both ycsb and cassandra are in the same machine

**Comment by keerthibs** [comment]
I tried to ping, it works. 
But when i do a telnet, it says connection refused. I even tried by disabling the firewall, but doesnt work.

Please help

**Comment by cmccoy** [comment]
It sounds like Cassandra isn't running. You might check the logs from Cassandra, or see if there's anything in the [DataStax documentation](http://docs.datastax.com/en/landing_page/doc/landing_page/current.html).

**Comment by kruthar** [comment]
@keerthibs - any luck here? We recently had an issue that discussed Cassandra settings to ensure accessibility #502, check that out and see if it is any help.

Also, if you are using Cassandra 2.X I would suggest using the ```cassandra-cql``` module for Cassandra 2.0 and ```cassandra2-cql``` for Cassandra 2.1+.

You can also debug Cassandra connectivity with ```cqlsh [host] [port]``` on you Cassandra machine defaults for those are localhost and 9042.

**Comment by keerthibs** [comment]
Hi Andy,
What i did was, there was a problem with my cassandra.yaml file.
I just reinstalled the entire package, and then tried. It worked.

I wasn't able to figure out what went wrong in my old cassandra.yaml

On 3 December 2015 at 20:20, Andy Kruth <notifications@github.com> wrote:

> @keerthibs <https://github.com/keerthibs> - any luck here? We recently
> had an issue that discussed Cassandra settings to ensure accessibility
> #502 <https://github.com/brianfrankcooper/YCSB/issues/502>, check that
> out and see if it is any help.
>
> Also, if you are using Cassandra 2.X I would suggest using the
> cassandra-cql module for Cassandra 2.0 and cassandra2-cql for Cassandra
> 2.1+.
>
> You can also debug Cassandra connectivity with cqlsh [host] [port] on you
> Cassandra machine defaults for those are localhost and 9042.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianfrankcooper/YCSB/issues/453#issuecomment-161852225>
> .
>



-- 
With regards ,
*Keerthi.B.S*

**Comment by kruthar** [comment]
Ok, well i'm glad you were able to resolve. Is this issue OK to close?

**Comment by keerthibs** [comment]
Yes please close it. Thank you.

Regards
Keerthi B S

**Comment by Hadi14** [comment]
i have the same problem
