### ISSUE TITLE
Release version 0.5.0

### ISSUE THREAD

**Issue by cmccoy** [brianfrankcooper/YCSB#456]
Currently for the 0.5.0 release the following items have already been merged:

* #436: Fix classpath handling for running from source against BasicDB.
* #442: User-specified percentile output.
* #444: Kudu binding.
* #450: Rename some `README` files to `README.md`, so individual bindings can be generated.
* #452: `.gitignore` for Intellij.

I anticipate #454 being merged as well.

There are currently no known breaking changes in this release.

I'll create the release staging branch by next Tuesday, November 3rd.

Not many bindings were affected by this release, so I think a testing a subset of the bindings tested for 0.4.0 will be sufficient. At minimum:

* Kudu (newly added).
* Cassandra 2.1, 2.2 (pending #454).
* JDBC.

And at least 2 of:
* HBase
* MongoDB
* Tarantool
* Aerospike

Timeline for the release:
* RC1: Tuesday, November 3rd.
* RC2: Tuesday, November 10th.
* 0.5.0: By November 17th.

**Comment by busbey** [comment]
Does "HBase" mean the HBase 1.0 bindings, or all of them?

**Comment by cmccoy** [comment]
> Does "HBase" mean the HBase 1.0 bindings, or all of them?
 
I'd take any :). They were split out in the last release, making testing a bit more critical. Nothing specific to any HBase binding changed since last release.

**Comment by cmccoy** [comment]
I'll be a day late on RC0, sorry. Should have a build tomorrow.

**Comment by cmccoy** [comment]
RC1 published.

**Comment by cmccoy** [comment]
@kruthar: would you be able to test the JDBC bindings?
@allanbank: Willing to try MongoDB?

I'll run Cassandra 2.1, 2.2.

**Comment by kruthar** [comment]
So, not sure if I am doing this wrong or if there is actually something wrong with the build.

I tried pulling down ycsb-0.5.0-RC1.tar.gz from the RC1 page. Unpacked it and ran into this:

```sh
[vagrant@ycsb vagrant]$ /opt/ycsb-0.5.0-RC1/bin/ycsb load basic -P testworkload
java -cp /opt/ycsb-0.5.0-RC1/basic-binding/conf:/opt/ycsb-0.5.0-RC1/conf:/opt/ycsb-0.5.0-RC1/lib/HdrHistogram-2.1.4.jar:/opt/ycsb-0.5.0-RC1/lib/jackson-core-asl-1.9.4.jar:/opt/ycsb-0.5.0-RC1/lib/jackson-mapper-asl-1.9.4.jar:/opt/ycsb-0.5.0-RC1/lib/core-0.5.0-RC1.jar com.yahoo.ycsb.Client -db com.yahoo.ycsb.BasicDB -load
Error: Could not find or load main class com.yahoo.ycsb.Client
```

I also tried ycsb-jdbc-binding-0.5.0-RC1.tar.gz to the same effect. For sanity check I also tried the 0.4.0 release:

```sh
[vagrant@ycsb vagrant]$ /opt/ycsb-0.4.0/bin/ycsb load basic -P testworkload
java -cp /opt/ycsb-0.4.0/basic-binding/conf:/opt/ycsb-0.4.0/conf:/opt/ycsb-0.4.0/lib/HdrHistogram-2.1.4.jar:/opt/ycsb-0.4.0/lib/core-0.4.0.jar:/opt/ycsb-0.4.0/lib/jackson-core-asl-1.9.4.jar:/opt/ycsb-0.4.0/lib/jackson-mapper-asl-1.9.4.jar com.yahoo.ycsb.Client -db com.yahoo.ycsb.BasicDB -P testworkload -load
YCSB Client 0.1
Command line: -db com.yahoo.ycsb.BasicDB -P testworkload -load
Loading workload...
Starting test.
.
.
.
```

which works as expected. The classpaths look the same, although in different order.

**Comment by busbey** [comment]
just a side note on RC1 bit: previously we didn't publish convenience binaries for RCs in order to avoid downstream folks relying on them like normal releases.

I'm not sure we documented that in the release guide though. Thoughts on either approach?

**Comment by cmccoy** [comment]
I'm happy either way. I think it's somewhat useful to speed up testing, but
happy to take them down.

**Comment by cmccoy** [comment]
@kruthar: interesting. I can't reproduce this from the binary (tried BasicDB and Redis). What about building from the tag?

**Comment by risdenk** [comment]
I tested the basic workload with the following. It seems to work for me.
```
docker run --rm -it java:openjdk-8-jre /bin/bash -c "apt-get update && apt-get install -y python --no-install-recommends && wget https://github.com/brianfrankcooper/YCSB/releases/download/0.5.0-RC1/ycsb-0.5.0-RC1.tar.gz -O /opt/ycsb-0.5.0-RC1.tar.gz && tar zxvf /opt/ycsb-0.5.0-RC1.tar.gz -C /opt/ && /opt/ycsb-*/bin/ycsb load basic -P /opt/ycsb-0.5.0-RC1/workloads/workloada"
```

**Comment by jdcryans** [comment]
I checked out the tag, compiled it, and tested the Kudu bindings against a cluster using workloada. +1

**Comment by kruthar** [comment]
OK, compiled from the tagged source, tested the JDBC binding. In particular made sure that the scan latency is relatively constant for document sizes of 100, 1000, and 10000. Also verified #442, #469, and #473 in the JDBC module. :+1:

**Comment by cmccoy** [comment]
Thanks @jdcryans, @kruthar, and @risdenk!

**Comment by allanbank** [comment]
@cmccoy - I will get to the MongoDB testing this weekend.

**Comment by busbey** [comment]
@bigbes do you know if you'll have time to test Tarantool?

@tlopatic do you know if you'll have time to test Aerospike?

**Comment by cmccoy** [comment]
Cherry-picked #476.

**Comment by cmccoy** [comment]
I tested all workloads against Cassandra 2.2.3, using the `cassandra2-cql` binding. Looks good.

**Comment by allanbank** [comment]
MongoDB tested against:  3.2.0-rc2 3.0.7 2.6.11 2.4.14 2.2.7 2.0.9 1.8.5. No issues except a dying hard drive :(

**Comment by cmccoy** [comment]
Thanks, @allanbank!

@busbey - will you by any chance have time to test on Windows?

**Comment by busbey** [comment]
yeah, I'll make time today/tonight.

**Comment by cmccoy** [comment]
Pushed [0.5.0-RC2](https://github.com/brianfrankcooper/YCSB/releases/tag/0.5.0-RC2) - the only change is #476.

**Comment by cmccoy** [comment]
@busbey - thank you for the amazing instructions.

**Comment by busbey** [comment]
0.5.0-RC2 works-at-all on windows. #335 is still a problem, but no surprise there.

I had to build with -DskipTests due to a timeout on the Cassandra 2.1+ binding, see #495.

**Comment by cmccoy** [comment]
Thanks @busbey. RC2 has been tested against:

* MongoDB 3.2.0-rc2 3.0.7 2.6.11 2.4.14 2.2.7 2.0.9 1.8.5
* Cassandra 2.2.3
* JDBC
* Kudu

I'll try to run against HBase tonight. Barring any trouble, RC2 will become 0.5.0.

**Comment by tlopatic** [comment]
@busbey RC2 looks good with Aerospike. Sorry for the late response.

**Comment by busbey** [comment]
looks like we're about wrapped up? are there release notes to review?

**Comment by cmccoy** [comment]
Yes. Tested against Redis and HBase 1.0.2 with no issues.

Release notes:
https://gist.github.com/cmccoy/308ccc32488c087978f7

**Comment by busbey** [comment]
notes are missing:

* HBase binding supported
* Accumulo binding supported
* Tarantool binding supported

**Comment by cmccoy** [comment]
Thanks for reviewing, @busbey. Done.
@allanbank: did you test the MongoDB sync driver, async driver, or both?

**Comment by busbey** [comment]
I thought we were listing things that were supported in 0.4.0 as supported in 0.5.0 as long as we met the subset? Only things listed as "Tested support" get datastore-binding-specific binaries on the release.

If we're requiring things be actively tested in this release, I'd like time to get an Accumulo test in and I'd guess @bigbes might want Tarantool. I can get to Accumulo this evening.

**Comment by cmccoy** [comment]
I was planning on following the release guidelines on that, but am happy to be dissuaded; I don't have a problem releasing convenience binaries for databases with no binding-specific changes that were tested previously.

Other than smaller file size, is there an advantage to the individual distributions vs. monolithic YCSB distribution?

**Comment by busbey** [comment]
the two big advantages are smaller file size (which is a big advantage at our current size) and having the datastore specific README at the top level.

**Comment by cmccoy** [comment]
OK, I updated the release notes to specify that Tarantool and Accumulo are supported, but were not specifically tested. That will become 0.5.0.

**Comment by busbey** [comment]
:confetti_ball: :thumbsup: :confetti_ball:

**Comment by cmccoy** [comment]
Release pushed. Thanks all for testing! I won't be able to announce the release more broadly until tomorrow. Leaving this open until then.

**Comment by cmccoy** [comment]
Thanks everyone.

**Comment by busbey** [comment]
link to [0.5.0 final release](https://github.com/brianfrankcooper/YCSB/releases/tag/0.5.0)

**Comment by busbey** [comment]
I haven't noticed any release announcements on e.g. hbase-user, accumulo-user, cassandra-user, mongo user forums, or Hadoop Weekly. We normally get a shout-out in Hadoop Weekly when we have a release and I'm wondering if we missed where ever they normally see our announcements.

**Comment by cmccoy** [comment]
Oh, I misread the release instructions and thought that you *didn't* need to sign up for the groups posting to. My messages were rejected. Sending again, thanks.
