### ISSUE TITLE
Best practices for repeating the same benchmark multiple times?

### ISSUE THREAD

**Issue by sguazt** [brianfrankcooper/YCSB#457]
Hello,

I want to repeat the same benchmark against the same server multiple times.
This is useful to me to collect the same performance measure several times and then to compute a statistical estimator (e.g., confidence interval,...).

I've read the [documentation](https://github.com/cloudius-systems/osv/wiki/Benchmarking-Cassandra-and-other-NoSQL-databases-with-YCSB), but I haven't found any hint.

My question is: should the "DB configuration phase" and "load phase" always be performed before the "run phase"? Or, can it be skipped?

Specifically, if I want to repeat the same Cassandra benchmark N times, what of the following cases applies?

1. Case 1:
   ````
   for i=1 to N do
     - Drop/Create usertable keyspace on the server side
     - ./bin/ycsb load cassandra-10 -s -P workloads/workloada -P mysettings_load.dat
     - ./bin/ycsb run cassandra-10 -s -P workloads/workloada -P mysettings_run.dat
   done
   ````

2. Case 2:
    ````
    - Drop/Create usertable keyspace on the server side
    - ./bin/ycsb load cassandra-10 -s -P workloads/workloada -P mysettings_load.dat
    for i=1 to N do
      - ./bin/ycsb run cassandra-10 -s -P workloads/workloada -P mysettings_run.dat
    done
    ````

3. Case 3: something else?

Thank you so much!

Best,

Marco

**Comment by cmccoy** [comment]
For any database with compaction / garbage collection (Cassandra included), I would expect more consistent results from your first solution.

**Comment by cmatser** [comment]
Do you want to benchmark the load phase?  Does your workload insert records?

One issue I see if your workload inserts records, you are not testing with the same data set for each run of 1 to N in case 2.  Case 1 would seem to yield more consistent results, but if you don't care about the load phase, then you are doing extra work.

When I did my benchmarks, I ran the test 3 times.  Theoretically, running once with a large enough number of operations should give you a stable benchmark.  However, I ran it 3 times just to be sure I got consistent results (which I did get).  The only thing I noticed with regards to consistency was a sort of "spin up" effect.  When the test starts out and you have a number of threads all connecting at once, there's a bit of a delay vs when all threads are connected and steadily processing.  Having a large enough number of operations seems to even things out.

For me, I did a modified version of your case 2 in that I deleted any added records done by the workload between each run.  I created a special program to do this for my data set as this is not part of YCSB functionality.

Good luck.

Chrisjan

**Comment by sguazt** [comment]
Thank you both for the replies.

@cmatser: I'm interested in benchmarking the "run phase" only. The workload I'm using is [workloada](https://github.com/brianfrankcooper/YCSB/wiki/Core-Workloads) which consists of 50% of reads and 50% of writes. As you, I'm repeating the benchmark three times, removing from the results the very first and very last observations (I consider them part of a "ramp-up"/"ramp-down" phase).

Among the two cases, I'm currently following the advice from @cmccoy, that is, I'm using Case 1. But, if I have time, I'd like to experiment with Case 2 too, just for curiosity.
My main concern with Case 2 is that some operation (especially, write operation) could benefit from the fact that it could have been already performed in a previous run. This obviously depends by how operations are generated (random vs. deterministic way) and what kind of optimizations performs the DB server.

Cheers,

Marco

**Comment by busbey** [comment]
Any other questions @sguazt?

**Comment by sguazt** [comment]
No, sorry I forgot to close this comment.
I do this now.

Best,

Marco
