### ISSUE TITLE
CassandraCQLClient v2 doesn't use prepared statements

### ISSUE THREAD

**Issue by dprotaso** [brianfrankcooper/YCSB#458]
Loading data is really slow

**Comment by cmccoy** [comment]
v1 doesn't either. Would you be willing to contribute a patch?

**Comment by dprotaso** [comment]
I don't have much free time - plus I see the work being done here: https://github.com/brianfrankcooper/YCSB/pull/98

**Comment by busbey** [comment]
just to set expectations, I've been trying to get #98 into a merge-able state for several months. recent improvements in our code style are probably going to make it even harder.

**Comment by busbey** [comment]
closed by #1051
