### ISSUE TITLE
README for jdbc binding

### ISSUE THREAD

**Issue by kruthar** [brianfrankcooper/YCSB#459]
I have been looking into using the jdbc driver a bit and found that there is not a concise, central location for documentation on usage, properties, etc.

To really understand what was going on and how to use the jdbc binding I looked at information in a few different places:
* https://github.com/brianfrankcooper/YCSB/wiki/Using-the-Database-Libraries is a good start but does not give any information on what your database state needs to look like, or how to configure for it.
* #128 - sheds some light on where to stick your driver, not mentioned there is you can also just specify it directly in your command with -cp.
* https://github.com/brianfrankcooper/YCSB/tree/master/jdbc/src/main/resources/sql and https://github.com/brianfrankcooper/YCSB/blob/master/jdbc/src/main/java/com/yahoo/ycsb/db/JdbcDBCreateTable.java, but the usage and locations of these are not document anywhere I can find, also it does not seem that the JdbcDBCreateTable.java works for MySQL.
* properties and default values in https://github.com/brianfrankcooper/YCSB/blob/master/jdbc/src/main/java/com/yahoo/ycsb/db/JdbcDBClientConstants.java

Not sure if anyone else has had issues getting it running but at the moment I think the jdbc-binding could benefit by having an intuitive README like most of the other bindings.

**Comment by cmccoy** [comment]
That would be great. Would you be willing to submit a patch?

**Comment by kruthar** [comment]
Probably, I've already done a lot of the research for myself. I'll put together a README similar to the other bindings.
