### ISSUE TITLE
Document and make consistent JDBC binding return codes

### ISSUE THREAD

**Issue by kruthar** [brianfrankcooper/YCSB#462]
Currently there are 4 different return codes coming from the JDBC binding. They are not consistent across operation methods but roughly equate to:

-2 = Operational Error (Used rarely, could probably be consolidated to -1)
-1 = Configuration/Operational Error
0 = Success
1 = Successful but unexpected result from database

It should be easy to make these consistent within the JDBC module, but are there guidelines for return codes across all YCSB modules?

**Comment by cmccoy** [comment]
There aren't, but I think it would be great if there were. I started on this in cmccoy@621d5151af79ea61a86f443024abc13118bf23ca.  The HBase bindings also use `-3` to indicate that the requested record wasn't found.

**Comment by kruthar** [comment]
@cmccoy that link ended up as a mailto?

**Comment by cmccoy** [comment]
Sorry. How about [here](https://github.com/cmccoy/YCSB/commit/621d5151af79ea61a86f443024abc13118bf23ca)?

**Comment by kruthar** [comment]
Cool, any plan on merging in StatusCode.java? I think making that a standard is a good idea, though may take some work to see what types of errors are being reported from the other modules and mixing that in where applicable. I think you may be able to get a tad more granular on error types.

**Comment by cmccoy** [comment]
Opened #469. I agree that we could be more granular. Would you mind posting your suggestions there?

**Comment by cmccoy** [comment]
I believe this is closed by #469. @kruthar - feel free to re-open if you disagree.
