### ISSUE TITLE
How to get client report status in a log file

### ISSUE THREAD

**Issue by hsalahi** [brianfrankcooper/YCSB#471]
Hello.

How is it possible to redirect Client report status (specified by -s parameter in YCSB command) to a log file?

Thanks.

**Comment by kruthar** [comment]
Hi @hsalahi the summary messages are printed to stderr, so one way to catch that is to route stderr to a file with something like this:

```sh
bin/ycsb run basic -P workloads/workloada -s 2> summary.txt
```

Note that this will write all other stderr messages to that file as well.

**Comment by kruthar** [comment]
@hsalahi did this work for you?

**Comment by hsalahi** [comment]
@kruthar It worked. Thanks...
