### ISSUE TITLE
pom.xml for ycsb test

### ISSUE THREAD

**Issue by Hadi14** [brianfrankcooper/YCSB#478]
i want run ycsb and follow this steps :
https://course.cs.tau.ac.il/secws12/sites/drupal-courses.cs.tau.ac.il.secws12/files/Distributed%20Databases%20-%20YCSB%20Tutorial.docx

and add this pom file to ycsb directory but it got error
pom:
https://github.com/brianfrankcooper/YCSB/blob/master/pom.xml
what is correct source od pom.xml ?

**Comment by kruthar** [comment]
hi @Hadi14, I looked at the document you linked. First off it is a little outdated, especially the download location for YCSB. You can download the latest release here: https://github.com/brianfrankcooper/YCSB/releases/download/0.4.0/ycsb-0.4.0.tar.gz.

Can you explain a little more what you are trying to do with the pom.xml? You shouldn't have to mess around with that at all if you are using a release, and even if you plan to build from source it should work as is.

Can you also post what type of errors you are seeing?

**Comment by Hadi14** [comment]
hi kruthar thank you for reply
i want to do test Nosql databases with YCSB 
now is this error:

[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] YCSB Root
[INFO] Core YCSB
[INFO] Per Datastore Binding descriptor
[INFO] YCSB Datastore Binding Parent
[INFO] Accumulo DB Binding
[INFO] Aerospike DB Binding
[INFO] Cassandra DB Binding
[INFO] Cassandra 2.1+ DB Binding
[INFO] Couchbase Binding
[INFO] DynamoDB DB Binding
[INFO] ElasticSearch Binding
[INFO] Gemfire DB Binding
[INFO] HBase 0.98.x DB Binding
[INFO] HBase 0.94.x DB Binding
[INFO] HBase 1.0 DB Binding
[INFO] Hypertable DB Binding
[INFO] Infinispan DB Binding
[INFO] JDBC DB Binding
[INFO] Kudu DB Binding
[INFO] MongoDB Binding
[INFO] OrientDB Binding
[INFO] Redis DB Binding
[INFO] Tarantool DB Binding
[INFO] YCSB Release Distribution Builder
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building YCSB Root 0.6.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-checkstyle-plugin/2.15/maven-checkstyle-plugin-2.15.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] YCSB Root .......................................... FAILURE [  3.615 s]
[INFO] Core YCSB .......................................... SKIPPED
[INFO] Per Datastore Binding descriptor ................... SKIPPED
[INFO] YCSB Datastore Binding Parent ...................... SKIPPED
[INFO] Accumulo DB Binding ................................ SKIPPED
[INFO] Aerospike DB Binding ............................... SKIPPED
[INFO] Cassandra DB Binding ............................... SKIPPED
[INFO] Cassandra 2.1+ DB Binding .......................... SKIPPED
[INFO] Couchbase Binding .................................. SKIPPED
[INFO] DynamoDB DB Binding ................................ SKIPPED
[INFO] ElasticSearch Binding .............................. SKIPPED
[INFO] Gemfire DB Binding ................................. SKIPPED
[INFO] HBase 0.98.x DB Binding ............................ SKIPPED
[INFO] HBase 0.94.x DB Binding ............................ SKIPPED
[INFO] HBase 1.0 DB Binding ............................... SKIPPED
[INFO] Hypertable DB Binding .............................. SKIPPED
[INFO] Infinispan DB Binding .............................. SKIPPED
[INFO] JDBC DB Binding .................................... SKIPPED
[INFO] Kudu DB Binding .................................... SKIPPED
[INFO] MongoDB Binding .................................... SKIPPED
[INFO] OrientDB Binding ................................... SKIPPED
[INFO] Redis DB Binding ................................... SKIPPED
[INFO] Tarantool DB Binding ............................... SKIPPED
[INFO] YCSB Release Distribution Builder .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.604 s
[INFO] Finished at: 2015-11-06T21:19:01+03:30
[INFO] Final Memory: 10M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.apache.maven.plugins:maven-checkstyle-plugin:2.15 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-checkstyle-plugin:jar:2.15: Could not transfer artifact org.apache.maven.plugins:maven-checkstyle-plugin:pom:2.15 from/to central (https://repo.maven.apache.org/maven2): This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

**Comment by kruthar** [comment]
Can you also explain where you are downloading YCSB from, is it the source or a released version? Why are you trying to replace the pom.xml, there should already be a valid one there?

And is the command you are running that is giving you the output you just posted?

**Comment by Hadi14** [comment]
i download ycsb again with this command:
git clone https://github.com/brianfrankcooper/YCSB.git

and then i write this command :"mvn clean package"    and got this error.

**Comment by kruthar** [comment]
Are you trying to run ```mvn clean package``` on an internal network that has a proxy to the internet?

Are you running Maven through a plugin on an IDE (such as Eclipse) or directly from the command line?

This message in your error output: "This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server" sounds like your Maven cannot successfully connect to download plugins and such.

**Comment by Hadi14** [comment]
i run it on my local system through directly from the command line

**Comment by kruthar** [comment]
So, depending on you environment this sounds like it could be your issue but I cannot be sure: http://stackoverflow.com/questions/12533885/could-not-calculate-build-plan-plugin-org-apache-maven-pluginsmaven-resources.

Otherwise, you can always trying using a prebuilt release and skip the compiling step by following the Getting Started instructions here: https://github.com/brianfrankcooper/YCSB.

**Comment by Hadi14** [comment]
now it got this error:

[INFO] Reactor Summary:
[INFO]
[INFO] YCSB Root .......................................... SUCCESS [  2.176 s]
[INFO] Core YCSB .......................................... SUCCESS [ 21.617 s]
[INFO] Per Datastore Binding descriptor ................... SUCCESS [  0.833 s]
[INFO] YCSB Datastore Binding Parent ...................... SUCCESS [  1.631 s]
[INFO] Accumulo DB Binding ................................ FAILURE [  6.660 s]
[INFO] Aerospike DB Binding ............................... SKIPPED
[INFO] Cassandra DB Binding ............................... SKIPPED
[INFO] Cassandra 2.1+ DB Binding .......................... SKIPPED
[INFO] Couchbase Binding .................................. SKIPPED
[INFO] DynamoDB DB Binding ................................ SKIPPED
[INFO] ElasticSearch Binding .............................. SKIPPED
[INFO] Gemfire DB Binding ................................. SKIPPED
[INFO] HBase 0.98.x DB Binding ............................ SKIPPED
[INFO] HBase 0.94.x DB Binding ............................ SKIPPED
[INFO] HBase 1.0 DB Binding ............................... SKIPPED
[INFO] Hypertable DB Binding .............................. SKIPPED
[INFO] Infinispan DB Binding .............................. SKIPPED
[INFO] JDBC DB Binding .................................... SKIPPED
[INFO] Kudu DB Binding .................................... SKIPPED
[INFO] MongoDB Binding .................................... SKIPPED
[INFO] OrientDB Binding ................................... SKIPPED
[INFO] Redis DB Binding ................................... SKIPPED
[INFO] Tarantool DB Binding ............................... SKIPPED
[INFO] YCSB Release Distribution Builder .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 33.431 s
[INFO] Finished at: 2015-11-07T18:40:16+03:30
[INFO] Final Memory: 37M/319M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project accumulo-binding: Could not resolve dependencies for project com.yahoo.ycsb:accumulo-binding:jar:0.6.0-SNAPSHOT: The following artifacts could not be resolved: org.apache.accumulo:accumulo-core:jar:1.6.0, com.google.guava:guava:jar:15.0, jline:jline:jar:2.11, log4j:log4j:jar:1.2.16, org.apache.accumulo:accumulo-fate:jar:1.6.0, org.apache.accumulo:accumulo-start:jar:1.6.0, org.apache.accumulo:accumulo-trace:jar:1.6.0, org.apache.commons:commons-math:jar:2.1, org.apache.commons:commons-vfs2:jar:2.0, org.apache.maven.scm:maven-scm-api:jar:1.4, org.codehaus.plexus:plexus-utils:jar:1.5.6, org.apache.maven.scm:maven-scm-provider-svnexe:jar:1.4, org.apache.maven.scm:maven-scm-provider-svn-commons:jar:1.4, regexp:regexp:jar:1.3, org.apache.hadoop:hadoop-client:jar:2.2.0, org.apache.hadoop:hadoop-hdfs:jar:2.2.0, com.google.protobuf:protobuf-java:jar:2.5.0, org.apache.hadoop:hadoop-mapreduce-client-app:jar:2.2.0, org.apache.hadoop:hadoop-mapreduce-client-common:jar:2.2.0, org.apache.hadoop:hadoop-yarn-client:jar:2.2.0, com.google.inject:guice:jar:3.0, javax.inject:javax.inject:jar:1, com.sun.jersey.jersey-test-framework:jersey-test-framework-grizzly2:jar:1.9, com.sun.jersey.jersey-test-framework:jersey-test-framework-core:jar:1.9, javax.servlet:javax.servlet-api:jar:3.0.1, com.sun.jersey:jersey-client:jar:1.9, com.sun.jersey:jersey-grizzly2:jar:1.9, org.glassfish.grizzly:grizzly-http:jar:2.1.2, org.glassfish.grizzly:grizzly-framework:jar:2.1.2, org.glassfish.gmbal:gmbal-api-only:jar:3.0.0-b023, org.glassfish.external:management-api:jar:3.0.0-b012, org.glassfish.grizzly:grizzly-http-server:jar:2.1.2, org.glassfish.grizzly:grizzly-rcm:jar:2.1.2, org.glassfish.grizzly:grizzly-http-servlet:jar:2.1.2, org.glassfish:javax.servlet:jar:3.1, com.sun.jersey:jersey-server:jar:1.9, asm:asm:jar:3.1, com.sun.jersey:jersey-core:jar:1.9, com.sun.jersey:jersey-json:jar:1.9, org.codehaus.jettison:jettison:jar:1.1, stax:stax-api:jar:1.0.1, com.sun.xml.bind:jaxb-impl:jar:2.2.3-1, javax.xml.bind:jaxb-api:jar:2.2.2, javax.activation:activation:jar:1.1, org.codehaus.jackson:jackson-jaxrs:jar:1.8.3, org.codehaus.jackson:jackson-xc:jar:1.8.3, com.sun.jersey.contribs:jersey-guice:jar:1.9, org.apache.hadoop:hadoop-yarn-server-common:jar:2.2.0, org.apache.hadoop:hadoop-mapreduce-client-shuffle:jar:2.2.0, org.slf4j:slf4j-log4j12:jar:1.7.5, org.apache.hadoop:hadoop-yarn-api:jar:2.2.0, org.apache.hadoop:hadoop-mapreduce-client-core:jar:2.2.0, org.apache.hadoop:hadoop-yarn-common:jar:2.2.0, org.apache.hadoop:hadoop-mapreduce-client-jobclient:jar:2.2.0, org.apache.hadoop:hadoop-annotations:jar:2.2.0, org.apache.thrift:libthrift:jar:0.9.0, org.apache.httpcomponents:httpclient:jar:4.1.3, org.apache.httpcomponents:httpcore:jar:4.1.3, org.slf4j:slf4j-api:jar:1.6.4, org.apache.zookeeper:zookeeper:jar:3.3.1, org.apache.hadoop:hadoop-core:jar:0.20.203.0, xmlenc:xmlenc:jar:0.52, commons-httpclient:commons-httpclient:jar:3.0.1, commons-net:commons-net:jar:1.4.1, org.mortbay.jetty:jetty:jar:6.1.26, org.mortbay.jetty:servlet-api:jar:2.5-20081211, org.mortbay.jetty:jetty-util:jar:6.1.26, tomcat:jasper-runtime:jar:5.5.12, tomcat:jasper-compiler:jar:5.5.12, org.mortbay.jetty:jsp-api-2.1:jar:6.1.14, org.mortbay.jetty:servlet-api-2.5:jar:6.1.14, org.mortbay.jetty:jsp-2.1:jar:6.1.14, ant:ant:jar:1.6.5, commons-el:commons-el:jar:1.0, net.java.dev.jets3t:jets3t:jar:0.7.1, net.sf.kosmosfs:kfs:jar:0.3, hsqldb:hsqldb:jar:1.8.0.10, org.eclipse.jdt:core:jar:3.1.1: Could not transfer artifact org.apache.accumulo:accumulo-core:jar:1.6.0 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: Unknown host repo.maven.apache.org -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :accumulo-binding

**Comment by kruthar** [comment]
This is a similar error to before just on a different dependency. I'm sorry, likely not going to be able to help you, please check out the link I posted earlier. Your issue is likely a connection to the internet or lack thereof that is causing Maven to not be able to download packages.

Did you try to use the prebuilt release? You will not have to use Maven at all, just extract and use.

**Comment by Hadi14** [comment]
Hi i download it with "git clone https://github.com/brianfrankcooper/YCSB.git" command
i think that my connection be disconnect Sometimes and this problem caused than it
but i run it many several times.

**Comment by kruthar** [comment]
Using ```git clone``` will get you the source, which you then have to use Maven to build, which is where you are having issues.

Please go here: https://github.com/brianfrankcooper/YCSB scroll down to the README and follow the Getting Started instructions. That should tell you exactly how to get a prebuilt release package and run YCSB that way.

**Comment by Hadi14** [comment]
do you know where is place files like "cassandra-unit-shaded-2.1.9.2" on win directory?

**Comment by Hadi14** [comment]
it now got this error next casandra 


[ERROR] Failed to execute goal on project hypertable-binding: Could not resolve dependencies for project com.yahoo.ycsb:hypertable-binding:jar:0.6.0-SNAPSHOT: Failed to collect dependencies at org.hypertable:hypertable:jar:0.9.5.6: Failed to read artifact descriptor for org.hypertable:hypertable:jar:0.9.5.6: Could not transfer artifact org.hypertable:hypertable:pom:0.9.5.6 from/to clojars.org (<a href="http://clojars.org/repo):" target="_blank">http://clojars.org/repo):</a> Connect to clojars.org:80 [clojars.org/173.230.139.200] failed: Connection timed out: connect -> [Help 1]

**Comment by allanbank** [comment]
@Hadi14 - 

As @kruthar mentioned it looks like your connection to the internet is compromised in some way. All of the errors you have posted are trying to go to very common repositories on the internet. It is impossible for us to tell if the failure is your machine, organization or what without a lot more detail.

Since you seem to be able to get to GitHub OK I am going to repeat @kruthar suggestion and strongly encourage you download one of the pre-built bindings. Your guide uses the the Cassandra bindings which have only recently included with the distribution. You will need to use the [0.5.0-RC1](https://github.com/brianfrankcooper/YCSB/releases/download/0.5.0-RC1/ycsb-cassandra2-binding-0.5.0-RC1.tar.gz) version. Note that the binding is designed to work with Cassandra 2.x CQL interface.

Once you have downloaded and untar'd the file you should be able to:

    cd ycsb-cassandra2-binding-0.5.0-RC1
    bin/ycsb

You can then start from the section titled "Run YCSB" in the document you posted.

If you would like to continue trying to build the distribution from source we are happy to help with any issues with the YCSB build errors not related to failures caused by not being able to connect to the internet.

For the connection failures I will recommend:
*  If you are connected via Wifi or other wireless mechanism, try getting a physical internet connection.
* If that does not work you should contact your local IT technical support organization to help troubleshoot the issues.

**Comment by Hadi14** [comment]
thank you allanbank
should i extract cassandra2-binding whch directory?

**Comment by allanbank** [comment]
What type of system are you running on?  Windows? Linux?

**Comment by Hadi14** [comment]
it is windows 10

**Comment by allanbank** [comment]
@Hadi14 - Give me a day to get some instructions together.  I know that Python needs to be installed and you can read about that here: https://github.com/brianfrankcooper/YCSB/wiki/Prerequisites-for-Windows.

**Comment by Hadi14** [comment]
Hi allanbank ok
when you free?
this is my id "ghamzadeh2010@yahoo.com"

**Comment by Hadi14** [comment]
ok when are you free?
i download it and copy files on it's folder , it worked
but i will have many question next times properly.

**Comment by Hadi14** [comment]
now it have this error (for connect to cassandra)

$ bin/cqlsh
Connection error: ('Unable to connect to any servers', {'192.168.1.200': error(10061, "Tried connecting to [('192.168.1.200', 9042)]. Last error: No connection could be made because the target machine actively refused it")})

**Comment by busbey** [comment]
if cqlsh can't connect to Cassandra, you should ask the Cassandra user forums for help getting your basic set up squared away.

**Comment by kruthar** [comment]
@Hadi14  - There was a recent post that went into Cassandra configuration #502 you might check that out if you are still having issues.
