### ISSUE TITLE
Cassandra 2.1+ Binding fails on windows due to timeout

### ISSUE THREAD

**Issue by busbey** [brianfrankcooper/YCSB#495]
Could just be that my build box for windows is underpowered. It's a eee pc with ~1GB memory and an Atom N550@1.5GHz.

[ycsb-0.5.0-rc2-failure-cassandra21.txt](https://github.com/brianfrankcooper/YCSB/files/32527/ycsb-0.5.0-rc2-failure-cassandra21.txt)

**Comment by busbey** [comment]
I don't know if the timeout is adjustable. If it isn't, maybe we could add a profile for resource intensive tests?

**Comment by risdenk** [comment]
Does it make sense to move tests that require a DB/cluster to integration tests and use something like https://maven.apache.org/surefire/maven-failsafe-plugin/? This could allow certain tests to be categorized and run separately.

**Comment by busbey** [comment]
Categorizing the tests would be nice. But I think this particular issue can be closed out; I just finished successfully building with this test in place on a Windows 10 machine with a Celeron N3050 and 2GB of memory. That's still low end enough for me to be comfortable.

**Comment by busbey** [comment]
started seeing this on my windows build laptop again.

**Comment by risdenk** [comment]
This seems to happen on Travis CI quite often. Not sure it is only Windows based.

**Comment by risdenk** [comment]
Found that the timeout is adjustable and will open a PR in a few minutes. This has been failing a lot on recent travis builds.
