### ISSUE TITLE
cassandra 2.1 transportException YCSB, cqlsh working

### ISSUE THREAD

**Issue by pushpendrachaturvedi** [brianfrankcooper/YCSB#501]
I am using latest version of YCSB to benchmark performance of my Cassandra cluster- composed of 4 virtualbox VMs. From another 5th VM , i am trying to generate load on my cluster as per instructions on https://github.com/cloudius-systems/osv/wiki/Benchmarking-Cassandra-and-other-NoSQL-databases-with-YCSB and https://github.com/brianfrankcooper/YCSB

i am able to reach to my cluster through cqlsh from the same machine.
I think its some dependency issue but dont know what.
Please help asap.

Tried many suggestion from this platform since yesterday , but nothing working

Following is the error

stress@stress:~/ycsb-0.4.0$ sudo bin/ycsb load cassandra-cql -p host="192.168.0.107" -P workloads/workloada -s > workloada_load_res.txtjava -cp /home/stress/ycsb-0.4.0/cassandra-binding/conf:/home/stress/ycsb-0.4.0/conf:/home/stress/ycsb-0.4.0/lib/HdrHistogram-2.1.4.jar:/home/stress/ycsb-0.4.0/lib/core-0.4.0.jar:/home/stress/ycsb-0.4.0/lib/jackson-mapper-asl-1.9.4.jar:/home/stress/ycsb-0.4.0/lib/jackson-core-asl-1.9.4.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/cassandra-thrift-1.2.9.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/lz4-1.1.0.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/snaptree-0.1.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/servlet-api-2.5-20081211.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/httpcore-4.0.1.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/high-scale-lib-1.1.2.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/stringtemplate-3.2.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/httpclient-4.0.1.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/jetty-util-6.1.22.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/json-simple-1.1.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/commons-logging-1.1.1.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/servlet-api-2.5.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/cassandra-binding-0.4.0.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/commons-lang-2.6.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/jbcrypt-0.3m.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/netty-3.5.9.Final.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/log4j-1.2.16.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/slf4j-log4j12-1.7.2.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/jamm-0.2.5.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/jackson-mapper-asl-1.9.2.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/concurrentlinkedhashmap-lru-1.3.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/compress-lzf-0.8.4.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/jackson-core-asl-1.9.2.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/antlr-2.7.7.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/jetty-6.1.22.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/avro-1.4.0-cassandra-1.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/cassandra-all-1.2.9.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/cassandra-driver-core-1.0.3.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/libthrift-0.7.0.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/antlr-runtime-3.2.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/slf4j-api-1.6.4.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/snakeyaml-1.6.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/commons-cli-1.1.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/metrics-core-2.0.3.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/commons-codec-1.2.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/jline-1.0.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/guava-13.0.1.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/antlr-3.2.jar:/home/stress/ycsb-0.4.0/cassandra-binding/lib/snappy-java-1.0.5.jar com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.CassandraCQLClient -p host=192.168.0.107 -P workloads/workloada -s -load
Loading workload...
Starting test.
2015-11-20 09:09:08:397 0 sec: 0 operations; est completion in 0 seconds 
log4j:WARN No appenders could be found for logger (com.datastax.driver.core.Cluster).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
com.yahoo.ycsb.DBException: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /192.168.0.107 ([/192.168.0.107] Unexpected error during transport initialization (com.datastax.driver.core.TransportException: [/192.168.0.107] Channel has been closed)))
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:158)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:63)
	at com.yahoo.ycsb.ClientThread.run(Client.java:289)
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /192.168.0.107 ([/192.168.0.107] Unexpected error during transport initialization (com.datastax.driver.core.TransportException: [/192.168.0.107] Channel has been closed)))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:186)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:81)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:644)
	at com.datastax.driver.core.Cluster$Manager.access$100(Cluster.java:586)
	at com.datastax.driver.core.Cluster.<init>(Cluster.java:69)
	at com.datastax.driver.core.Cluster.buildFrom(Cluster.java:96)
	at com.datastax.driver.core.Cluster$Builder.build(Cluster.java:567)
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:131)
	... 2 more
2015-11-20 09:09:08:811 0 sec: 0 operations; est completion in 106751991167300 days 15 hours

**Comment by cmccoy** [comment]
What port is Cassandra running on?  Have you tried connecting to hosts other than 192.168.0.107?

**Comment by kruthar** [comment]
Hey @pushpendrachaturvedi - so, looks like you are using the 0.4.0 release of YCSB, right? At that point the default port for the cassandra-cql binding was 9160, which is not correct. For remote RPC connections the default port needs to be 9042. This has been fixed: https://github.com/brianfrankcooper/YCSB/commit/c60b114a611d27e895b5daf22725f30ddf64ecfc#diff-b989977a1535ef89d83a22ac96d9c360, and you can find it in the next release.

Until then you can manually specify the correct port with:

```sh
-p port=9042
```

Can you give that a try and see if you can connect?

**Comment by pushpendrachaturvedi** [comment]
Thanks, running with port 9042 worked. 

I am using cassandra 2.15, which workload will be suitable for it? cassandra-cql or cassandra-10. 
Can i find details about the two workloads somewhere?

thanks again for your help.

**Comment by pushpendrachaturvedi** [comment]
I would also like to know how can i save the results? where can i find the result of running this benchmark?
I am fairly new, so kindly bear if it is a dumb question.

currently when i loaded the workload cassandra-1.0 and run the same
it shows command run but i am not able to retain anything from it.

**Comment by kruthar** [comment]
>I am using cassandra 2.15, which workload will be suitable for it? cassandra-cql or cassandra-10. 
>Can i find details about the two workloads somewhere?

The main difference between the bindings like cassandra-cql and cassandra-10 are the protocols they use to send queries to Cassandra. cassandra-cql uses Cassandra CQL language, whereas I think cassandra-10 uses Thrift. You can find more info here: http://wiki.apache.org/cassandra/ClientOptions. 

As for actual workflows, that is really up to you. Ask yourself what you really care about testing, like read, update, or scan latency and go from there. There are a few workflow examples here: https://github.com/brianfrankcooper/YCSB/tree/master/workloads and the list of properties to customize your workloads are here: https://github.com/brianfrankcooper/YCSB/wiki/Core-Properties.

>I would also like to know how can i save the results? where can i find the result of running this benchmark?

All of the results are printed to stdout and stderr so you can capture them however you like, a simple example is like:

```sh
bin/ycsb run basic -P workloads/workloada > out.log 2> err.log
```

**Comment by kruthar** [comment]
@pushpendrachaturvedi - from other posts it sounds like you have things working, is this issue good to close?

**Comment by pushpendrachaturvedi** [comment]
yes, thanks @kruthar  , i am closing this one .
