### ISSUE TITLE
Error in connection cassandra

### ISSUE THREAD

**Issue by Hadi14** [brianfrankcooper/YCSB#503]
when run "casandra -f"  this error:

C:\Evaluate\apache-cassandra-2.2.3>bin\cassandra -f
C:\Evaluate\apache-cassandra-2.2.3>f@REM
'f@REM' is not recognized as an internal or external command,
operable program or batch file.
WARNING! Powershell script execution unavailable.
   Please use 'powershell Set-ExecutionPolicy Unrestricted'
   on this user-account to run cassandra with fully featured
   functionality on this platform.
Starting with legacy startup options
Starting Cassandra Server
The system cannot find the path specified.

when run "cqlsh" this error:

Connection error: ('Unable to connect to any servers', {'127.0.0.1': error(10061, "Tried connecting to [('127.0.0.1', 9042)]. Last error: No connection could be made because the target machine actively refused it")})

this is my cassandra.yaml:
http://s000.tinyupload.com/?file_id=83919387831918059887

**Comment by kruthar** [comment]
Hi @Hadi14, happy to help with issues using the YCSB Cassandra bindings, but I apologize, this is not the correct place to seek help with issues regarding Cassandra itself. 

Please check out some Cassandra specific support forums such as the user mailing list: http://www.mail-archive.com/user@cassandra.apache.org/. Or even Stackoverflow: http://stackoverflow.com/search?q=cassandra.

**Comment by Hadi14** [comment]
Hi @kruthar you say right
I apologize and not continue this post.

**Comment by prashant-isbest** [comment]
make sure cassandra is running and then you can perform the cqlsh command
