### ISSUE TITLE
YCSB should not record latency data from failed operations

### ISSUE THREAD

**Issue by stfeng** [brianfrankcooper/YCSB#506]
If a DB failed 100 operations with 1ms latency and processed 98 successful operations with 20ms latency, YCSB gonna report its p50 latency as 1ms, so great! ;)

Yes, I know we also report *number of* failed and successful operations, but that really tells nothing about how much impact those failed operations had to the overall latency percentiles.

The proposed change is pretty simple, in DBWrapper.java, call measure() only if the res is Status.OK, like this:

	@Override
  public Status update(String table, String key, HashMap<String,ByteIterator> values)
	{
	    long ist=_measurements.getIntendedtartTimeNs();
	    long st = System.nanoTime();
		Status res=_db.update(table,key,values);
		long en=System.nanoTime();
		if (res == Status.OK) { <=================== [Added by stfeng]
		  measure("UPDATE",ist, st, en);
		}
		_measurements.reportStatus("UPDATE",res);
		return res;
	}

**Comment by stfeng** [comment]
Let me know if you guys have any objections to this proposal, if not, I'd be happy to submit a PR for this.

Thanks.

**Comment by busbey** [comment]
How about if we do measurements for eah of successful and failed?

**Comment by stfeng** [comment]
SGTM. Please take a look at PR: #507

**Comment by kruthar** [comment]
This was merged.
