### ISSUE TITLE
Make the YCSB load phase more robust

### ISSUE THREAD

**Issue by stfeng** [brianfrankcooper/YCSB#508]
The YCSB load phase consists of inserting records into the DB. Currently, a single failed insertion to the DB would fail/abandon the entire load phase. For a DB service that has a 99.9% availability SLA (which isn't that bad), it can legitimately fail one insert operation out of 1000. For YCSB users, this means they will have a (very) hard time to load that DB with just a few thousands of records. (I had to deal with a DB with 99.9% availability and had a very hard time to load that DB with just 5000 records, the closest I got was 4535 successful insertions and then a single failure caused the entire load to fail...).

Repeating the load process won't help because the new load process will repeat the key sequence numbers from 0 - X and simply overwrite existing records instead of adding new ones.

A better solution is to make the load process more robust by retrying a failed insertion (the retry will use the same key).

The code executed during the load phase is CoreWorkload.java:doInsert() (Note: it's NOT the doTransactionInsert()), and currently doInsert() returns false immediately after it sees a failure from _db.insert().

I'm proposing we add some (very) simple retry behavior in doInsert(), we can retry up to N times (N configurable) with randomized wait time between retries (wait time can also be made configurable).

I have already made a private fix for this and it enabled me to load pretty much as many records to my DB as I wanted (up to 100,000) with the retry limit set at just 5. (yes, working with a DB of 99.9% availability, 5 retries will "fix" almost everything for you. :-)

**Comment by stfeng** [comment]
Guys, let me know what your thoughts are, happy to submit a PR for this!

**Comment by kruthar** [comment]
@stfeng I think configurable retry on load is a good idea. A couple of ideas to go along with your initial proposal:

* Configurable number of (subsequent, or maybe not subsequent) failures that would trigger a full stop to loading. Example of the need for this is if there truly is a DB issue, you don't want to have to sit through all the remaining retries before the load would finish.
* Default retry number should probably be 0 to conform to current behavior
* Warnings should be logged to stderr or stdout for each retry, along with reason for failure, to inform the user
* A failed insert should probably get a new Status, something to the effect of "Failed but retrying"

p.s. what DB are you using? I have done successful benchmarks on Couchbase and MongoDB with 100,000,000 records without much issue during loading. Then again there may be retry logic built into some DB drivers.

**Comment by busbey** [comment]
I'm also curious what datastore binding you're using.

A given datastore shouldn't fail the load when a given insert fails, it should just count the number of failed responses.

We've been trying to remove any retry code from our datastore bindings, because we want folks to get a realistic idea of what their application will get out of the box when using a given driver. So if we can pass some kind of "you should retry" parameter to the driver that talks to whatever datastore, that'd be fine.

**Comment by stfeng** [comment]
@busbey - The load is failed by the CoreWorkload and ClientThread classes upon a single insertion failure in the following functions (as shown below). I completely agree that a DB binding should NOT retry a failed operation, it should just return failure code to its caller, and then the DBWrapper class (in YCSB core) will log and report that failed operation to a measurement class and show up in the final status summary. I am not going to change any of these. 

What has caused me headache is: with even just one single failed insert operation, the core workload logic (and ClientThread.java code) would abandon the entire load process, here is the code:

In CoreWorkload.java:
	public boolean doInsert(DB db, Object threadstate)
	{
		int keynum=keysequence.nextInt();
		String dbkey = buildKeyName(keynum);
		HashMap<String, ByteIterator> values = buildValues(dbkey);
		if (db.insert(table,dbkey,values).equals(Status.OK))
			return true;
		else
			return false;
	}

In ClientThread.java which calls the above function in the following while loop that implements the "load" phase:

       while (((_opcount == 0) || (_opsdone < _opcount)) && !_workload.isStopRequested())
        {

          if (!_workload.doInsert(_db,_workloadstate))
          {
            break; <--- This breaks out of the while loop on one single failure.
          }

          _opsdone++;

          throttleNanos(startTimeNanos);
        }

To fix this, I am proposing that we add retry logic to the CoreWorkload.java class in the doInsert() function: when an insertion to the DB fails, retry up to K times (as configured by the user and the default is 0), and the retry must use the same key name so we leave no "holes" in the integer key name space. Then why not retry in the ClientThread.java code? Because if we retry there, a new key sequence number will be used to do the insertion and we will leave "holes" in the key name space, which means subsequent reads or updates may fail of "not-found" errors. The only place that knows how to construct a key name properly is the coreworkload class which calls keysequence.nextInt() in a stateful manner, so if there is a failure to insert a particular key, we should let the coreworkload class to do the retry, because it knows exactly which key name it should use for the retry.

Re: which db binding I was using:

I was using a "managed" noSQL DB service in the cloud (google cloud datastore), the test client runs on  GCE VMs and there are multiple hops and layers from my client to the service and its backend. In such environment, a service availability of 99.9% or above isn't too shabby, but that also means 1 out of 1000 or 2000 or 3000 requests may fail. A robust client should be able to tolerate this, and simply retrying usually addresses such problem pretty well. 

I have tested using a private fix to CoreWorkload.java on my end with a retry limit of 5, before the fix, I wasn't able to load anywhere more than 5000 records to my DB, but after the fix, loading 100,000 or more records has not been a problem at all.

Re: kruthar's comments:

1. Yes, there will be a configurable max retry limit, and by default it will be 0 meaning no retry to conform with current behavior.
2. yes, when retry happens, a message will be output to the stderr so user knows. The failures will still reported to the measurement class (by DBWrapper class) as it is today, I'm not going to change those. 
3. As to the suggestion of trigger a full stop of the load process if/when the DB is really in "trouble", a user can achieve this by setting the retry limit to a reasonably low value (such as 2 or 3) and if the DB is really doing poorly then at some point that retry limit will be violated and the load process will stop. I want to keep things here and the number of knobs low for the user. I know in theory I can add a global variable called "totalAllowedRetryCountSinceTheBeginningOfLoad" ;) and ask the user to configure that variable in addition to the per-insert retry limit.... but I'd like to do that later when there is a strong need for it.

Thank you both for the great discussions! Let me know if you have further questions or concerns on this, otherwise, I will submit a PR soon...

**Comment by stfeng** [comment]
Hi Folks, just a quick update that I have not forgotten this issue and I still plan to submit a PR for this fairly soon, in O(days). (Having been busy with work on something else....)

**Comment by stfeng** [comment]
Folks, I've submitted a PR for this. Please take a look. Thanks!

**Comment by kruthar** [comment]
#527 was merged
