### ISSUE TITLE
Generate Workload on entire Cassandra Cluster, How to increase size of workload and what is the default workload size?

### ISSUE THREAD

**Issue by pushpendrachaturvedi** [brianfrankcooper/YCSB#513]
Hello,
I have two question 

Part 1
I have a 4-node cassandra cluster on physical host-Ubuntu.
I am using YCSB benchmarking to load and run Workload on seed node. (Keyspace is created as per instructions on https://github.com/cloudius-systems/osv/wiki/Benchmarking-Cassandra-and-other-NoSQL-databases-with-YCSB.)

Its working,

I am still not sure if the workload is shared between all other nodes in the cluster or it is just running on the seed node.

I want to start nodes one-by-one automatically through virsh in my scripts.
The load is initially generated on the seed node and as soon as other nodes start, the workload should be shared with other nodes.

Does it works like that when i generate load on SEED node only?
Do i need to include address ofall  other nodes in the cluster, or just IP address of SEED node is enough?
as in following command
 ./bin/ycsb load cassandra-10 -p hosts="seedNodeIP" -P workloads/workloada -s > workloada_load_res.txt

Part 2

How can i increase the size of workload generated on the cluster?

What is the default size of workload generated on cluster (in terms of memory)?

**Comment by kruthar** [comment]
>I am still not sure if the workload is shared between all other nodes in the cluster or it is just running on the seed node.

Not sure if you are using Cassandra from Apache, or using a distribution from Datastax. Either way this bit of documentation from Datastax may help you out. It discusses how to monitor the JMX output from Cassandra. In this way you can see what type of load and data each node is taking in. http://docs.datastax.com/en/cassandra/2.0/cassandra/operations/ops_monitoring_c.html

>I want to start nodes one-by-one automatically through virsh in my scripts.
>The load is initially generated on the seed node and as soon as other nodes start, the workload should be shared with other nodes.

I'm not quite sure what you are trying to accomplish here. Generally you would install configure and test your Cassandra cluster to make sure that it is up and ready, then use YCSB to run some workloads. It sounds like you want to start with a single node running Cassandra, start your workload testing, then start your other nodes. You may be able to do this, but I'm not sure it is supported behaviour and not sure if it is going to work how you want it to.

>Do i need to include address ofall other nodes in the cluster, or just IP address of SEED node is enough?

You should NOT have to include every node in your ```hosts``` specification. If your Cassandra cluster is configured correctly then a single node address should suffice. The reason why you would want to include more is to avoid any initial complications with connecting to the cluster. EX. If you specify only one node address and the connection fails, then you could not connect. If you were to give a few addresses and the first fails, then you have others to try to connect to. After the initial connection, the driver should communicate with the cluster and get larger insights on the topology of the cluster.

>How can i increase the size of workload generated on the cluster?

Several ways:

* increase number of threads with ```threadcount```
* specify reading or writing all fields with ```readallfields``` and ```writeallfields```
* increase number of operations with ```operationcount```
* increasing the number of records could effect performance with ```recordcount```

Check out the properties listing here: https://github.com/brianfrankcooper/YCSB/wiki/Core-Properties

>What is the default size of workload generated on cluster (in terms of memory)?

Actually not sure about this one, but you can check memory usage with something as simple as the ```top``` command. Running it on the YCSB machine will show how much memory YCSB is using and running it on your Cassandra machines will show how much memory the Cassandra nodes are using (also try the monitoring tools I listed above).

**Comment by kruthar** [comment]
@pushpendrachaturvedi - did this answer your questions in this issue?

**Comment by pushpendrachaturvedi** [comment]
yes it, did , closing this one too, thanks
