### ISSUE TITLE
YCSB for Aerospike benchmark

### ISSUE THREAD

**Issue by phanimv** [brianfrankcooper/YCSB#524]
Hi there,

I am trying to use YCSB to benchmark Aerospike(AS) database. I have successfully installed Aerospike and the installation seems to be good (verified as per AS site),  I have downloaded the YCSB via Git and compiled and built using Maven, and build is successsful, 
then I am trying to load data for AS using the below command as suggested in the site / wiki:

./bin/ycsb load aerospike -s -P workloads/workloada >outputLoad.txt

but it fails with an error:
: No such file or directory

but infact all the directories and contents are present, permissions seems to be good for bin and ycsb both, am not sure where going wrong, 
need help

thanks

**Comment by kruthar** [comment]
@phanimv - can you post the entire output when you run your load command?

Also, are you running YCSB on the same machine that Aerospike is installed on?

**Comment by phanimv** [comment]
I am running YCSB on the same machine on which AS installed,
here is what i get, am listing the pwd and contents of the same, which might help,

[root@pkhr YCSBbfc]# pwd
/root/myGit/YCSBbfc

[root@pkhr YCSBbfc]# ls
accumulo        cassandra2      dynamodb         hbase10      mapkeeper       pom.xml
aerospike       checkstyle.xml  elasticsearch    hypertable   mongodb         README.md
bin             core            gemfire          infinispan   nosqldb         redis
binding-parent  couchbase       googledatastore  jdbc         NOTICE.txt      tarantool
BUILD           distribution    hbase094         kudu         orientdb        voldemort
cassandra       doc             hbase098         LICENSE.txt  outputLoad.txt  workloads

[root@pkhr YCSBbfc]# ./bin/ycsb load aerospike -s -P workloads/workloada >outputLoad.txt
: No such file or directory
[root@pkhr YCSBbfc]#

**Comment by kruthar** [comment]
Oh, right you're also directing the output to outputLoad.txt. Can you rerun the command without ```>outputLoad.txt``` and post the output?

**Comment by phanimv** [comment]
I have re-run the command, which seems to be same, also i have tried cat of outputLoad.txt which is empty as well.

[root@pkhr YCSBbfc]# ./bin/ycsb load aerospike -s -P workloads/workloada
: No such file or directory
[root@pkhr YCSBbfc]# cat outputLoad.txt
[root@pkhr YCSBbfc]#


thanks

**Comment by kruthar** [comment]
@phanimv - what OS and what type of shell are you using?

I can almost replicate your issue if I try and run something that does not exist, ex: ```./bin/ycsb2``` but I get a little better output from bash. This leads me to believe that there is something strange in the environment you are running in.

The base line test you can run is simply:

```
./bin/ycsb
```

This should print out a usage report. If it does not then you have an issue probably unrelated to YCSB.

**Comment by cmccoy** [comment]
A few other things you might check:

* Is `java` on your path? `which java`
* Have you tried running from a [release](https://github.com/brianfrankcooper/YCSB/releases/tag/0.5.0) of YCSB, rather than a git checkout?

**Comment by phanimv** [comment]
RHEL 7
bash
java path is set properly, 
using which am able to build packages usign Maven

**Comment by phanimv** [comment]
even with simple ./bin/ycsb it is the same

 ./bin/ycsb
: No such file or directory

**Comment by cmccoy** [comment]
Are you missing python?

**Comment by phanimv** [comment]
@cmccoy 
Have you tried running from a release of YCSB
does this mean, I have to download the gz files from the below page ?
https://github.com/brianfrankcooper/YCSB/releases/tag/0.5.0

I should download ycsb-0.5.0.tar.gz ? does this suffice ? 
ycsb-aerospike-binding ? also required ?

thanks

**Comment by kruthar** [comment]
This should be all you need: https://github.com/brianfrankcooper/YCSB/releases/download/0.5.0/ycsb-0.5.0.tar.gz

Unpack it with something like ```tar -xvf```, then run ```./bin/ycsb``` from inside.

From trying some random things, I see similar ```No such file or directory``` errors (with a little better diagnostic attached) when things like this are happening:

* no ```python```
* no ```/usr/bin/env```
* no ```bin/ycsb```

**Comment by phanimv** [comment]
@kruthar @cmccoy 
just now I have downloaded ycsb-0.5.0.tar.gz, ,
unzipped and tried the basic command ./bin/ycsb, it gives the usage as below:
I believe it got downloaded properly.

[root@pkhr ycsb-0.5.0]# ./bin/ycsb
usage: ./bin/ycsb command database [options]

Commands:
    load           Execute the load phase
    run            Execute the transaction phase
    shell          Interactive mode

Databases:
    accumulo       https://github.com/brianfrankcooper/YCSB/tree/master/accumulo
    aerospike      https://github.com/brianfrankcooper/YCSB/tree/master/aerospike
    basic          https://github.com/brianfrankcooper/YCSB/tree/master/basic
    cassandra-10   https://github.com/brianfrankcooper/YCSB/tree/master/cassandra
    cassandra-7    https://github.com/brianfrankcooper/YCSB/tree/master/cassandra
    cassandra-8    https://github.com/brianfrankcooper/YCSB/tree/master/cassandra
    cassandra-cql

**Comment by kruthar** [comment]
Great, so the usage report is expected. Go ahead and try your full command now.

**Comment by phanimv** [comment]
I have tried the below command 

./bin/ycsb load aerospike -s -P workloads/workloada

now the question / clarity I need is, how to make sure this is running proper and everything is clean 

it executes as below:

/usr/java/jdk1.8.0_65/bin/java -cp /root/ycsb5/ycsb-0.5.0/aerospike-binding/conf:/root/ycsb5/ycsb-0.5.0/conf:/root/ycsb5/ycsb-0.5.0/lib/jackson-core-asl-1.9.4.jar:/root/ycsb5/ycsb-0.5.0/lib/core-0.5.0.jar:/root/ycsb5/ycsb-0.5.0/lib/HdrHistogram-2.1.4.jar:/root/ycsb5/ycsb-0.5.0/lib/jackson-mapper-asl-1.9.4.jar:/root/ycsb5/ycsb-0.5.0/aerospike-binding/lib/jbcrypt-0.3m.jar:/root/ycsb5/ycsb-0.5.0/aerospike-binding/lib/luaj-jse-3.0.jar:/root/ycsb5/ycsb-0.5.0/aerospike-binding/lib/aerospike-binding-0.5.0.jar:/root/ycsb5/ycsb-0.5.0/aerospike-binding/lib/aerospike-client-3.1.2.jar:/root/ycsb5/ycsb-0.5.0/aerospike-binding/lib/gnu-crypto-2.0.1.jar com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.AerospikeClient -s -P workloads/workloada -load
YCSB Client 0.1
Command line: -db com.yahoo.ycsb.db.AerospikeClient -s -P workloads/workloada -load
Loading workload...
Starting test.
2015-12-08 01:15:07:231 0 sec: 0 operations; est completion in 0 seconds
2015-12-08 01:15:07:614 0 sec: 1000 operations; 1216.55 current ops/sec; [CLEANUP: Count=1, Max=1049, Min=1049, Avg=1049, 90=1049, 99=1049, 99.9=1049, 99.99=1049] [INSERT: Count=1000, Max=30303, Min=110, Avg=318.83, 90=392, 99=1896, 99.9=9711, 99.99=30303]
[OVERALL], RunTime(ms), 822.0
[OVERALL], Throughput(ops/sec), 1216.54501216545
[CLEANUP], Operations, 1.0
[CLEANUP], AverageLatency(us), 1049.0
[CLEANUP], MinLatency(us), 1049.0
[CLEANUP], MaxLatency(us), 1049.0
[CLEANUP], 95thPercentileLatency(us), 1049.0
[CLEANUP], 99thPercentileLatency(us), 1049.0
[INSERT], Operations, 1000.0
[INSERT], AverageLatency(us), 318.834
[INSERT], MinLatency(us), 110.0
[INSERT], MaxLatency(us), 30303.0
[INSERT], 95thPercentileLatency(us), 457.0
[INSERT], 99thPercentileLatency(us), 1896.0

**Comment by kruthar** [comment]
The output here looks good. There should be an additional line at the bottom with return codes from the operations that isn't shown here. If you have 1000 entries for ```OK```, then you shouldn't have had any issues. 

You can verify that the records were properly inserted by some other means like looking directly in Aerospike.

**Comment by phanimv** [comment]
Yeah I can see that, infact I didn't copy whole message in earlier message:

here is the tail of the message:

[INSERT], MaxLatency(us), 30303.0
[INSERT], 95thPercentileLatency(us), 457.0
[INSERT], 99thPercentileLatency(us), 1896.0
[INSERT], Return=OK, 1000

thanks

**Comment by phanimv** [comment]
@kruthar based on your response, I believe ycsb installation is good,
I shall try to load large data and try to benchmark AS, shall get back to you about it went on,
otherwise, 
@kruthar @cmccoy thank you very much for your quick turn around and responses, very much appreciate it and it is helpful.

Thanks and Cheers, Shall get back to you soon

**Comment by phanimv** [comment]
Hi,

I am able to successfully load data ~40GB,
but when am trying to run the stress test using the below command, 
./bin/ycsb run aerospike -s -P workloads/workloada


there are lot of errors of key not found, though at the sametime there are many reads, still ultimately it breaks out with the following error

Error while writing key user126681452320941688: com.aerospike.client.AerospikeException: Error Code 2: Key not found
Record key user4200679211667895822 not found (read)
Record key user9156865532434275658 not found (read)
Record key user2406830966585268249 not found (read)
Write failed: Connection reset by peer

**Comment by kruthar** [comment]
So, it looks like there could possibly be two issues here.

1. Keys not found on reads and updates
2. Whatever is causing this: "Write failed: Connection reset by peer"

I'm going to focus on the first one for now. A few questions:

* Do you have your configuration and command you used to load your data? 
* Did you see any errors when you loaded your data, did you get all ```OK``` return codes? 
* Can you verify that you have the expected number of records in Aerospike?
* Have you tried manually checking Aerospike for the missing records by key?
* Have you tried loading and testing a smaller data set, if so, did you have the same issues?

**Comment by phanimv** [comment]
the configuration is mostly defaults, except the record count:

1.
recordcount=30000000
operationcount=30000000
workload=com.yahoo.ycsb.workloads.CoreWorkload

readallfields=true

readproportion=0.5
updateproportion=0.5
scanproportion=0
insertproportion=0

requestdistribution=zipfian

2.  there were no errors in data load:  tails of the same below:

[CLEANUP], 99thPercentileLatency(us), 2007.0
[INSERT], Operations, 3.0E7
[INSERT], AverageLatency(us), 141.3889395
[INSERT], MinLatency(us), 52.0
[INSERT], MaxLatency(us), 28319.0
[INSERT], 95thPercentileLatency(us), 238.0
[INSERT], 99thPercentileLatency(us), 269.0
[INSERT], Return=OK, 30000000


I have tried the default for the smaller which is 1000 records, both load and run were good,

**Comment by kruthar** [comment]
@phanimv - any luck here? Were you able to do these two things:

>* Can you verify that you have the expected number of records in Aerospike?
* Have you tried manually checking Aerospike for the missing records by key?

I would also suggest trying a few load values that start small and build up to your 30000000 and see at what point things go wrong.

One other thing you should look into is if you are using a Aerospike on a virtual machine, if that machine is capable of holding all ~40GB of your data or whatever the final amount is.

**Comment by phanimv** [comment]
Hi,
@kruthar - I was off from the work for couple of days, and couldnt try over weekend as well,
going to give a try today, I hope I should have good luck in this, get back to you tomorow.

thanks

**Comment by phanimv** [comment]
@kruthar  Hi,

I have loaded, end of the load below is the message:

[CLEANUP], MaxLatency(us), 2005.0
[CLEANUP], 95thPercentileLatency(us), 2005.0
[CLEANUP], 99thPercentileLatency(us), 2005.0
[INSERT], Operations, 3.0E7
[INSERT], AverageLatency(us), 173.0263865
[INSERT], MinLatency(us), 53.0
[INSERT], MaxLatency(us), 31103.0
[INSERT], 95thPercentileLatency(us), 273.0
[INSERT], 99thPercentileLatency(us), 292.0
[INSERT], Return=OK, 30000000

which I believe should be good,

then I have run the stress test against the DB, end of which below is the message:

[CLEANUP], MaxLatency(us), 2909.0
[CLEANUP], 95thPercentileLatency(us), 2909.0
[CLEANUP], 99thPercentileLatency(us), 2909.0
[UPDATE], Operations, 1.5004515E7
[UPDATE], AverageLatency(us), 153.63754423251933
[UPDATE], MinLatency(us), 47.0
[UPDATE], MaxLatency(us), 17535.0
[UPDATE], 95thPercentileLatency(us), 243.0
[UPDATE], 99thPercentileLatency(us), 272.0
[UPDATE], Return=OK, 15004515


I believe now the load is good and proper. the final OK should be the confirmation, right ?

thanks

**Comment by kruthar** [comment]
Looks fine to me as long as you didn't get any errors reported.

**Comment by GavinDmello** [comment]
We faced a similar issues where the reads failed. The problem was that the inserts during the loads failed if the  set wasn't empty which is weird. We had to clear the set and run the load everytime which made the test work

**Comment by busbey** [comment]
@GavinDmello if this was with a current version of YCSB, please open a new issue with details. You should only need to run the load phase a single time, presuming your test runs are all with the built-in core workload generator.
