### ISSUE TITLE
[Cassandra] cassandra-binding major refactor

### ISSUE THREAD

**Issue by kruthar** [brianfrankcooper/YCSB#532]
All the Thrift-based clients (all clients except CassandraCQLClient) in the cassandra-binding are essentially the same. They have no major functional differences (except for better property support in CassandraClient10). They are all built against the same dependencies and so to me it seems that they are all redundant.

Dredging back through commit history, it looks like the multiple Cassandra clients used to be built against different versions of the Cassandra driver and so were necessary. #64 brought a major paradigm shift in how the project was built and it seems that that is when they really started to just be copies of each other.

Posting this issue to see if anyone sees any reason why they are different that I may have missed. Otherwise they should be consolidated into a single client. This may help ease confusion between which Cassandra clients do what and are for what versions.

I'd be happy to take this on, just want to make sure I did not miss any reason why they are actually different and necessary as they are now.

**Comment by busbey** [comment]
Related question: do we have anyone willing to test against the earlier versions of Cassandra that need to use (or even _can_ use) the older Thrift-base clients?

If not, should we just deprecate them and remove them in e.g. 6 months?

**Comment by kruthar** [comment]
I had planned on testing against 7, 8, and 10 as the binding suggests. But I agree, deprecating might also make sense, most if not all people are going to be using the cassandra2-binding now.

**Comment by busbey** [comment]
It might be worth asking on the cassandra user list, since they're more likely to have visibility into current prevalence.

**Comment by kruthar** [comment]
I received a few responses from folks on the Cassandra users mailing list: http://www.mail-archive.com/user@cassandra.apache.org/msg45162.html. Looks like they don't expect many people to be using Cassandra versions in 0.X or 1.X.

So, my thoughts are to follow @busbey suggestion and plaster a deprecation warning on the cassandra-binding README, give it a stated amount of time, then remove it. Really no point in spending much effort on fixing that binding.

I would think keeping the cassandra2-binding named as it is, self documenting, and clearly state the versions it is compatible with at the top of the README. The current README suggests it is good for 2.1+, I want to test and see if it is actually good for 2.0 also.
