### ISSUE TITLE
orientdb README tells folks to clone a third party repo

### ISSUE THREAD

**Issue by busbey** [brianfrankcooper/YCSB#539]
the orientdb README tells folks to download a fork repo:

> git clone git://github.com/nuvolabase/YCSB.git

we should not recommend this. :)

**Comment by kruthar** [comment]
@busbey - can we edit this issue to be a general 'things to fix in the orientdb client' conversation. I have been messing around with it and there are several things that likely need to be updated and fixed. What I have found so far, in no particular order:

1. Update README with better getting started instructions, YCSB repo, etc.
2. Update driver version - current version does not allow remote connections (further on this below)
3. Create tests - OrientDB has an inmemory option so tests should be possible.
4. General code overview - this database isn't in the tested list, so need to give it a look through and see what needs to happen to promote to the tested and verified list.

First bit of discussion: Currently there is a default url set to use a plocal address. I see two issues with this:

1. Should we allow benchmarking of embedded or inmemory databases? What do the benchmark results mean in that case? It doesn't make sense to me.
2. Related, I don't think there should be a default url, in this case it points to in embedded database which seems wrong.

My thought is that all connections need to be remote.

**Comment by busbey** [comment]
sure, fine by me. I only kept it tightly scoped at first to make sure the very wrong bit could be fixed quickly.

In general,  embedded datastores are fine I think. It's totally legit to decide between e.g. using leveldb (or sqlite) and a local single node mongodb deployment in a simple application. I agree, however, that our docs should be geared primarily towards remote when a given datastore has such a mode.

+1 on no default url, folks should have to conscientiously choose to be in local mode if there is a remote mode.

**Comment by risdenk** [comment]
@kruthar How much of this issue is left to address?

**Comment by kruthar** [comment]
@risdenk - everything is taken care of except for updating the README with better getting started instructions. Building from source is actually still required to get all the major changes we just pushed to the orientdb binding. Before the next release we should commit a final set of instructions to the orientdb README with instructions on how to get started with a prebuilt released version.

**Comment by risdenk** [comment]
@kruthar Can this issue be closed?
