### ISSUE TITLE
Release version 0.6.0

### ISSUE THREAD

**Issue by bigbes** [brianfrankcooper/YCSB#542]
For the next release, 0.6.0, the following items have already been merged:

* Memcached bingings were added: #518, #535 
* Added variance calculation of histogram latency reporting: #90 
* Add a Google Datastore client: #500
* Record latency of successful and failed operations separately: #507
* Added support for Vim and Emacs in .gitignore: #514 
* There was a long history with S3 database bindings: #372, #512, 
* Added editorconfig for easy style conformance: #520
* Cassandra: Added large deprecation message: #537
* Cassandra 2: Added better property handling: #536 
* Improved `bin/ycsb` script: #526 
* Kudu: #528, #540 

Known bugs:

I don't see any bugs, that i can reproduce.

Bindings to test:

* Google Datastore [newly added]
* Memcached [newly added]
* S3 [newly added]
* Cassandra 2 [fixes]
* Kudu [fixes]

Also it'll be great to test:

* MongoDB
* Tarantool [I'll do it]
* Redis [I can do it]
* Aerospike
* JDBC

I plan to release next version (0.6.0) of YCSB until December 31.

**Comment by bigbes** [comment]
OK, i've broke kudu building when replaced all `0.6.0` with `0.7.0`. Fix in the gh-544

**Comment by bigbes** [comment]
I've tested memcached bindings on version 1.4.24 and basic workloads - everything works fine.
Tarantool bindings are broken

**Comment by bigbes** [comment]
Fixes for Tarantool bindings are in gh-545

**Comment by bigbes** [comment]
Redis is tested - everything works fine to me.

**Comment by busbey** [comment]
I should be able to test windows early this week. It'll be on windows 10 this time instead of 7 if that matters to anyone.

**Comment by busbey** [comment]
my windows build environment is ready to go now, whenever an release candidate is ready.

**Comment by busbey** [comment]
have an expected schedule for 0.6.0-RC1? I'm trying to plan out when I can test windows support this week.

**Comment by bigbes** [comment]
I'm sorry for delay, it was a hell of a week.
RC1 is out: https://github.com/brianfrankcooper/YCSB/releases/tag/0.6.0-RC1

**Comment by kruthar** [comment]
I tested ```cassandra2-cql``` on Cassandra 2.0 and 2.1 and things look good.

Also tested ```jdbc``` on MySQL, looks good.

**Comment by busbey** [comment]
#561 should get cherry picked to the 0.6.0 release branch.

**Comment by busbey** [comment]
windows works on RC1

**Comment by bigbes** [comment]
@busbey i've merged #562 into staging branch and released 0.6.0-RC2

**Comment by bigbes** [comment]
@busbey what's about #567 ?

**Comment by allanbank** [comment]
I ran the normal suite of MongoDB tests with RC2. Everything looked good. 

Current MongoDB versions tested are 3.2.0 3.0.8 2.6.11 2.4.14 2.2.7 2.0.9 1.8.5.

Version 1.8.5 is only tested with the 'mongodb-async' binding as the driver for the 'mongodb' binding does not work with that version.

**Comment by busbey** [comment]
I think #567 should get pulled in, but @kruthar is willing to keep it with other upcoming orientdb improvements for the next version. Up to you, since neither of us have a strong opinion AFAICT.

**Comment by busbey** [comment]
I started testing with Accumulo 1.6 and ran into a problem where it doesn't get a table name. Trying to figure out if I changed something in my helper scripts or if something has changed on our end.

**Comment by busbey** [comment]
Accumulo currently is broken due to #570. The fix should be included in 0.6.0.

**Comment by busbey** [comment]
@jdcryans will you have a chance to test out kudu for this RC?

@cmccoy do you have the time to handle the hbase test?

@ivanB1975 could you check on S3?

@stfeng could you check on the google datastore binding?

@tlopatic could you handle aerospike?

**Comment by busbey** [comment]
I believe these known issues from 0.5.0 still apply:

:exclamation: The Cassandra CQL clients do not use prepared statements (#458).
The mongodb binding does not honor the maxPoolSize=XX parameter and instead opens a connection per client thread. (see #317)
:bangbang: Running directly from a source checkout on Windows is not supported. (see #335)
Several unsupported datastore bindings are still listed in CLI help. (see #328)
The Accumulo binding may report errors during cleanup. (see #340)
The HBase binding does not report a clear error message on encountering version incompatibility. (see #343)

**Comment by ivanB1975** [comment]
@busbey I answered in the last merged #564 
It is working, I only get some warnings for each thread used: DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
making a git pull after the testing I made didn't changed anything in s3 binding so I guess it is fine.
What do you think about the warning, can it be ignored?

**Comment by busbey** [comment]
Excellent. Glad to hear S3 is fine.

Yeah, the warning is fine. I think I already filed an issue to clean up the message so it's more clear what we're actually doing.

**Comment by ivanB1975** [comment]
Perfect!

**Comment by jdcryans** [comment]
I tested RC2 against a small 0.6.0 Kudu cluster, +1.

Sorry I didn't get to this sooner, I'm now watching the project so I should get notifications :)

**Comment by stfeng** [comment]
@busbey - LGTM on google datastore front. 

@bigbes - Many thanks for driving the release!

**Comment by cmccoy** [comment]
`hbase10` looks good against an HBase server running locally. Tested with/without buffered mutation.

**Comment by tlopatic** [comment]
0.6.0-RC2 looks good with Aerospike, too.

**Comment by bigbes** [comment]
@busbey, I've pushed #570 fix into 0.6.0-staging and've created RC3.
Can you check Accumulo bindings?

**Comment by busbey** [comment]
I'm running through the core workloads against accumulo with RC3 now. Should be done in a few hours.

**Comment by busbey** [comment]
RC3 looks good with Accumulo 1.6.0.

**Comment by busbey** [comment]
please let me know when there are draft release notes.

**Comment by busbey** [comment]
Draft release notes have been posted by @bigbes : https://github.com/brianfrankcooper/YCSB/releases/tag/untagged-83eeffe6ef8299c6b451

**Comment by busbey** [comment]
I don't see #570 listed. It should get called out as important, since it was a known issue (and a regression) in 0.5.0.

**Comment by busbey** [comment]
Looks like we're also missing #561, which is a perf improvement for cassandra.

I'd recommend calling out #537 as important, since it's the warning for downstream folks that we'll be removing something.

Personally, I don't think #514 and #520 are worthy of a release note, since they just impact those of us doing development on the project and not downstream folks.

Otherwise looks good. I think previously we had listed changes that impacted particular data stores next to their names in the datastore list, but I'm fine with either that or this approach.

**Comment by bigbes** [comment]
@busbey I've updated draft. Everyone OK with release message?

**Comment by busbey** [comment]
one nit:

> #561: removed tracing from insert

would be clearer as

> #561: removed tracing from Cassandra insert operations

otherwise +1 LGTM.

**Comment by gkamat** [comment]
Draft looks good, +1.

**Comment by bigbes** [comment]
@busbey https://github.com/brianfrankcooper/YCSB/pull/593 - PR for README on main page

**Comment by bigbes** [comment]
It seems like everything is done! Thank you all for your help with this release.
Link to [0.6.0 final release](https://github.com/brianfrankcooper/YCSB/releases/tag/0.6.0)
I'll send messages to them as soon as I get a chance.
