### ISSUE TITLE
a number ask on detiles of workloads

### ISSUE THREAD

**Issue by Hadi14** [brianfrankcooper/YCSB#548]
Hi All
excusme  i have a number of ask again :(
1-on workloads we have recordcount argument , what is different between it and operationcoun ? seem them are identical.

2- if we set readallfields=false and writeallfields=false what is going to happen?

3-what is fieldlengthdistribution, scanlengthdistribution,hotspotdatafraction arguments?

**Comment by kruthar** [comment]
>1-on workloads we have recordcount argument , what is different between it and operationcoun ? seem them are identical.

* recordcount - number of records to put into the database on ```load``` and number of records to possibly reference in ```run``` operations.
* operationcount - number of total operations (read, update, insert, scan) to perform during ```run```.

>2- if we set readallfields=false and writeallfields=false what is going to happen?

* readallfields=false - all read operations will specify a single field to read from the row of the operation (as opposed to reading all fields of the row)
* writeallfields=false - all update operations will specify a single field to update for the row of the operation (as opposed to updating all fields of the row)

These settings will affect different databases differently.

>3-what is fieldlengthdistribution, scanlengthdistribution,hotspotdatafraction arguments?

* fieldlengthdistribution - (constant, uniform, zipfian, histogram) this determines the type of generator used to pick the field lengths when inserting records.
* scanlengthdistribution - (uniform, zipfian) this determines the type of generator used to pick the length of each scan operation.
* hotspotdatafraction - (and hotspotopnfraction) are used to create a hotspot type generator for selecting keys used for operations. Checkout the hotspot generator to see what it does: https://github.com/brianfrankcooper/YCSB/blob/master/core/src/main/java/com/yahoo/ycsb/generator/HotspotIntegerGenerator.java.

Writing this I realized that only some of these properties are listed on the core properties page: https://github.com/brianfrankcooper/YCSB/wiki/Core-Properties. I will open an issue to rectify that.

**Comment by kruthar** [comment]
For reference #550 has been created to update documentation on core properties.

**Comment by Hadi14** [comment]
if we have 1000 record and if we want have 200 read,100 update,50 insert,250 scan
, so we will have recordcount=1000 , operationcount=600 ?

**Comment by cmccoy** [comment]
Roughly, yes, assuming you've set the `{read,update,insert,scan}proportion`s to match. But each operation is randomly selected according to those proportions, so you most likely won't get exactly 200, 100, 50, 250.

**Comment by Hadi14** [comment]
on readallfields=true , how to specify one of fileds for read?

**Comment by kruthar** [comment]
You cannot specify which field to read or update. The field that gets read on each read operation, and also the field that gets updated on each update operation are randomly chosen for each operation.

**Comment by Hadi14** [comment]
@kruthar ok
can we get that how many of operation do on what time and other how many of operation on what time?
for example 100 of total 200 operation do on 10ms mean 100=10ms , 50=15ms , 50=20ms

**Comment by kruthar** [comment]
I think you are asking if you can see the operation latencies in buckets? Yes, you can. Take a look at Core Properties for more details on these two properties https://github.com/brianfrankcooper/YCSB/wiki/Core-Properties.

* ```measurementtype=histogram``` - this will show results in buckets of latency.
* ```histogram.buckets=1000``` - specifies the number of buckets

The default hdrhistogram measurementtype also has useful information such as latency min, max, avg and percentiles.

**Comment by Hadi14** [comment]
when run YCSB on single machine can we define number of replications and get Their impact?

**Comment by kruthar** [comment]
Do you mean replications of data in your database? or replicating the workload via threads?

**Comment by Hadi14** [comment]
my meaning is simulation replications of data on YCSB  , unless when run a workloads all therads do it?

**Comment by kruthar** [comment]
YCSB doesn't directly deal with replication of data. How your database will replicate data depends on how you configure the database. Some YCSB clients do come with write consistency settings which determine how replicated data has to be for an insert or update operation to be considered successful. 

YCSB threads are just a way to increase load on the database by spinning up multiple YCSB client threads that act against the database at the same time.

```insertorder``` just deals with what the record keys look like. ```insertorder=hashed``` will hash the key id before storing it so they if you were to line all the keys up they would not be 'ordered'. ```insertorder=ordered``` does not hash the keys and so they are ordered.

**Comment by Hadi14** [comment]
meaning if we want to use replicate should setting replicate cosistency on our database like cassandra?

when we use insertorder=hashed , first all key sorted next them inserted ?

**Comment by Hadi14** [comment]
other question , in most of benchmark that talk about number of core , their Purpose is only real core or virtual core too?

**Comment by kruthar** [comment]
>meaning if we want to use replicate should setting up replicate cosistency on our database like cassandra?

Yes, you should look into how to setup the type of replication you want on the database you are using. Then check the respective YCSB binding README for consistency settings.

>when we use insertorder=hashed , first all key sorted next them inserted ?

They are not sorted perse. When you do your load, YCSB starts at 0 and counts up to whatever number of records you are inserting. Each value (0, 1, 2...) is then hashed and appended to 'user'. The hashed values will not be sorted.

>other question , in most of benchmark that talk about number of core , their Purpose is only real core or virtual core too?

This I can't say for sure, it depends on who is publishing the information and what is written there.

**Comment by Hadi14** [comment]
meaning that when threads want do insert , they select records randomly?

**Comment by Hadi14** [comment]
with change values on workloadd like this , can i use it on YCSB with insert , read (50%,50%)?

[workloadh.txt](https://github.com/brianfrankcooper/YCSB/files/72152/workloadh.txt)

**Comment by kruthar** [comment]
>meaning that when threads want do insert , they select records randomly?

No. If you are doing ```load``` with multiple threads then each thread gets distributed a range of consecutive record keys to insert. Then it inserts that group in order.

>in YCSB if we want leave example for 50% read and 50% insert , what is use case for this? and also 50% insert ,50 readmodifywrite proportion ?

workloada is 50% read, 50% update which is a common starting point for people. As for specific use cases, the predefined workloads are just starting points, you really need to identify what type of load use case you want to simulate then design a workload around that. The sample workload files have a short description of a possible use case for each one.

>with change values on workloadd like this , can i use it on YCSB with insert , read (50%,50%)?
>
>workloadh.txt
>
>should i use license for it?

It looks like this is just a copy of workloadd with different percentage values? If so I don't see any issue with it.

**Comment by Hadi14** [comment]
in Meteorology, data is heavy , right?
on your opinion what is proporation of operations on Meteorology?

**Comment by kruthar** [comment]
You'll really have to do your own research here to see what data use cases look like.

**Comment by Hadi14** [comment]
ok,if i use cpu that have 4 thread , can i define thread=100 on load command ?

**Comment by Hadi14** [comment]
Hi
excusme , if i set operationcount=1000 but i set "-p recordcount=80000" on command line load , can it work as well?

**Comment by cmccoy** [comment]
Yes, operation count can be larger or smaller than record count.

**Comment by Hadi14** [comment]
if operation count can be larger than record count how run it? it have less operation.

**Comment by kruthar** [comment]
@Hadi14 - operationcount and recordcount are unrelated. You can have operationcount be larger than recordcount, you would run that the same way as you normally would.

YCSB uses number generators to pick a new key value to perform each operation on. This means that the same key value may be chosen more than once. So, if your operationcount is higher than your recordcount than certain record keys will be operated on more than once.

There should be no issues with having an operationcount higher than the record count.

**Comment by Hadi14** [comment]
ok, What is the benefit of set target while we always want throughput?

**Comment by kruthar** [comment]
I'm sorry, I don't understand the question.

**Comment by Hadi14** [comment]
on YCSB we often want do benchmark for mesurement  throughput ,
so use target switch what is advantage?

**Comment by kruthar** [comment]
Ah. So, yes you may be trying to measure throughput under certain workloads, and so throttling throughput seems counter productive in your case.

But YCSB can also conceivable be used as a constant load generator in which you would set your target ops/sec to send to your database. This could be useful to test other things like how well your database handles prolonged constant load, or maybe failover scenarios under load.

**Comment by Hadi14** [comment]
than you 
well , when we set  for example target=100 , it must do 100 op/s overall variety loads. right?excuse me so what is meaning "prolonged constant load"?

2- what is 95,99thPercentileLatency ?i dont understand theme.

**Comment by kruthar** [comment]
>well , when we set for example target=100 , it must do 100 op/s overall variety loads. right?excuse me so what is meaning "prolonged constant load"?

Correct. By "prolonged constant load" I just mean that the workload is running for a long time.

 >2- what is 95,99thPercentileLatency ?i dont understand theme.

These are statistical figures calculated at the end of the workload. You can read more about what a percentile value is here: https://en.wikipedia.org/wiki/Percentile

**Comment by Hadi14** [comment]
ok,
what is cleanup on my load phase?

<code><pre>YCSB Client 0.1
Command line: -db com.yahoo.ycsb.db.RedisClient -s -P workloads/workloada -p redis.host=127.0.0.1 -p redis.port=6379 -load
[OVERALL], RunTime(ms), 6043.0
[OVERALL], Throughput(ops/sec), 165.48072149594572
[CLEANUP], Operations, 1.0
[CLEANUP], AverageLatency(us), 211.0
[CLEANUP], MinLatency(us), 211.0
[CLEANUP], MaxLatency(us), 211.0
[CLEANUP], 95thPercentileLatency(us), 211.0
[CLEANUP], 99thPercentileLatency(us), 211.0
[INSERT], Operations, 1000.0
[INSERT], AverageLatency(us), 3972.91
[INSERT], MinLatency(us), 218.0
[INSERT], MaxLatency(us), 1188863.0
[INSERT], 95thPercentileLatency(us), 5051.0
[INSERT], 99thPercentileLatency(us), 30623.0
[INSERT], Return=OK, 1000</code></pre>

**Comment by kruthar** [comment]
```[CLEANUP]``` is just the result of running the cleanup operation on the client you are using. Typically it will run once per thread at the end of the workload. The cleanup operation is different for each client and in general just takes care of things like closing connections to the database.

Most of the time the cleanup metrics won't be very useful as they are not really measuring anything of value.

**Comment by Hadi14** [comment]
runtime and Latency times is contain of cleanup?

**Comment by kruthar** [comment]
Yes, the time it takes to do the cleanup operations will be part of the overall runtime. The overall throughput is just operations / runtime.

**Comment by Hadi14** [comment]
so why in my above benchmark is "[INSERT], MaxLatency(us), 1188863.0" And "[INSERT], 99thPercentileLatency(us), 30623.0" while overalltime is=6043 ms?

**Comment by kruthar** [comment]
For both of these questions you have to look at the units. example:

>also in follow why "[CLEANUP], AverageLatency(us), 26328.0" is very larger RunTime?

26328.0 us == 26.328 ms, the total run time is 5659 ms which is larger then the cleanup latency.

**Comment by Hadi14** [comment]
ok @kruthar very thanks 
us what unit is? what is which word?

**Comment by kruthar** [comment]
ms = milliseconds
us = microseconds
ns = nanoseconds

**Comment by Hadi14** [comment]
@kruthar other Question , why is not the same of Operations on read and update as Exactly?

**Comment by kruthar** [comment]
YCSB uses a discrete generator which takes in the different operation proportions you specify and probabilistically chooses which operation should happen next depending on the relative proportions.

What this means is that with properties such as:

```
readproportion=0.5
updateproportion=0.5
```

each operation has a 50-50 chance of being a read or an update. YCSB effectively flips a coin to decide what each operation should be in this case. You are not guaranteed that you will get a perfect 50-50 operation split. It will be close but not exact.

**Comment by Hadi14** [comment]
if we set a parameter for example recordcount on command line , is priority with command line? or parameter on work load? is different that which on last or first?

**Comment by kruthar** [comment]
Yes, command line takes priority.

Issues like this it doesn't hurt to just go ahead and try yourself?

**Comment by Hadi14** [comment]
i dont understand your question completely but i did benchmark with 1 thread and 2000 operation count :
    [OVERALL], RunTime(ms), 5659.0
    [OVERALL], Throughput(ops/sec), 353.4193320374624
and other benchmark with 2 thread and 2000 operation count :
    [OVERALL], RunTime(ms), 8933.0
    [OVERALL], Throughput(ops/sec), 223.88895108026418

**Comment by Hadi14** [comment]
benchmarks with 2 thread have RunTime larger than 1 thread , is i natural?

**Comment by kruthar** [comment]
Yes, that seems possible. It all depends on your workload configuration and the performance of your database.

When you add a second thread you are doubling the load on your database. Each thread is going to perform the number of operations you specify in ```operationcount```. The results seem to say that with double the workload it takes a little longer to complete all of the operations.

**Comment by Hadi14** [comment]
ok , mean that if we set operationcount=1000 and -threads 2  any of thread run 1000 operation separately?

**Comment by kruthar** [comment]
Are you sure you changed the operation count to 1000? Earlier you said you were working with 2000 operationcount:

>and other benchmark with 2 thread and 2000 operation count :

**Comment by busbey** [comment]
the operation count is the total for the given client run. the total is split up amongst the number of threads you specify. So with thread =2 and count = 2k, a total of 2k operations are performed. this still might take longer than with 1 thread and 2k operations because there is overhead to running multiple threads (in YCSB and possibly in the data store driver) and 2 thousand is a small enough number that you may not over come that overhead in throughput savings.

**Comment by Hadi14** [comment]
@kruthar my mean is 1000 for example.

**Comment by kruthar** [comment]
@busbey explained threaded functionality. At this point I'm not sure what the question is?

**Comment by Hadi14** [comment]
sorry ,when we load and run workload for many time , Is the previous loaded data will be erased on previous run?

**Comment by busbey** [comment]
No, YCSB doesn't do anything to clean up data already in a datastore, whether from prior YCSB runs or elsewhere.

**Comment by Hadi14** [comment]
i gotg this error , is it's cause low to memory?

**Comment by busbey** [comment]
You missed the error text.

**Comment by Hadi14** [comment]
this http://stackoverflow.com/questions/33031214/unable-to-start-cassandra-dsc-on-mac-error-starting-local-jmx-server solution?

**Comment by busbey** [comment]
If you're having trouble getting Cassandra to run, you should seek help from the Cassandra community.

Their user mailing list details are here:

http://mail-archives.apache.org/mod_mbox/cassandra-user/

**Comment by Hadi14** [comment]
@busbey thankyou

**Comment by Hadi14** [comment]
Hi , on workload F i got this output,
1- additional READ-MODIFY-WRITE , why there is READ and CLEANUP and UPDATE?
2- why only 989 update?
<pre><code>[OVERALL], RunTime(ms), 4132.0
[OVERALL], Throughput(ops/sec), 484.027105517909
[READ], Operations, 2000.0
[READ], AverageLatency(us), 1219.5885
[READ], MinLatency(us), 370.0
[READ], MaxLatency(us), 99263.0
[READ], 95thPercentileLatency(us), 3177.0
[READ], 99thPercentileLatency(us), 7739.0
[READ], Return=OK, 2000
[READ-MODIFY-WRITE], Operations, 989.0
[READ-MODIFY-WRITE], AverageLatency(us), 2380.6511627906975
[READ-MODIFY-WRITE], MinLatency(us), 816.0
[READ-MODIFY-WRITE], MaxLatency(us), 101759.0
[READ-MODIFY-WRITE], 95thPercentileLatency(us), 5883.0
[READ-MODIFY-WRITE], 99thPercentileLatency(us), 10399.0
[CLEANUP], Operations, 1.0
[CLEANUP], AverageLatency(us), 9036.0
[CLEANUP], MinLatency(us), 9032.0
[CLEANUP], MaxLatency(us), 9039.0
[CLEANUP], 95thPercentileLatency(us), 9039.0
[CLEANUP], 99thPercentileLatency(us), 9039.0
[UPDATE], Operations, 989.0
[UPDATE], AverageLatency(us), 1092.4924165824066
[UPDATE], MinLatency(us), 392.0
[UPDATE], MaxLatency(us), 14423.0
[UPDATE], 95thPercentileLatency(us), 2631.0
[UPDATE], 99thPercentileLatency(us), 6683.0
[UPDATE], Return=OK, 989</code></pre>

**Comment by kruthar** [comment]
>1- in additional READ-MODIFY-WRITE , why there is READ and CLEANUP and UPDATE?

readmodifywrite is actual just a measure of a read operation and a write operation on the same key. All read and update operations report their performance metrics, readmodifywrite reports its total performance as well. This is why you have readmodifywrite, read, and update metrics. We have already talked about cleanup on this thread, each thread of the workload runs a cleanup operation at the end.

>2- why only 989 for READ-MODIFY-WRITE and UPDATE?

This is another case of probabilistic operation selection. We talked about this a few posts up. Please check my answer to your question about why the number of read and update operations are not exactly the same with 50-50 proportions.

**Comment by Hadi14** [comment]
But the workloada was not operation on the same key? on this test we have 2000 read but 989 READ-MODIFY-WRITE and 989 UPDATE (989+989=1978) so  22 other operation?

**Comment by kruthar** [comment]
As I said, the readmodifywrite operations are actually double counts of the read and update operations that are contained in the readmodifywrite. This means that 989 readmodifywrite operations consist of 989 read operations and 989 update operations.

As you can see there are 989 update operations recorded. There are 2000 read operations recorded, this is because there are 989 read operations from readmodifywrite, and 1,011 plain read operations. This is because workloadf is 50% readmodifywrite, and 50% read. 1,011 is very close to 989, but not exact. This is to be expected.

So, 989 + 1,011 = 2000 total operations which should be your ```operationcount```, correct?

**Comment by Hadi14** [comment]
mean on this workload(read/readmodifywrite  50%/50%)  there is two step 1-simple Read (50%) and 2-readmodifywrite (50%).
on step2 and this example we have 989 read and modify and next write mean:
<pre><code>[READ-MODIFY-WRITE], Operations, 989.0
[READ-MODIFY-WRITE], AverageLatency(us), 2380.6511627906975
[READ-MODIFY-WRITE], MinLatency(us), 816.0
[READ-MODIFY-WRITE], MaxLatency(us), 101759.0
[READ-MODIFY-WRITE], 95thPercentileLatency(us), 5883.0
[READ-MODIFY-WRITE], 99thPercentileLatency(us), 10399.0
[CLEANUP], Operations, 1.0
[CLEANUP], AverageLatency(us), 9036.0
[CLEANUP], MinLatency(us), 9032.0
[CLEANUP], MaxLatency(us), 9039.0
[CLEANUP], 95thPercentileLatency(us), 9039.0
[CLEANUP], 99thPercentileLatency(us), 9039.0
[UPDATE], Operations, 989.0
[UPDATE], AverageLatency(us), 1092.4924165824066
[UPDATE], MinLatency(us), 392.0
[UPDATE], MaxLatency(us), 14423.0
[UPDATE], 95thPercentileLatency(us), 2631.0
[UPDATE], 99thPercentileLatency(us), 6683.0
[UPDATE], Return=OK, 989</code></pre>
correct?
but for step1 we have 2000 operation?
<pre><code>[READ], Operations, 2000.0
[READ], AverageLatency(us), 1219.5885
[READ], MinLatency(us), 370.0
[READ], MaxLatency(us), 99263.0
[READ], 95thPercentileLatency(us), 3177.0
[READ], 99thPercentileLatency(us), 7739.0
[READ], Return=OK, 2000</code></pre>

**Comment by kruthar** [comment]
The ordering of the print outs is arbitrary. YCSB performs all the operations in a random order, so there really is no notion of 'step1 and step2'.

Each readmodifywrite operation counts one for ```[READ-MODIFY-WRITE]``` and also one each for ```[READ]``` and ```[UPDATE]```. So, because there were 989 readmodifywrite operations, that means there were 989 operations each for read and update.

But as you pointed out there are actually: ```[READ], Operations, 2000.0```. As I just explained, 989 of those came from readmodifywrite, which means that 1,011 more read operations were just simple reads. We know that this makes since because 1,011 is very close to 989, workloadf has a 50-50 ratio between simple reads and readmodifywrite operations.

**Comment by Hadi14** [comment]
ok understand thankyou :).

**Comment by busbey** [comment]
closing out since it seems like we've covered everything relevant to what workload parameters mean.

**Comment by metonymic-smokey** [comment]
> The ordering of the print outs is arbitrary. YCSB performs all the operations in a random order, so there really is no notion of 'step1 and step2'.
> 

@kruthar , considering the ordering of the prints is arbitrary, is getting cleanup before the operations valid, or is it a sign there's something wrong?  
I'm asking this since I'm making some modifications to the source code of an existing DB binding in YCSB and get the cleanup before the operations on running certain operations.  
Would love your inputs on the same!  
Thanks!
