### ISSUE TITLE
Question : Capturing metrcis

### ISSUE THREAD

**Issue by gogoisgone** [brianfrankcooper/YCSB#576]
Team,

I am running some tests using a custom workload on a mysql database using jdbc. 
I would like to collect info and compare when using 1 thread vs 2 threads.

I need to capture the throughput, latency, cpu, ram , network  and i/o info...

Is using top on the same server the answer to it or are there any parameters that can be tweaked to capture the same. 

Please advise and thanks in advance.

**Comment by cmccoy** [comment]
YCSB will report about throughput and latency (as observed by the client), but not server side resource usage (CPU, memory, etc) - you'll need some sort other tool for that. [dstat](http://dag.wiee.rs/home-made/dstat/) is a simple one.

**Comment by gogoisgone** [comment]
Appreciate the input and the promptness.
