### ISSUE TITLE
About orientDB

### ISSUE THREAD

**Issue by bokyoungbin** [brianfrankcooper/YCSB#579]
Hi! First off, thanks for your work on this project. It really helps a lot of people save time when choosing databases. 
I have a question regarding OrientDB. I read the issues that is being tracked with orientDB, but I could not get it to work.
I have installed orientDB and I ran its server.
I have also git cloned YCSB, went into orientdb/src/.... *.java and changed the url, user and password information.
Then I mvn clean package -DskipTests in the YCSB directory. 
(mvn clean package  did not work due to Failure in the OrientDb Binding:
 Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.10:test (default-test) on project orientdb-binding: There are test failures.)

Next, I started the orientDb server  ./server.sh (in the orientDB directory's bin file) and did ./bin/ycsb load orientdb -s -P workloads/workloada
which worked fine.

However, what did not work was 
./bin/ycsb run orientdb -s -P workloads/workloada

It gives me the following:
[OVERALL], RunTime(ms), 1754.0
[OVERALL], Throughput(ops/sec), 570.1254275940707
[READ], Operations, 0.0
[READ], AverageLatency(us), NaN
[READ], MinLatency(us), 9.223372036854776E18
[READ], MaxLatency(us), 0.0
[READ], 95thPercentileLatency(us), 0.0
[READ], 99thPercentileLatency(us), 0.0
[READ], Return=ERROR, 515
[UPDATE-FAILED], Operations, 485.0
[UPDATE-FAILED], AverageLatency(us), 180.41030927835052
[UPDATE-FAILED], MinLatency(us), 139.0
[UPDATE-FAILED], MaxLatency(us), 1008.0
[UPDATE-FAILED], 95thPercentileLatency(us), 246.0
[UPDATE-FAILED], 99thPercentileLatency(us), 489.0
[CLEANUP], Operations, 1.0
[CLEANUP], AverageLatency(us), 88.0
[CLEANUP], MinLatency(us), 88.0
[CLEANUP], MaxLatency(us), 88.0
[CLEANUP], 95thPercentileLatency(us), 88.0
[CLEANUP], 99thPercentileLatency(us), 88.0
[READ-FAILED], Operations, 515.0
[READ-FAILED], AverageLatency(us), 182.4019417475728
[READ-FAILED], MinLatency(us), 142.0
[READ-FAILED], MaxLatency(us), 1487.0
[READ-FAILED], 95thPercentileLatency(us), 243.0
[READ-FAILED], 99thPercentileLatency(us), 570.0
[UPDATE], Operations, 0.0
[UPDATE], AverageLatency(us), NaN
[UPDATE], MinLatency(us), 9.223372036854776E18
[UPDATE], MaxLatency(us), 0.0
[UPDATE], 95thPercentileLatency(us), 0.0
[UPDATE], 99thPercentileLatency(us), 0.0
[UPDATE], Return=ERROR, 485

All the errors are NullPointExceptions
java.lang.NullPointerException
	at com.yahoo.ycsb.db.OrientDBClient.update(OrientDBClient.java:211)

I did not change anything in the workload files or anything else in the YCSB directory.

Can you give me some help on how to fix this issue?
By the way, its my first time working with YCSB. I have failed on different levels while trying to test orientDb, rocksDb, levelDb and riak.
Some I couldn't get them to build properly (some maven packaging issues, which I have no idea on how to fix) Some loads but cannot run (riak-out of bounds error)  etc etc.

If I am able to get this to work with workloada, I am planning to change options of the workload to suit my needs. But I am continuously getting stuck on this most basic part of the program.

I have worked on this for about a week now.. without having any success at all. 
It would be really great if you gave me some help. 
Again, thanks for all your work!

**Comment by busbey** [comment]
Sorry for all the difficulty you're having! I'm pretty convinced that we'd benefit tremendously from a "getting started" tutorial that did an end-to-end example, and your difficulties reinforce that.

Have you tried starting with one of the convenience binary tarballs from a release? Generally, you shouldn't need to alter the source code to test any particular binding (and we'd consider such a need a bug).

Lemme check how OrientDB support was doing in our last release. I know @kruthar has been doing a bunch of cleanup on that binding for the release that should be out in early February, but I didn't think it was unusable.

**Comment by bokyoungbin** [comment]
Thank you for your quick reply!
I did try using the binary tarballs from the 0.5.0 release. 
I downloaded the tar.gz file (https://github.com/brianfrankcooper/YCSB/archive/0.5.0.tar.gz)
changed orientdb/main/.../*.java to fix the configuration and executed 
$ ./bin/ycsb load orientdb -s -P workloads/workloada
$ ./bin/ycsb run orientdb -s -P workloads/workloada
Where again, load worked and run did not. It gave me the same errors NullPointException.
The only difference was that even after I changed the java code in YCSB/orientdb.../*.java,
mvn clean package did work. (All the tests were able to pass)

I am wondering if this problem is:
1. mine alone
or 
2. only for orientdb  (because I could not get rocksdb, leveldb, riak to work. I looked for github source codes to try these databases.)

Thanks so much for your help!

**Comment by kruthar** [comment]
hi @bokyoungbin

>I downloaded the tar.gz file (https://github.com/brianfrankcooper/YCSB/archive/0.5.0.tar.gz)

This is just a tar of the source code, not a prebuilt version. See below for a link to a release version.

>I have also git cloned YCSB, went into orientdb/src/.... *.java and changed the url, user and password information.

@busbey is correct, you should not have to alter any of the source code to get things to work, since you are having issues building the project you could try downloading a prebuilt release so you do not need to build it to use it. To set the properties all you have to do is create a properties file, set the url, user, and password and include it just like you included the workload file with ```-P``` on the command line.

>Then I mvn clean package -DskipTests in the YCSB directory. 
(mvn clean package did not work due to Failure in the OrientDb Binding:
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.10:test (default-test) on project orientdb-binding: There are test failures.)

This may be caused by the changes you made in the Java file. Can't be sure without seeing the changes you made and the actual failed test information from the Maven print out.

I would suggest grabbing a release version: https://github.com/brianfrankcooper/YCSB/releases/download/0.5.0/ycsb-0.5.0.tar.gz, setting the url, user and password in a properties file and trying again. Let me know how that goes, these are the properties you need to set:

```
orientdb.url=[your db path]
orientdb.user=[your user]
orientdb.password=[your password]
```

>By the way, its my first time working with YCSB. I have failed on different levels while trying to test orientDb, rocksDb, levelDb and riak.

How were you trying to use YCSB with these other databases? We do not currently have bindings for rocksdb, leveldb, or riak.

**Comment by bokyoungbin** [comment]
Ok I was definitely doing something wrong then. I changed the url user password in the ycsb orientdb code because it was using it. 
If I were to create a new properies file would the command line be something like 
./bin/ycsb load -s -P myorientDBprop -P workloads/workloada 

and myorientDBprop would just have those three lines of code?
I am not sure how I missed this properties setting part.. I was pretty sure I went over the wiki a few times before asking this question. 
Where can I see the documents regarding setting this property? I do not want to be distracting you and keep asking things here.. 
Thank you for your help!

**Comment by kruthar** [comment]
The command would look something like:

```
./bin/ycsb load orientdb -s -P myorientDBprop -P workloads/workloada
```

```myorientDBprop``` would indeed have the three properties. Check the README for a little more information on what they are: https://github.com/brianfrankcooper/YCSB/tree/master/orientdb, you can also look at the main README for more info on how to run using a source release: https://github.com/brianfrankcooper/YCSB, under Getting Started.

**Comment by bokyoungbin** [comment]
It gives me the exact same error. NullPointerException for the reads and updates:

java.lang.NullPointerException
	at com.yahoo.ycsb.db.OrientDBClient.read(OrientDBClient.java:179)
	at com.yahoo.ycsb.DBWrapper.read(DBWrapper.java:92)
	at com.yahoo.ycsb.workloads.CoreWorkload.doTransactionRead(CoreWorkload.java:651)
	at com.yahoo.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:567)
	at com.yahoo.ycsb.ClientThread.run(Client.java:329)

My exact steps were:
1. Install the release version
2. Set the properties at ycsb-0.5.0/workloads/prop
cat prop    gives me:
orientdb.url=plocal:/home/user/testoriDB
orientdb.user=myusername
orientdb.password=mypassword
3. executed orientdb/bin/server.sh  (the server is created at /home/user/testoriDB
4. executed ./bin/ycsb load orientdb -s -P workloads/prop -P workloads/workloada
It worked fine up to here.
5. executed ./bin/ycsb run orientdb -s -P workloads/prop -P workloads/workloada
and it gives me the same error.

I searched for github codes that binded riak/leveldb/rocksdb and added them into the ycsb folder (or downloaded their own ycsb folder with the maven dependencies worked out)
then I did the exact same thing. Riak gives me a similiar problem when doing run.
As for level/rocksdb I could not get them to load. (I don't know what I am doing wrong)

Thanks a lot for helping me out.

**Comment by kruthar** [comment]
At this point I can't say what the issue is. Can you do a small test for me. You actually don't even need to install OrientDB to use the orientdb binding in YCSB. On whatever machine you have YCSB installed on run these two commands to see if it works:

```
bin/ycsb load orientdb -P workloads/workloada -p orientdb.url=plocal:/tmp/ycsb -p orientdb.user=admin -p orientdb.password=admin
bin/ycsb run orientdb -P workloads/workloada -p orientdb.url=plocal:/tmp/ycsb -p orientdb.user=admin -p orientdb.password=admin
```

You can run those as is, you may need to change the url path only if you don't have permissions to that directory. Does this work for you?

**Comment by bokyoungbin** [comment]
Sorry I am currently not on a machine at the moment I will run it as soon as I get back. But do I not have to install and run the databases in order to check there performances? Is this only for orientdb or for other dbs such as mongo or riak or leveldb etc  as well?

**Comment by busbey** [comment]
normally, yes you need to install whatever datastore you're attempting to benchmark. The piece of code that allows YCSB to talk to a particular datastore is called a _driver_. Normally that driver allows YCSB to communicate with a installed service. In the case of OrientDB the driver has a mode called 'plocal' where the driver reads/writes directly to the local filesystem rather than going through some server process.

**Comment by bokyoungbin** [comment]
Thank you @kruthar ! This works very well. But I am unclear on WHY this works. The only difference seems to be the path of the db and the id/pw. Seeing that the 'load' part worked correctly before, I assumed that the path of the db and id/pw of my settings was not the problem. 

@busbey Ok so this is an orientDB only thing, through plocal, and the other dbs should be installed and run. Thanks for the explanation!

**Comment by kruthar** [comment]
hi @bokyoungbin - I could not pin down your issue exactly, but I am able to reproduce similar null pointers. They happen when I have not loaded any data into the database before trying to use the ```run``` command. I don't see any printouts for your ```load``` command, are you sure it was successful?

I'll echo @busbey in that typically you do need to install your target database first, configure it, then run YCSB against it. OrientDB is a little different in that it's Java API allows you to create local filesystem (plocal) and in-memory (memory) databases without the use of a pre installed database server. In fact, it seems to me that the only reason you need the database server is to facilitate remote connections and administration of OrientDB databases.

Currently only local database connections are supported in the orientdb-binding so you do not need to run the OrientDB server. In the next few days I have a PR coming which enables the orientdb-binding to work over a remote connection. So, if that is something you are interested in stay tuned.

**Comment by bokyoungbin** [comment]
I am pretty sure that the load worked because it returned the same results that I am getting now. I have a feeling that load and run were accessing different databases.. although I am not quite sure why.
Anyways, luckily the orientDB performances look pretty good to me so I don't think I have to bind other DBs. 
Thank you SO MUCH for your help. I didn't think that the responses were going to be this detailed and quick. I really appreciated your answers.
Hope you have a great day!

**Comment by busbey** [comment]
Glad we could help!
