### ISSUE TITLE
Metrics for dynamo benchmarking

### ISSUE THREAD

**Issue by mj-jadhav** [brianfrankcooper/YCSB#582]
Hi there,

I did dynamodb benchmarking using YCSB. I checked performance statistics. But now I want to plot metrics/graph for those numbers. Is there any way to do that in YCSB? or can you please suggest any other tools that can help me?

**Comment by kruthar** [comment]
YCSB doesn't have any visualizations built in, but something like Excel or Google Docs should be simple to use.

**Comment by busbey** [comment]
I like using [gnuplot](http://www.gnuplot.info/), but it involves an investment of time for the initial learning curve and getting data into a good format.

[ggplot2](http://ggplot2.org/) is also nice, if you are fine with writing in R.

**Comment by busbey** [comment]
Anyone else have suggestions? Was there anything that worked well for you, @mj-jadhav?

**Comment by mj-jadhav** [comment]
@busbey I used https://plot.ly/ which works really good with csv.

**Comment by busbey** [comment]
Glad to hear it!
