### ISSUE TITLE
Does YCSB support variable key,value length?

### ISSUE THREAD

**Issue by sktzwhj** [brianfrankcooper/YCSB#587]
As key,value length are critical to benchmark key-value stores in different scenarios, does YCSB supports it at present?

**Comment by cmatser** [comment]
Values of variable length are supported through properties starting with "FIELD_LENGTH_".  For example you can set
<code>
FIELD_LENGTH_DISTRIBUTION_PROPERTY_DEFAULT = uniform
</code>
And values will be of uniformly random lengths between 1 to 100.  The current default is a constant field length of 100.

Keys, however, are of constant length at this time.  I'm fairly certain this was done to be able to lookup keys easily for read tests.  The typical testing scenario is to load data into storage using YCSB in one run.  Then use subsequent runs of YCSB to benchmark read, update, and write operations.

I agree variable length keys could be an important benchmarking feature.  If you have an idea of how variable keys could be stored in one run and later computed to be read in a subsequent run, we'd be interested in your contribution.

**Comment by kruthar** [comment]
Agree with @cmatser. For reference these are the two properties needed to control field length:

```
fieldlengthdistribution=constant     # constant, uniform, zipfian
fieldlength=100
```

As far as key lengths go, it depends on settings. ```insertorder=hashed``` (default) appends a hashed value to 'user'. ```insertorder=ordered``` appends an incremented integer to 'user'. EX:

```
insertorder=hashed      # user6284781860667377211, user8517097267634966620, user1820151046732198393
insertorder=ordered     # user1, user2, user3032
```

The hashing function can be seen here: https://github.com/brianfrankcooper/YCSB/blob/master/core/src/main/java/com/yahoo/ycsb/Utils.java#L100-L115 the algorithm used is on Wikipedia: https://en.wikipedia.org/wiki/Fowler%E2%80%93Noll%E2%80%93Vo_hash_function. I am not sure if that algorithm produces a constant length value, or if there is variance.

So, short overview of how keys are generated. At this point there is not a way to explicitly control the key length.

**Comment by cmatser** [comment]
Oops, my bad on the property names.  Thanks for catching that @kruthar !

**Comment by sktzwhj** [comment]
Thank you all! I got the point.
