### ISSUE TITLE
YSCB clean package fails

### ISSUE THREAD

**Issue by bijugs** [brianfrankcooper/YCSB#590]
Tried ``mvn clean package`` at the top and it fails with the following error. Could get past this since we are not using ``kudu`` but may be of interest to other users.

```
[ERROR] Failed to execute goal on project kudu-binding: Could not resolve dependencies for project com.yahoo.ycsb:kudu-binding:jar:0.7.0-SNAPSHOT: Failed to collect dependencies for [org.kududb:kudu-client:jar:0.6.0 (compile), com.yahoo.ycsb:core:jar:0.7.0-SNAPSHOT (provided)]: Failed to read artifact descriptor for org.kududb:kudu-client:jar:0.6.0: Could not transfer artifact org.kududb:kudu-client:pom:0.6.0 from/to cloudera-repo (https://repository.cloudera.com/artifactory/cloudera-repos): peer not authenticated -> [Help 1]
```

**Comment by busbey** [comment]
Do you have anything special for Maven or JVM security settings? Are you behind a firewall perhaps? What version of maven are you using?

I just did a clean rebuild with a blank maven repository and things built fine. (see attached log)

[mvn_clean_package.log.txt](https://github.com/brianfrankcooper/YCSB/files/97838/mvn_clean_package.log.txt)

**Comment by bijugs** [comment]
Thanks @busbey . Did a clean build on a new machine and it worked fine.
