### ISSUE TITLE
How can i use timeseries?

### ISSUE THREAD

**Issue by Hadi14** [brianfrankcooper/YCSB#594]
Hi All
i use this command line but i got error 

<pre><code>./bin/ycsb run cassandra2-cql -p hosts="localhost"-P workloads/workloada -p operationcount=128000 -s -threads 1 -p measurementtype=timeseries -p timeseries.granularity=2000 > transactions.dat</code></pre>

**Comment by busbey** [comment]
please include the full text of the error you got.

**Comment by Hadi14** [comment]
this is error content:
<pre><code>Usage: java com.yahoo.ycsb.Client [options]
Options:
  -threads n: execute using n threads (default: 1) - can also be specified as the 
        "threadcount" property using -p
  -target n: attempt to do n operations per second (default: unlimited) - can also
       be specified as the "target" property using -p
  -load:  run the loading phase of the workload
  -t:  run the transactions phase of the workload (default)
  -db dbname: specify the name of the DB to use (default: com.yahoo.ycsb.BasicDB) - 
        can also be specified as the "db" property using -p
  -P propertyfile: load properties from the given file. Multiple files can
           be specified, and will be processed in the order specified
  -p name=value:  specify a property to be passed to the DB and workloads;
          multiple properties can be specified, and override any
          values in the propertyfile
  -s:  show status during run (default: no status)
  -l label:  use label for status (e.g. to label one experiment out of a whole batch)

Required properties:
  workload: the name of the workload class to use (e.g. com.yahoo.ycsb.workloads.CoreWorkload)

To run the transaction phase from multiple servers, start a separate client on each.
To run the load phase from multiple servers, start a separate client on each; additionally,
use the "insertcount" and "insertstart" properties to divide up the records to be inserted</code></pre>

**Comment by risdenk** [comment]
At minimum it looks like you are missing a space here:

hosts="localhost"-P  workloads/workloada

**Comment by Hadi14** [comment]
@risdenk 
Yes thankyou :)
