### ISSUE TITLE
Document HdrHistogram percentiles parameter

### ISSUE THREAD

**Issue by uluyol** [brianfrankcooper/YCSB#597]
I was digging through the docs and couldn't find any mention of `hdrhistogram.percentiles`. Looks like the feature was implemented in #442 but no docs were written.

**Comment by kruthar** [comment]
Yes, I have been meaning to update the Core Properties page, this is not the only property that is missing in documentation: #550. I just added a usage description at the bottom: https://github.com/brianfrankcooper/YCSB/wiki/Core-Properties.

For more context, the hdrhistogram measurement type (default) calculates percentile values for you, EX:

```
[INSERT], 95thPercentileLatency(us), 604.0
[INSERT], 99thPercentileLatency(us), 1457.0
```

The default is to print out the 95th and 99th percentile, but the ```hdrhistogram.percentiles``` property lets you specify any number of percentiles to calculate by specifying a comma separated list.

**Comment by uluyol** [comment]
Thanks!
