### ISSUE TITLE
Exporting HDRHistogram data

### ISSUE THREAD

**Issue by uluyol** [brianfrankcooper/YCSB#599]
Currently, YCSB only allows users to request different latency percentiles for their benchmark. However, HDRHistogram supports a variety of ways of viewing the data (linear/logarithmic iterators, percentile distributions, individual percentiles). Rather than put logic for handling these into YCSB, I suggest that we instead encode the histogram data itself and let users use it however they wish. However, I'm not sure how such a feature should be exposed to users given the current format for exporting data.

I can implement this if no one else is.

**Comment by busbey** [comment]
The current HDRHistogram implementation already does this. Unfortunately, the docs for the HDRHistogram work ended up in this little nook: [core/CHANGES.md on master](https://github.com/brianfrankcooper/YCSB/blob/master/core/CHANGES.md) (alt [same in 0.6.0](https://github.com/brianfrankcooper/YCSB/blob/0.6.0/core/CHANGES.md)).

I would love a pull request that removed this file and integrated the information in it into the rest of our docs.

**Comment by uluyol** [comment]
Whoops. I documented this on the wiki, it looks like docs in the repo have been out of date.
