### ISSUE TITLE
Getting errors like "Using 1 shardsDBWrapper: report latency for each error is false and specific error codes to track for latency are: []" running Mysql 5.7.10 with YCSB 0.6.0

### ISSUE THREAD

**Issue by talwar** [brianfrankcooper/YCSB#601]
[nohup_workloada_load_readinsert_test_db_2016_Jan_26_13_29_24.txt](https://github.com/brianfrankcooper/YCSB/files/107477/nohup_workloada_load_readinsert_test_db_2016_Jan_26_13_29_24.txt)
[nohup_workloada_run_readinsert_test_db_2016_Jan_26_14_12_32.txt](https://github.com/brianfrankcooper/YCSB/files/107476/nohup_workloada_run_readinsert_test_db_2016_Jan_26_14_12_32.txt)

OS: Centos 7.2
YCSB Version: ycsb 0.6.0
Mysql 5.7.10

-------------------------------------------------
Workload file for RUNNING workload:
-------------------------------------------------

workload=com.yahoo.ycsb.workloads.CoreWorkload
readallfields=true
readproportion=0.5
updateproportion=0
insertproportion=0.5
requestdistribution=zipfian
fieldlength=10000
recordcount=100000000
operationcount=100000000
maxexecutiontime=3600

--------------------------------------------------
Workload File for LOADING workload:
--------------------------------------------------

workload=com.yahoo.ycsb.workloads.CoreWorkload
readallfields=true
requestdistribution=zipfian
fieldlength=10000
operationcount=2810000
maxexecutiontime=3600

--------------------------------------------------
I installed YCSB and then installed Mysql5.7.10 and when I load/run the workload, I am getting these errors in my output. I have attached the output with this bug.

This is how I am executing the Load workload
----------------------------------------------------------
../bin/ycsb load jdbc -p hosts="$hostname" -P ../workloads/workloada -P ../jdbc-binding/conf/db.properties -s -threads 100 > "nohup_workloada_${runtype}_${workloadtype}_test_db_${E}.txt" 2>&1

This is how I am executing the Run workload
----------------------------------------------------------
../bin/ycsb run jdbc -p hosts="$hostname" -P ../workloads/workloada -P ../jdbc-binding/conf/db.properties -s -threads 100 > "nohup_workloada_${runtype}_${workloadtype}_test_db_${E}.txt" 2>&1

OUTPUT
------------
 Using 1 shardsDBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []Using 1 shards
Using 1 shardsDBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []Using 1 shards
Using 1 shardsDBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Using 1 shardsDBWrapper: report latency for each error is false and specific error codes to track for latency are: []

**Comment by kruthar** [comment]
@talwar - The lines you posted:

```
Using 1 shards
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
```

are not errors. The first line is saying that JDBC is connecting to only one shard on your database. The second is admittedly cryptic, but is also not an error. It simple means you have not specified to track any specific error codes, there is an issue out to make this more clear: #546.

These lines, as well as others show up so much because they print once for every thread you are using, and with 100 threads, you get a lot of benign printouts. It looks like your workload completes successfully, this was at the very end:

```
[OVERALL], RunTime(ms), 2585465.0
[OVERALL], Throughput(ops/sec), 1086.8451129680734
[CLEANUP], Operations, 100.0
[CLEANUP], AverageLatency(us), 3028.89
[CLEANUP], MinLatency(us), 69.0
[CLEANUP], MaxLatency(us), 288255.0
[CLEANUP], 95thPercentileLatency(us), 221.0
[CLEANUP], 99thPercentileLatency(us), 978.0
[INSERT], Operations, 2810000.0
[INSERT], AverageLatency(us), 91818.95399964413
[INSERT], MinLatency(us), 2646.0
[INSERT], MaxLatency(us), 784895.0
[INSERT], 95thPercentileLatency(us), 153087.0
[INSERT], 99thPercentileLatency(us), 185599.0
[INSERT], Return=OK, 2810000
```

I would suggest rethinking using so many threads. With that many threads the machine running YCSB starts to slow down regardless of whether your target database can handle the potential load. This is because the YCSB machine now has to spend a lot of time flip flopping between threads which makes the whole system slow down. From my own experience using more threads then cores in your machine is generally not a good idea.

From looking at your outputs, you do have some other configuration issues though. You are using ```recordcount=100000000``` which means you are expecting to have 100000000 records in your database. But in your load command you are not specifying ```recordcount``` at all and so only ```operationcount=2180000``` records actually get inserted into the database. This can be verified when looking at the output of your run workload:

```
[OVERALL], RunTime(ms), 3600409.0
[OVERALL], Throughput(ops/sec), 1871.732905900413
[READ], Operations, 150103.0
[READ], AverageLatency(us), 4553.472568836066
[READ], MinLatency(us), 212.0
[READ], MaxLatency(us), 227583.0
[READ], 95thPercentileLatency(us), 13655.0
[READ], 99thPercentileLatency(us), 20047.0
[READ], Return=OK, 150103
[READ], Return=NOT_FOUND, 3219963
[CLEANUP], Operations, 100.0
[CLEANUP], AverageLatency(us), 283258.88
[CLEANUP], MinLatency(us), 269312.0
[CLEANUP], MaxLatency(us), 315135.0
[CLEANUP], 95thPercentileLatency(us), 308479.0
[CLEANUP], 99thPercentileLatency(us), 314623.0
[READ-FAILED], Operations, 3219963.0
[READ-FAILED], AverageLatency(us), 400.6977105016424
[READ-FAILED], MinLatency(us), 73.0
[READ-FAILED], MaxLatency(us), 196479.0
[READ-FAILED], 95thPercentileLatency(us), 953.0
[READ-FAILED], 99thPercentileLatency(us), 5087.0
[INSERT], Operations, 3368938.0
[INSERT], AverageLatency(us), 106214.08369699887
[INSERT], MinLatency(us), 3258.0
[INSERT], MaxLatency(us), 972287.0
[INSERT], 95thPercentileLatency(us), 181247.0
[INSERT], 99thPercentileLatency(us), 222719.0
[INSERT], Return=OK, 3368938
```

Specifically this line: ```[READ], Return=NOT_FOUND, 3219963``` There are a lot of missing records.

**Comment by cmatser** [comment]
I'll go ahead a disagree with @kruthar on running with a bunch of threads.  Certainly, there can be a point of diminishing returns where the client machine is tied up managing the threads and their resources.  My experience with YCSB on a sufficiently powerful client machine is that it can handle multiple threads much faster than a sufficiently powerful NoSQL server processing requests.  The time it takes for YCSB to calculate the next key to perform an operation on and process the result of that operation is usually much faster than the latency of making a network call to a database that has to lookup that record for the requested key and return those results.

I ran my YCSB tests with up to 1000 threads and never felt that my client machine was a limiting factor in my performance results.  Plus, I got very interesting results where I felt I could see at what point the database started to get overwhelmed by client requests.  It was this information that could help decide things like cluster size or get a sense of the performance curve when under load.

Happy testing.

**Comment by busbey** [comment]
Has this helped clear things up @talwar?

**Comment by talwar** [comment]
Thanks a lot for your help. I am going to rerun my test with the
recommendations given to me and let you know how it goes. Again, I am
really thankful for all your help.

Sunny

**Comment by busbey** [comment]
Glad to hear it! If we can answer more questions, please open a new issue.
