### ISSUE TITLE
there are multi result on Run with -s

### ISSUE THREAD

**Issue by Hadi14** [brianfrankcooper/YCSB#602]
Hi
i do run with switch -s on 20000ms but for example there are multi result on 0 or 20000ms:
<pre><code>[READ], 0, 5908.162790697675
[READ], 0, 5908.162790697675
[READ], 0, 5908.162790697675
[READ], 20000, 5908.162790697675  <---------------
[READ], 20000, 1035.7512682808986 <--------------
[READ], 40000, 956.9894372294373
[READ], 40000, 956.9894372294373
[READ], 60000, 1127.4477242507926
[READ], 80000, 1039.71592466718
[READ], 100000, 1350.4055450660837
[READ], 120000, 1131.6684111152158
[READ], 140000, 1406.7080012262415
[READ], 160000, 1010.5504497138185
[READ], 180000, 1272.785008915101
[READ], 200000, 1167.1696089248499
[READ], 220000, 1048.2495843340107</code></pre>

why there are two value on 20000? they have different values ,this is what meaning?
thank you :)

**Comment by kruthar** [comment]
@Hadi14 - Can you please post the full command you are running as well as any configuration files if they are different then those base files in the project. Please consider doing this EVERY time you post an issue the more information we have the easier it is to help explain your issue.

**Comment by Hadi14** [comment]
@kruthar yes of course 
command line is:
<pre><code>Command line: -db com.yahoo.ycsb.db.CassandraCQLClient -p hosts=localhost -P workloads/workloadf -p operationcount=512000 -s -threads 4 -p measurementtype=timeseries -p timeseries.granularity=20000 -t
2016-01-25 09:10:06:318 0 sec: 0 operations; est completion in 0 seconds 
Datacenter: datacenter1; Host: localhost/127.0.0.1; Rack: rack1</code></pre>

and full result is attached.
[workrun_res.txt](https://github.com/brianfrankcooper/YCSB/files/109303/workrun_res.txt)

**Comment by kruthar** [comment]
@Hadi14 - thanks for catching this, it is, in fact, a bug. You can see exactly what is going on in #604.

Most of the time, the repeated printouts have the same value, and so you can ignore them. But in your example there is a repeat that has two separate values. I would suggest taking the last value for each repeated group.

I'm submitting a PR to fix this, but it won't be available in the prebuilt packages until the next release.

**Comment by Hadi14** [comment]
ok,
excuse me , for example in  ``` [READ], 0, 5908.162790697675 ```  is 5908.162790697675 Average Run Time for 0 to 20000 time?

**Comment by kruthar** [comment]
That reading is the average operation latency (in microseconds) for that time period. So, in your case each reading is the average operation latency for the last 20,000ms.

**Comment by busbey** [comment]
This has now been fixed in #605. Are you fine with closing this issue, @Hadi14?

**Comment by Hadi14** [comment]
ok , it fixed on YCSB 5 ? should download it?

**Comment by busbey** [comment]
No, the issue is fixed in our yet-to-be-released main development branch. The fix would make it into 0.7.0.

To test the fix to the time series measurement type for now, you'd have to build from the current repo.

**Comment by Hadi14** [comment]
sorry , where i should create change ?

**Comment by kruthar** [comment]
@Hadi14 - you can either just drop the duplicate printouts, and just keep the latest print out from each duplicate group, or you can build from source.

Check the Getting Started Wiki: https://github.com/brianfrankcooper/YCSB/wiki/Getting-Started and follow the instructions under ```Or clone the git repository and build:```. This will build the latest version into a tar located in ```distribution/target```, you can then unpack and use that tar normally.

**Comment by Hadi14** [comment]
ok 
thankyou @kruthar , @busbey.
