### ISSUE TITLE
Couchbase benchmarking

### ISSUE THREAD

**Issue by devmurali6** [brianfrankcooper/YCSB#603]
I recently did a couchbase Benchmarking with default values like (Default data size: 1 KB records (10 fields, 100 bytes each, plus key) I have in workloads, i just want to overwrite the default size to 32 KB..

Appreciate for help ..

**Comment by cmccoy** [comment]
You can try overriding the `fieldcount` and/or `fieldlength` properties to increase record size - see [Core Properties](https://github.com/brianfrankcooper/YCSB/wiki/Core-Properties) on the wiki.

**Comment by devmurali6** [comment]
So, as I edited the record count and operation count in workload file directly , can I override over there ?

**Comment by cmccoy** [comment]
You can override it either in the workload file or by passing parameters on the command line (i.e., `-p fieldcount=320`)

**Comment by devmurali6** [comment]
gotcha, Thank you ..

**Comment by devmurali6** [comment]
[OVERALL], Throughput(ops/sec), 21951.005356045305
[CLEANUP], Operations, 25.0
[CLEANUP], AverageLatency(us), 7809.04

what is this clean indicates here ?

**Comment by kruthar** [comment]
```[CLEANUP]``` is just performance metrics of running the cleanup() operation on the YCSB clients at the end of the workload. cleanup() will be run on each thread, so since there are 25 cleanup operations I would guess you ran 25 threads?

**Comment by devmurali6** [comment]
thank you kruthar
