### ISSUE TITLE
Release version 0.7.0

### ISSUE THREAD

**Issue by risdenk** [brianfrankcooper/YCSB#624]
For the next release, 0.7.0, the following items have already been merged:

* Apache Solr binding was added: #574, #583
* GemFire -> Apache Geode (incubating) binding: #620
* OrientDB improvements: #567, #569, #572, #577, #581, #585, #586, #609, #625
* HBase Kerberos support and use single connection: #591
* Accumulo improvements: #570, #596
* JDBC improvements: #588, #600
* Couchbase scan implementation: #610
* MongoDB improvements: #522, #578
* DynamoDB version increase: #592
* Elasticsearch version increase: #552
* Code formatting/cleanup: #555, #556, #557, #559, #561, #564, #565, #566

Breaking changes:
* gemfire binding changed to geode

Bindings to test:
* Solr [newly added]
* GemFire -> Geode [newly added]
* OrientDB [fixes]
* HBase [fixes]
* Accumulo [fixes]
* JDBC [fixes]
* Couchbase [fixes]
* MongoDB [fixes]
* DynamoDB [version bump]
* Elasticsearch [version bump]

Release plan:
* RC1 - Tues Feb 16th
* 0.7.0 - by Fri Feb 26th

**Comment by risdenk** [comment]
RC1 is out: https://github.com/brianfrankcooper/YCSB/releases/tag/0.7.0-RC1

**Comment by risdenk** [comment]
First draft of release notes (a bit early but figured I'd get a start on it): https://gist.github.com/risdenk/2c739719a815c4e74c64

**Comment by busbey** [comment]
Excellent! thanks for driving this Kevin.

I can take care of Accumulo and Windows platform testing.

* @ghaughian could you test out the Release Candidate to make sure it works with SOLR?
* @sbawaska could you check out the Release Candidate to make sure the new geode binding works?

**Comment by risdenk** [comment]
@kruthar Can you take care of testing OrientDB, JDBC, and Couchbase bindings?

**Comment by sbawaska** [comment]
The Geode binding looks good.

**Comment by busbey** [comment]
I tried building on windows and ran into #617 again. submitted PR #626 to skip the Accumulo tests on windows. We should cherry-pick that back for the 0.7.0 release to make sure building from source on windows works.

**Comment by risdenk** [comment]
@busbey Merged #626. I'll cherry-pick that commit back to 0.7.0 and respin the RC.

**Comment by risdenk** [comment]
@busbey had to back out #626. When it is fixed I can merge it and respin the RC.

**Comment by risdenk** [comment]
RC2 is out: https://github.com/brianfrankcooper/YCSB/releases/tag/0.7.0-RC2

Fixes from @busbey for Accumulo and @kruthar for OrientDB readallfields

**Comment by busbey** [comment]
RC2 builds on windows fine. running tests through accumulo now.

**Comment by busbey** [comment]
Accumulo works. I had a server-side issue while running through the workload a loading phase and everything properly tracked the failures and continued on.

Running HBase10 next.

**Comment by kruthar** [comment]
I tested a few dbs, everything looks ok to me:

```jdbc``` MySQL 5.1.73
```cassandra2-cql``` Cassandra 2.0.17
```couchbase``` Couchbase 4.0.0
```memcached``` Memcached 1.4.4
```orientdb``` OrientDB 2.1.2 (remote and local)
```mongodb``` MongoDB 3.0.9


For the curious, I'm running:

```
bin/ycsb load mongodb -P ~/projects/YCSB/testing/testworkload
bin/ycsb run mongodb -P ~/projects/YCSB/testing/testworkload
```

testworkload:

```
operationcount=10000
recordcount=10000
fieldcount=3
fieldlength=20
dataintegrity=true
writeallfields=true
readallfields=true
insertorder=ordered
maxscanlength=100
threadcount=1
workload=com.yahoo.ycsb.workloads.CoreWorkload

scanproportion=0.3
readproportion=0.3
updateproportion=0.4
insertproportion=0.0

hdrhistogram.percentiles=50,75,95

# mysql
db.driver=com.mysql.jdbc.Driver
db.url=jdbc:mysql://mysql.vagrant:3306/ycsb
db.user=admin
db.passwd=admin

# cassandra
hosts=cassandra.vagrant

# couchbase
couchbase.url=http://couchbase.vagrant:8091/pools
couchbase.bucket=usertable
couchbase.ddoc=ycsb_ddoc
couchbase.view=ycsb_view

# memcached
memcached.hosts=memcached.vagrant

# orientdb
# orientdb.url=plocal:ycsb
orientdb.url=remote:orientdb.vagrant/ycsb
orientdb.user=root
orientdb.password=password
orientdb.remote.storagetype=plocal

# mongodb
mongodb.url=mongodb://mongodb.vagrant:27017/ycsb?w=1
```

**Comment by risdenk** [comment]
@ghaughian - Do you have time to test out the new Solr bindings? If not I can take a look at testing it.

**Comment by risdenk** [comment]
@kruthar Thanks!

**Comment by ghaughian** [comment]
@risdenk it would be Thursday before I get a chance to test the Solr binding unfortunately. Would that work?

**Comment by risdenk** [comment]
@ghaughian Thanks! That should work. I'll update this thread if I get around to testing the Solr binding before you do.

**Comment by busbey** [comment]
Tested hbase10 and hbase098 bindings against a small (7 worker) cluster. Both work fine.

**Comment by busbey** [comment]
@yuyantingzero do you think you could check out the release candidate and make sure the updated DynamoDB client works as expected?

**Comment by busbey** [comment]
@magicbane could you spare some time to validate the release candidate works with ElasticSearch with the newer version?

**Comment by busbey** [comment]
@allanbank do you think we need the full mongodb battery of tests given the changes that happened?

@risdenk I just want to confirm that the plan is to keep these previously listed "tested supported" bindings from 0.6.0 as some form of "supported / expected to work" for this release:

* S3
* Google Cloud Datastore
* Apache Kudu (incubating)
* Aerospike
* Tarantool

**Comment by risdenk** [comment]
@busbey Yes going to keep the bindings that haven't changed from 0.6.0 as Supported but not listed as tested for this release.

I need to make a few minor edits still to the release notes, but draft release notes are here: https://gist.github.com/risdenk/2c739719a815c4e74c64

**Comment by busbey** [comment]
I also tested the HBase 098 binding, so it should be in "tested supported". @kruthar mentioned testing Memcached, so it should be in "tested supported".

Technically, the version of HBase I ran against was the CDH5.5.1 version (which is 1.0.0 based). Similarly, the Accumulo version was the Cloudera packaging 1.6.0-CDH5.1.4 (which is 1.6.0 based). I don't think the distinction is worth calling out, but now folks can find it later if I'm wrong. :)

The JDBC note should probably include what backing database it was used against because that can make a big difference in how tolerant of correctness things are.

I haven't seen anyone test DynamoDB or ElasticSearch yet. More importantly, I haven't seen anyone agree to test them.

**Comment by risdenk** [comment]
@busbey yea agreed on all your comments. Those were the edits that I was planning to make to the release notes. Just waiting to see what other testing comes in.

**Comment by risdenk** [comment]
Updated release notes based on comments from @busbey https://gist.github.com/risdenk/2c739719a815c4e74c64

Currently waiting on testing for Solr.

**Comment by yuyantingzero** [comment]
Sry for the late reply. I just tested dynamodb binding with workloada as well as some manual testing using ycsb shell for both HASH and HASH_AND_RANGE key mode.

**Comment by busbey** [comment]
excellent! thanks for checking it.

**Comment by ghaughian** [comment]
@risdenk Tested the Solr binding, everything looks good!

**Comment by risdenk** [comment]
thanks @yuyantingzero and @ghaughian.

@yuyantingzero - Which version of DynamoDB did you test?

@ghaughian - Which version of Solr did you test?

**Comment by ghaughian** [comment]
Solr 5.4.0

**Comment by risdenk** [comment]
All testing for RC2 has been completed. Draft release notes: https://gist.github.com/risdenk/2c739719a815c4e74c64

**Comment by busbey** [comment]
+1 release notes look good to me.

**Comment by risdenk** [comment]
Thanks @busbey. Going ahead with the steps for releasing 0.7.0.

**Comment by cmatser** [comment]
+1 Nice work handling this release.

**Comment by risdenk** [comment]
YCSB 0.7.0 is out https://github.com/brianfrankcooper/YCSB/releases/tag/0.7.0

**Comment by risdenk** [comment]
Starting release announcements. Will close out this issue when announcements are done.

**Comment by busbey** [comment]
excellent!

one nit on the release: the elasticsearch binding ended up in the untested category, so it shouldn't have convenience binaries included.

**Comment by risdenk** [comment]
Oops thanks @busbey. Removed the elasticsearch convenience binary.

**Comment by magicbane** [comment]
Sorry I'm currently traveling, so I didn't have time to test it. I can see
if I have time later today.

**Comment by busbey** [comment]
No worries @magicbane. We'll start another release in a few weeks and can get it tested in that release cycle.

**Comment by yuyantingzero** [comment]
@risdenk dynamodb is managed, doesn't have a version. But the aws sdk version is 1.10.48.

**Comment by risdenk** [comment]
@yuyantingzero Thanks yea my mistake when asking. I knew that but just blanked when responding to this thread.

**Comment by risdenk** [comment]
Announcement template: https://gist.github.com/risdenk/c921e833aaf46bb59500

Announced to the following:
* Apache Accumulo - user@accumulo.apache.org
* Apache Cassandra - user@cassandra.apache.org
* Apache Geode (incubating) - user@geode.incubator.apache.org
* Apache HBase - user@hbase.apache.org
* Apache Kudu (incubating) - user@kudu.incubator.apache.org
* Apache Solr - solr-user@lucene.apache.org
* Couchbase - https://forums.couchbase.com/c/other-product
* Elasticsearch - https://discuss.elastic.co/t/announce-ycsb-0-7-0-release/42890
* MongoDB - https://groups.google.com/forum/#!forum/mongodb-user
* OrientDB - https://groups.google.com/forum/#!forum/orient-database
* Tarantool - https://groups.google.com/forum/#!forum/tarantool
