### ISSUE TITLE
problem in running ycsb for benchmarking mongodb

### ISSUE THREAD

**Issue by mydata28** [brianfrankcooper/YCSB#630]
Hi,
I m new with all nosql ,ycsb. I am working on benchmarking mongodb2.6.7 using ycsb 0.2.0 on windows platform. I have mongodb,ycsb on E: drive and python and java on c: drive.

It work with basic database.
E:\ycsb-0.2.0>c:\Python27\python.exe bin\ycsb run basic -P workloads\workloada -
P companies.json -s > companies_out.txt	

But its not working with mongodb. i hv written following command:
E:\ycsb-0.2.0>c:\Python27\python.exe bin\ycsb load mongodb -P workloads\workloada -p mongodb.url=mongodb://localhost:27017 -p mongodb.database=ycsb -p mongodb.writeConcern=strict

which shows---------------------------------------
Command line: -db com.yahoo.ycsb.db.MongoDbClient -P workloads\workloada -p mong
odb.url=mongodb://localhost:27017 -p mongodb.database=ycsb -p mongodb.writeConce
rn=strict -load
Loading workload...
Starting test.
WARNING: Invalid writeConcern: 'strict' will be ignored. Must be one of [ unackn
owledged | acknowledged | journaled | replica_acknowledged | majority ]
Exception in thread "Thread-1" java.lang.NoSuchFieldError: ACKNOWLEDGED
        at com.mongodb.MongoClientOptions$Builder.<init>(MongoClientOptions.java
:687)
        at com.mongodb.MongoClientURI.<init>(MongoClientURI.java:150)
        at com.yahoo.ycsb.db.MongoDbClient.init(MongoDbClient.java:184)
        at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:63)
        at com.yahoo.ycsb.ClientThread.run(Client.java:195)
[OVERALL], RunTime(ms), 16.0
[OVERALL], Throughput(ops/sec), 0.0

I am not getting what is wrong here. Pls help me out .

**Comment by busbey** [comment]
could you try with our most recent release?

**Comment by busbey** [comment]
mongodb specific binaries for 0.6.0:

https://github.com/brianfrankcooper/YCSB/releases/download/0.6.0/ycsb-mongodb-binding-0.6.0.tar.gz

**Comment by mydata28** [comment]
hi,
Thanks for reply. I ll chk it.
But I am having one doubt is version of mongodb and ycsb having any issues??
I have tried with mongodb-async driver load phase WORK
E:\ycsb-0.2.0>c:\Python27\python.exe bin\ycsb load mongodb-async -s -P workloads \workloada > load2.txt
 Its not working with sync
E:\ycsb-0.2.0>c:\Python27\python.exe bin\ycsb load mongodb -s -P workloads \workloada > load2.txt
Command line: -db com.yahoo.ycsb.db.MongoDbClient -s -P workloads\workloada -loa
d
Loading workload...
Starting test.
Exception in thread "Thread-1" java.lang.NoSuchFieldError: ACKNOWLEDGED
        at com.mongodb.MongoClientOptions$Builder.<init>(MongoClientOptions.java
:687)
        at com.mongodb.MongoClientURI.<init>(MongoClientURI.java:150)
        at com.yahoo.ycsb.db.MongoDbClient.init(MongoDbClient.java:184)
        at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:63)
        at com.yahoo.ycsb.ClientThread.run(Client.java:195)
2016-02-23 14:02:21:881 0 sec: 0 operations;
[OVERALL], RunTime(ms), 31.0
[OVERALL], Throughput(ops/sec), 0.0


Why so

**Comment by mydata28** [comment]
For using this binaries should I use ycsb0.6 ??

**Comment by busbey** [comment]
generally speaking, you should use the most recent release unless some incompatible change prevents it.

IIRC, mongodb 2.6.11 was tested for both the normal and async clients for YCSB 0.6.0. @allanbank might have a better idea about your current issue once you try with the latest release.

**Comment by mydata28** [comment]
Thanks busbey...

**Comment by mydata28** [comment]
I am working with mongodb2.6.7 ...so is thre any alternative solution

**Comment by mydata28** [comment]
hi
i have downloaded both new releases. pls can u tell me how to use binaries??

**Comment by kruthar** [comment]
@mydata28 - I ran a command very similar to yours, only difference is the mongodb address because mine is on a VM:

```
bin/ycsb load mongodb -P workloads/workloada -p mongodb.url=mongodb://mongodb.vagrant:27017 -p mongodb.database=ycsb -p mongodb.writeConcern=strict
```

I am using YCSB 0.2.0 and MongoDB 2.6.7 and cannot reproduce your error. Although I did notice that you have an invalid value for ```mongodb.writeConcern```. You can see that from the logs you posted:

>WARNING: Invalid writeConcern: 'strict' will be ignored. Must be one of [ unackn
owledged | acknowledged | journaled | replica_acknowledged | majority ]

I tested MongoDB 2.6.7 on YCSB 0.6.0 and works fine so I would second @busbey in that you try that release. To do that download the MongoDB specific release package @busbey linked: https://github.com/brianfrankcooper/YCSB/releases/download/0.6.0/ycsb-mongodb-binding-0.6.0.tar.gz. Unpack it anywhere on your system. Change into the ```ycsb-mongodb-binding-0.6.0``` directory and run your YCSB commands as usual.

I would also suggest that you fix your writeConcern issue. You can simplify your YCSB command by altering your connection string like this:

```
bin/ycsb load mongodb -P workloads/workloada -p mongodb.url=mongodb://localhost:27017/ycsb?w=1
```

Notice how I specified the database to connect to as well as gave the ```w=1``` property which sets the write concern to acknowledged. More on connection string options: https://docs.mongodb.org/v2.6/reference/connection-string/#connections-connection-options

**Comment by busbey** [comment]
Since you're on windows, also check out our guide on [prerequisites for running on windows](https://github.com/brianfrankcooper/YCSB/wiki/Prerequisites-for-Windows#running-from-a-release)

**Comment by mydata28** [comment]
hi 
Kruthar,
Thanks ..
i ll try with your suggestions.

**Comment by mydata28** [comment]
@kruthar 
i tried 
E:\ycsb-0.2.0>c:\Python27\python.exe bin/ycsb load mongodb -P workloads/workloada -p mongodb.url=mongodb://localhost:27017/ycsb?w=1
still gives error
Starting test.
Exception in thread "Thread-1" java.lang.NoSuchFieldError: ACKNOWLEDGED
        at com.mongodb.MongoClientOptions$Builder.<init>(MongoClientOptions.java
:687)
        at com.mongodb.MongoClientURI.<init>(MongoClientURI.java:150)
        at com.yahoo.ycsb.db.MongoDbClient.init(MongoDbClient.java:184)
        at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:63)
        at com.yahoo.ycsb.ClientThread.run(Client.java:195)
[OVERALL], RunTime(ms), 44.0
[OVERALL], Throughput(ops/sec), 0.0

**Comment by mydata28** [comment]
@busbey 
i have mongodb 2.6.11, ycsb0.6 and ycsb-mongodb-binding-0.6.0.tar.gz. with me.
i run 
 bin\ycsb load mongodb -P workloads\workloada -p mongodb.url=mongodb://localhost:27017/ycsb?w=1;
the result is 
onnectionId{localValue:1, serverValue:2}
OVERALL], RunTime(ms), 3661.0
OVERALL], Throughput(ops/sec), 273.1494127287626
CLEANUP], Operations, 1.0
CLEANUP], AverageLatency(us), 2981.0
CLEANUP], MinLatency(us), 2980.0
CLEANUP], MaxLatency(us), 2981.0
CLEANUP], 95thPercentileLatency(us), 2981.0
CLEANUP], 99thPercentileLatency(us), 2981.0
INSERT], Operations, 1000.0
INSERT], AverageLatency(us), 2965.421
INSERT], MinLatency(us), 1175.0
INSERT], MaxLatency(us), 697855.0
INSERT], 95thPercentileLatency(us), 3455.0
INSERT], 99thPercentileLatency(us), 5095.0
INSERT], Return=OK, 1000

now am i on right track??

**Comment by mydata28** [comment]
how to check performance of mongodb for different databases/collections.

**Comment by kruthar** [comment]
@mydata - Yes, it looks like you latest run has completed successfully.

> how to check performance of mongodb for different databases/collections.

I'm not sure what you mean. Do you mean how do you compare results of benchmarking MongoDB against other databases? Or do you mean how do you run YCSB against a different MongoDB database? or something else?

**Comment by mydata28** [comment]
@Andy
if I have a different databases with different size in mongodb like

>show dbs
   test1  (700mb)
   test2  (1 Gb)
   test3  (1.5GB)

can I check performance of mongodb for above 3 different databases.
performance of mongodb for loading and running <test1>
performance of mongodb for loading and running <test2>
performance of mongodb for loading and running <test3>




On Wed, Feb 24, 2016 at 7:31 PM, Andy Kruth <notifications@github.com>
wrote:

> @mydata <https://github.com/mydata> - Yes, it looks like you latest run
> has completed successfully.
>
> how to check performance of mongodb for different databases/collections.
>
> I'm not sure what you mean. Do you mean how do you compare results of
> benchmarking MongoDB against other databases? Or do you mean how do you run
> YCSB against a different MongoDB database? or something else?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianfrankcooper/YCSB/issues/630#issuecomment-188266822>
> .
>



-- 
Mrs.Rohini Gaikwad
Assistant Professor (MCA)
VIIT, Baramati.
Pune, Maharashtra.

**Comment by kruthar** [comment]
Yes, you can. The connection string you specify with ```mongodb.url``` contains the database name. From your examples above you are using the ```ycsb``` database currently. So, to test multiple databases on the same MongoDB cluster, just change the database name in the connection string.

Are test1, test2, and test3 just example names? Or are those preexisting databases with preexisting data? If the latter then is that data that is already there inserted from YCSB? If not I would caution that any extra data that is already present may effect your benchmark in unexpected ways.

**Comment by mydata28** [comment]
yes i would like to try with the exsting databases with data in mongodb cluster.
Is it possible

**Comment by mydata28** [comment]
test1, test2 are just examples.
I m planning about  importing data of agriculture sector in mongodb .Then testing different workloads for it.
Am i on right track

**Comment by kruthar** [comment]
>yes i would like to try with the exsting databases with data in mongodb cluster.
Is it possible

Yes, using existing databases is possible. Just specify the database name you want to use in the connection string.

>I m planning about importing data of agriculture sector in mongodb .Then testing different workloads for it.
Am i on right track

YCSB only performs operations against data that was inserted with YCSB. It is OK to have your own data in the database, YCSB will still work, but I would not advise it for these reasons:

* You will be adding a bunch of arbitrary data to an existing database, this may effect the performance or functionality of your existing applications connected to that database.
* YCSB does not operate on any data except for the data YCSB itself has inserted. So, adding your own data does not conceptually change your benchmark.
* Adding your own data to the database will almost certainly affect the performance of the benchmark in ways that may not be expected or measurable.

The fact that you are adding agricultural data into your database doesn't mean anything. By doing that you ARE NOT benchmarking a system similar to an agricultural application because YCSB doesn't care about the data in your database. I just want to make that clear.

**Comment by mydata28** [comment]
@kruthar 
HI,
Then how can I do this.
Whats the other solution to check the performance of database(Mongodb) for different databases(test1,test2..)

**Comment by kruthar** [comment]
I'm sorry if I am not clear. I am telling you that benchmarking against multiple existing databases IS possible. Just specify the database name in the connection string:

```
bin\ycsb load mongodb -P workloads\workloada -p mongodb.url=mongodb://localhost:27017/test1?w=1;
```

**Comment by risdenk** [comment]
@mydata28 YCSB has 2 main phases:
1. load data
2. execute workload
(outlined in more detail here (https://github.com/brianfrankcooper/YCSB/wiki/Running-a-Workload)

For YCSB to function, no matter which database YCSB is pointed at, YCSB loads data and then YCSB can execute the workload on that data. YCSB only works on data that it has loaded during the load phase. Having data that YCSB did NOT load in the databases will not be tested by YCSB. YCSB is not designed to test against your specific data. It is only designed to load test and perform some certain types of predefined data. The data that is loaded can be modified to change a few properties like number of records, data size, and some other parameters (https://github.com/brianfrankcooper/YCSB/wiki/Core-Properties#core-workload-package-properties).

**Comment by mydata28** [comment]
Kevin,
Thank u ...


On Thu, Mar 3, 2016 at 11:21 PM, Kevin Risden <notifications@github.com>
wrote:

> @mydata28 <https://github.com/mydata28> YCSB has 2 main phases:
> 1. load data
> 2. execute workload
> (outlined in more detail here (
> https://github.com/brianfrankcooper/YCSB/wiki/Running-a-Workload)
>
> For YCSB to function, no matter which database YCSB is pointed at, YCSB
> loads data and then YCSB can execute the workload on that data. YCSB only
> works on data that it has loaded during the load phase. Having data that
> YCSB did NOT load in the databases will not be tested by YCSB. YCSB is not
> designed to test against your specific data. It is only designed to load
> test and perform some certain types of predefined data. The data that is
> loaded can be modified to change a few properties like number of records,
> data size, and some other parameters (
> https://github.com/brianfrankcooper/YCSB/wiki/Core-Properties#core-workload-package-properties
> ).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianfrankcooper/YCSB/issues/630#issuecomment-191884897>
> .
>



-- 
Mrs.Rohini Gaikwad
Assistant Professor (MCA)
VIIT, Baramati.
Pune, Maharashtra.

**Comment by mydata28** [comment]
Andy,
Thanks .


On Thu, Mar 3, 2016 at 8:22 AM, Andy Kruth <notifications@github.com> wrote:

> I'm sorry if I am not clear. I am telling you that benchmarking against
> multiple existing databases IS possible. Just specify the database name in
> the connection string:
>
> bin\ycsb load mongodb -P workloads\workloada -p mongodb.url=mongodb://localhost:27017/test1?w=1;
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianfrankcooper/YCSB/issues/630#issuecomment-191553104>
> .
>



-- 
Mrs.Rohini Gaikwad
Assistant Professor (MCA)
VIIT, Baramati.
Pune, Maharashtra.

**Comment by mydata28** [comment]
I resolved my problem.
Thanks to all...

**Comment by sirimeraoui** [comment]
> I resolved my problem. Thanks to all...

Hello, were you able to find a workaround to benchmark your own data with YCSB?
