### ISSUE TITLE
Repo description link is dead

### ISSUE THREAD

**Issue by risdenk** [brianfrankcooper/YCSB#637]
This was pointed out on a reply from someone who saw the YCSB 0.7.0 release email.

```
Yahoo! Cloud Serving Benchmark http://research.yahoo.com/Web_Information_Management/YCSB
```

That link is dead and should point to: https://labs.yahoo.com/news/yahoo-cloud-serving-benchmark/

@busbey @brianfrankcooper - Do you have permissions to change that link in the repo description?

**Comment by busbey** [comment]
Just @brianfrankcooper AFAIK. I took care of what I could with #623. I'd send him an email.

**Comment by risdenk** [comment]
I sent an email to @brianfrankcooper waiting on a response. The link (https://labs.yahoo.com/news/yahoo-cloud-serving-benchmark/) that was dead now redirects to https://yahooresearch.tumblr.com/post/139436148571/yahoos-new-research-model

**Comment by risdenk** [comment]
Closing due to new report #823

**Comment by risdenk** [comment]
Seems to be ok right now.
