### ISSUE TITLE
Is recordcount and operationcount always 1000?

### ISSUE THREAD

**Issue by raimonbosch** [brianfrankcooper/YCSB#638]
Hi,

I'm trying to play with the YCSB benchmark by modifying recordcount and operationcount i.e.

  /ycsb/bin/ycsb load cassandra-10 -P /ycsb/workloads/workloada -p hosts=172.17.0.2 -p operationcount=1000000 -p recordcount=1000000

The output I get is the folowing:
  ...
  [INSERT], 991, 0
  [INSERT], 992, 0
  [INSERT], 993, 0
  [INSERT], 994, 0
  [INSERT], 995, 0
  [INSERT], 996, 0
  [INSERT], 997, 0
  [INSERT], 998, 0
  [INSERT], 999, 0
  [INSERT], >1000, 0

I suppose that internally it is really inserting 1.000.000 of records, but I don't understand why I get this output. Is this correct?

**Comment by kruthar** [comment]
@raimonbosch - what version of YCSB are you using? Can you point me towards any guide you are following to do your benchmark?

That output is not the default anymore, I would suggest updating your YCSB version: https://github.com/brianfrankcooper/YCSB/releases, the new default is more readable.

That is the histogram output style. In a nutshell all of the operation times are put into a histogram and output at the end of the workload. So, what you can see from what yo posted is that there were 0 operations that took 991, 992,..., 1000 milliseconds. If you were to look at the beginning of the histogram you would see a lot of counts on the smaller numbers of the histogram.

What version of Cassandra are you working with? The `cassandra-10` binding is for older versions of Cassandra, so just want to make sure you are using the correct binding.

Can you send me a link to the guide or tutorial that you are using to do your YCSB benchmark? Thanks a lot.

**Comment by raimonbosch** [comment]
I see. I didn't understood that this was an histogram. Then it makes sense. Here is the benchmark if you want to check: http://cloudsuite.ch/dataserving/ 
(haven't found a --version option to check YCSB version)

**Comment by kruthar** [comment]
I don't think there is a version flag, sounds like a good feature request!

I checked out cloudsuite, thanks for the link. I couldn't find any documentation or listing on versions that they are using for Cassandra or YCSB.

Both of them are old versions, that's not necessarily an issue if they work together, just something to be aware of.

**Comment by busbey** [comment]
we currently print an incorrect version string on every launch, see #320

**Comment by risdenk** [comment]
@raimonbosch The versions aren't listed but the link you provided shows running YCSB from the Docker image `cloudsuite/data-serving:client`. I can't find the Dockerfile that generated that and the link to their Github account is dead (https://github.com/CloudSuite-EPFL/DataServing/tree/master). If you want to update to the latest release version of YCSB 0.7.0 or Cassandra) then you need to build new Docker images.

For reference it looks like that image is running YCSB 0.3.0:
```
docker run --rm -it cloudsuite/data-serving:client bash -c 'ls -l /ycsb/lib/core-*.jar'
-rw-r--r-- 1 1000 users 1184196 Aug  8  2015 /ycsb/lib/core-0.3.0.jar
```

**Comment by raimonbosch** [comment]
Seems that it is using 0.3.0. Here is the updated Dockerfile: https://github.com/ParsaLab/cloudsuite/blob/master/benchmarks/data-serving/client/Dockerfile

**Comment by risdenk** [comment]
@raimonbosch - The original question about the output always being 1000 was answered by @kruthar here https://github.com/brianfrankcooper/YCSB/issues/638#issuecomment-191014575. Did that help?

**Comment by raimonbosch** [comment]
Yes, of course. I guess you can close the issue. Thanks!

**Comment by risdenk** [comment]
@raimonbosch great. Feel free to open a new issue if you have more questions.

**Comment by raimonbosch** [comment]
Furthermore, I was missing information provided by "-s" option. Which gives you information about avg operations/sec during execution.
