### ISSUE TITLE
READ-FAILED operation?

### ISSUE THREAD

**Issue by kamsz** [brianfrankcooper/YCSB#639]
Hi,

I'm receiving such entries in YCSB log:

```
2016-03-02 14:58:23:453 100 sec: 97621 operations; 912.3 current ops/sec; est completion in 1 minutes [READ AverageLatency(us)=10945.5] [UPDATE AverageLatency(us)=3496.61] [READ-FAILED AverageLatency(us)=4593.01] 
2016-03-02 14:58:23:453 100 sec: 97621 operations; 912.3 current ops/sec; est completion in 1 minutes [READ AverageLatency(us)=10945.5] [UPDATE AverageLatency(us)=3496.61] [READ-FAILED AverageLatency(us)=4593.01] 
2016-03-02 14:58:33:453 110 sec: 107778 operations; 1015.7 current ops/sec; est completion in 1 minutes [READ AverageLatency(us)=9686.13] [UPDATE AverageLatency(us)=3453.05] [READ-FAILED AverageLatency(us)=4478.34] 
2016-03-02 14:58:33:453 110 sec: 107778 operations; 1015.7 current ops/sec; est completion in 1 minutes [READ AverageLatency(us)=9686.13] [UPDATE AverageLatency(us)=3453.05] [READ-FAILED AverageLatency(us)=4478.34] 
2016-03-02 14:58:43:453 120 sec: 117358 operations; 958 current ops/sec; est completion in 1 minutes [READ AverageLatency(us)=10317.59] [UPDATE AverageLatency(us)=3562.18] [READ-FAILED AverageLatency(us)=4896.01] 
2016-03-02 14:58:43:453 120 sec: 117358 operations; 958 current ops/sec; est completion in 1 minutes [READ AverageLatency(us)=10317.59] [UPDATE AverageLatency(us)=3562.18] [READ-FAILED AverageLatency(us)=4896.01] 
2016-03-02 14:58:53:453 130 sec: 126732 operations; 937.4 current ops/sec; est completion in 1 minutes [READ AverageLatency(us)=10497.2] [UPDATE AverageLatency(us)=3673.27] [READ-FAILED AverageLatency(us)=4770.35] 
2016-03-02 14:58:53:453 130 sec: 126732 operations; 937.4 current ops/sec; est completion in 1 minutes [READ AverageLatency(us)=10497.2] [UPDATE AverageLatency(us)=3673.27] [READ-FAILED AverageLatency(us)=4770.35] 
```

What does READ-FAILED mean? Is this bad? If so, how can I fix that?

**Comment by kruthar** [comment]
Yes, in general ```READ_FAILED``` is bad. It means for what ever reason YCSB was not able to perform a read operation it attempted. Can you please post the command you ran, all of the output (if it is not too long), and any workload files you are using if you have modified them?

**Comment by kamsz** [comment]
Output is almost 92k lines long :)

Used commands:
```
/opt/ycsb-0.7.0/bin/ycsb load cassandra2-cql -s -P /opt/tests/workload -target 1500 -p measurementtype=timeseries -threads 8 -p recordcount=600000 -p cassandra.readconsistencylevel=QUORUM -p cassandra.writeconsistencylevel=QUORUM -p cassandra.scanconsistencylevel=QUORUM -p cassandra.deleteconsistencylevel=QUORUM -p insertcount=200000 -p insertstart=0 -p hosts=10.251.9.165,10.251.9.164,10.251.9.159
/opt/ycsb-0.7.0/bin/ycsb run cassandra2-cql -s -P /opt/tests/workload -target 1500 -p measurementtype=timeseries -threads 8 -p recordcount=600000 -p cassandra.readconsistencylevel=QUORUM -p cassandra.writeconsistencylevel=QUORUM -p cassandra.scanconsistencylevel=QUORUM -p cassandra.deleteconsistencylevel=QUORUM -p insertcount=200000 -p insertstart=0 -p maxexecutiontime=6000 -p operationcount=2100000 -p hosts=10.251.9.165,10.251.9.164,10.251.9.159
```

Workload file:
```
workload=com.yahoo.ycsb.workloads.CoreWorkload
fieldcount=20
fieldlength=255
readallfields=True
writeallfields=True

readproportion=0.75
updateproportion=0.25
scanproportion=0
insertproportion=0

requestdistribution=zipfian
operationcount=2100000
recordcount=600000
```

**Comment by risdenk** [comment]
@kamsz Are you sure that you have your Cassandra cluster configured properly? The exception you posted says `2 responses were required but only 1 replica responded`. This is causing the reads to fail since not all the replicas are responding.

**Comment by kamsz** [comment]
@risdenk I went with default Cassandra configuration (3 node and 5 node setups). Nothing interesting in logs except
```
│DEBUG [SharedPool-Worker-12] 2016-03-03 18:07:50,161 StorageProxy.java:1462 - Read timeout; received 1 of 2 responses
```

**Comment by kruthar** [comment]
@kamsz - so, it looks like some of the read operations are succeeding, since you have ```READ``` latency numbers. Can you confirm that by posting the final printout after the entire benchmark has finished? There should be some final output.

If some reads succeed and some don't then you might be exceeding a comfortable load level of your Cassandra cluster.

Checkout the Read Consistency table here: http://docs.datastax.com/en/cassandra/2.0/cassandra/dml/dml_config_consistency_c.html
The QUORUM level reads:

>Ensures strong consistency if you can tolerate some level of failure.

So, you have high consistency, but potentially with some expected failure since Cassandra must meet a Quorum before returning you an answer, or just not returning you an answer which seems like is happening here. You might try fiddling with ```-p cassandra.readtimeoutmillis```, making this longer may give Cassandra more opportunity to return a quorum on reads.

You might also be able confirm that you have passed the comfortable load threshold if by running smaller workloads (less operations + less threads) runs successfully with no issues.

>Forgot to add, I'm running 1:1 YCSB/Cassandra ratio. Perhaps that's the issue?
>
>Edit: Tried wih 1:2 YCSB/Cassandra ratio, same result.

Can you explain what you mean by this? do you have multiple instances of YCSB running? 1 instance of YCSB for each node of Cassandra?

**Comment by kamsz** [comment]
@kruthar Yes, I've several YCSB instances that are stressing Cassandra cluster. From the summary log for  I'm getting:
* 211438 READ-FAILED operations,
* 275771 UPDATE operations,
* 612790 READ operations.
* 864 operations/second

I've lowered operation count, but I'm still getting READ-FAILED operations...

**Comment by kruthar** [comment]
Are you all the YCSB instances at the same time? with the same command I presume?

By how much did you lower the operation count?

**Comment by kamsz** [comment]
@kruthar Yup, same command, but I split insertstart based on YCSB instances. I've lowered operation count to 1100000.

**Comment by kruthar** [comment]
So, 1100000 operations, 8 threads, 3 instances of YCSB is still a very large test. If you run a test that is maybe just one instance of YCSB running on one thread, do you have the same issues.

Did you try ```cassandra.readtimeoutmillis```?

What I'm trying to get at here is that what it looks like is that there is actually no problem happening, that you have simply surpassed your Cassandra cluster's capability. Keep trying to lower your benchmarks and see at what point you don't have any issues anymore.

**Comment by kamsz** [comment]
@kruthar the results are the same However, I've noticed that the number of the READ-FAILED operations is equal to actual successful reads, but with NOT_FOUND response. Is there any way to diagnose why there's NOT_FOUND status in these reads?

**Comment by risdenk** [comment]
@kamsz - Which version of YCSB are you using? Is the load phase working correctly?

**Comment by kruthar** [comment]
@kamsz - can you try with an easier read consistency? say ```cassandra.readconsistencylevel=ONE```, which is the default. If you don't see issues with ```ONE``` as the consistency level then that would seem to tell me that your Cassandra cluster cannot keep up with the load because it is having to wait to long on each read request.

And just to be clear, you said that the results were the same when you tried to increase ```cassandra.readtimeoutmillis```? What did you try to increase it to?

**Comment by kamsz** [comment]
@kruthar @risdenk I've resolved the issue... the problem was field_length in workload file - apparently it doesn't like 255 value. When I lowered that to 250, everything started to work.
