### ISSUE TITLE
Load thread

### ISSUE THREAD

**Issue by cgara** [brianfrankcooper/YCSB#642]
When using threads 10 workload is multiplied by 10? Or each thread receives a proportional fraction of the workload?

Thank you

**Comment by kruthar** [comment]
Each thread will receive a tenth of the operation count you have set.

**Comment by cgara** [comment]
Thank you

**Comment by risdenk** [comment]
@cgara - If this issue is resolved can this be closed? Thanks.

**Comment by cgara** [comment]
Yes, thank you!!
