### ISSUE TITLE
Write heavy workload

### ISSUE THREAD

**Issue by akmalabbasov** [brianfrankcooper/YCSB#643]
Hi, I'd like to benchmark HBase write performance on different hardware configurations. Which workload file should I use in order to test write performance?
Thank you

**Comment by risdenk** [comment]
Descriptions of workloads are available here:
* https://github.com/brianfrankcooper/YCSB/wiki/Core-Workloads
* https://github.com/brianfrankcooper/YCSB/wiki/Implementing-New-Workloads

You may be able to test just the load phase if that is all that is important to you.

**Comment by busbey** [comment]
any more questions @akmalabbasov?

**Comment by akmalabbasov** [comment]
@busbey no, as suggested by risdenk, I've used loading phase to measure write performance. Thank you.

**Comment by baiwfg2** [comment]
@risdenk Workloada has a mix of 50/50 reads and writes. I don't understand why it's a update heavy workload. I think write/read = 90:10 is write heavy, but 50:50 isn't. Is it ?
