### ISSUE TITLE
Insert Redis

### ISSUE THREAD

**Issue by cgara** [brianfrankcooper/YCSB#645]
Para o benchmark com o SGBD Redis, são inseridos os registros de uma frma sequencial ou gera um arquivo de texto contendo o protocolo Redis?

Thank you

**Comment by risdenk** [comment]
@cgara - I don't speak Portugese but put your question into Google translate and got the following:
> For the benchmark with the DBMS Redis , they are inserted records in a sequential manner or creates a text file containing the Redis protocol?

YCSB during the load phase rows for any DB binding inserts records directly to the database. There is no text file generated. The records are inserted based on properties described here:

https://github.com/brianfrankcooper/YCSB/wiki/Core-Properties#core-workload-package-properties

**Comment by cgara** [comment]
Thank you!
