### ISSUE TITLE
Fail to load data. Exception: fails to use maven on windows

### ISSUE THREAD

**Issue by cindywang** [brianfrankcooper/YCSB#655]
Hi there, 

I have an issue of load data.

**OS: windows 7
Apache Maven 3.3.9
Cassandra 3.4
YCSB 0.7.0
**

Build successfully. Added _C:\Program Files\YCSB\cassandra2\target;C:\Program Files\DataStax-DDC\apache-cassandra\lib_ in my system environment variable.
Tried ./bin/ycsb then help lunched. But "./bin/ycsb shell basic" doesn't work
Error message:
**$ ./ycsb shell basic**
[WARN]  Running against a source checkout. In order to get our runtime dependencies we'll have to invoke Maven. Depending on the state of your system, this may take ~30-45 seconds
[DEBUG]  Running 'mvn -pl com.yahoo.ycsb:core -am package -DskipTests dependency:build-classpath -DincludeScope=compile -Dmdep.outputFilterFile=true'
Traceback (most recent call last):
  File "./ycsb", line 259, in <module>
    sys.exit(main())
  File "./ycsb", line 232, in main
    maven_says = get_classpath_from_maven(project)
  File "./ycsb", line 178, in get_classpath_from_maven
    + err.output)
TypeError: cannot concatenate 'str' and 'NoneType' objects

**$ ./ycsb load cassandra-cql -p hosts="192.168.xxx.xx" -P workloads/workloada -s > workloada_load_res.txt**
[WARN]  Running against a source checkout. In order to get our runtime dependencies we'll have to invoke Maven. Depending on the state of your system, this may take ~30-45 seconds
[DEBUG]  Running 'mvn -pl com.yahoo.ycsb:cassandra-binding -am package -DskipTests dependency:build-classpath -DincludeScope=compile -Dmdep.outputFilterFile=true'
Traceback (most recent call last):
  File "./ycsb", line 259, in <module>
    sys.exit(main())
  File "./ycsb", line 232, in main
    maven_says = get_classpath_from_maven(project)
  File "./ycsb", line 178, in get_classpath_from_maven
    + err.output)
TypeError: cannot concatenate 'str' and 'NoneType' objects

Could anybody help me out? Was it because of the version of Cassandra? If so, which version I should switch to? Any suggestions or comments are highly appreciated. 

Struggling for a long time... Many thanks!!!

**Comment by risdenk** [comment]
@cindywang Is this the same thing that was just posted on #335?

**Comment by cindywang** [comment]
@risdenk Yes, I tried `cassandra2-cql` instead and it still failed to load the data. So I think it is probably because of the version. Would it be okay if switch to 2.2+?

**Comment by risdenk** [comment]
For future reference, double posting won't help get the answer any faster.

Did you use the 0.7.0 release as outlined by @busbey when trying cassandra2-cql? The output you pasted is from a source checkout.

**Comment by cindywang** [comment]
@risdenk  thanks for your reply and I am so sorry about this. I thought the problem is different with #335. 

Here is what I got after executed from 0.7.0 release.
**$ ./ycsb shell basic**
C:\Program Files\Java\jdk1.8.0_73/bin/java -cp /cygdrive/c/Program Files/ycsb-0.7.0/basic-binding/conf:/cygdrive/c/Program Files/ycsb-0.7.0/conf:/cygdrive/c/Program Files/ycsb-0.7.0/lib/core-0.7.0.jar:/cygdrive/c/Program Files/ycsb-0.7.0/lib/HdrHistogram-2.1.4.jar:/cygdrive/c/Program Files/ycsb-0.7.0/lib/jackson-core-asl-1.9.4.jar:/cygdrive/c/Program Files/ycsb-0.7.0/lib/jackson-mapper-asl-1.9.4.jar com.yahoo.ycsb.CommandLine -db com.yahoo.ycsb.BasicDB
Error: Could not find or load main class com.yahoo.ycsb.CommandLine

**Administrator@xxx /cygdrive/c/Program Files/ycsb-0.7.0/bin
$ ./ycsb load cassandra2-cql -p hosts="192.168.xxx.xx" -P workloads/workloada -s > workloada_load_res.txt**
C:\Program Files\Java\jdk1.8.0_73/bin/java -cp /cygdrive/c/Program Files/ycsb-0.7.0/cassandra2-binding/conf:/cygdrive/c/Program Files/ycsb-0.7.0/conf:/cygdrive/c/Program Files/ycsb-0.7.0/lib/core-0.7.0.jar:/cygdrive/c/Program Files/ycsb-0.7.0/lib/HdrHistogram-2.1.4.jar:/cygdrive/c/Program Files/ycsb-0.7.0/lib/jackson-core-asl-1.9.4.jar:/cygdrive/c/Program Files/ycsb-0.7.0/lib/jackson-mapper-asl-1.9.4.jar:/cygdrive/c/Program Files/ycsb-0.7.0/cassandra2-binding/lib/cassandra-driver-core-2.1.8.jar:/cygdrive/c/Program Files/ycsb-0.7.0/cassandra2-binding/lib/cassandra2-binding-0.7.0.jar:/cygdrive/c/Program Files/ycsb-0.7.0/cassandra2-binding/lib/guava-14.0.1.jar:/cygdrive/c/Program Files/ycsb-0.7.0/cassandra2-binding/lib/metrics-core-3.0.2.jar:/cygdrive/c/Program Files/ycsb-0.7.0/cassandra2-binding/lib/netty-buffer-4.0.27.Final.jar:/cygdrive/c/Program Files/ycsb-0.7.0/cassandra2-binding/lib/netty-codec-4.0.27.Final.jar:/cygdrive/c/Program Files/ycsb-0.7.0/cassandra2-binding/lib/netty-common-4.0.27.Final.jar:/cygdrive/c/Program Files/ycsb-0.7.0/cassandra2-binding/lib/netty-handler-4.0.27.Final.jar:/cygdrive/c/Program Files/ycsb-0.7.0/cassandra2-binding/lib/netty-transport-4.0.27.Final.jar:/cygdrive/c/Program Files/ycsb-0.7.0/cassandra2-binding/lib/slf4j-api-1.6.4.jar com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.CassandraCQLClient -p hosts=192.168.xxx.xx -P workloads/workloada -s -load
Error: Could not find or load main class com.yahoo.ycsb.Client

**Comment by risdenk** [comment]
@cindywang Can you extract YCSB in a folder without spaces and try again? From the output you posted it looks like the classpath has spaces in it.

**Comment by cindywang** [comment]
Hi, I tried the path below directly under c:/. Still, `./ycsb` works fine yet `./ycsb shell basic` not.

**Administrator@bicass2 /cygdrive/c/ycsb-0.7.0/bin
$ ./ycsb shell basic**
C:\Program Files\Java\jdk1.8.0_73/bin/java -cp /cygdrive/c/ycsb-0.7.0/basic-binding/conf:/cygdrive/c/ycsb-0.7.0/conf:/cygdrive/c/ycsb-0.7.0/lib/core-0.7.0.jar:/cygdrive/c/ycsb-0.7.0/lib/HdrHistogram-2.1.4.jar:/cygdrive/c/ycsb-0.7.0/lib/jackson-core-asl-1.9.4.jar:/cygdrive/c/ycsb-0.7.0/lib/jackson-mapper-asl-1.9.4.jar com.yahoo.ycsb.CommandLine -db com.yahoo.ycsb.BasicDB
Error: Could not find or load main class com.yahoo.ycsb.CommandLine

**Comment by risdenk** [comment]
Try running the ycsb command from ycsb-0.7.0 instead of in bin/. The invocation would be `bin/ycsb` instead of `./ycsb`

**Comment by cmatser** [comment]
This looks like a windows path issue to me.  When invoking a java program on windows, the jar paths are usually separated by semicolons with the entire path string in quotes.  So this command should read something like:

C:\Program Files\Java\jdk1.8.0_73/bin/java -cp "/cygdrive/c/ycsb-0.7.0/basic-binding/conf;/cygdrive/c/ycsb-0.7.0/conf;/cygdrive/c/ycsb-0.7.0/lib/core-0.7.0.jar;/cygdrive/c/ycsb-0.7.0/lib/HdrHistogram-2.1.4.jar;/cygdrive/c/ycsb-0.7.0/lib/jackson-core-asl-1.9.4.jar;/cygdrive/c/ycsb-0.7.0/lib/jackson-mapper-asl-1.9.4.jar" com.yahoo.ycsb.CommandLine -db com.yahoo.ycsb.BasicDB

**Comment by busbey** [comment]
It looks like you're running in cygwin. Can you try running in a normal command prompt?

**Comment by cindywang** [comment]
Hi, thanks for reply. I tried in command prompt before I switched to cygwin since it didn't work. I did that again and same output:
c:\Program Files\YCSB\bin>ycsb
'ycsb' is not recognized as an internal or external command, operable program or batch file.

So I am wondering if it is because of the windows path issue just like @cmatser mentioned? But I still don't get why cygwin worked with `./ycsb` but not `./ycsb shell basic` or anything else.

Any other suggestions? Thanks again!

**Comment by busbey** [comment]
Hi Cindy!

You should still be attempting to run from the `YCSB` directory and not the `YCSB/bin` directory. From that directory, the correct command to run (presuming Python is installed at `C:\Python27`) is:

```bash
C:\Python27\python.exe bin\ycsb load basic -P workloads\workloada -p recordcount=4
```

It will probably help if you step through [our guide for running a release on Windows](https://github.com/brianfrankcooper/YCSB/wiki/Prerequisites-for-Windows#running-from-a-release) to make sure you have the correct prerequisites and are using the correct commands.

**Comment by cindywang** [comment]
Hi @busbey, Thank you very much for your help. I tried the way as mentioned in the above link. And it does worked with 'basic'. But when I tried to load data to cassandra, it failed. 
I have 3 cassandra nodes and I was running YCSB on one of them. Besides, I followed the instruction [Apache Cassandra 2.x CQL binding ](https://github.com/brianfrankcooper/YCSB/tree/master/cassandra2) and created keyspace `ycsb` as well as table `usertable`.

Could you please help take a look at the following error messages? Is there any problem with my cassandra DB configuration or the parameters declared to pass to YCSB?

Many thanks!!!

c:\ycsb-0.7.0>C:\Python27\python.exe bin\ycsb load cassandra2-cql -p hosts="192.
168.108.10" -P workloads/workloada -s > workloada_load_res.txt
C:\Program Files\Java\jdk1.8.0_73\bin\java -cp c:\ycsb-0.7.0\cassandra2-binding\
conf;c:\ycsb-0.7.0\conf;c:\ycsb-0.7.0\lib\core-0.7.0.jar;c:\ycsb-0.7.0\lib\HdrHi
stogram-2.1.4.jar;c:\ycsb-0.7.0\lib\jackson-core-asl-1.9.4.jar;c:\ycsb-0.7.0\lib
\jackson-mapper-asl-1.9.4.jar;c:\ycsb-0.7.0\cassandra2-binding\lib\cassandra-dri
ver-core-2.1.8.jar;c:\ycsb-0.7.0\cassandra2-binding\lib\cassandra2-binding-0.7.0
.jar;c:\ycsb-0.7.0\cassandra2-binding\lib\guava-14.0.1.jar;c:\ycsb-0.7.0\cassand
ra2-binding\lib\metrics-core-3.0.2.jar;c:\ycsb-0.7.0\cassandra2-binding\lib\nett
y-buffer-4.0.27.Final.jar;c:\ycsb-0.7.0\cassandra2-binding\lib\netty-codec-4.0.2
7.Final.jar;c:\ycsb-0.7.0\cassandra2-binding\lib\netty-common-4.0.27.Final.jar;c
:\ycsb-0.7.0\cassandra2-binding\lib\netty-handler-4.0.27.Final.jar;c:\ycsb-0.7.0
\cassandra2-binding\lib\netty-transport-4.0.27.Final.jar;c:\ycsb-0.7.0\cassandra
2-binding\lib\slf4j-api-1.6.4.jar com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.Ca
ssandraCQLClient -p hosts=192.168.108.10 -P workloads/workloada -s -load
**Loading workload...
Starting test.**
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further detail
s.
2016-03-22 14:25:52:232 0 sec: 0 operations; est completion in 0 seconds
com.yahoo.ycsb.DBException: com.datastax.driver.core.exceptions.NoHostAvailableE
xception: All host(s) tried for query failed (tried: /192.168.108.10:9042 (com.d
atastax.driver.core.exceptions.InvalidQueryException: **unconfigured table schema_
keyspaces))**
        at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:193
)
        at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:77)
        at com.yahoo.ycsb.ClientThread.run(Client.java:289)
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All hos
t(s) tried for query failed (tried: /192.168.108.10:9042 (com.datastax.driver.co
re.exceptions.InvalidQueryException: unconfigured table schema_keyspaces))
        at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlC
onnection.java:227)
        at com.datastax.driver.core.ControlConnection.connect(ControlConnection.
java:86)
        at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1409)
        at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:382)
        at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:180
)
        ... 2 more
2016-03-22 14:25:54:594 2 sec: 0 operations; est completion in 106751991167300 d
ays 15 hours

**Comment by busbey** [comment]
What version of Cassandra?

If your Cassandra cluster is 3 nodes, I believe you're supposed to give all three in the "--hosts=" cli option.

**Comment by cindywang** [comment]
I am using Cassandra 3.4 on windows 7. But isn't cli been deprecated after 2.0+, is it? Could you please describe this in more details? I already give the _seed _node in all of the configuration files and `./nodetool status` works fine. it's all set.

**Comment by busbey** [comment]
Ah. your failure is because the driver we use to talk to Cassandra doesn't work with Cassandra 3. #614  is the issue tracking the update needed.

**Comment by cindywang** [comment]
Oh, ok. Thank you very much for all the help. 

And do you have any suggestion on which the most stable version of Cassandra is that I should use to perfectly suit with YCSB. I have been struggling for a long time..

Thanks again!

**Comment by busbey** [comment]
If you check the [release notes for e.g. 0.7.0](https://github.com/brianfrankcooper/YCSB/releases/tag/0.7.0) the "Tested supported" section lists the specific version(s) that were checked against in the release vetting.

**Comment by cindywang** [comment]
Sure, thanks a lot for the help!! 

Should I close this question or leave it?

**Comment by busbey** [comment]
Happy to help. I can close the ticket. If you have another question, please open a new issue.
