### ISSUE TITLE
Hi there, what's the difference between READ and SCAN the workload

### ISSUE THREAD

**Issue by amirjuve** [brianfrankcooper/YCSB#658]

**Comment by busbey** [comment]
Read retrieves a particular key. Scan retrieves a range of keys that are contiguous.

**Comment by amirjuve** [comment]
Thanks for your reply, would you to explain more

**Comment by amirjuve** [comment]
@busbey  so SCAN works with the globality ?

**Comment by amirjuve** [comment]
@busbey  Thanks

**Comment by busbey** [comment]
happy to help! let us know if you have any more questions.
