### ISSUE TITLE
large.dat doesn't override recorcount property 

### ISSUE THREAD

**Issue by amirjuve** [brianfrankcooper/YCSB#659]
when i run the default workloada : 
./bin/ycsb run mongodb -P workloads/workloada -P large.dat -s > transactions.dat

i got 1000 operation done, that means recordcount property is not overrided by large.dat (recordcount =10000).
Any solution, thanks in advance.

**Comment by cmatser** [comment]
You want to change operationcount property.

**Comment by amirjuve** [comment]
thanks bro
