### ISSUE TITLE
Cassandra drivers for Datastax 4.6 

### ISSUE THREAD

**Issue by inderjeet-sandy** [brianfrankcooper/YCSB#661]
I'm wondering where could I find the Java drivers for Cassandra Datastax 4.6 to run YSCB benchmark against 4.6 Datastax Cassandra Cluster.

On Datastax site , i can see the drivers for version 3.0. Will that work with 4.6?

Appreciate your help and support on this.

**Comment by busbey** [comment]
The PR you'll want to watch is #614. That's our current path to updating to the datastax driver version 3.

According to the driver's [release notes](http://docs.datastax.com/en/latest-java-driver/java-driver/whatsNew2.html), it is expected to work with Apache Cassandra 1.2+ and Datastax Enterprise 3.1+.

I presume that means it ought to work with Datastax Enterprise 4.6, though we only currently test with Apache Cassandra, so I don't know how much help we'd be debugging a problem with Datastax's commercial offering.

AFAIK, Apache Cassandra has no 4.y release line, so I'm guessing Datastax Enterprise is what you mean. If that's not the case I can look about some more.

**Comment by risdenk** [comment]
Relates to issue #612

**Comment by risdenk** [comment]
@inderjeet-sandy this should be fixed in master now. You'll have to compile YCSB from source to try it. Let us know how it works. To run against Cassandra 3.x you will probably have to use Java 8 when running the YCSB client.

**Comment by risdenk** [comment]
Closing since YCSB 0.8.0 was just released: https://github.com/brianfrankcooper/YCSB/releases/tag/0.8.0 It should contain support for Cassandra 3.x. 

Please reopen if it doesn't work.
