### ISSUE TITLE
use hbase10 to test hbase1.1.2  in 30 threads and 100 threads has a very different network

### ISSUE THREAD

**Issue by zengweizhan** [brianfrankcooper/YCSB#663]
i user ycsb hbase10 to test mysql hbase-1.1.2 cluster。when i set 200 threads , the regionserver network(ganglia  network_report) is achieve  30% . but  in 30 threads  and use hbase PerformanceEvaluation  , the regsionserver networt can achieve  90%。

**Comment by risdenk** [comment]
This might be related to PR #651 that was just merged into master. It isn't in a YCSB release yet.
