### ISSUE TITLE
SyntaxError while "./bin/ycsb"

### ISSUE THREAD

**Issue by srzmldl** [brianfrankcooper/YCSB#679]
when I input the command "./bin/ycsb", it shows: 

File "./bin/ycsb", line 172
    except subprocess.CalledProcessError, err:
SyntaxError: invalid syntax

I am a freshman to python and YCSB. What should I do now ?

Related information: 
YCSB version: both extracted ycsb-0.7.0.tar.gz and built version from the latest master branch
Python 3.5.1
Linux version 4.4.5-1-ARCH

**Comment by busbey** [comment]
Hi!

I don't believe our python wrapper will work with Python 3. You'll need python 2.7.

**Comment by srzmldl** [comment]
Thanks for your timely reply. It works well when using python2.7 ^_^
