### ISSUE TITLE
HBaseClient10 should share Connection instance between threads in the same process

### ISSUE THREAD

**Issue by carp84** [brianfrankcooper/YCSB#681]
As titled, in current code of HBaseClient10#init, line 136~138, we could see:

      synchronized(THREAD_COUNT) {
        connection = ConnectionFactory.createConnection(config);
      }

which should be changed to:

      synchronized(THREAD_COUNT) {
        if(connection == null) connection = ConnectionFactory.createConnection(config);
      }

to use one connection per process. In our testing with the same hbase 1.x cluster, with HBaseClient in hbase098 the pure read(get) performance is ~20% better than HBaseClient10 because of this wrong usage.

**Comment by risdenk** [comment]
https://github.com/brianfrankcooper/YCSB/blob/master/hbase10/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java#L138

The lines you referenced already has the null check. This was fixed in PR #651. It will be released with YCSB 0.8.0.

**Comment by carp84** [comment]
Ah I see, was looking at 0.7.0 code base. Thanks for the note @risdenk
