### ISSUE TITLE
what does the zipfian distribution constant value mean?

### ISSUE THREAD

**Issue by xinjiacs** [brianfrankcooper/YCSB#685]
By looking at the ycsb source code of generator, it uses a zipfian distribution constant value 0.99, what does the number mean? Unfortunately, it's not configurable. 

However, does 0.99 indicates a very skew workload? What's the range of this constant value? Is it from 0 to 1.0 exclusively? Why choose 0.99 as the default one?

Any help is welcome. 
Thanks,
Xin

**Comment by xinjiacs** [comment]
Zipfian constant number ranges from 0. For YCSB zipfian distribution, 1.0 is an invalid number. As the number goes bigger, the skew is more obvious.  0.99 is a pretty obvious skewed workload. 1.5 is even more skewed. 

To get the idea of the quantity of skewness, simply generate 1 million integers and draw the histogram.

**Comment by sfc-gh-dschumann** [comment]
Does someone know how this constant relates to the alpha value used by e.g. numpy.random.zipf ? that value needs to be > 1. The closer to 1, the more evenly distributed the numbers.
