### ISSUE TITLE
JDK 9, 10, and 11 support for YCSB

### ISSUE THREAD

**Issue by risdenk** [brianfrankcooper/YCSB#705]
Since JDK 9 is in early access, it would be good to start testing with it and see what changes may be required to support it.

**Comment by risdenk** [comment]
There is an early report in #704 where the build fails.

**Comment by busbey** [comment]
:shakes_fist: No tests after rebase!!! arg. taking a look.

**Comment by risdenk** [comment]
The fixes from PR #712 worked need to extend for a few other bindings. Just ran on latest 9-ea 138 and got the following:

Solr 5.x - need to exclude from jdk 9
JDBC - redundant throws error from checkstyle

**Comment by risdenk** [comment]
@busbey I'll have a PR in a minute to fix the above two issues.

**Comment by busbey** [comment]
sweet. I just verified it was a flakey build and not that #712 broke things.

**Comment by risdenk** [comment]
Looks like there is an issue with the `rest` binding. The other bindings look good. I ran `mvn clean package` with the following environment:

```bash
# java -version
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+149)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+149, mixed mode)

# mvn --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T11:41:47-05:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 9-ea, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.3", arch: "x86_64", family: "mac"
```

**Comment by risdenk** [comment]
I opened #914 to track fixing the rest binding.

**Comment by risdenk** [comment]
An update here, I just tested master and got no failures with the following:

```
#java -version
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+163)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+163, mixed mode)

#mvn --version
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T15:39:06-04:00)
Maven home: /usr/local/Cellar/maven/3.5.0/libexec
Java version: 9-ea, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.4", arch: "x86_64", family: "mac"
```

**Comment by risdenk** [comment]
Manually tested on 9/10/17 at commit 0350c37ec1d6a4e7f9dc7bca290a2270ec156c8e:

```
# java -version
java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)

# mvn --version
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T14:39:06-05:00)
Maven home: /usr/local/Cellar/maven/3.5.0/libexec
Java version: 9, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.6", arch: "x86_64", family: "mac"

# mvn clean package
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:20 min
[INFO] Finished at: 2017-09-10T16:14:57-05:00
[INFO] Final Memory: 83M/278M
[INFO] ------------------------------------------------------------------------
```

**Comment by risdenk** [comment]
Travis now supports `oraclejdk9` as an option for JDKs.

https://docs.travis-ci.com/user/languages/java/#Overview

**Comment by busbey** [comment]
Let's add it to the Travis matrix and then start working through which jdk-specific test activations work on jdk9?

**Comment by risdenk** [comment]
Yea agreed started down this path just haven't put up the PR yet. Will do so this week.

**Comment by busbey** [comment]
Maybe obsoleted by the move to LTS versions in Java? Should we just focus on JDK11?

**Comment by risdenk** [comment]
@busbey yes focusing on LTS versions of Java might be the best course of action. I just put up PR #1186 to try to add JDK 10 and 11 to test on Travis. The same bindings that failed with JDK 9 failed with JDK 10 and 11.

**Comment by risdenk** [comment]
With PR #1186 closed, we can probably close this issue. We are now testing against each JDK 8-11.
