### ISSUE TITLE
issues running ycsb client

### ISSUE THREAD

**Issue by ledzepu2** [brianfrankcooper/YCSB#71]
I am having issues running the YCSB shell. When i run any shell command, the J2SE binary dies. Any inputs. ?Please let me know if you need any more details. I am trying to run the YCSB  Shell on a windows machine

**Comment by Ash140** [comment]
Hello,
I am working on benchmarking mysql. When I pass the workload I get this error
Ashwin@Ashu /cygdrive/c/Users/Ashwin/Downloads/ycsb-0.1.4
$ ./bin/ycsb load jdbc -P workloads/workloada properties.dat -s > mysql1.load.txt
Error: Could not find or load main class com.yahoo.ycsb.Client

Please help me out

**Comment by busbey** [comment]
Hi @Ash140, let's try to keep this on your new issue, #257 rather than bringing this thread back to life.

**Comment by mydata28** [comment]
H,
I  m using ycsb 0.2.0 for benchmarking mongodb2.6.7 on windows platform. For basic database it works but when I write following command
>c:\Python27\python.exe bin\ycsb load mongodb -P workloads\workload a -p companies.json -s > mogotest.txt
it doesnot work.

**Comment by mydata28** [comment]
pls help me out

**Comment by busbey** [comment]
@mydata28 please keep your request on #630. most folks won't get notifications on this older closed issue.

**Comment by saniadeyi** [comment]
What error message are u getting?
On Feb 23, 2016 7:52 AM, mydata28 <notifications@github.com> wrote:H,
I  m using ycsb 0.2.0 for benchmarking mongodb2.6.7 on windows platform. For basic database it works but when I write following command


c:\Python27\python.exe bin\ycsb load mongodb -P workloads\workload a -p companies.json -s > mogotest.txt
it doesnot work.
