### ISSUE TITLE
build fail because of style

### ISSUE THREAD

**Issue by srzmldl** [brianfrankcooper/YCSB#713]
Hi,

I try to build YCSB on my vps. 
I followed the README. Cloned the repository without any modify, then 'mvn clean package'. 
But '[INFO] Core YCSB ......................................... FAILURE [4.716s]'
Countless error like  'LineLength: Line is longer than 120 characters (found 179).'
' LeftCurly: '{' should be on the previous line.' and etc.

I build the same code on my PC but there is no problem.

What's the reason and how to solve it ?

related information:
Linux version 3.5.0-23-generic
Apache Maven 3.0.4

**Comment by busbey** [comment]
Those are warnings, which ought not fail the build. Somewhere in that wall of text is the actual error.

Try rebuilding with checkstyle logging to the console turned off:
```
mvn -Dcheckstyle.console=false clean package
```

Note that if you've edited the source, we do have checkstyle enforcement on in some modules, which will fail the build if there are violations. But that should only be for those that currently have no errors. The core module, for example, is not in enforcing mode.

**Comment by srzmldl** [comment]
Thanks for your reply.

There is indeed other problem "Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project core: Fatal error compiling: invalid target release: 1.7 -> [Help 1]" And I am solving it now.

However. please see the screenshot
![a](https://cloud.githubusercontent.com/assets/9389474/14581403/1b686750-041f-11e6-9f9e-455a2baad3de.png)

But I have not edited the source. It seems the required style was not certain.

**Comment by busbey** [comment]
what is the output of  `mvn --version`

**Comment by srzmldl** [comment]
Apache Maven 3.2.1 
But could the style depends on the mvn ?

**Comment by busbey** [comment]
the maven version command will also include what version of Java Maven is actually using.  Java 1.7 should not be an invalid target, which suggests something is wrong with your Java installation.

**Comment by srzmldl** [comment]
Thanks! I
