### ISSUE TITLE
[core] Measure JVM Behavior

### ISSUE THREAD

**Issue by manolama** [brianfrankcooper/YCSB#717]
When comparing the various databases it's critical to determine how the YCSB JVM is behaving regarding thread count, memory usage, garbage collection, etc. Java provides some useful tools out of the box so I'd like to do the following:

* Add a core param like "measurejvm" that enables the JVM tracking
* Track:
  * max/min thread count in the Status thread
  * max/min memory used count in the Status thread
  * System load avg in the Status thread (from the JVM's perspective at least, not going to call any system utilities)
  * gc count in Status thread to track GCs per execution
  * final gc count for each pool (depends on the JVM)
  * Threads and mem just before each client cleanup (to see resource usage before closing down clients in case users don't have the Status thread running)
  * Hopefully track full GCs using the GC MXBeans

So far it looks pretty straightforward. We can slap a GC notification consumer on the GC beans then poll the JVM as needed for the other stats.

**Comment by nitsanw** [comment]
It sounds like an investment in extra monitoring utils, all of which available externally in different forms on different platforms. Not sure it would be worth including the extra code in this project. If there's a clean external module (platform independent, maintained by other people, well established) you could use that would be nice.

**Comment by manolama** [comment]
It would be really nice to get some system stats while running the benchmarks, but that would be completely platform dependent like you said. It would still be good to look at doing that, see if there's a module that would call the proper utilities based on the system it was installed on.

For the JVM metrics though, Java includes all of the calls you need for high-level details (memory, threads, GCs) and I think those are a good enough start for YCSB for now. Anything else you'd like to see measured?

**Comment by busbey** [comment]
anything else going to happen here beyond #719?

**Comment by nitsanw** [comment]
@manolama @busbey  looked at the merge, not clear: why is a secondary reporting thread required? why not use the StatusThread?

**Comment by risdenk** [comment]
Looks like this was addressed via #719 

@nitsanw if you are interested in addressing changes due to #719 can you open a new issue?
