### ISSUE TITLE
How to set the port

### ISSUE THREAD

**Issue by StephenRi** [brianfrankcooper/YCSB#724]
I set the on the command line just like this:  
`./bin/ycsb load memcached -s -P workloads/workloada  -p "memcached.hosts=127.0.0.1" -p "memcached.port=5000" > outputLoad.txt`  
but it doesn't work, I want to know how to set this property.

**Comment by risdenk** [comment]
Can you include more details on what doesn't work? Can you try removing the quotes from the parameters?

**Comment by StephenRi** [comment]
I mean the port. I try to set the port to 5000, but it's still 11211.

**Comment by busbey** [comment]
AFAICT from reading the instructions in the README and example properites file, you should specify the port per individual host in your hosts list.

So to do localhost on port 5000, it would be `memcached.hosts=127.0.0.1:5000`

**Comment by StephenRi** [comment]
Thanks

**Comment by StephenRi** [comment]
Yes, thank you very much. But now I have a new problem. Can you help me please?
#726
