### ISSUE TITLE
Update Behavior

### ISSUE THREAD

**Issue by cgara** [brianfrankcooper/YCSB#730]
Hi,
Using zipfian distribution;
Running load update 10,000;

When I run update 10,000, they are updated 10,000 different records, or repeats the update of the same record in the procedure?

With reading and insertion is the same thing?

This information is in the wiki, or in any article?

Thank you

**Comment by kruthar** [comment]
I'm not positive that I fully understand your question. Are you asking that if you run a `load` benchmark with 10,000 operations and specify the zipfian distribution, will YCSB update 10,000 different records or will it update the same record 10,000 times?

The answer to that is somewhere in the middle, the essence of the zipfian generator is that it picks items out of a set with some items being more likely to be chosen then others. So, you will almost definitely be updating many different records, but there is a good chance that certain items will get update multiple times.

You can read more about how the zipfian generator works by looking at the ZipfianGenerator.java class: https://github.com/brianfrankcooper/YCSB/blob/master/core/src/main/java/com/yahoo/ycsb/generator/ZipfianGenerator.java. Hope this helps.

**Comment by cgara** [comment]
Very good, exactly what I needed.

Thank you
