### ISSUE TITLE
How do I set up a database system to test (or run workload)?

### ISSUE THREAD

**Issue by jabirfatah91** [brianfrankcooper/YCSB#738]
I want to benchmark Cassandra database. I am aware about the link (https://github.com/brianfrankcooper/YCSB/wiki/Running-a-Workload) where they have explained how to set up databases system to test. Problem is, the instruction doesn't exactly mention how to create _usertable_, _column_ etc in cassandra. I have YCSB in my computer and it includes all the necessary databases. I don't see any executable file inside the database file, where I can create table, inserting data into it etc. Is there any clear explanation that clearly tells us how the tables must be created in order to run the YCSB clients?

**Comment by busbey** [comment]
Hi!

Each datastore binding is supposed to have a README that explains the specifics of getting YCSB working with that datastore.

If you check out [the README for the cassandra2 module](https://github.com/brianfrankcooper/YCSB/tree/0.8.0/cassandra2), it should have instructions on how to create the needed table. IIRC, the instructions presume you will be running with the default number of fields (10).

The page you mentioned above, _Running a Workload_, contains a step that does loading data prior to a read/write workload.

**Comment by jabirfatah91** [comment]
busbey, thank you for your quick comment. yes, the README file has its instruction; and also from your given link: it seems that I should run all the query to interact with Cassandra in `cqlsh` (in CQL binding). But in my installed ycsb-0.8.0, no `cqlsh` executable file is included in the Cassandra2-binding. It has only` lib` folder, that is not useful.
Fortunately, a manually installed Cassandra includes `bin` folder and it has `cqlsh` type executable file inside, though I can't execute it just by clicking it. In this case, where do I get the Cassandra CQL binding that offers me to write command in `cqlsh`?

**Comment by busbey** [comment]
YCSB doesn't provide a datastore instance to run tests against. You have to have already set that up. This paragraph from _Running a Workload_:
>The first step is to set up the database system you wish to test. This can be done on a single machine or a cluster, depending on the configuration you wish to benchmark.

is meant to cover whatever is involved in such an installation. For most datastores that means

1. downloading an installer from the project
2. installing the system on one or more machines
3. verifying the installation using the tools for that project

In the case of Apache Cassandra, I recommend you [follow the Getting Started guide from that project](http://wiki.apache.org/cassandra/GettingStarted#Installing_Cassandra_Locally).

**Comment by jabirfatah91** [comment]
Thank you again, I may be on the right track now. I am trying to configure the Cassandra Apache from their official site. While following the instruction from here: [http://wiki.apache.org/cassandra/GettingStarted#Installing_Cassandra_Locally](url), I am stuck on _Step 2.1: Directories Used by Cassandra_. 

> Otherwise, you will want to check the following config settings from conf/cassandra.yaml: data_file_directories (/var/lib/cassandra/data), commitlog_directory (/var/lib/cassandra/commitlog), and saved_caches_directory (/var/lib/cassandra/saved_caches). Make sure these directories exist and can be written to. By default, Cassandra will write its logs in /var/log/cassandra/. Make sure this directory exists and is writeable, or change this line in conf/log4j-server.properies:

I don't see those directories as mentioned. I only see the `conf/cassandra.yaml` (like here: [http://imgur.com/eM8HHS6](url)).

**Comment by busbey** [comment]
Unfortunately, I'm not really an Apache Cassandra person. Your best bet will be to seek help on the [Apache Cassandra User Mailing List](http://mail-archives.apache.org/mod_mbox/cassandra-user/). Be sure to subscribe if you'd like to get responses to your question directly, rather than check the archives for them later.

**Comment by busbey** [comment]
closing this as answered. please feel free reopen if you something remains unclear.
