### ISSUE TITLE
Which command shell is used to write the following command to load the data?

### ISSUE THREAD

**Issue by jabirfatah91** [brianfrankcooper/YCSB#739]
Acording to the instruction [https://github.com/brianfrankcooper/YCSB/wiki/Running-a-Workload](url):

> **Step 5. Load the data**

> 
> Workloads have two executable phases: the loading phase (which defines the data to be inserted) and the transactions phase (which defines the operations to be executed against the data set). To load the data, you run the YCSB Client and tell it to execute the loading section.
> 
> For example, consider the benchmark workload A (more details about the standard workloads are in Core Workloads). To load the standard dataset:

`$ ./bin/ycsb load basic -P workloads/workloada `
What command shell is used to run the above command?
Can I run the YCSB client in windows shell with the following command?
`"C:\Python27\python.exe" bin\ycsb`

**Comment by risdenk** [comment]
There is documentation about using Windows to run the YCSB client: https://github.com/brianfrankcooper/YCSB/wiki/Prerequisites-for-Windows

**Comment by jabirfatah91** [comment]
risdenk, thank you for your comment. I already have the documentation read. I understand that it has something to do with Python shell. But the piece of instruction I have referred doesn't give any hint in which shell is required to write the command. For example `$` symbol isn't accepted any shell as far as I have tried, and the `./bin` isn't any standard format in windows shell.

**Comment by busbey** [comment]
on windows, you should be able to follow the examples given in the guide risdenk quoted on the Powershell (that's where I tested them).

The examples on other pages that look like this:

```
$ ./bin/ycsb load basic -P workloads/workloada
```

are meant to be run on a system that has a posix shell, e.g. bash.

**Comment by busbey** [comment]
all worked out now @jabirfatah91, or are you still having trouble?

**Comment by jabirfatah91** [comment]
Hi busby, yes, that part is working, but I have got another issue and I have posted it as new issue. i can close this issue.
