### ISSUE TITLE
Less no of records being inserted in cassandra DB

### ISSUE THREAD

**Issue by SourabhSanghi** [brianfrankcooper/YCSB#74]
Hi,
I am trying to insert 1 Billion records to stress test Cassandra DB using multiple ycsb clients. I observe that less than 1 Billion records are inserted when i sum up the insert record count from each individual client. Is it a know issue with ycsb?? there is a loss of about 100 to 500 records overall.

**Comment by kruthar** [comment]
@SourabhSanghi - sorry for the long pause on this issue. I tried to replicate with YCSB 0.5.0, Cassandra 2.1, and the ```cassandra2-cql``` client, but was unable to reproduce.

I tested with:

```
insertstart=0
insertcount=990
```

the record count seemed to be correct. Output excerpt from YCSB:

```
[INSERT], Operations, 990.0
[INSERT], AverageLatency(us), 2646.6656565656567
[INSERT], MinLatency(us), 1549.0
[INSERT], MaxLatency(us), 32399.0
[INSERT], 95thPercentileLatency(us), 3605.0
[INSERT], 99thPercentileLatency(us), 9327.0
[INSERT], Return=OK, 990
```

and cqlsh output:

```
cqlsh:ycsb> select count(*) from usertable;

 count
-------
   990
```

Is this still an issue?

**Comment by busbey** [comment]
closing as stale. please reopen if you're still seeing the issue with the changes that @kruthar noted

**Comment by ashleyblackmore** [comment]
I saw this in a very early version of YCSB, and dealt with it in typical student manner, by discarding in my application what were NPEs, iirc. I remember it was fixed in a later YCSB version.
