### ISSUE TITLE
Release version 0.9.0

### ISSUE THREAD

**Issue by stfeng** [brianfrankcooper/YCSB#740]
Folks, 

I will create the release staging branch for 0.9.0 after EOD today (5pm 05/04 PDT), whatever is in Main before that point will be included in 0.9.0.

If you have pending PRs that would like to make it to the 0.9.0 release, please get it in by today. If you believe the release needs to be postponed for certain reason, please feel free to comment on this thread and we'd be happy to discuss.

My next update to this thread will provide a list of features in this release, specific plans for testing, and timeline. 

@busbey: FYI.

**Comment by busbey** [comment]
excellent! thanks for driving this release.

I'll take care of testing on windows once we're feature locked. If Accumulo is on the to-test list I'll take care of that as well.

**Comment by stfeng** [comment]
Here is a list of components and DB bindings that are changed in this release 0.9.0:

* asyncbase: #718, #714
* bigtable: #734,
* couchbase2: #736, #711
* core: #727, #529, #719, #674, #694, #696
* elasticsearch: #721, #693, #684
* geode: #725
* googlebigtable: #698, #690
* googledatastore: #682
* hbase10: #692, #689
* hbase098: #688
* kudu: #720
* riak: #723, #686
* scripts: #709


Breaking changes:

* None.

Bindings to test:

* asyncbase
* bigtable
* couchbase2
* elasticsearch
* geode
* googlebigtable
* googledatastore
* hbase10
* hbase098
* kudu
* riak

Release plan:

* RC1 - Friday May 6th
* Bindings testing start - Monday May 9th 
* 0.9.0 - Bindings testing complete + ~2 days 

My next update will provide an RC1 build for bindings contributors to start testing.

**Comment by stfeng** [comment]
RC1 is ready for testing:

https://github.com/brianfrankcooper/YCSB/releases/tag/0.9.0-RC1

**Comment by stfeng** [comment]
Folks, we are doing release 0.9.0 which contains latest changes in one or more bindings you have recently contributed to, your help in testing them will be highly appreciated!

RC1 build is here: https://github.com/brianfrankcooper/YCSB/releases/tag/0.9.0-RC1

@manolama, can you please test asynchbase, and googlebigtable?
@daschl, can you please test couchbase2?
@jasontedor, can you please test elasticsearch?
@metatype, can you please test geode?
@yuyantingzero, can you please test googledatastore?
@saintstack, can you please test hbase10?
@jdcryans, can you please test kudu?
@nygard89, can you please test riak?

Thank you all once again for your contributions!

**Comment by metatype** [comment]
Tested geode:
- `mvn clean package` succeeds
- Followed instructions in geode/README.md to start up a geode cluster
- Ran workloads a-d,f successfully

LGTM.  Let me know if you need further testing.

**Comment by daschl** [comment]
Couchbase2 is good to go :)

**Comment by nygard89** [comment]
Riak KV good to go :smile: :+1:  !

**Comment by busbey** [comment]
#684 and #693 were in 0.8.0.

#721 should be called out as a breaking change.

**Comment by busbey** [comment]
#692 was also in 0.8.0

**Comment by stfeng** [comment]
Thanks @busbey. Updated my release notes in the first comment to reflect what you said. 

BTW, I used "git log 0.8.0.." to find all PRs that were made after the 0.8.0 tag, and that output shows those 3 PRs you mentioned above...

**Comment by yuyantingzero** [comment]
googledatastore good to go

**Comment by cmatser** [comment]
@stfeng I believe I cherry picked those PRs after the 0.8.0 tag as they were fixes that came out of testing the inital release candidate.

**Comment by jdcryans** [comment]
+1
I downloaded RC1, mvn package'd it, ran it against a Kudu 0.8.0 cluster, all good.

**Comment by manolama** [comment]
@stfeng Confirmed asynchbase and googlebigtable from the tarball. Thanks!

**Comment by stfeng** [comment]
Wow, this is some seriously fast turnaround! ;) Thank you all! 

@jasontedor - would you mind do a quick sanity check on ElasticSearch? 

@busbey Could you please do a pass on Windows?

**Comment by jasontedor** [comment]
> @jasontedor - would you mind do a quick sanity check on ElasticSearch?

Elasticsearch is good, but I would like to bump the version to 2.3.2 if we can? I opened #741 and tested this patch against the 0.9.0-staging branch and it's good.

**Comment by stfeng** [comment]
Thank you @jasontedor! Merged your fix to master and cherry-picked to the release staging branch.

**Comment by stfeng** [comment]
Here is the release notes ready for review:

https://gist.github.com/stfeng/3b46e4550c046715765d13356c686f58

**Comment by jasontedor** [comment]
One small change: 

> Elasticsearch 2.0.2, 2.1.2, 2.2.2, 2.3.1 (via elasticsearch binding).

Version 2.3.1 can be replaced in that list by 2.3.2.

**Comment by stfeng** [comment]
@jasontedor Thanks! Updated the release notes.

**Comment by busbey** [comment]
I would not call out #665 as a known issue, since we have yet to determine what is going on in that case.

**Comment by busbey** [comment]
> Apache HBase prior to 0.9.8 (via hbase094 binding).

This should be "prior to 0.98"

**Comment by busbey** [comment]
> Build failure with JDK 9 (#704)

I would phrase this as "JDK9 is not supported"

**Comment by busbey** [comment]
> Repo description link is dead (#637)

Is this of interest to downstream users?

> Building Cassandra CQL with JDK 8 issues a org.hyperic.sigar.SigarException: no libsigar-amd64-linux.so in java.library.path. JDK 7 builds OK.

There's no issue associated with this? I don't think this is worth calling out in release notes. It might be worth a note in the README for the cassandra2 module, since it is very prominent for a warning that essentially should just be ignored.

**Comment by stfeng** [comment]
@busbey, incorporated your comments to the release notes. Also, I agree those two issues (#637 and the Cassandra build warnings) are not worth calling out as "issues" and removed the from the release notes. (btw, I inherited the second "issue" from the last release notes ;)

**Comment by busbey** [comment]
windows works as expected. #335 is still an issue. I still hit the same timeout on `cassandra2` tests as I did during the 0.8.0 RCs. the rest of the bindings all pass and running from the tarball with the `basic` datastore as explained in our docs works.

**Comment by stfeng** [comment]
Thanks @busbey. #335 has already been noted as known issue in release notes. 

Looks like all has checked out fine so far, I will proceed with the next step(s) of the release today.

**Comment by busbey** [comment]
Yay! Thanks again for driving the release.

Couple of quick updates to the release notes:

* Google BigTable should be listed as tested this cycle via its dedicated binding
* Cassandra3 should be listed as untested via cassandra2-cql
* Google BigTable via hbase10 should be listed as untested

**Comment by busbey** [comment]
+1 release notes look good now.

I'm giving a talk at ApacheCon BigData 2016 tomorrow around 2pm PT. It'd be great if I could refer to this release as out the door, even if it hasn't been announced yet. ;)

**Comment by stfeng** [comment]
Thanks @busbey 

I've been building-the-world (convenience artifacts) since this afternoon, man, this takes a while... :) I will officially tag the release once the artifacts are built.

**Comment by busbey** [comment]
sounds good.

I noticed one last slight tweak on the release notes. #709 should be described as "make bin/ycsb work with Python 2.6 in addition to Python 2.7" or the like. It should be a big help to folks trying to get started on CentOS/RHEL 6.

**Comment by stfeng** [comment]
Release has been published [here] (https://github.com/brianfrankcooper/YCSB/releases/tag/0.9.0)

Thanks again to everyone for your help and contribution to this release!

**Comment by busbey** [comment]
heya @metatype, which version of the Geode server did you run in your test?

**Comment by busbey** [comment]
@stfeng I copied the release notes directly into the release's description (issue #s are linked the other way). hope you don't mind.

**Comment by stfeng** [comment]
@busbey, saw your new updates to the release description. LGTM. Thanks!

**Comment by metatype** [comment]
@busbey I tested the geode binding against v1.0.0-incubating.M2.

**Comment by busbey** [comment]
thanks for the response @metatype. I've updated the release notes with the corrected version.
