### ISSUE TITLE
HBase 0.92.1

### ISSUE THREAD

**Issue by martinalig** [brianfrankcooper/YCSB#75]
As I was not able to make YCSB working with the binaries from the download section, I tried to build YCSB against HBase 0.92.1 myself. For this I had to adjust the following things to make the maven build work:

In the root pom.xml: Set the hbase.version property to 0.92.1

In the hbase-binding pom.xml I had to add the following dependency:

<dependency>
	<groupId>org.apache.hadoop</groupId>
	<artifactId>hadoop-core</artifactId>
	<version>1.0.2</version>
</dependency>

Using the downloadable binaries from here, the exception I got was something like:

"Not a host:port pair"

Maybe this can be usefull for somebody.

**Comment by busbey** [comment]
closing as stale, since 0.92 is a defunct HBase version. please reopen if you still need HBase 0.92  support.
