### ISSUE TITLE
How to turn off MongoDB logging?

### ISSUE THREAD

**Issue by vreniers** [brianfrankcooper/YCSB#752]
Hi,

I'm currently running some tests with MongoDB. However, the YCSB benchmark generates a large amount of debug information as output. I normally execute the benchmark and redirect the output to a file for later analysis. However, with the amount of debug information the driver is generating these files are becoming unnecessarily large. At the very end of the run I finally get the required info such as average throughput, total runtime etc.

Example of execution:
```
python ./bin/ycsb run mongodb -P workloads/workloadc -p recordcount=100000 
-p operationcount=20000  -p mongodb.url=mongodb://localhost:27017/ycsb
```

Output (sample):
```
19:37:35.058 [Thread-2] DEBUG org.mongodb.driver.protocol.query - Sending query of namespace ycsb.usertable on connection [connectionId{localValue:2, serverValue:337}] to server localhost:27017
19:37:35.058 [Thread-2] DEBUG org.mongodb.driver.protocol.query - Query completed
19:37:35.058 [Thread-2] DEBUG org.mongodb.driver.protocol.query - Sending query of namespace ycsb.usertable on connection [connectionId{localValue:2, serverValue:337}] to server localhost:27017
19:37:35.058 [Thread-2] DEBUG org.mongodb.driver.protocol.query - Query completed
19:37:35.058 [Thread-2] DEBUG org.mongodb.driver.protocol.query - Sending query of namespace ycsb.usertable on connection [connectionId{localValue:2, serverValue:337}] to server localhost:27017
```

Is there any way to turn off the debugging? (preferably without modifying the source code)

**Comment by busbey** [comment]
Hi!

What version are you running?

The general answer to your question is that you should be able to adjust logging by including a log4j.properties file as a "additional classpath" argument via {{-cp path/to/log4j.properties}}.

However, the inclusion of debug output by default was supposed to be fixed in version 0.7.0+ via pr #578.

**Comment by vreniers** [comment]
Hi,

I'm using the latest compiled release (0.9.0). I've tried using -cp path/../log4j.properties as you suggested, using the log4j file from [#578](https://github.com/brianfrankcooper/YCSB/pull/578). 
Additionally, I've also tried to make a new property file with contents: ``` log4j.rootLogger=OFF```

Example:
```
python ./bin/ycsb run mongodb -P workloads/workloadc -p recordcount=100000 -p operationcount=20000  
-p mongodb.url=mongodb://localhost:27017/ycsb -cp ~/Experiments/ycsb/log4j.properties 
```

Both approaches did not work. However, the strange thing is if I use the (0.9.0) source code and build everything with maven, then I do not get the debugging logs. The only downside from this approach is that I do get this warning message each time after running:
```
[WARN]  Running against a source checkout. In order to get our runtime dependencies we'll have to invoke Maven. Depending on the state of your system, this may take ~30-45 seconds
```
Which does seem to take a moment (few seconds). Not really a big problem to be honest. But I was kind of hoping to be able to disable the logging without having to built it.

Any ideas? Thanks in advance.

**Comment by kruthar** [comment]
@vreniers - the mongodb driver is setup to use slf4j and logback-classic so you actually need a logback.xml configuration present. I used something similar to this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
                <encoder>
                        <pattern>%d{HH:mm:ss.SSS}  %-5level %logger{36} - %msg%n</pattern>
                </encoder>
        </appender>

        <logger name="org.mongodb" level="WARN">
                <appender-ref ref="STDOUT"/>
        </logger>

        <root level="INFO">
                <appender-ref ref="STDOUT"/>
        </root>
</configuration>
```

Putting the logback.xml on the classpath was not sufficient, I had to specify it with a jvm property. Similar to:

```
python ./bin/ycsb run mongodb -P workloads/workloadc -p recordcount=100000 -p operationcount=20000 -p mongodb.url=mongodb://localhost:27017/ycsb -jvm-args="-Dlogback.configurationFile=/path/to/logback.xml"
```

**Comment by kruthar** [comment]
@veneers - did adding this log file help you at all?

**Comment by busbey** [comment]
@vreniers bump, did the instructions for adding logback.xml solve your issue?

**Comment by vreniers** [comment]
Thanks for the suggestion. I haven't had the time to verify it yet. 
However I will report back.

**Comment by vreniers** [comment]
This works, thank you.
