### ISSUE TITLE
How to add a new database

### ISSUE THREAD

**Issue by StephenRi** [brianfrankcooper/YCSB#754]
I find the help document at `https://github.com/brianfrankcooper/YCSB/wiki/Adding-a-Database`,  
but I still don't know what I should do to add a database. Assuming I want to add a database named dbtest, should I modify the file `pom.xml`?

**Comment by kruthar** [comment]
@StephenRi - I added a new first step to the instructions on this page: https://github.com/brianfrankcooper/YCSB/wiki/Adding-a-Database. The highlight is that if you want to create a new database interface module the true first step is creating a top level directory structure for it which will include a pom.xml.

Then follow the rest of the steps to extend the `DB` class and implement the methods needed to perform actions against your database.

**Comment by kruthar** [comment]
@StephenRi - Was this information helpful to get you started? Are you still having issues creating a new DB driver?

**Comment by StephenRi** [comment]
Yes， it works. Thanks very much

2016-06-10 9:21 GMT+08:00 Andy Kruth <notifications@github.com>:
