### ISSUE TITLE
Workload D and Duplicate Key Errors with MongoDB

### ISSUE THREAD

**Issue by ahackett** [brianfrankcooper/YCSB#762]
Hi

I am running Core Workload D using YCSB  0.9.0 and MongoDB v3.2.6.

I am loading into a brand new fresh database, but am experiencing duplicate key errors.

Here are the steps to reproduce in my environment:

Verify that the target database does not already exist via the mongo shell

`ycsb load mongodb -s -P /home/ec2-user/ycsb-0.9.0/workloads/workloadd -threads 2 -p 'mongodb.url=mongodb://UserName:Password@HostName:27000/aghtest2?w=1&authSource=admin&authMechanism=SCRAM-SHA-1' -p recordcount=10000 -p mongodb.batchsize=1000`

Run db.usertable.count() in the mongo shell to verify that 10000 records were successfully inserted.

`ycsb run mongodb -s -P /home/ec2-user/ycsb-0.9.0/workloads/workloadd -threads 2 -p 'mongodb.url=mongodb://UserName:Password@HostName:27000/aghtest2?w=1&authSource=admin&authMechanism=SCRAM-SHA-1' -p maxexecutiontime=1800 -p operationcount=10000`

When the benchmark runs I see a number of the following errors:

Exception while trying bulk insert with 0
com.mongodb.MongoWriteException: E11000 duplicate key error collection: aghtest2.usertable index: _id_ dup key: { : "user2769515498912162190" }
        at com.mongodb.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:487)
        at com.mongodb.MongoCollectionImpl.insertOne(MongoCollectionImpl.java:277)
        at com.yahoo.ycsb.db.MongoDbClient.insert(MongoDbClient.java:270)
        at com.yahoo.ycsb.DBWrapper.insert(DBWrapper.java:240)
        at com.yahoo.ycsb.workloads.CoreWorkload.doTransactionInsert(CoreWorkload.java:811)
        at com.yahoo.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:636)
        at com.yahoo.ycsb.ClientThread.run(Client.java:458)
        at java.lang.Thread.run(Thread.java:745)

The statistics for the run show that all the inserts failed:

[INSERT-FAILED], Operations, 510.0
[INSERT-FAILED], AverageLatency(us), 17188.835294117645
[INSERT-FAILED], MinLatency(us), 656.0
[INSERT-FAILED], MaxLatency(us), 5480447.0
[INSERT-FAILED], 95thPercentileLatency(us), 1663.0
[INSERT-FAILED], 99thPercentileLatency(us), 2523.0
[INSERT], Operations, 0.0
[INSERT], AverageLatency(us), NaN
[INSERT], MinLatency(us), 9.223372036854776E18
[INSERT], MaxLatency(us), 0.0
[INSERT], 95thPercentileLatency(us), 0.0
[INSERT], 99thPercentileLatency(us), 0.0
[INSERT], Return=ERROR, 510

I am aware that I could set the upsert property to true as a workaround, but this turn it into an update workload instead of an insert workload.

Here are the contents of workloadd (comments and whitespace removed for brevity):

recordcount=1000
operationcount=1000
workload=com.yahoo.ycsb.workloads.CoreWorkload
readallfields=true
readproportion=0.95
updateproportion=0
scanproportion=0
insertproportion=0.05
requestdistribution=latest

I also tried doing the load with Workload A, and running the benchmark with Workload D, but got the same errors.

Any help would be much appreciated.

Thanks

**Comment by kruthar** [comment]
Hi @ahackett - sorry haven't been able to test this solution, but I think the issue is that you have `recordcount=10000` in your load job but you do not specify it in your run job so it defaults to the workload which is `recordcount=1000`.

The run job still needs the recordcount specified so that it understands which records are stored in MongoDB. WorkloadD has a small proportion of inserts. YCSB is going to try and insert to a user ID greater than 1000 which means there is a definite possibility it will choose a user ID that is already encompassed in your 10000 loaded records.

The solution is simple, just add the recordcount to your run job. Hope this helps

**Comment by ahackett** [comment]
Hi Andy

A sincere thank you for your help - that was exactly the problem.

Much appreciated

**Comment by yasselpiloto** [comment]
I was running into the same issue. I would receive [READ-FAILED] and [UPDATE-FAILED] for almost all operations in the 'run' phase. 

It got resolved by adding -p recordcount to both ycsb load and ycsb run commands.

Thanks!
