### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by wuxiaomin98** [brianfrankcooper/YCSB#763]
Hi there,

    I'm using MacOS X EI Captan. The python version is 2.7.10. I want to test Cassandra with YCSB. But I got some error like below. I do check google but did not find anything helpful. It's probably something wrong with the python? Did anyone have the same issue? Thanks!

> YCSB WXM$ bin/ycsb load cassandra2-cql -P workloads/workloada -s > test_res2.txt
> [WARN]  Running against a source checkout. In order to get our runtime dependencies we'll have to invoke Maven. Depending on the state of your system, this may take ~30-45 seconds
> [DEBUG]  Running 'mvn -pl com.yahoo.ycsb:cassandra2-binding -am package -DskipTests dependency:build-classpath -DincludeScope=compile -Dmdep.outputFilterFile=true'
> Traceback (most recent call last):
>   File "bin/ycsb", line 259, in <module>
>     sys.exit(main())
>   File "bin/ycsb", line 232, in main
>     maven_says = get_classpath_from_maven(project)
>   File "bin/ycsb", line 167, in get_classpath_from_maven
>     "-Dmdep.outputFilterFile=true"])
>   File "bin/ycsb", line 122, in check_output
>     p = subprocess.Popen(cmd, stdout=subprocess.PIPE)
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
>     errread, errwrite)
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory

**Comment by kruthar** [comment]
What version of YCSB? There was recent work to fix bin/ycsb around the checkout_output method, which is where your error is happening: https://github.com/brianfrankcooper/YCSB/pull/709.

**Comment by wuxiaomin98** [comment]
@kruthar Thanks for the reply. 

I'm not sure what's the version for YCSB now. I guess it maybe the latest version. I was using the git command to clone the ycsb. It's like below:

git clone git://github.com/brianfrankcooper/YCSB.git
cd YCSB
mvn clean package

For the issue #709 , I did not catch the answer for my problem. Am I missing something, or the solution is still under working? Do you have any suggestions on what should I do for my problem?

Thanks!

**Comment by busbey** [comment]
Please try using the [getting started instructions](https://github.com/brianfrankcooper/YCSB/blob/master/README.md#getting-started) to download our latest release and use the precompiled artifacts.

**Comment by wuxiaomin98** [comment]
Hi @busbey . Thanks for the information.

I downloaded the tar file. I'm trying to connect to Cassandra version 2.1 deployed in my local machine. According to the readme file in cassandra-binding folder, it seems that it's been deprecated like below:

> # THIS BINDING IS DEPRECATED
> ----------------------------
> Date of removal from YCSB: **March 2016**
> 
> Due to the low amount of use and support for older Cassandra lineages (0.X and 1.X), YCSB will not support clients for these versions either.
> 
> For Cassandra 2.X use the ```cassandra2-cql``` client: https://github.com/brianfrankcooper/YCSB/tree/master/cassandra2.

Since it's precompiled, I donot need to compile it with mvn again. But I did not find information on how to load the workload. The instruction gave an example with bin/ycsb load basic -P workloads/workloada. But for cassandra-binding folder, there's just one lib folder with jars inside. I'm not sure what kind of command should I use. 

Thanks again!

**Comment by wuxiaomin98** [comment]
Command I have tried:

bin/ycsb load cassandra2-cql -P workloads/workloada -p hosts="localhost"

Then I got the following:

> /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java -cp /Users/WXM/ycsb-0.9.0/cassandra2-binding/conf:/Users/WXM/ycsb-0.9.0/conf:/Users/WXM/ycsb-0.9.0/lib/core-0.9.0.jar:/Users/WXM/ycsb-0.9.0/lib/HdrHistogram-2.1.4.jar:/Users/WXM/ycsb-0.9.0/lib/htrace-core4-4.1.0-incubating.jar:/Users/WXM/ycsb-0.9.0/lib/jackson-core-asl-1.9.4.jar:/Users/WXM/ycsb-0.9.0/lib/jackson-mapper-asl-1.9.4.jar com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.CassandraCQLClient -P workloads/workloada -p hosts=localhost -load
> YCSB Client 0.9.0
> Command line: -db com.yahoo.ycsb.db.CassandraCQLClient -P workloads/workloada -p hosts=localhost -load
> Loading workload...
> Starting test.
> java.lang.ClassNotFoundException: com.yahoo.ycsb.db.CassandraCQLClient
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
> 	at com.yahoo.ycsb.DBFactory.newDB(DBFactory.java:37)
> 	at com.yahoo.ycsb.Client.main(Client.java:1058)
> Exception in thread "Thread-2" java.lang.NullPointerException
> 	at com.yahoo.ycsb.ClientThread.run(Client.java:418)
> 	at java.lang.Thread.run(Thread.java:745)
> [OVERALL], RunTime(ms), 1.0
> [OVERALL], Throughput(ops/sec), 0.0
> [TOTAL_GCS_PS_Scavenge], Count, 0.0
> [TOTAL_GC_TIME_PS_Scavenge], Time(ms), 0.0
> [TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.0
> [TOTAL_GCS_PS_MarkSweep], Count, 0.0
> [TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 0.0
> [TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.0
> [TOTAL_GCs], Count, 0.0
> [TOTAL_GC_TIME], Time(ms), 0.0
> [TOTAL_GC_TIME_%], Time(%), 0.0

**Comment by kruthar** [comment]
hi @wuxiaomin98 - Sorry, we just identified that the cassandra2-binding that you are attempting to use may have been left out of the ycsb-0.9.0 release. Can you download ycsb-0.8.0 and try using that?

https://github.com/brianfrankcooper/YCSB/releases/download/0.8.0/ycsb-0.8.0.tar.gz

**Comment by wuxiaomin98** [comment]
Hi @kruthar . Thank you so much that you point it out. 

Yes, there's no cassandra2 binding in ycsb-0.9.0. I downloaded 0.8.0 version and it works now.

Thanks again and I do hope that you'll fix this to avoid further same error happened to others.
