### ISSUE TITLE
Bad link in Getting Started

### ISSUE THREAD

**Issue by jseaidou** [brianfrankcooper/YCSB#765]
In the `Getting Started` page, the link for 
```
HBase 0.20.3 Client Package Description
```
is incorrect and is broken.

**Comment by kruthar** [comment]
@jseaidou - Thanks. I couldn't find the exact match for that link, but I changed the link to the fully distributed quickstart guide in the HBase book. That should atleast get folks thinking about dependencies like Zookeeper for HBase.
