### ISSUE TITLE
Cleanup Role 

### ISSUE THREAD

**Issue by amirjuve1** [brianfrankcooper/YCSB#769]
when we get the YCSB report, it shows cleanup property, i would like to know  what's its role.

**Comment by kruthar** [comment]
At the end of the workload YCSB runs the `cleanup()` method from of the binding being used once for each thread being used. The `cleanup()` operations are meant to 'cleanup' after all the work is done, this would include shutting down any database connections, disposing of any datastructures, etc. 

The cleanup operations are measured, but for the most part they don't mean anything.

**Comment by busbey** [comment]
please let us know if you'd like additional information.
