### ISSUE TITLE
Debug when ycsb is stuck

### ISSUE THREAD

**Issue by AnkitaD** [brianfrankcooper/YCSB#771]
Hi guys,

I am working on hbase10, while running YCSB it works with one thread till 30K record count and operation count( beyong that it fails with 1 thread also).

I tried with multiple threads then it fails saying 0 operations/sec and  my region server goes down.Even I give two threads.

Do YCSB have some way to debug whats going in there to know why its not able to run multiple  threads ?

**Comment by busbey** [comment]
you can increase logging by placing a log4j.properties file on the classpath.

what does the log for your region server say?

what version of YCSB are you using?

what version of HBase?

what's the entire load/run command you're using?

**Comment by busbey** [comment]
closing as stale. If you're still having an issue please reopen with the requested information.
