### ISSUE TITLE
Running workload in parallel : HBase

### ISSUE THREAD

**Issue by AnkitaD** [brianfrankcooper/YCSB#778]
Hi guys I would like to run multiple YCSB clients in HBase. I am running one YCSB client on Master tried inserting 10Million records its working fine but above that it can't handle. I am planning to run multiple client how that can be done in HBase I need to run command in another server and need to point it to HBase master so that it can use region server to load data parallel.

Can anybody suggest me the command or parameters that need to mention on another server to  pointing it to the HBase Master server.??

**Comment by busbey** [comment]
Is your current difficulty in coordinating what the YCSB clients work on, or is it connecting to the HBase instance?

I use a [helper script to give YCSB the correct options to split loading and running across hosts](https://gist.github.com/busbey/c26ad8856d4a9434665b), to the extent that YCSB currently supports doing so. I haven't updated the published version in some time, so you'd likely have to make some adjustments for the current version of YCSB.

**Comment by busbey** [comment]
any update here? did the example script answer your questions?

**Comment by busbey** [comment]
Closing as stale. If you have follow-up questions on the same topic please reopen.
