### ISSUE TITLE
remove deprecated Cassandra client

### ISSUE THREAD

**Issue by busbey** [brianfrankcooper/YCSB#794]
the old cassandra client was deprecated back in December (#537) with a notice that it would probably get pulled in March.

Now that it's been ~6 months, let's get it removed.

Personally, I think we should delete the current `cassandra` module, rename the `cassandra2` module to `cassandra`, and then make it so using `cassandra2` on the CLI still works but gives a deprecation warning that it's moved to the name `cassandra` now.

**Comment by cmatser** [comment]
Agreed.  The current `cassandra` module is far outdated.  Renaming the `cassandra2` module sounds like the right move.  As for the CLI I think you are suggesting that invoking the binding `cassandra-cql` will call what is currently `cassandra2-cql` and that invoking `cassandra2-cql` will call the same binding but additionally provide a deprecation warning.  That sounds fine to me.
