### ISSUE TITLE
how to draw up the graphs by those testing-results in mongoDB?

### ISSUE THREAD

**Issue by hzruandd** [brianfrankcooper/YCSB#799]

**Comment by busbey** [comment]
Are you looking for advice on generating charts of latency results? Or something else?

**Comment by busbey** [comment]
If you mean charting the results, currently folks use post-processing tools to chart what they're interested in. In particular, if you use the feature to export HDRHistogram log files, then you can use [that projects web-based plotting tool](http://hdrhistogram.github.io/HdrHistogram/plotFiles.html) to make charts.

**Comment by busbey** [comment]
did this answer your question?

**Comment by busbey** [comment]
Closing as stale. If you have follow-up questions on this same topic please reopen.
