### ISSUE TITLE
HELP!!! Error while building from source riak binding...

### ISSUE THREAD

**Issue by RuyiOne** [brianfrankcooper/YCSB#806]
While loading riak I get this error from building the riak-binding from source. Need clues to resolving this cheers.

 ./bin/ycsb load riak -s -P workloads/workloada > results/riak1.txt
[WARN]  Running against a source checkout. In order to get our runtime dependencies we'll have to invoke Maven. Depending on the state of your system, this may take ~30-45 seconds
[DEBUG]  Running 'mvn -pl com.yahoo.ycsb:riak-binding -am package -DskipTests dependency:build-classpath -DincludeScope=compile -Dmdep.outputFilterFile=true'
java -cp /root/YCSB-master/riak/conf:/root/YCSB-master/riak/target/riak-binding-0.11.0-SNAPSHOT.jar:/root/.m2/repository/org/apache/htrace/htrace-core4/4.1.0-incubating/htrace-core4-4.1.0-incubating.jar:/root/.m2/repository/io/netty/netty-all/4.0.33.Final/netty-all-4.0.33.Final.jar:/root/.m2/repository/joda-time/joda-time/2.1/joda-time-2.1.jar:/root/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.4/HdrHistogram-2.1.4.jar:/root/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-joda/2.2.2/jackson-datatype-joda-2.2.2.jar:/root/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.4/jackson-core-asl-1.9.4.jar:/root/.m2/repository/com/basho/riak/riak-client/2.0.5/riak-client-2.0.5.jar:/root/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.2.2/jackson-core-2.2.2.jar:/root/.m2/repository/com/google/collections/google-collections/1.0/google-collections-1.0.jar:/root/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.2.2/jackson-annotations-2.2.2.jar:/root/.m2/repository/org/slf4j/slf4j-api/1.6.4/slf4j-api-1.6.4.jar:/root/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.2.2/jackson-databind-2.2.2.jar:/root/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.4/jackson-mapper-asl-1.9.4.jar:/root/YCSB-master/core/target/core-0.11.0-SNAPSHOT.jar com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.riak.RiakKVClient -s -P workloads/workloada -load
YCSB Client 0.11.0-SNAPSHOT
Command line: -db com.yahoo.ycsb.db.riak.RiakKVClient -s -P workloads/workloada -load
Loading workload...
Starting test.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2016-07-21 16:11:43:373 0 sec: 0 operations; est completion in 0 seconds
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Error inserting, not retrying any more. number of attempts: 1Insertion Retry Limit: 0
2016-07-21 16:11:43:617 0 sec: 0 operations; est completion in 106751991167300 days 15 hours [CLEANUP: Count=1, Max=719, Min=719, Avg=719, 90=719, 99=719, 99.9=719, 99.99=719] [INSERT: Count=0, Max=0, Min=9223372036854775807, Avg=�, 90=0, 99=0, 99.9=0, 99.99=0] [INSERT-FAILED: Count=1, Max=54943, Min=54912, Avg=54928, 90=54943, 99=54943, 99.9=54943, 99.99=54943]

**Comment by busbey** [comment]
Please download the convenience tarball of binaries for the 0.10.0 release and try using those.

Also please include your riak version.

**Comment by RuyiOne** [comment]
hi @busbey , got similar error... with ycsb-0.10.0. my riak version is 2.1.3.......

**Comment by busbey** [comment]
can you paste what the output looks like?

have you verified that your riak installation is working correctly? does anything show up in its logs?

**Comment by RuyiOne** [comment]
output from loading ycsb 

` ./bin/ycsb load riak -s -P workloads/workloadf > resu                                                                                        lts/riaktest.txt
java -cp /root/ycsb-0.10.0/riak-binding/conf:/root/ycsb-0.10.0/conf:/root/ycsb-0                                                                                        .10.0/lib/core-0.10.0.jar:/root/ycsb-0.10.0/lib/htrace-core4-4.1.0-incubating.ja                                                                                        r:/root/ycsb-0.10.0/lib/jackson-mapper-asl-1.9.4.jar:/root/ycsb-0.10.0/lib/jacks                                                                                        on-core-asl-1.9.4.jar:/root/ycsb-0.10.0/lib/HdrHistogram-2.1.4.jar:/root/ycsb-0.                                                                                        10.0/riak-binding/lib/joda-time-2.1.jar:/root/ycsb-0.10.0/riak-binding/lib/googl                                                                                        e-collections-1.0.jar:/root/ycsb-0.10.0/riak-binding/lib/jackson-core-2.2.2.jar:                                                                                        /root/ycsb-0.10.0/riak-binding/lib/riak-client-2.0.5.jar:/root/ycsb-0.10.0/riak-                                                                                        binding/lib/jackson-datatype-joda-2.2.2.jar:/root/ycsb-0.10.0/riak-binding/lib/j                                                                                        ackson-annotations-2.2.2.jar:/root/ycsb-0.10.0/riak-binding/lib/jackson-databind                                                                                        -2.2.2.jar:/root/ycsb-0.10.0/riak-binding/lib/riak-binding-0.10.0.jar:/root/ycsb                                                                                        -0.10.0/riak-binding/lib/netty-all-4.0.33.Final.jar:/root/ycsb-0.10.0/riak-bindi                                                                                        ng/lib/slf4j-api-1.6.4.jar com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.riak.Riak                                                                                        KVClient -s -P workloads/workloadf -load
YCSB Client 0.10.0
Command line: -db com.yahoo.ycsb.db.riak.RiakKVClient -s -P workloads/workloadf                                                                                         -load
Loading workload...
Starting test.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further detail                                                                                        s.
2016-07-22 03:23:56:174 0 sec: 0 operations; est completion in 0 seconds
DBWrapper: report latency for each error is false and specific error codes to tr                                                                                        ack for latency are: []
Error inserting, not retrying any more. number of attempts: 1Insertion Retry Lim                                                                                        it: 0
2016-07-22 03:23:56:567 0 sec: 0 operations; est completion in 106751991167300 d                                                                                        ays 15 hours [CLEANUP: Count=1, Max=547, Min=547, Avg=547, 90=547, 99=547, 99.9=                                                                                        547, 99.99=547] [INSERT: Count=0, Max=0, Min=9223372036854775807, Avg=�, 90=0, 9                                                                                        9=0, 99.9=0, 99.99=0] [INSERT-FAILED: Count=1, Max=32527, Min=32512, Avg=32520,                                                                                         90=32527, 99=32527, 99.9=32527, 99.99=32527]
`

my nodes are currently on a different ip from 127.0.0.1 though.......

could this be the challenge?

**Comment by busbey** [comment]
Right. You need to tell the Riak binding where to connect or it will default to localhost.

**Comment by RuyiOne** [comment]
got past the earlier error but a new one has come up.....


` ./bin/ycsb load riak -s -P workloads/workloada -p "ri                                                                                        ak.hosts=127.0.0.1" -p "riak.port=8087" > results/riaktest.txt
java -cp /root/ycsb-0.10.0/riak-binding/conf:/root/ycsb-0.10.0/conf:/root/ycsb-0                                                                                        .10.0/lib/core-0.10.0.jar:/root/ycsb-0.10.0/lib/htrace-core4-4.1.0-incubating.ja                                                                                        r:/root/ycsb-0.10.0/lib/jackson-mapper-asl-1.9.4.jar:/root/ycsb-0.10.0/lib/jacks                                                                                        on-core-asl-1.9.4.jar:/root/ycsb-0.10.0/lib/HdrHistogram-2.1.4.jar:/root/ycsb-0.                                                                                        10.0/riak-binding/lib/joda-time-2.1.jar:/root/ycsb-0.10.0/riak-binding/lib/googl                                                                                        e-collections-1.0.jar:/root/ycsb-0.10.0/riak-binding/lib/jackson-core-2.2.2.jar:                                                                                        /root/ycsb-0.10.0/riak-binding/lib/riak-client-2.0.5.jar:/root/ycsb-0.10.0/riak-                                                                                        binding/lib/slf4j-nop-1.7.21.jar:/root/ycsb-0.10.0/riak-binding/lib/jackson-data                                                                                        type-joda-2.2.2.jar:/root/ycsb-0.10.0/riak-binding/lib/jackson-annotations-2.2.2                                                                                        .jar:/root/ycsb-0.10.0/riak-binding/lib/jackson-databind-2.2.2.jar:/root/ycsb-0.                                                                                        10.0/riak-binding/lib/riak-binding-0.10.0.jar:/root/ycsb-0.10.0/riak-binding/lib                                                                                        /netty-all-4.0.33.Final.jar:/root/ycsb-0.10.0/riak-binding/lib/slf4j-api-1.6.4.j                                                                                        ar com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.riak.RiakKVClient -s -P workloads                                                                                        /workloada -p riak.hosts=127.0.0.1 -p riak.port=8087 -load
YCSB Client 0.10.0
Command line: -db com.yahoo.ycsb.db.riak.RiakKVClient -s -P workloads/workloada                                                                                         -p riak.hosts=127.0.0.1 -p riak.port=8087 -load
Loading workload...
Starting test.
2016-07-25 20:39:22:874 0 sec: 0 operations; est completion in 0 seconds
DBWrapper: report latency for each error is false and specific error codes to tr                                                                                        ack for latency are: []
Error inserting, not retrying any more. number of attempts: 1Insertion Retry Lim                                                                                        it: 0
2016-07-25 20:39:23:123 0 sec: 0 operations; est completion in 106751991167300 d                                                                                        ays 15 hours [CLEANUP: Count=1, Max=562, Min=562, Avg=562, 90=562, 99=562, 99.9=                                                                                        562, 99.99=562] [INSERT: Count=0, Max=0, Min=9223372036854775807, Avg=�, 90=0, 9                                                                                        9=0, 99.9=0, 99.99=0] [INSERT-FAILED: Count=1, Max=51231, Min=51200, Avg=51216,                                                                                         90=51231, 99=51231, 99.9=51231, 99.99=51231]
`

I set up three riak and put them in a cluster.... what else?

**Comment by busbey** [comment]
it looks like you're still telling YCSB that the riak hosts are on localhost.

**Comment by RuyiOne** [comment]
well I have changed my settings so that my riak nodes are on localhost.

**Comment by RuyiOne** [comment]
Please can any one help me.......


`./bin/ycsb load riak -s -P workloads/workloada -p "riak.hostname=127.0.0.1" -p "riak.port=8087" > results/redistest.txt
[WARN]  Running against a source checkout. In order to get our runtime dependencies we'll have to invoke Maven. Depending on the state of your system, this may take ~30-45 seconds
[DEBUG]  Running 'mvn -pl com.yahoo.ycsb:riak-binding -am package -DskipTests dependency:build-classpath -DincludeScope=compile -Dmdep.outputFilterFile=true'
java -cp /root/YCSB-master/riak/conf:/root/YCSB-master/riak/target/riak-binding-0.11.0-SNAPSHOT.jar:/root/.m2/repository/org/apache/htrace/htrace-core4/4.1.0-incubating/htrace-core4-4.1.0-incubating.jar:/root/.m2/repository/io/netty/netty-all/4.0.33.Final/netty-all-4.0.33.Final.jar:/root/.m2/repository/joda-time/joda-time/2.1/joda-time-2.1.jar:/root/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.4/HdrHistogram-2.1.4.jar:/root/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-joda/2.2.2/jackson-datatype-joda-2.2.2.jar:/root/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.4/jackson-core-asl-1.9.4.jar:/root/.m2/repository/com/basho/riak/riak-client/2.0.5/riak-client-2.0.5.jar:/root/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.2.2/jackson-core-2.2.2.jar:/root/.m2/repository/com/google/collections/google-collections/1.0/google-collections-1.0.jar:/root/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.2.2/jackson-annotations-2.2.2.jar:/root/.m2/repository/org/slf4j/slf4j-api/1.6.4/slf4j-api-1.6.4.jar:/root/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.2.2/jackson-databind-2.2.2.jar:/root/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.4/jackson-mapper-asl-1.9.4.jar:/root/YCSB-master/core/target/core-0.11.0-SNAPSHOT.jar com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.riak.RiakKVClient -s -P workloads/workloada -p riak.hostname=127.0.0.1 -p riak.port=8087 -load
YCSB Client 0.11.0-SNAPSHOT
Command line: -db com.yahoo.ycsb.db.riak.RiakKVClient -s -P workloads/workloada -p riak.hostname=127.0.0.1 -p riak.port=8087 -load
Loading workload...
Starting test.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2016-07-27 16:46:11:047 0 sec: 0 operations; est completion in 0 seconds
DEBUG ENABLED. Configuration parameters:
-----------------------------------------
Hosts: [127.0.0.1]
Port: 8087
Bucket Type: ycsb
R Val: 1
W Val: 1
Read Retry Count: 5
Wait Time Before Retry: 200 ms
Transaction Time Limit: 10 s
Consistency model: Strong
Strong Consistent Scan Transactions NOT allowed.
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Unable to insert key user6284781860667377211. Reason: java.util.concurrent.ExecutionException: com.basho.riak.client.core.netty.RiakResponseException: no_type
Error inserting, not retrying any more. number of attempts: 1Insertion Retry Limit: 0
2016-07-27 16:46:11:339 0 sec: 0 operations; est completion in 106751991167300 days 15 hours [CLEANUP: Count=1, Max=594, Min=594, Avg=594, 90=594, 99=594, 99.9=594, 99.99=594] [INSERT: Count=0, Max=0, Min=9223372036854775807, Avg=�, 90=0, 99=0, 99.9=0, 99.99=0] [INSERT-FAILED: Count=1, Max=55967, Min=55936, Avg=55952, 90=55967, 99=55967, 99.9=55967, 99.99=55967]`


debug-enabled..... shows the following....

**Comment by busbey** [comment]
please stick with running from the 0.10.0 release binary tarball instead of source.

Did you follow the instructions [from the riak binding README on creating an appropriate bucket-type](https://github.com/brianfrankcooper/YCSB/tree/0.10.0/riak#creating-a-bucket-type-to-use-with-ycsb)?

**Comment by RuyiOne** [comment]
Thanks, I missed out on following that instruction earlier....
