### ISSUE TITLE
Do I need DataStax to benchmark Cassandra? 

### ISSUE THREAD

**Issue by jabirfatah91** [brianfrankcooper/YCSB#818]
I want to benchmark Cassandra with the core workload. According to the instruction I need to create table in the Cassandra database. Now my question is where do I create the table? Do I need to install a Cassandra management tool like DataStax? If so, how do I associate that table (created in datastax) while loading the workload into the database?

**Comment by risdenk** [comment]
Any reason for the cross post? Looks like this was already posted and closed in #811

The Cassandra binding README has information about how to create a table with cqlsh.

**Comment by jabirfatah91** [comment]
risdek, thank you for your quick reply. I closed the issue because nobody was answering my question, and I thought it is better to close it than keeping it open without having any reply. However, now I feel that I should really get help.

Yes, the Cassandra has read me file, but the file doesn't say how do I communicate with the usertable created in an external database (i.e. Cassandra) by using YCSB.

My current progress:
I can access/interact with YCSB through Python executable file by writing command on windows command:
```
cd C:\ycsb
"C:\Python27\python.exe" bin\ycsb
```
By using Cassandra CQL shell, I have created a table:

```
create keyspace mykeyspace WITH REPLICATION = {'class' : 'SimpleStrategy', 'replication_factor': 3 };
use mykeyspace;
create table myusertable1 (user_id PRIMARY KEY, fname text, lname text);
insert into myusertable1 (user_id PRIMARY KEY, fname text, lname text) VALUES (123,'Fatah', 'Jabir');
```
Now my question is how do I load the workload into the table and execute it?

**Comment by busbey** [comment]
Hiya!

some various docs to read through:

1. for running ycsb commands, generally, see [our guide for proper installation on Windows](https://github.com/brianfrankcooper/YCSB/wiki/Prerequisites-for-Windows). It sounds like you have this generally down. Just remember that when other docs talk about running YCSB with particular cli args, you'll be using `"C:\Python27\python.exe" bin\ycsb`
1. The docs on [Core Workloads](https://github.com/brianfrankcooper/YCSB/wiki/Core-Workloads) describes what the various example workloads are meant to simulate
1. The [README for the Cassandra2 binding](https://github.com/brianfrankcooper/YCSB/blob/0.10.0/cassandra2/README.md#cassandra-configuration-parameters) describes what connection parameters you'll need to use (probably for the cluster hosts, port, authentication information, and table name)
1. Finally load / run whatever test you plan to do. For example, to load and run workload a with the default 1000 records and 1000 operations
```
"C:\Python27\python.exe" bin\ycsb load basic -P workloads/workloada
"C:\Python27\python.exe" bin\ycsb run basic -P workloads/workloada
```

**Comment by jabirfatah91** [comment]
Hello again!
Thanks for the cooperation. I am really trying to follow you but now I stuck in the middle. In the point 3 you mentioned the README file to connection parameters. But the instruction, I guess, started from the middle of nowhere. I just do not know where to write the hosts,port, etc. 

**1.** In short, after creating table, where in command line (inside which directory, i.e. ycsb) I should write those parameters and how? Something similar as shown below?
`host(localhost), port(9042);`
 _**1.1.**_ Can you please provide me an example of a parameter configuration?

**2.** Should I use windows command line or Cassandra cql shell to write those parameters?

_I am looking forward to hear from you._

**Comment by kruthar** [comment]
You'll want to run your ycsb commands from wherever you installed YCSB. Recalling  @busbey's example invocations:
```
"C:\Python27\python.exe" bin\ycsb load basic -P workloads/workloada
"C:\Python27\python.exe" bin\ycsb run basic -P workloads/workloada
```
The `bin/ycsb` part is actually a relative path to the ycsb run script inside the bin directory, which is inside of your YCSB installation.

About the parameters you have two options:

1. Add your properties to the workload file which is specified by the `workloads/workloada` relative path in the commands above. Just open up that file and add in the parameters required to connect to your Cassandra installation, you can find out more about the available properties here: https://github.com/brianfrankcooper/YCSB/tree/master/cassandra.
2. Or, you can add your properties directly to your command like so:
```
"C:\Python27\python.exe" bin\ycsb load basic -P workloads/workloada -p hosts=127.0.0.1 -p port=8080
```

As for the specific properties and their values that you will need, that will depend on your installation of Cassandra.

**Comment by jabirfatah91** [comment]
Thanks for pulling me one step up. After all, there seems to be failure at the edge of success. I am getting the error (attached in the file) while loading the workload into the table. More specifically, the error is : **Unconfigure table _usertable_**. What I am guessing- perhaps, there is something wrong with my table creation in Cassandra. 
(1) Do I missing defining COLUMN FAMILY? as the guideline says, 
> For example, in Cassandra, you must define "column families" in addition to keyspaces. 

(2) If so, what would be the right Query to define column family, in addition to the query I already have used to create table?
(3) Or what else could be the reason that the command is unable to load?

**Comment by busbey** [comment]
Please ensure you followed the instructions in the [README on setting up Cassandra through the cqlsh prompt](https://github.com/brianfrankcooper/YCSB/tree/0.10.0/cassandra2#creating-a-table-for-use-with-ycsb)

**Comment by jabirfatah91** [comment]
Thank you for supporting me, I got great help and I am on the right track. I may post new issue about Riak, but for now I would like to close this issue.
