### ISSUE TITLE
ycsb can not work by  multiprocess？

### ISSUE THREAD

**Issue by shuyuanbingbing** [brianfrankcooper/YCSB#821]
cpu:8,
mem,7G,
disk,486GB
mongo,3.2.6

**top result->:**
Cpu0  :  1.4%us,  1.0%sy,  0.0%ni, 97.6%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu1  :  0.3%us,  0.0%sy,  0.0%ni, 97.7%id,  2.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu2  : 64.0%us,  2.7%sy,  0.0%ni, 33.3%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu3  :  0.0%us,  0.0%sy,  0.0%ni,100.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu4  :  0.0%us,  0.0%sy,  0.0%ni,100.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu5  :  0.3%us,  0.0%sy,  0.0%ni, 99.7%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu6  :  0.3%us,  0.0%sy,  0.0%ni, 99.7%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu7  :  0.0%us,  0.0%sy,  0.0%ni,100.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st

**At the same time, mongostat result->:**

insert query update delete getmore command % dirty % used flushes vsize  res qr|qw ar|aw netIn netOut conn                      time
   1931    *0     *0     *0       0     2|0     0.1   19.4       0  8.7G 8.4G   0|0   0|0  221k    89k    6 2016-08-09T11:02:04+08:00
  3967    *0     *0     *0       0     3|0     0.1   19.5       0  8.7G 8.4G   0|0   0|0  229k    91k    6 2016-08-09T11:02:05+08:00
  2870    *0     *0     *0       0     3|0     0.1   19.5       0  8.7G 8.4G   0|0   0|0  206k    86k    6 2016-08-09T11:02:06+08:00
   957    *0     *0     *0       0     2|0     0.1   19.5       0  8.7G 8.4G   0|0   0|0  227k    90k    6 2016-08-09T11:02:07+08:00
   886    *0     *0     *0       0     2|0     0.1   19.5       0  8.7G 8.4G   0|0   0|0  210k    86k    6 2016-08-09T11:

**ycsb result->:**
[OVERALL], RunTime(ms), 7004044.0
**[OVERALL], Throughput(ops/sec), 2498.5565481884464**
[TOTAL_GCS_PS_Scavenge], Count, 14116.0
[TOTAL_GC_TIME_PS_Scavenge], Time(ms), 36446.0
[TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.5203565254587207
[TOTAL_GCS_PS_MarkSweep], Count, 88.0
[TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 2638.0
[TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.03766395528069212
[TOTAL_GCs], Count, 14204.0
[TOTAL_GC_TIME], Time(ms), 39084.0
[TOTAL_GC_TIME_%], Time(%), 0.5580204807394128
[CLEANUP], Operations, 16.0
[CLEANUP], AverageLatency(us), 18652.5625
[CLEANUP], MinLatency(us), 2.0
[CLEANUP], MaxLatency(us), 298495.0
[CLEANUP], 95thPercentileLatency(us), 12.0
[CLEANUP], 99thPercentileLatency(us), 298495.0
[INSERT], Operations, 1.6625986E7
[INSERT], AverageLatency(us), 5730.168577851563
[INSERT], MinLatency(us), 164.0
[INSERT], MaxLatency(us), 1.0674175E7
[INSERT], 95thPercentileLatency(us), 26191.0
[INSERT], 99thPercentileLatency(us), 65439.0
[INSERT], Return=OK, 16625986
[READ], Operations, 874014.0
[READ], AverageLatency(us), 18701.229844144375
[READ], MinLatency(us), 118.0
[READ], MaxLatency(us), 1.0534911E7
[READ], 95thPercentileLatency(us), 56063.0
[READ], 99thPercentileLatency(us), 111487.0
[READ], Return=OK, 874014

**Comment by busbey** [comment]
what's your ycsb version? what's the command line you used to start things? what's your question?

**Comment by shuyuanbingbing** [comment]
ycsb version is the newest.

./bin/ycsb load mongodb-async -P workloads/workloada

the tps is only 2498, just like a shit.

**Comment by busbey** [comment]
> ycsb version is the newest.

does this mean the 0.10.0 release?

> ./bin/ycsb load mongodb-async -P workloads/workloada

This set of options means you are using the default of a single worker thread. please read [the "Running A Workload" guide, esp section 4 on setting options](https://github.com/brianfrankcooper/YCSB/wiki/Running-a-Workload#step-4-choose-the-appropriate-runtime-parameters) for guidance on generating a heavier workload.

**Comment by shuyuanbingbing** [comment]
thanks, in my workloada:
recordcount=10000000
operationcount=10000000
workload=com.yahoo.ycsb.workloads.CoreWorkload

readallfields=true

readproportion=0.5
updateproportion=0.5
scanproportion=0
insertproportion=0

requestdistribution=zipfian
mongodb.url=mongodb://10.9.1.xxx:27017/ycsb?w=1
exportfile=run1.txt
**threadcount=16**

**Comment by busbey** [comment]
try setting it on the command line.

**Comment by shuyuanbingbing** [comment]
could you paste your test results?

**Comment by busbey** [comment]
I'm not currently running any tests. Did setting the number of threads on the command line instead of as a property work?

**Comment by kruthar** [comment]
From your initial results it looks like you are running on 16 threads:
```
[CLEANUP], Operations, 16.0
```
16 cleanup operations is a fair indicator of 16 threads.

Have you run this same workload on a single thread and compared the TPS?

**Comment by shuyuanbingbing** [comment]
**official data**
 [https://www.mongodb.com/blog/post/performance-testing-mongodb-30-part-1-throughput-improvements-measured-ycsb](url)

Our test results, in contrast, poor too far away

**Comment by risdenk** [comment]
@shuyuanbingbing This is most likely your hardware. You are comparing apples and oranges:

Legend: You -> Blog
Ram: 7GB -> 128GB
Disk: 486GB spinning? -> 2x 960GB SSD RAID
CPU: 8 CPUS -> 20 CPUS (2 deca core CPUS)

Additionally the blog you referenced has multiple machines. 

This doesn't seem like an issue with YCSB so going to close this issue. Reopen if you feel differently. Thanks!
