### ISSUE TITLE
cassandra tests should use prepared statements rather than the query builder

### ISSUE THREAD

**Issue by rustyrazorblade** [brianfrankcooper/YCSB#822]

**Comment by busbey** [comment]
duplicate of #458 probably?

Interested in putting together a PR?

**Comment by rustyrazorblade** [comment]
oops, sorry, i searched for open cassandra issues and didn't see it.  I think I can put together a PR for this, it looks reasonably straightforward.

**Comment by risdenk** [comment]
Closing as duplicate of #458
