### ISSUE TITLE
links to yahoo research paper are broken

### ISSUE THREAD

**Issue by stevencasey** [brianfrankcooper/YCSB#823]
on wiki page https://github.com/brianfrankcooper/YCSB/wiki/Papers-and-Presentations link to https://research.yahoo.com/node/3202

**Comment by stevencasey** [comment]
https://research.yahoo.com/node/3202

**Comment by busbey** [comment]
Oof. @brianfrankcooper do you have your paper hosted elseweb?

**Comment by at15** [comment]
The one you can found via google is https://www.cs.duke.edu/courses/fall13/cps296.4/838-CloudPapers/ycsb.pdf But this may not be a proper link since it's just the instructor put the reading materials online.

**Comment by katsel** [comment]
Alternative sources for the pdf currently are http://s.yimg.com/ge/labs/v1/files/ycsb.pdf and http://www.brianfrankcooper.net/home/publications/ycsb.pdf

**Comment by risdenk** [comment]
Thanks @katsel! I updated the Papers and Presentations page with details.
