### ISSUE TITLE
status updates always use plural nouns

### ISSUE THREAD

**Issue by madrob** [brianfrankcooper/YCSB#825]
From my logs when running with status reporting enabled:

> 2016-08-16 12:09:55:708 7790 sec: 67767950 operations; 9577.7 current ops/sec; est completion in 1 hours 1 minutes [INSERT: Count=95777, Max=537087, Min=181, Avg=3077.51, 90=3907, 99=22319, 99.9=75519, 99.99=467711] 

This should say "est completion in 1 hour 1 minute" instead of using hours/minutes plural.

**Comment by risdenk** [comment]
@madrob thanks for the report. Would you be willing to contribute a PR?

**Comment by busbey** [comment]
fixed by #1029
