### ISSUE TITLE
Do I need to run Cassandra and Riak on some cloud environments before I benchmark them?

### ISSUE THREAD

**Issue by jabirfatah91** [brianfrankcooper/YCSB#829]
I have installed Cassandra (from DataStax) and Riak (from basho) in my computer. If I mean to benchmark them (in order to understand/measure their consistency level) with varieties workload and record size, 

(1) do I need to use any public datacentre/cloud environment (e.g., Google cloud, Amazon) before I benchmark? 
(2) Or, the Databases are already running in some cloud environments? If so How do I know that?
(3) During benchmarking, I haven't created/define any node numbers or cluster- then how this loading phase outputs the data centre name (see attachment below)?

[UPDATE: These might be vague questions to ask, but please- I will be grateful if someone answer me.]

![Output](https://cloud.githubusercontent.com/assets/11571725/17908804/35a0434a-6982-11e6-8d6b-e5b8203448e2.PNG)

**Comment by cmatser** [comment]
Your post leaves me with more questions than I have answers for you...

Basically, I feel you need to think about what you are looking for in a benchmark.  You should try to match your benchmark testing setup to the environment you plan to have in production.  The closer you can duplicate your target environment the more relevant your benchmark will be.

Regarding your current setup with a nosql database on your computer.  There's no problem in running a test there.  It will work, and if this setup matches your production environment, then you'll have a good benchmark.

Chrisjan

**Comment by jabirfatah91** [comment]
Hello, thank you for the comment. I have some basics understanding now. Actually I dont have any specific production environment standard. The benchmarking is purely for my own, for my own interest.

So this question will draw an end of this post hopefully.

**When I load data (e.g., 1000 records) into the database, where do they get stored? Is it in my local machine, or any remote server (e.g., Cassandra's ow n data centre/server), which I doubt obviously?**

**Comment by cmatser** [comment]
When you download/install Cassandra (or Riak) on your computer, you are installing a full database server.  It does not talk to the cloud or any other server.  It is a contained solution/product.  So, "datacenter1" and "rack1" are default names that are actually on your computer.  Data stored there will be stored on your physical hard drive.

Cassandra has the ability to work in clusters, ie on multiple machines and/or at multiple data centers.  You can setup your own cassandra cluster and give them names like datacenter2, 3, 4, etc.  This cluster will work together to represent a single database instance.

Chrisjan
