### ISSUE TITLE
want to check large garbage collection overhead

### ISSUE THREAD

**Issue by SeungukHan** [brianfrankcooper/YCSB#836]
Hi, folks.
I'm newbie on YCSB and Cassandra.
I just installed and ran YCSB workloadb on Cassandra in order to check garbage collection overhead.
But the overhead is too small (about 0.5 ~ 1% of total execution time).
Many documents related to Cassandra note about garbage collection overhead and tuning methods.
So I still think there is a way to make the workload using memory heavily.

Can I get any advice?

**Comment by cmatser** [comment]
I haven't tested for this, but I wanted to suggest playing with memory settings on your Cassandra server.  Doing the opposite of what it suggests for tuning against overhead should give you more overhead.

Just a thought.

**Comment by SeungukHan** [comment]
thanks cmaster!
I tried YCSB benchmark several times with your advise, but still the results showed small overhead.
What the result was close is 13% of total execution time for garbage collection overhead when the data set is 10GB (Load only) and heap size is 4GB on 8 core.

What I wonder is my benchmark environment.
I have executed YCSB benchmark on single node cassandra and 
did this condition largely effect on garbage collection overhead?

once again thanks cmaster ;)

**Comment by risdenk** [comment]
@SeungukHan Can you reiterate your question? Not sure what you are asking.

**Comment by SeungukHan** [comment]
Hi, risdenk.

Actually I use YCSB benchmark with the object of checking JVM garbage collection overhead on Cassandra.
But against my expectation, there is few garbage collection overhead while Cassandra works.

I run Cassandra with stand-alone mode. (8-cores, 16GB main memory)

So far, I have done many experiments with different Cassandra tuning. (cassandra.yaml file)
And I found the tuning values where garbage collection overhead can not be neglected.

But still on default tuning value, Cassandra works well and garbage collection overhead is too small.

Thank you for your attention.

**Comment by risdenk** [comment]
Ok not sure what else the YCSB project could do for you. This sounds more specific to Cassandra. Maybe asking on the Cassandra mailing lists would get you some helpful information.
