### ISSUE TITLE
not able to compile,  POM for com.yahoo.ycsb:core:jar:0.12.0-SNAPSHOT is missing

### ISSUE THREAD

**Issue by kennethlwk** [brianfrankcooper/YCSB#839]
[log.txt](https://github.com/brianfrankcooper/YCSB/files/461646/log.txt)
Hi,

I am trying to do execute the ycsb with maven, but it is complaining the  POM for com.yahoo.ycsb:core:jar:0.12.0-SNAPSHOT is missing. Just wondering is there something that Ihave to configured?

**Command executed on linus shell**
mvn -pl com.yahoo.ycsb:mongodb-binding -am clean package

**Error message**
/applications/YCSB2/YCSB/mongodb (master)*$ mvn -pl com.yahoo.ycsb:mongodb-binding -am clean package
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building MongoDB Binding 0.12.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.yahoo.ycsb:core:jar:0.12.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.995s
[INFO] Finished at: Thu Sep 08 14:40:25 CEST 2016
[INFO] Final Memory: 13M/481M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project mongodb-binding: Could not resolve dependencies for project com.yahoo.ycsb:mongodb-binding:jar:0.12.0-SNAPSHOT: Could not find artifact com.yahoo.ycsb:core:jar:0.12.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by risdenk** [comment]
@kennethlwk is this still an issue? I just pulled latest and ran the command you specified `mvn -pl com.yahoo.ycsb:mongodb-binding -am clean package` and it works.

**Comment by risdenk** [comment]
Closing due to no update.
