### ISSUE TITLE
Cassandra Support

### ISSUE THREAD

**Issue by minghan** [brianfrankcooper/YCSB#84]
Hi,

I noticed that in the Cassandra Client patch 5 months ago (https://github.com/brianfrankcooper/YCSB/commit/012873a01cae914bf6f04eb5de3d94f59a8405e2),
the Cassandra client version was downgraded from 1.0.7 to 0.7.0, in order to ensure backward compatibility in compiling CassandraClient7.java and CassandraClient8.java.

I was wondering if using the older version of the client wouldn't be ideal for benchmarking purposes?

Thanks,
minghan

**Comment by busbey** [comment]
The Cassandra version is now 1.2.9.
