### ISSUE TITLE
 Could not find or load main class com.yahoo.ycsb.CommandLine

### ISSUE THREAD

**Issue by helin2206** [brianfrankcooper/YCSB#841]
What problem, to help solve the next

**Comment by helin2206** [comment]
/bin/ycsb shell cassandra2-cql -p cassandra2-cql.host192.145.50.142 -p cassandra2-cql.port=9160
/opt/ces/jdk/bin/java -cp /tmp/ycsb/ycsb-0.10.0/cassandra2-binding/conf:/tmp/ycsb/ycsb-0.10.0/conf:/tmp/ycsb/ycsb-0.10.0/cassandra2-binding/lib/cassandra-driver-core-3.0.0.jar:/tmp/ycsb/ycsb-0.10.0/cassandra2-binding/lib/guava-16.0.1.jar com.yahoo.ycsb.CommandLine -db com.yahoo.ycsb.db.CassandraCQLClient -p cassandra2-cql.host192.145.50.142 -p cassandra2-cql.port=9160
Error: Could not find or load main class com.yahoo.ycsb.CommandLine

**Comment by cmatser** [comment]
Could you try using the newer startup scripts?  Either ycsb.sh or ycsb.bat depending on whether you have a linux or windows install.

I see from your output that ycsb's core-[version].jar is not on the classpath.  Hopefully, using the newer startup script will solve your issue.

Chrisjan

**Comment by risdenk** [comment]
Closing as stale. @helin2206 if still an issue please reopen.
