### ISSUE TITLE
Unable to run with ssl configuration

### ISSUE THREAD

**Issue by sff2578** [brianfrankcooper/YCSB#845]
My mongodb is set up to sslRequired, but i couldn't make it work
the command is
`./bin/ycsb load mongodb  -s -P workloads/workloada -p recordcount=10000 -threads 16 -p mongodb.url="mongodb://user:pass@localhost:27017/database?ssl=true" -p mongodb.auth="true"`
and the output is like

> com.mongodb.MongoSocketWriteException: Exception sending message
>         at com.mongodb.connection.InternalStreamConnection.translateWriteException(InternalStreamConnection.java:462) ~[mongo-java-driver-3.0.3.jar:na]
>         at com.mongodb.connection.InternalStreamConnection.sendMessage(InternalStreamConnection.java:205) ~[mongo-java-driver-3.0.3.jar:na]
>         at com.mongodb.connection.CommandHelper.sendMessage(CommandHelper.java:89) ~[mongo-java-driver-3.0.3.jar:na]
>         at com.mongodb.connection.CommandHelper.executeCommand(CommandHelper.java:32) ~[mongo-java-driver-3.0.3.jar:na]
>         at com.mongodb.connection.InternalStreamConnectionInitializer.initializeConnectionDescription(InternalStreamConnectionInitializer.java:83) ~[mongo-java-driver-3.0.3.jar:na]
>         at com.mongodb.connection.InternalStreamConnectionInitializer.initialize(InternalStreamConnectionInitializer.java:43) ~[mongo-java-driver-3.0.3.jar:na]
>         at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:115) ~[mongo-java-driver-3.0.3.jar:na]
>         at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:127) ~[mongo-java-driver-3.0.3.jar:na]
>         at java.lang.Thread.run(Thread.java:745) [na:1.7.0_111]
> Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
>         at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:963) ~[na:1.7.0_111]
>         at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1342) ~[na:1.7.0_111]
>         at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:719) ~[na:1.7.0_111]
>         at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:122) ~[na:1.7.0_111]
>         at com.mongodb.connection.SocketStream.write(SocketStream.java:75) ~[mongo-java-driver-3.0.3.jar:na]
>         at com.mongodb.connection.InternalStreamConnection.sendMessage(InternalStreamConnection.java:201) ~[mongo-java-driver-3.0.3.jar:na]
>         ... 7 common frames omitted
> Caused by: java.io.EOFException: SSL peer shut down incorrectly
>         at sun.security.ssl.InputRecord.read(InputRecord.java:482) ~[na:1.7.0_111]
>         at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:944) ~[na:1.7.0_111]
>         ... 12 common frames omitted
> 01:22:19.658 [cluster-ClusterId{value='57e4e63bf7492366ba513b75', description='null'}-localhost:27017] DEBUG org.mongodb.driver.cluster - Updating cluster description to  {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketWriteException: Exception sending message}, caused by {javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake}, caused by {java.io.EOFException: SSL peer shut down incorrectly}}]
> 01:22:20.174 [cluster-ClusterId{value='57e4e63bf7492366ba513b75', description='null'}-localhost:27017] DEBUG org.mongodb.driver.connection - Closing connection connectionId{localValue:2}

thanks

**Comment by allanbank** [comment]
SSL peer shut down incorrectly

That error usually means that the server is not expecting SSL or did not like something in the initial handshake message. Was there an error in the servers log?

**Comment by sff2578** [comment]
i'll check when i'm able to, but now i remember, when logging to the database, i need to ass --ssl --sslAllowInvalidCertificates options, does this have anything to do with the error? Thanks

**Comment by rainmanwy** [comment]
How about your JDK version.
https://github.com/escline/InstallCert

You may have a try this. I have met same problem before. And fix with this way

**Comment by risdenk** [comment]
Closing due to no update.
