### ISSUE TITLE
turn on reviews?

### ISSUE THREAD

**Issue by busbey** [brianfrankcooper/YCSB#855]
I'd like us to switch to using the new review system on github. we should be able to reflect at least part of our current policy (+1 required for merge), though I'm not sure if it will allow us to accurately capture the fact that we allow binding reviews from non-maintainers.

any concerns?

**Comment by risdenk** [comment]
I've been using the code reviews feature of Github since it came out. Made it a lot easier instead of the one off comments. Also easy to see if things were approved.

Having an original +1 should still work. No?

**Comment by busbey** [comment]
some examples where it was used thus far (at least maintainers can opt-in to use a review on individual issues), if folks wanna look for the checkmark:

* https://github.com/brianfrankcooper/YCSB/pull/854
* https://github.com/brianfrankcooper/YCSB/pull/842

**Comment by busbey** [comment]
> Having an original +1 should still work. No?

yep, I'm just not sure if we can make it provide the nice integrated check mark or auto-merging.

**Comment by risdenk** [comment]
> nice integrated check mark or auto-merging.

That would be cool.

**Comment by busbey** [comment]
It's not clear to me from looking at the options to enforce reviews if a self-review works, or if reviews can come from outsiders. later this weekend I'll make a test repo we can check.

**Comment by busbey** [comment]
reviews are on. things have been going okay.
