### ISSUE TITLE
Elastic in remote mode does not work

### ISSUE THREAD

**Issue by zagorulkinde** [brianfrankcooper/YCSB#856]
Hello! i'm faced the following:
`
./bin/ycsb load elasticsearch -s -P workloads/workloada -p path.home=$(pwd) -p es.remote=true -p cluster.name=elasticsearch -p es.newdb=true -p es.index.key=es.ycsb -p es.number_of_shards=1 -p es.number_of_replicas=0 -p es.hosts.list=127.0.0.1:9300`

/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/bin/java -cp /Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/elasticsearch-binding/conf:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/conf:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/commons-cli-1.3.1.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/compress-lzf-1.0.2.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/core-0.12.0-SNAPSHOT.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/elasticsearch-2.4.0.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/elasticsearch-binding-0.12.0-SNAPSHOT.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/guava-18.0.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/HdrHistogram-2.1.4.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/hppc-0.7.1.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/htrace-core4-4.1.0-incubating.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/jackson-core-2.8.1.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/jackson-core-asl-1.9.4.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/jackson-dataformat-cbor-2.8.1.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/jackson-dataformat-smile-2.8.1.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/jackson-dataformat-yaml-2.8.1.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/jackson-mapper-asl-1.9.4.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/jna-4.1.0.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/joda-convert-1.2.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/joda-time-2.9.4.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/jsr166e-1.1.0.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/lucene-analyzers-common-5.5.2.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/lucene-backward-codecs-5.5.2.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/lucene-core-5.5.2.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/lucene-grouping-5.5.2.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/lucene-highlighter-5.5.2.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/lucene-join-5.5.2.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/lucene-memory-5.5.2.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/lucene-misc-5.5.2.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/lucene-queries-5.5.2.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/lucene-queryparser-5.5.2.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/lucene-sandbox-5.5.2.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/lucene-spatial-5.5.2.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/lucene-spatial3d-5.5.2.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/lucene-suggest-5.5.2.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/netty-3.10.6.Final.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/securesm-1.0.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/snakeyaml-1.15.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/spatial4j-0.5.jar:/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT/lib/t-digest-3.0.jar com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.ElasticsearchClient -s -P workloads/workloada -p path.home=/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT -p es.remote=true -p cluster.name=elasticsearch -p es.newdb=true -p es.index.key=es.ycsb -p es.number_of_shards=1 -p es.number_of_replicas=0 -p es.hosts.list=127.0.0.1:9300 -load
YCSB Client 0.12.0-SNAPSHOT
Command line: -db com.yahoo.ycsb.db.ElasticsearchClient -s -P workloads/workloada -p path.home=/Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT -p es.remote=true -p cluster.name=elasticsearch -p es.newdb=true -p es.index.key=es.ycsb -p es.number_of_shards=1 -p es.number_of_replicas=0 -p es.hosts.list=127.0.0.1:9300 -load
Loading workload...
Starting test.
2016-10-03 19:01:58:686 0 sec: 0 operations; est completion in 0 seconds
` Elasticsearch starting node = elasticsearch
Elasticsearch node path.home = /Users/Dmitry/Developer/Sbt/Tests/YCSB/elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT
Elasticsearch Remote Mode = true
Elasticsearch Remote Hosts = 127.0.0.1:9300
Oct 03, 2016 7:01:58 PM org.elasticsearch.plugins.PluginsService <init>
INFO: [Mechamage] modules [], plugins [], sites []
Exception in thread "Thread-3" NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{127.0.0.1}{127.0.0.1:9300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)
	at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:288)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:348)
	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1221)
	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.exists(AbstractClient.java:1241)
	at com.yahoo.ycsb.db.ElasticsearchClient.init(ElasticsearchClient.java:148)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:99)
	at com.yahoo.ycsb.ClientThread.run(Client.java:418)
	at java.lang.Thread.run(Thread.java:745) `
2016-10-03 19:01:59:957 1 sec: 0 operations; est completion in 106751991167300 days 15 hours
[OVERALL], RunTime(ms), 1292.0
[OVERALL], Throughput(ops/sec), 0.0
[TOTAL_GCS_PS_Scavenge], Count, 1.0
[TOTAL_GC_TIME_PS_Scavenge], Time(ms), 7.0
[TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.541795665634675
[TOTAL_GCS_PS_MarkSweep], Count, 0.0
[TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 0.0
[TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.0
[TOTAL_GCs], Count, 1.0
[TOTAL_GC_TIME], Time(ms), 7.0
[TOTAL_GC_TIME_%], Time(%), 0.541795665634675

but

`→ curl localhost:9200                                                                                                                               [001b64d]
{
  "name" : "Unthinnk",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.4.0",
    "build_hash" : "ce9f0c7394dee074091dd1bc4e9469251181fc55",
    "build_timestamp" : "2016-08-29T09:14:17Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.2"
  },
  "tagline" : "You Know, for Search"
}

λ Dmitry [elasticsearch/target/ycsb-elasticsearch-binding-0.12.0-SNAPSHOT] at  master ✔
→ curl localhost:9300                                                                                                                               [001b64d]
This is not a HTTP port%`

Thank in advance!

**Comment by jasontedor** [comment]
This does not reproduce for me. Are you sure that Elasticsearch was running and available for requests when you attempted to run the load? Can you start the node again with `--logger.transport=TRACE` and provide the relevant logs here?

**Comment by zagorulkinde** [comment]
i'm using es from official docker image. I'll try to install es on my localhost and provide the relevant logs.

**Comment by zagorulkinde** [comment]
I have tried with vanilla elastic in remote mode deploys on my local machine. Actually it works fine!

**Comment by jasontedor** [comment]
Okay, then I'm going to assume that this is merely an issue with not correctly bridging to your Docker instance. Thanks for trying out both YCSB and Elasticsearch!

**Comment by aliakseihaidukou** [comment]
@jasontedor according to [this stackoverflow article](http://stackoverflow.com/questions/30231372/failed-to-connect-to-dockerized-elasticsearch-via-java-client) `client.transport.sniff` should be set to `false` to make the remote mode work with dockerized elastic. It is set to `true` here - https://github.com/brianfrankcooper/YCSB/blob/master/elasticsearch/src/main/java/com/yahoo/ycsb/db/ElasticsearchClient.java#L118

**Comment by risdenk** [comment]
@aliakseihaidukou another option is to correct set the network.publish_host for the ES running in the Docker container.
