### ISSUE TITLE
java.lang.ClassNotFoundException: com.yahoo.ycsb.workloads.CoreWorkload

### ISSUE THREAD

**Issue by ycmy2016** [brianfrankcooper/YCSB#867]
[root@jenkins YCSB-master]# mvn -pl com.yahoo.ycsb:mongodb-binding -am clean package
## T E S T S

Running com.yahoo.ycsb.db.OptionsSupportTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.077 sec
Running com.yahoo.ycsb.db.AsyncMongoDbClientTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.013 sec
Running com.yahoo.ycsb.db.MongoDbClientTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 sec

Results :

Tests run: 6, Failures: 0, Errors: 0, Skipped: 2

[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ mongodb-binding ---
[INFO] Building jar: /soft/YCSB-master/mongodb/target/mongodb-binding-0.12.0-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-dependency-plugin:2.10:copy-dependencies (stage-dependencies) @ mongodb-binding ---
[INFO] Copying mongodb-async-driver-2.0.1.jar to /soft/YCSB-master/mongodb/target/dependency/mongodb-async-driver-2.0.1.jar
[INFO] Copying logback-core-1.1.2.jar to /soft/YCSB-master/mongodb/target/dependency/logback-core-1.1.2.jar
[INFO] Copying mongo-java-driver-3.0.3.jar to /soft/YCSB-master/mongodb/target/dependency/mongo-java-driver-3.0.3.jar
[INFO] Copying logback-classic-1.1.2.jar to /soft/YCSB-master/mongodb/target/dependency/logback-classic-1.1.2.jar
[INFO] Copying slf4j-api-1.6.4.jar to /soft/YCSB-master/mongodb/target/dependency/slf4j-api-1.6.4.jar
[INFO] 
[INFO] --- maven-assembly-plugin:2.5.5:single (default) @ mongodb-binding ---
[WARNING] The following patterns were never triggered in this artifact exclusion filter:
o  '*:sources'

[INFO] Building tar: /soft/YCSB-master/mongodb/target/ycsb-mongodb-binding-0.12.0-SNAPSHOT.tar.gz
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] YCSB Root .......................................... SUCCESS [  1.387 s]
[INFO] Core YCSB .......................................... SUCCESS [  5.892 s]
[INFO] Per Datastore Binding descriptor ................... SUCCESS [  0.218 s]
[INFO] YCSB Datastore Binding Parent ...................... SUCCESS [  0.519 s]
[INFO] MongoDB Binding .................................... SUCCESS [  1.478 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.917 s
[INFO] Finished at: 2016-10-28T12:50:01+08:00
[INFO] Final Memory: 36M/355M
[INFO] ------------------------------------------------------------------------
[root@jenkins YCSB-master]# ^C

[root@jenkins YCSB-master]# ./bin/ycsb load mongodb-async -s  -P workloads/workload-youren-test > outputLoad.txt
[WARN]  Running against a source checkout. In order to get our runtime dependencies we'll have to invoke Maven. Depending on the state of your system, this may take ~30-45 seconds
[DEBUG]  Running 'mvn -pl com.yahoo.ycsb:mongodb-binding -am package -DskipTests dependency:build-classpath -DincludeScope=compile -Dmdep.outputFilterFile=true'
/home/dev/soft/jdk1.7/bin/java -cp /soft/YCSB-master/mongodb/conf:/soft/YCSB-master/mongodb/target/mongodb-binding-0.12.0-SNAPSHOT.jar:/root/.m2/repository/com/allanbank/mongodb-async-driver/2.0.1/mongodb-async-driver-2.0.1.jar:/root/.m2/repository/org/apache/htrace/htrace-core4/4.1.0-incubating/htrace-core4-4.1.0-incubating.jar:/root/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.4/jackson-core-asl-1.9.4.jar:/root/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.4/HdrHistogram-2.1.4.jar:/soft/YCSB-master/core/target/core-0.12.0-SNAPSHOT.jar:/root/.m2/repository/org/mongodb/mongo-java-driver/3.0.3/mongo-java-driver-3.0.3.jar:/root/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.4/jackson-mapper-asl-1.9.4.jar com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.AsyncMongoDbClient -s -P workloads/workload-youren-test -load
YCSB Client 0.12.0-SNAPSHOT
Command line: -db com.yahoo.ycsb.db.AsyncMongoDbClient -s -P workloads/workload-youren-test -load
Loading workload...
java.lang.ClassNotFoundException: com.yahoo.ycsb.workloads.CoreWorkload  #workloadå®ç°ç±» 
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at com.yahoo.ycsb.Client.main(Client.java:998)

Env:    centos6.5     jdk7    maven3.3
I do not how to solve this problem,so I hope to get answer from who can solve this question 
thanks...

**Comment by risdenk** [comment]
@ycmy2016 can you try using a release of YCSB instead of compiling yourself?

**Comment by ycmy2016** [comment]
@risdenk   when I use root     ./bin/ycsb load mongodb-async -s -P workloads/workload-youren-test > outputLoad.txt  .when we use centos ,we should use user root all the time, this problem no longer appear.

**Comment by risdenk** [comment]
Closing due to not an issue.
