### ISSUE TITLE
compiling error: AsyncHBase Client Binding for Apache HBase ........ FAILURE

### ISSUE THREAD

**Issue by caijieming-baidu** [brianfrankcooper/YCSB#870]
When using"mvn -X package -rf :asynchbase-binding" to compile ycsb project, I always met an error like: "[ERROR] Failed to execute goal on project asynchbase-binding: Could not resolve dependencies for project com.yahoo.ycsb:asynchbase-binding:jar:0.11.0: Could not find artifact com.yahoo.ycsb:core:jar:0.11.0 in central (http://repo.maven.apache.org/maven2) -> [Help 1]
"
but it will succeed, when exe "mvn -X -pl com.yahoo.ycsb:asynchbase-binding -am clean package"

Is it a bug?

note: my ycsb's version is 0.11.0

**Comment by risdenk** [comment]
Can you use a release of YCSB instead of compiling yourself?

https://github.com/brianfrankcooper/YCSB/releases

**Comment by caijieming-baidu** [comment]
my env is too old to use release version, (by the way, hadoop and base also complied by mysql)

**Comment by risdenk** [comment]
A release is just a tar.gz. There is nothing special about it. What is too old about your env?

**Comment by caijieming-baidu** [comment]
[root@xxxxxxxxxxxxxxx ~]# rpm -qa |grep glibc
glibc-2.3.4-2.19
glibc-devel-2.3.4-2.19
compat-glibc-headers-2.3.2-95.30
glibc-2.3.4-2.19
glibc-headers-2.3.4-2.19
glibc-common-2.3.4-2.19
glibc-kernheaders-2.4-9.1.98.EL
glibc-devel-2.3.4-2.19
compat-glibc-2.3.2-95.30
[root@xxxxxxxxxxxxxxx ~]# java -version
java version "1.4.2"
gcj (GCC) 3.4.5 20051201 (Red Hat 3.4.5-2)
Copyright (C) 2004 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[root@xxxxxxxxxxxxxxx ~]# gcc -v
Reading specs from /usr/lib/gcc/x86_64-redhat-linux/3.4.5/specs
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --enable-shared --enable-threads=posix --disable-checking --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-java-awt=gtk --host=x86_64-redhat-linux
Thread model: posix
gcc version 3.4.5 20051201 (Red Hat 3.4.5-2)

**Comment by risdenk** [comment]
As far as I know you are going to need at least Java 7 to even run or compile YCSB.

**Comment by risdenk** [comment]
You need `-am` because the additional modules need to be made before the binding. That is why this isn't a bug.

**Comment by risdenk** [comment]
Closing due to now update.
