### ISSUE TITLE
hbase10 test： performance problem

### ISSUE THREAD

**Issue by caijieming-baidu** [brianfrankcooper/YCSB#871]
- use ycsb load workloada, reach nearly 1,600 qps, i expects it can easily reach 10,000+(single client with threads=1). Becase using baidu's database [tera](github.com/baidu/tera) , in sequence write mode, its write qps can be 100,000 ~ 200,000 qps. Is thera anything wrong in default configuration?

Test env: 10 datanodes, 10 regionservers, 10 GigE network

**Comment by risdenk** [comment]
Did you test baidu's tera on your servers?

**Comment by risdenk** [comment]
Closing due to no update.
