### ISSUE TITLE
Could not wait until max specified time, TerminatorThread interrupted.

### ISSUE THREAD

**Issue by longquanzheng** [brianfrankcooper/YCSB#874]
Running:
$ ./bin/ycsb load basic -P workloads/workloada  -P workloads/workloadc -p fieldcount=1 -p requestdistribution=uniform -p recordcount=1000000  -s -p maxexecutiontime=600 > /tmp/basic.600s

would get:

Could not wait until max specified time, TerminatorThread interrupted.

**Comment by risdenk** [comment]
Can you share more of the output?

**Comment by risdenk** [comment]
Closing due to no update.

**Comment by hq6** [comment]
I ran into this issue also. After digging around it, it looks like this gets printed to `stderr` if the benchmark finishes `operationcount` before `maxexecutiontime` is actually reached. 

This is usually benign unless you forgot to specify `operationcount` and wound up with the default `operationcount` of only 1000, which is usually not what you intended.
