### ISSUE TITLE
Running rest-module throws NoClassDefFound  -  org/apache/htrace/core/HTraceConfiguration

### ISSUE THREAD

**Issue by shivam-maharshi** [brianfrankcooper/YCSB#880]
**_Platform:_** Windows 10

**_Command:_**

`C:/Users/Sam/Downloads/YCSB-0.12.0-RC1/bin/ycsb.bat run rest -s -P C:/Users/Sam/Downloads/YCSB-0.12.0-RC1/workloads/workload_rest`

**_Error Received:_**

`C:\Users\Sam\Downloads\YCSB-0.12.0-RC1>"C:\Program Files\Java\jdk1.8.0_60\bin\java.exe"  -classpath "C:\Users\Sam\Downloads\YCSB-0.12.0-RC1\conf;C:\Users\Sam\Downloads\YCSB-0.12.0-RC1\core\target\core-0.12.0-RC1.jar;C:\Users\Sam\Downloads\YCSB-0.12.0-RC1\rest\target\rest-binding-0.12.0-RC1.jar;C:\Users\Sam\Downloads\YCSB-0.12.0-RC1\rest\target\dependency\aopalliance-repackaged-2.2.0.jar;C:\Users\Sam\Downloads\YCSB-0.12.0-RC1\rest\target\dependency\commons-codec-1.9.jar;C:\Users\Sam\Downloads\YCSB-0.12.0-RC1\rest\target\dependency\commons-logging-1.2.jar;C:\Users\Sam\Downloads\YCSB-0.12.0-RC1\rest\target\dependency\ecj-4.4.2.jar;C:\Users\Sam\Downloads\YCSB-0.12.0-RC1\rest\target\dependency\hk2-api-2.2.0.jar;C:\Users\Sam\Downloads\YCSB-0.12.0-RC1\rest\target\dependency\hk2-locator-2.2.0.jar;C:\Users\Sam\Downloads\YCSB-0.12.0-RC1\rest\target\dependency\hk2-utils-2.2.0.jar;C:\Users\Sam\Downloads\YCSB-0.12.0-RC1\rest\target\dependency\httpclient-4.5.1.jar;C:\Users\Sam\Downloads\YCSB-0.12.0-RC1\rest\target\dependency\httpcore-4.4.4.jar;C:\Users\Sam\Downloads\YCSB-0.12.0-RC1\rest\target\dependency\javassist-3.18.1-GA.jar;C:\Users\Sam\Downloads\YCSB-0.12.0-RC1\rest\target\dependency\javax.annotation-api-1.2.jar;C:\Users\Sam\Downloads\YCSB-0.12.0-RC1\rest\target\dependency\javax.inject-2.2.0.jar;C:\Users\Sam\Downloads\YCSB-0.12.0-RC1\rest\target\dependency\javax.ws.rs-api-2.0.jar;C:\Users\Sam\Downloads\YCSB-0.12.0-RC1\rest\target\dependency\jersey-client-2.6.jar;C:\Users\Sam\Downloads\YCSB-0.12.0-RC1\rest\target\dependency\jersey-common-2.6.jar;C:\Users\Sam\Downloads\YCSB-0.12.0-RC1\rest\target\dependency\jersey-container-servlet-core-2.6.jar;C:\Users\Sam\Downloads\YCSB-0.12.0-RC1\rest\target\dependency\jersey-guava-2.6.jar;C:\Users\Sam\Downloads\YCSB-0.12.0-RC1\rest\target\dependency\jersey-server-2.6.jar;C:\Users\Sam\Downloads\YCSB-0.12.0-RC1\rest\target\dependency\osgi-resource-locator-1.0.1.jar;C:\Users\Sam\Downloads\YCSB-0.12.0-RC1\rest\target\dependency\system-rules-1.16.0.jar;C:\Users\Sam\Downloads\YCSB-0.12.0-RC1\rest\target\dependency\tomcat-dbcp-8.0.28.jar;C:\Users\Sam\Downloads\YCSB-0.12.0-RC1\rest\target\dependency\tomcat-embed-core-8.0.28.jar;C:\Users\Sam\Downloads\YCSB-0.12.0-RC1\rest\target\dependency\tomcat-embed-el-8.0.28.jar;C:\Users\Sam\Downloads\YCSB-0.12.0-RC1\rest\target\dependency\tomcat-embed-jasper-8.0.28.jar;C:\Users\Sam\Downloads\YCSB-0.12.0-RC1\rest\target\dependency\tomcat-embed-logging-juli-8.0.28.jar;C:\Users\Sam\Downloads\YCSB-0.12.0-RC1\rest\target\dependency\tomcat-embed-logging-log4j-8.0.28.jar;C:\Users\Sam\Downloads\YCSB-0.12.0-RC1\rest\target\dependency\tomcat-embed-websocket-8.0.28.jar;C:\Users\Sam\Downloads\YCSB-0.12.0-RC1\rest\target\dependency\validation-api-1.1.0.Final.jar" com.yahoo.ycsb.Client -t -db com.yahoo.ycsb.webservice.rest.RestClient -s -P C:/Users/Sam/Downloads/YCSB-0.12.0-RC1/workloads/workload_rest
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/htrace/core/HTraceConfiguration
        at com.yahoo.ycsb.Client.main(Client.java:947)
Caused by: java.lang.ClassNotFoundException: org.apache.htrace.core.HTraceConfiguration
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 1 more`

**Comment by risdenk** [comment]
This isn't related only to the rest-binding. See #877. It has to do with it being a source checkout and ycsb.sh and ycsb.bat not putting the right dependencies on the classpath.
