### ISSUE TITLE
Should we use YCSB to benchmark BigTable/Dynamo ?

### ISSUE THREAD

**Issue by manavgarg** [brianfrankcooper/YCSB#881]
Hi,

So, I am using YCSB to benchmark BigTable and I cam across this problem. I am using a client machine which has 16 cores and 64gb memory. Now, since the basic BigTable cluster that we can reserve is a 3 node setup with a combined QCS of 30,000 , I decided to launch YCSB with multiple client threads in order to make sure that I am actually stressing the DB.
Here is my experience:

threads =100; avg cpu_util: 55%; mem_used: 8gb; total runtime: 777.8 secs; throughput: 1285 ops/sec

threads = 500; avg cpu_util:  ~96%; mem_used: 12 gb; total RunTime(ms) =  544.7 secs; throughput = 1835.5 ops/sec

threads = 1000; avg cpu_util: ~97%; mem_used:  13gb;  total RunTime(ms) = 507.2 secs; throughput =  1971

Higher threads didn't provide additional throughput as the system was CPU limited.

As we can see, with just a few number of threads (500), I was already CPU-limited. Moreover, this only gave me like 2k ops/sec which is nowhere close to the basic google offering of 30k ops/sec.
Now, I believe I used a powerful enough machine with 16 cores. Does this mean that it is not possible to benchmark BigTable without having a ultra powerful machine with like 128/256 cores ?
Is it possible to run YCSB on a cluster of machines and somehow still be able to reason about the results ?

**Comment by k1xme** [comment]
Yes, we definitely can use YCSB to test it. The simple reason is that, the Perf team in GCP use YCSB to test BigTable as well with the help of PerfKitBenchMarker.

I happened to benchmark on BigTable few months ago and went across the same situation as you did. The thing is that you need more client machines to push Bigtable's throughput to its limit instead of more threads. I ran 8 2-core 4G-RAM basic VMs with not over 50 threads per client and achieved 30K OPS.

**Comment by manavgarg** [comment]
That makes sense. So, if you use a bunch of client machines, how do you reason about the results. I mean how do you aggregate the results across all the machines. So to compute the avg latency for an operation, do you just take an average across all ?

**Comment by k1xme** [comment]
@manavgarg Yes, I aggregated the OPS across all the machines, and compute avg latency. But all these calculation was taken care of by [PerfKitBenchmarker](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker) I highly recommend you to use that framework to do benchmark if you're planning to launch over 2 VMs.

**Comment by manavgarg** [comment]
Thanks a lot for the clarification. Will use PerfKitBenchmarker then.
