### ISSUE TITLE
Solr Kerberos authentication support?

### ISSUE THREAD

**Issue by allxone** [brianfrankcooper/YCSB#882]
I really appreciated HBase binding with kerberos support. Any plan to add it also to the Solr one?

* https://cwiki.apache.org/confluence/display/solr/Kerberos+Authentication+Plugin
* https://issues.apache.org/jira/browse/SOLR-9496

Thanks,
Stefano

**Comment by risdenk** [comment]
@allxone thanks for the request. Having Kerberos support for Solr would be great it just hasn't been added yet. We welcome any contributions. Feel free to open a PR!

**Comment by risdenk** [comment]
Here are a few of the things that must be done:
1. Add commons-codec dependency to solr/solr6 pom.xml
```
<dependency>
  <groupId>commons-codec</groupId>
  <artifactId>commons-codec</artifactId>
  <version>1.10</version>
</dependency>
```

2. Modify solr/solr6 bindings to add Kerberos support
Before creating either CloudSolrClient or HttpSolrClient, add the following:
```
System.setProperty("java.security.auth.login.config", "/home/foo/jaas-client.conf");
HttpClientUtil.setConfigurer(new Krb5HttpClientConfigurer());
```
As outlined in https://cwiki.apache.org/confluence/display/solr/Kerberos+Authentication+Plugin under "Using SolrJ with a Kerberized Solr"

**Comment by risdenk** [comment]
@allxone I opened PR #887 without tests to see if that would help the Kerberos support. I didn't add a README or tests yet.
