### ISSUE TITLE
How Can I Specify Different Length for Fields

### ISSUE THREAD

**Issue by yaoyaminaco0571** [brianfrankcooper/YCSB#890]
hi guys,
I have a cassandra table with 2 fields, I want to specify the length for first field to 64KB, and another 1KB.
I found that there is a generator : https://github.com/brianfrankcooper/YCSB/blob/master/core/src/main/java/com/yahoo/ycsb/generator/HistogramGenerator.java

It is likely match my requirement, but how to use it? 

Thanks for help.

**Comment by risdenk** [comment]
Different lengths for fields are described under the core properties:

https://github.com/brianfrankcooper/YCSB/wiki/Core-Properties

**Comment by yaoyaminaco0571** [comment]
I found field count & field length , but how can I set field1=64KB filed2=1KB?

**Comment by yaoyaminaco0571** [comment]
Dear risden, need your help.
I can define 2 filed in 1 column family using fieldcount=2 and fieldlength=20. 
But if I want filed1 has 64K bytes and filed2 has 1K bytes, how to do it ?

**Comment by busbey** [comment]
I don't think we have a set of properties for specifying multiple different fixed field lengths. It'd make a nice addition if you'd like to try adding it.

**Comment by risdenk** [comment]
This could be related to #310

**Comment by risdenk** [comment]
Closing since this is a duplicate of #310
