### ISSUE TITLE
How Can I Get 50thPercentileLatency ?

### ISSUE THREAD

**Issue by yaoyaminaco0571** [brianfrankcooper/YCSB#891]
Hi guys,
Pls help me, I found the measurement output include 95thPercentileLatency, but how to get other precision just like 50thPercentileLatency ?

**Comment by risdenk** [comment]
The percentiles can be adjusted as detailed here:

https://github.com/brianfrankcooper/YCSB/wiki/Core-Properties#hdrhistogram

**Comment by yaoyaminaco0571** [comment]
Thanks risdenk!
