### ISSUE TITLE
YCSB binding for Elasticsearch 5.x

### ISSUE THREAD

**Issue by risdenk** [brianfrankcooper/YCSB#893]
YCSB has bindings for Elasticsearch 2.x but not the new Elasticsearch 5.x line.

**Comment by risdenk** [comment]
@hjxhjh and @jasontedor - here is the issue I created for adding a YCSB binding for Elasticsearch 5.x

**Comment by jasontedor** [comment]
Thanks @risdenk, I'll submit a PR soon.

**Comment by hjxhjh** [comment]
@risdenk  @jasontedor  thanks.

**Comment by evanbreznyik** [comment]
This would be superb to have.  I see some of the initial bindings going in for elasticsearch5 -- any idea when this might make it to the next release?
