### ISSUE TITLE
run YCSB with a cluster with low specifications

### ISSUE THREAD

**Issue by ivankirit** [brianfrankcooper/YCSB#894]
Its not issue, but dont know the exact place to put this question. 
I would like to know if for testing purposes,  i can use a cluster of 2 nodes with 1vCpu and 512 Mb Ram and run YCSB benchmark for mongo and couchbase, will I  be able to see differences, and results?

**Comment by risdenk** [comment]
Most likely you will be able to see some results. It may not scale linearly if you were to add nodes. It also may fail if you put too much data in. If you are looking for a small comparison then it should work.

**Comment by ivankirit** [comment]
when you say small, how small is it?  500 000 rows maybe?

**Comment by risdenk** [comment]
It depends on a lot of different factors.

**Comment by risdenk** [comment]
@ivankirit were you able to make progress on this?

**Comment by risdenk** [comment]
Closing due to no update.
