### ISSUE TITLE
Error in compilation and creating table for JDBC binding

### ISSUE THREAD

**Issue by JigarProjects** [brianfrankcooper/YCSB#909]
JdbcDBClient referes to com.yahoo.ycsb.DB class, which is not available. Eithere one needs to reintroduce it or needs to delete the references.

**Comment by risdenk** [comment]
Can you share more of the steps that you tried to run and the specific error?

**Comment by JigarProjects** [comment]
I downloaded source code and tried to run mvn install in YCSB_HOME/jdbc directory. This generated compilation error.

**Comment by risdenk** [comment]
Share the whole command and error that you receive. Most likely you are not compiling with the correct command.

Is it possible for you to use a YCSB release? https://github.com/brianfrankcooper/YCSB/releases

**Comment by JigarProjects** [comment]
I followed https://github.com/brianfrankcooper/YCSB/tree/master/jdbc and at Step 3 I got following error.
> Closing database connection.
Error in creating table. com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'PRIMARY KEY, FIELD0 VARCHAR, FIELD1 VARCHAR, FIELD2 VARCHAR, FIELD3 VARCHAR, FIE' at line 1

**Comment by risdenk** [comment]
Share the whole command you tried to run. You aren't providing enough info to help effectively debug. You most likely have a typo in the create table command.

**Comment by JigarProjects** [comment]
Sorry for giving partial details.

Input:
` java -cp ./lib/jdbc-binding-0.12.0.jar:./lib/mysql-connector-java-5.0.8-bin.jar com.yahoo.ycsb.db.JdbcDBCreateTable -P ../db.properties -n test2`

Output:
Closing database connection.
Error in creating table. com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'PRIMARY KEY, FIELD0 VARCHAR, FIELD1 VARCHAR, FIELD2 VARCHAR, FIELD3 VARCHAR, FIE' at line 1

I am using YCSB's classes. My db.properties looks like below:

> db.driver=com.mysql.jdbc.Driver
> db.url=jdbc:mysql://127.0.0.1:3306/xxxx
> db.user=xxxx
> db.passwd=xxxx

**Comment by risdenk** [comment]
It may be easier if you create the table manually.  I haven't tried to use the JdbcDBCreateTable utility.

**Comment by JigarProjects** [comment]
Well it's minor issue in JdbcDbCreateTable utility. To run it on MySql, it is supposed to have VARCHAR(255) instead program generates query with VARCHAR only.

**Comment by risdenk** [comment]
This is changed to TEXT if you create the table manually. There is PR #797 that should address most of this. It needs to be updated a bit for documentation and javadocs.

**Comment by JigarProjects** [comment]
Thank you @risdenk  for quick response.

**Comment by risdenk** [comment]
I'll try to update PR #797 and hopefully get it fixed for YCSB 0.13.0

**Comment by risdenk** [comment]
The new PR is #910 if you can test it and comment on that PR that would be great. Thanks!

**Comment by risdenk** [comment]
If you are looking to build just the JDBC binding, `mvn -pl jdbc -am package`

**Comment by risdenk** [comment]
Closing since this seems resolved. @JigarProjects if still an issue please reopen or open a new issue.

**Comment by lordnynex** [comment]
@risdenk this appears to be an issue again. Using 0.17.0 with `mysql-connector-java-8.0.26.jar` and `db.driver=com.mysql.cj.jdbc.Driver`. 

Getting `Error in creating table. java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'PRIMARY KEY, FIELD0 TEXT, FIELD1 TEXT, FIELD2 TEXT, FIELD3 TEXT, FIELD4 TEXT, FI' at line 1`

I'm not sure what to make of this error. This bug appears to change from VARCHAR to TEXT. So the fields are being created as the intended type, but I'm not sure what the syntax error is.
