### ISSUE TITLE
Can not connect to AWS EMR HBase with S3 storage.

### ISSUE THREAD

**Issue by uagashe** [brianfrankcooper/YCSB#913]
HBase DynamicClassLoader initialization fails as it tries to dynamically load JARs from hdfs directory which is back by S3 in case of EMR deployment. YCSB HBase client code fails to connect to S3. Please see the attached log.

**Comment by uagashe** [comment]
[ycsb-emr-log.zip](https://github.com/brianfrankcooper/YCSB/files/740738/ycsb-emr-log.zip)

**Comment by risdenk** [comment]
It looks like YCSB is not being pointed at the HBase configuration files. Its not picking up the the access id or key for S3. https://github.com/brianfrankcooper/YCSB/tree/master/hbase098#4-run-the-workload The part that says `-cp /HBASE-HOME-DIR/conf`

**Comment by uagashe** [comment]
Yes, those details cannot be shared/ specified in client config. The expected behavior is to ignore it and proceed with the workloads. This is same as if non-existent dir is specified for dynamic libs. In fact I can proceed with workloads by adding following config:
`
  <property>
    <name>hbase.dynamic.jars.dir</name>
    <value>file://tmp/</value>
  </property>
`

**Comment by risdenk** [comment]
Not sure what your comment is trying to say.

> The expected behavior is to ignore it and proceed with the workloads.

What is "it" in this context?

The properties are determined by HBase and need to be specified. Does the workload run if you pass in the HBase configuration directory with `-cp`?

**Comment by uagashe** [comment]
HBase configuration files were copied from master to YCSB. Those files does not have AWS credentials. So when YCSB HBase client fails to access HDFS directory while loading jars dynamically, YCSB should log warning and proceed further with the workload.

**Comment by risdenk** [comment]
I don't think what you are referring to would be the responsibility of YCSB. YCSB is just calling out to the HBase client. 

Maybe @busbey or @gkamat knows more?

**Comment by busbey** [comment]
I thought getting a "I can't talk to this FileSystem" warning was a long standing issue when `hbase.dynamic.jars.dir` is left at the default. IIRC, that happens when the default filesystem is HDFS since we don't include the hdfs client libraries on the classpath by default.

Can someone summarize the difference in the failure mode here? Are we no longer logging the same warning? Are we failing instead? What kind of failure?

**Comment by risdenk** [comment]
Closing due to no update. @uagashe if you have more to provide please reopen.
