### ISSUE TITLE
Is there a way to specify other report time instead of the default 10s?

### ISSUE THREAD

**Issue by wuxiaomin98** [brianfrankcooper/YCSB#922]
Hi,

   I'm wondering whether there's way to specify other report time instead of the default 10 seconds. Right now I'm using ycsb 0.12.0. 

   When **execute/run the load**, I add the -s in the command. But the default interval is 10 seconds. Could I change it to other value, like 100 milliseconds?

    THANKS!

Jun

**Comment by risdenk** [comment]
There is a property called `status.interval`. It is in terms of seconds. That may do what you are looking for. I don't know if you would want it as frequent as 100 milliseconds since that would affect the performance of running YCSB most likely.

https://github.com/brianfrankcooper/YCSB/blob/master/core/src/main/java/com/yahoo/ycsb/Client.java#L1095

**Comment by wuxiaomin98** [comment]
@risdenk 
Thank you so much for the response!

Yes, I've tested the status.interval and it works. But it can only support  integers with unit in second. I'm wondering whether it can support for update of every 100 ms.

Actually my purpose is to use YCSB to test the performance of Cassandra. I want to know how many requests Cassandra can process in a 100 ms units and how vary it could be for every 100 ms. So that's why I want to setup the interval time.

Any comments on this?

Thanks!

Jun

**Comment by risdenk** [comment]
100ms is a small window. Decreasing the `status.interval` from 10 seconds to 100ms is 100x smaller. This means that 100x more work is done to print status out. If you are trying to push a Cassandra cluster you will most likely need multiple YCSB clients. If each YCSB client is doing 100x more printing out of status that would mean you need to have more YCSB clients to push Cassandra.

There is non trivial amount of work when you change something 100x even if its printing out to the console.

**Comment by risdenk** [comment]
The code could be changed to support smaller intervals than a second but you would need to do that. If there is a backwards compatible change we could try to add it to YCSB.

**Comment by wuxiaomin98** [comment]
Thank you so much for the explanation! @risdenk 

I'll try to see the result if I change it to 1 second instead of 100 milliseconds. 

Again, your information is quite useful and I really appreciate it!

**Comment by risdenk** [comment]
@wuxiaomin98 any update here?

**Comment by wuxiaomin98** [comment]
@risdenk Thanks for asking.
Yes, I've tried with 1 second. I did not compare my previous result with this 1 second interval result, but just take a look, the result seems to be almost similar. I did not tried with 100 ms, as I do not figure out how to get the data every 100ms.
