### ISSUE TITLE
Different type of workload

### ISSUE THREAD

**Issue by gioargyr** [brianfrankcooper/YCSB#926]
Hello all!
I am running ycsb against HBase, and as I can understand, every ycsb-client I use, tries to produce throughput as I state in "target" argument in workload.cfg. So, I always have a constant workload.
Is there a way to make a ycsb-client to produce sinusoidal workload or a workload with a variable throughput?
(Surprisingly enough, I couldn't find a similar question anywhere!)

**Comment by risdenk** [comment]
@gioargyr There is request distribution but that is more for the keys being requested. I think you are referring to changing the workload pattern over the course of minutes/hours/days. Like at 8am have more requests than at midnight. I'm pretty sure there isn't a workload that does that currently.
