### ISSUE TITLE
mvn build issue

### ISSUE THREAD

**Issue by ab-agni** [brianfrankcooper/YCSB#927]
I get this error on compiling any of the modules except core. I am focusing on cassandra. Only core compiled without an issue. Can you please assist?

[ERROR] Failed to execute goal on project cassandra-binding: Could not resolve dependencies for project com.yahoo.ycsb:cassandra-binding:jar:0.13.0-SNAPSHOT: Could not find artifact com.yahoo.ycsb:core:jar:0.13.0-SNAPSHOT ->

**Comment by risdenk** [comment]
Can you share the Maven command you are running exactly?

**Comment by ab-agni** [comment]
Thank you for looking at this. Cmd is mvn package. I downloaded the zip file and even tried the clone from https://github.com/brianfrankcooper/YCSB

Also tried compiling it in Spring Test Suite IDE. Maven build, install - both fail.

**Comment by risdenk** [comment]
What directory did you run it from?

If you are just trying to run YCSB you can download a release and you don't have to compile it.

**Comment by ab-agni** [comment]
I was running it from cassandra directory containing pom.xml. The mongo version worked great because I did what you said - run it directly. But the instructions for cassandra say - "host" substitution is required. So I was updating the code and thought I needed to recompile to generate a new jar. Please let me know if I am wrong on this and what is the correct approach.

**Comment by risdenk** [comment]
The `hosts` parameter is a property that can be specified when you run the job. Something like ` -p hosts=...` after the YCSB command.

**Comment by risdenk** [comment]
Closing since #928 is the same.
