### ISSUE TITLE
Question on running test in cassandra

### ISSUE THREAD

**Issue by ab-agni** [brianfrankcooper/YCSB#928]
Can someone please assist in clarifying how to run ycsb against cassandra db? 
Per https://github.com/brianfrankcooper/YCSB/tree/master/cassandra
1. Create keyspace ycsb and table - usertable.
2. Do I need to update code and replace "hosts" with public dns name and then recompile to generate a new jar?
3. Are these instructions for load and run valid? 
bin/ycsb.sh load basic -P workloads/workloada
bin/ycsb.sh run basic -P workloads/workloada

I looked at wiki, but got confused if I was doing this right. I was able to run against mongo successfully. Instructions were great.

**Comment by risdenk** [comment]
2. The hosts parameter is a property that can be specified when you run the job. Something like -p hosts=... after the YCSB command.

3. You need to run `cassandra` instead of `basic`

**Comment by cybertriton** [comment]
I ran "bin/ycsb.sh load cassandra -P workloads/workloada" but it returned with "[ERROR] The specified binding 'cassandra' was not found.  Exiting.".

**Comment by risdenk** [comment]
Sorry it would be cassandra-cql.

**Comment by risdenk** [comment]
Closing due to no more update. If this is not resolved please reopen.
