### ISSUE TITLE
[cassandra-cql] PreparedStatement JUnit Test; key-value iteration order

### ISSUE THREAD

**Issue by cricket007** [brianfrankcooper/YCSB#929]
I'm in the process of merging a piece of #98 (related to #458), and I think I am close. Meaning the Cassandra `PreparedStatements` are in the code, but I am trying to get the `insert` & `update` JUnit tests to pass now. 

The `PreparedStatement` looks like so `INSERT INTO usertable (y_id,field0,field1,field2,field3,field4,field5,field6,field7,field8,field9) VALUES (?,?,?,?,?,?,?,?,?,?,?);`

I was referring to this code on the 98 pull, and I see this.  
Basically, create the Object array from the values Map and simply call `bind()` with that array. 

```java
@Override
public int insert(String table, String key, Map<String, ByteIterator> values)
{
    try
    {
        Object[] vals = new Object[values.size() + 1];
        vals[0] = key;
        int i = 1;
        for (Map.Entry<String, ByteIterator> entry : values.entrySet())
        {
            vals[i++] = ByteBuffer.wrap(entry.getValue().toArray());
        }

        BoundStatement bs = (values.size() == 1 ? updateStatements.get(values.keySet().iterator().next()) : insertStatement).bind(vals);
```

Where the unit tests are failing - [CassandraCQLClientTest.java#L178][1] 

```java
assertThat(row.getString("field0"), is("value1"));

java.lang.AssertionError: 
Expected: is "value1"
     but: was "value2"
```

Which makes sense because `HashMap` ordering is not guaranteed. 

I was looking at the JDBC code and I see this [`private OrderedFieldInfo getFieldInfo`](https://github.com/brianfrankcooper/YCSB/blob/master/jdbc/src/main/java/com/yahoo/ycsb/db/JdbcDBClient.java#L486) method. However, that feels wrong, so I am looking for other suggestions. 

Follow-up question - Is iterating over that map in order something that needs to be done often? If so, why isn't a `LinkedHashMap` used?

  [1]: https://github.com/brianfrankcooper/YCSB/blob/master/cassandra/src/test/java/com/yahoo/ycsb/db/CassandraCQLClientTest.java#L178

**Comment by risdenk** [comment]
Can you share how you are creating the prepared statement? How do you know the order of `(y_id,field0,field1,field2,field3,field4,field5,field6,field7,field8,field9)`? If you know that order, can't you store that order and then loop through that list and grab  the values from the values map by field name? This wouldn't rely on the order of the map then.

**Comment by cricket007** [comment]
Good plan. Thanks @risdenk  

```java
fieldList = new ArrayList<String>(fieldCount);

final Insert is = QueryBuilder.insertInto(table);
is.value(YCSB_KEY, QueryBuilder.bindMarker());
fieldList.add(YCSB_KEY);

for (int i = 0; i < fieldCount; i++) {
  // Preserve field iteration order for the HashMaps used in the DB methods
  String field = FIELD_PREFIX + i;
  fieldList.add(field);
  is.value(field, QueryBuilder.bindMarker());
}
```
