### ISSUE TITLE
how to export result to file

### ISSUE THREAD

**Issue by Zihan0409** [brianfrankcooper/YCSB#931]
how to export result to file or reporter?

**Comment by JAlejandro** [comment]
The easy way is to redirect the output to a file (standard and error output).

**Comment by Zihan0409** [comment]
Thank you so much for the response!
I see that,but how to  take a chart? thank you very much!

**Comment by JAlejandro** [comment]
I don't know a standard mode to generate YCSB plots. Normally I use my custom scripts in GNUPlots or Python. A good start points could be this project: https://github.com/ashleyblackmore/ycsb-log-parser

**Comment by risdenk** [comment]
Closing due to no more updates. Looks like this was answered. Please reopen if not the case.
