### ISSUE TITLE
Running Parallel Clients

### ISSUE THREAD

**Issue by inteladyne** [brianfrankcooper/YCSB#932]
I'm using the command line 
```bash
time ./bin/ycsb run aerospike -s -P workloads/workloadc -p as.host=n2 -p as.port=3000 -p as.namespace=test -p as.user=root -p operationcount=10000000 -target 500000 -threads 50
```
which works perfect but when I add 
`-p insertstart=0 -p insertcount=50000000`
to the command line, it fails.

Complete command line 
```bash
time ./bin/ycsb run aerospike -s -P workloads/workloadc -p as.host=n2 -p as.port=3000 -p as.namespace=test -p as.user=root -p insertstart=0 -p insertcount=50000000 -p recordcount=100000000 -target 500 -threads 50 -P million.dat
```
Bombs out.  No output

**Comment by inteladyne** [comment]
Any information would be greatly appreciated

**Comment by risdenk** [comment]
I formatted your initial comment just to make it easier to read. Please do so in the future as well. 

Few questions:
* Does this happen with a smaller insertcount number?
* What does the load on the aerospike database look like? Is it working hard?

**Comment by risdenk** [comment]
Closing due to no update.
