### ISSUE TITLE
Issue in running with too many threads

### ISSUE THREAD

**Issue by JigarProjects** [brianfrankcooper/YCSB#938]
It looks like there is problem in max execution time.
I am running an experiment on virtual machine which has 256MB Ram with 3GB of Hard Disk.
I installed mysql and configured YCSB with 1000 thread to load database. I set maxexecutiontime to 10 second and YCSB is not responding.

It repeatedly says that "Still waiting for thread Thread-XXX to complete. Workload status: true"

**Comment by risdenk** [comment]
This is with the JDBC binding?

**Comment by risdenk** [comment]
Closing due to no update.
