### ISSUE TITLE
Data set issue

### ISSUE THREAD

**Issue by mscsf15m027** [brianfrankcooper/YCSB#941]
YCSB uses structured data set? what does it mean? Because sparkbench uses structured, unstructured and semi-structured data sets because it supports spark only. We can say that spark support unstructured data. But YCSB supports all NoSQL systems in which spark is also including then how we can say that YCSB data set is structured??

**Comment by risdenk** [comment]
Can you clarify where you are getting your assumptions from?

YCSB generates a structured data set as in fixed number of fields.

**Comment by mscsf15m027** [comment]
I am confusing in data set. How YCSB data set is structured? It supports all NoSQL systems in which Spark also included. Then how we can say that YCSB data set is structured?

**Comment by risdenk** [comment]
Instead of saying the same thing as your first message, can you try to restate the question in a different way? I'm not clear what you are trying to ask.

**Comment by mscsf15m027** [comment]
YCSB--------------Dataset(Structured)
SparkBench----- Dataset(Structured, unstructured, semi-structured)
HiBench-----------Dataset(Structured, unstructured, semi-structured)
LinkBench---------Dataset(Unstructured)

I want to ask all above benchmark suits support different datasets, on which factors their datasets are different? why we said YCSB is structured and Linkbench dataset is unstructured? please just explain the difference between them.

**Comment by busbey** [comment]
closing as stale.
