### ISSUE TITLE
Question while running latest YCSB with hbase

### ISSUE THREAD

**Issue by ramkrish86** [brianfrankcooper/YCSB#942]
This is not an issue. It is more of a query. 

I try to load my HBase database for doing some benchmarks. My intention is to load the DB with some data and then try out the pure read workload with different threads.

I use the workloada profile which generates ~1K record with 10 cols each (val is 100 bytes). I use 10 threads to load this data.

Now when I had the record count as recordcount=100144000, assuming each record is 1k (i know it is going to be more leaving out the key value serializtion overhead) i get around 95G as the size that will be loaded. Finally after the loading was complete when I try to scan the entire table I find 136G in the table.

Since this data size was not enough for my tests I tried increasing the record count
recordcount = 180144000 - assuming I will have 170G and even if I include 1/3rd of this size as the overhead due to kv serialization I still should get 220G to 230G of data. But on scanning the full table I find the size to be greater than 260G.
```
recordcount=180144000
operationcount=1
workload=com.yahoo.ycsb.workloads.CoreWorkload

readallfields=true

readproportion=0.5
updateproportion=0.5
scanproportion=0
insertproportion=0

requestdistribution=zipfian
```
I use ./ycsb load only so I assume it does not honour the the other proportions.

I think am missing out some where in the calculation part. Is it because the updateProportion is also taking into effect here?

**Comment by risdenk** [comment]
@ramkrish86 did you clear the HBase table out before rerunning the load? If not I would assume you would get 180144000 + 100144000 so that would be (136 + (136*(180144000/100144000))GB or 380GB? At least by my rough math there could be duplicates and stuff that doesn't mean you would get all unique numbers.

The load doesn't use read, update, scan, or insert proportions and instead is just loading data to work with.

**Comment by ramkrish86** [comment]
Am sure there is no duplicate because i format the entire cluster before loading . So the records that i insert is for a fresh table

**Comment by ramkrish86** [comment]
As per my math i expected around 220g at the worst case. But around 260g is a mystery to me

**Comment by risdenk** [comment]
Based on your numbers, it looks like the overhead is 35-40%. It would match exactly what your numbers are:
```
((num_cols*field_size+key_prefix+key_size)*records)*factor
((10*100+4+7)*100144000)*1.35 bytes to gigabytes = 136.681538 gigabytes
((10*100+4+7)*180144000)*1.4 bytes to gigabytes = 254.975818 gigabytes
```

**Comment by ramkrish86** [comment]
Ya I think so - the overhead for serializaton for every cel is 21 without considering the actual bytes forming the data of the cell which includes the row data bytes, family data bytes, qual data bytes etc.
So may  be there the row length is increasing the overrhead to around 35-40% including this 21 bytes per cell. Thanks @risdenk .
I think it may be useful to document saying every cell with 21 bytes fixed overhead and along with that since YCSB generates row length of say 'x' bytes adding all will have an overhead of 'y%'. This will help to make data loading calculation much easier.

**Comment by risdenk** [comment]
@ramkrish86 Do you have references on where you found the 21 bytes per cell overhead? If you can put together a PR that updates the HBase binding readme that could be useful.

**Comment by risdenk** [comment]
No update so closing issue.
