### ISSUE TITLE
Issue in Execution phase of YCSB

### ISSUE THREAD

**Issue by mscsf15m027** [brianfrankcooper/YCSB#943]
I want to benchmark mongodb with YCSB. I have two check performance degradation with two parameters 
1) No of threads
2) Recordcount.
i run this command
./bin/ycsb load mongodb -s -P workloads/workloada -p recordcount=10
it takes some seconds and shows the result but when i run the same command with "run"
./bin/ycsb run mongodb -s -P workloads/workloada -p recordcount=10
there is no output almost 4 hours have been passed but still processing.
Please anyone tell me what is the estimated time for this command??

**Comment by risdenk** [comment]
Loading 10 rows shouldn't take seconds in my opinion. Also running a workload for 10 records shouldn't take hours.

What is the hardware you are running on and configuration of MongoDB?

**Comment by mscsf15m027** [comment]
i am using this command
./bin/ycsb run mongodb -s -P workloads/workloada -p recordcount=10
and configured at my laptop. which is Hp core i3.

**Comment by risdenk** [comment]
This doesn't describe how MongoDB was setup or what the actual hardware configuration is.

**Comment by mscsf15m027** [comment]
![detail](https://cloud.githubusercontent.com/assets/26159856/24402445/141ff40e-13d2-11e7-91b5-bebe6a7bde47.png)

**Comment by risdenk** [comment]
This is a very small machine with <2GB of RAM. I wouldn't expect MongoDB to perform very well on such small amount of memory especially with the OS being run as well.

**Comment by risdenk** [comment]
Closing since this probably isn't an issue with YCSB. It is most likely environment setup.
