### ISSUE TITLE
YCSB output conflict

### ISSUE THREAD

**Issue by mscsf15m027** [brianfrankcooper/YCSB#950]
I performed same experiment three times with recordcount 100, 1000, 10000,50000, 100000. There is no consistency between the output.

**Experiment#1:
Recordcount : Throughput :  Read Latency : Update Latency
100               : 701              : 868                  :300
1000             :771               :529                   : 598
10000           :724               :573                   :612
50000           :750               :569                   :584
100000         :727               :556                   :597**

**Experiment#2:
Recordcount : Throughput :  Read Latency : Update Latency
100               : 332              : 592                  :539
1000             :755               :432                   : 703
10000           :761               :391                   :700
50000           :717               :625                   :566
100000         :747               :586                  :534**

**Experiment#3:
Recordcount : Throughput :  Read Latency : Update Latency
100               : 705              :521                  :612
1000             :757               :494                   :634
10000           :724               :717                   :485
50000           :744               :486                   :661
100000         :743               :475                   :655**

I load the dataset of Orientdb and performed this experiment with varying recordcount but each time there is confusion. For example in first experiment at recordcount 10000 throughput reduces, but in 2nd experiment for same recordcount it increases and in third experiment throughput again reduces for same recordcount. Same issue i am facing in latency. 

Kindly help me how i will interpret this? It is due to my fault or due to YCSB nature?

**Comment by risdenk** [comment]
It doesn't look like you have enough samples to draw a reasonable conclusion. This could have been on a single computer and something else could have been happening. Running the same experience for more runs would provide more insight. It doesn't seem like an issue with YCSB.
