### ISSUE TITLE
Can YCSB support both redis and redis-cluster benchmark?

### ISSUE THREAD

**Issue by zh1029** [brianfrankcooper/YCSB#954]
redis JDBC supports both redis and redis-cluster. Can YCSB support both redis and redis-cluster by adding one property?

**Comment by deadjoe** [comment]
same question

**Comment by busbey** [comment]
yes, as of the 0.14.0 release you can modify [the Redis connection properties to use cluster mode](https://github.com/brianfrankcooper/YCSB/tree/0.14.0/redis#4-provide-redis-connection-parameters). Note that only non-cluster mode was tested for the release.
