### ISSUE TITLE
Running workloads in mongodb after restarting system

### ISSUE THREAD

**Issue by nelsonbrabra** [brianfrankcooper/YCSB#956]
im having a strange issue right now.
i loaded 1 million itens on Mongodb then i started running workloada and the throughput was about 8k opp/sec. but then i restarted the OS and ran the same workload and the throughput dropped to a poor 200 opp/sec. 
Any ideia why this happening?? if i drop the ycsb database, and load the itens again, the throughput goes back to being the same, but i wanna be able to restart the OS after i run each workload

thanks in advance

**Comment by allanbank** [comment]
Can you collect a mongostat from when you are running after a reload and then after a reboot?  Assuming this is a single instance monogdb you can use the command:

  `mongostat --host localhost:27017 5`

It will also be helpful to know what version of MongoDB you are using.

More information on running mongostat is available on the MongoDB website: https://docs.mongodb.com/manual/reference/program/mongostat/

My suspicion is that after the reboot the MongoDB instance is having to page in all of the data to memory from disk. After a reload of the documents all of the documents are still in memory so you get better performance. There are [commands](https://docs.mongodb.com/manual/reference/command/touch/) to force MongoDB to preload data into memory but tthe mongostat should tell us if that will help.

**Comment by allanbank** [comment]
Have you tried adding ssl=true to the MongoDB URI you pass on the YCSB command line?

**Comment by busbey** [comment]
Any luck following this advice?

**Comment by busbey** [comment]
closing as stale. if you're still having the same problem feel free to reopen with some followup on the questions above.
