### ISSUE TITLE
number of connections to mongodb

### ISSUE THREAD

**Issue by tdeneau** [brianfrankcooper/YCSB#957]
I am connecting to a MongoDB database using ycsb.  Then while running my workload, I monitor the number of connections on the server side with  db.serverStatus().connections,
I have noticed that with a single YCSB process, I do not see more than 3 connections on the server side no matter how many threads I have on the ycsb side.  Similarly with P client ycsb processes, I don't see more than 3*P connections.  

Is there a setting on the client side (or mongodb server side) that will increase this number of connections?

**Comment by allanbank** [comment]
Yes you can control the number of connections using the [connection pool options](https://docs.mongodb.com/manual/reference/connection-string/#connection-pool-options) as part of the MongoDB URI used with YCSB.

**Comment by tdeneau** [comment]
I found by experimenting that adding &maxConnections=N did the trick but can you point me to the documentation that explains this, and also explains that the default is 3 (for the mongodb java driver).

**Comment by allanbank** [comment]
For the async driver the default is 3. 

http://www.allanbank.com/mongodb-async-driver/apidocs/com/allanbank/mongodb/MongoClientConfiguration.html#getMaxConnectionCount()

The non-async driver should be 100.

**Comment by busbey** [comment]
@tdeneau did this answer your question sufficiently?

**Comment by dineiar** [comment]
@tdeneau Take a look at [threadcount property](https://github.com/brianfrankcooper/YCSB/wiki/Core-Properties) as well.

**Comment by busbey** [comment]
please reopen if you need further clarification.
