### ISSUE TITLE
dummy driver

### ISSUE THREAD

**Issue by tdeneau** [brianfrankcooper/YCSB#958]
Is there any such thing as a dummy driver that just returns a result without going to a database?  I was thinking of using it to see whether I have any performance limitations on the ycsb side without even getting a database involved.

**Comment by allanbank** [comment]
I think you are looking for the BasicDB which is called 'basic' on the command line.

https://github.com/brianfrankcooper/YCSB/blob/master/core/src/main/java/com/yahoo/ycsb/BasicDB.java

For testing the YCSB overhead you will want to set `basicdb.verbose` to false (it defaults to true).

**Comment by busbey** [comment]
@tdeneau did that answer your question sufficiently?

**Comment by busbey** [comment]
closed as stale. please reopen if you have follow-on questions.
