### ISSUE TITLE
Building YCSB code

### ISSUE THREAD

**Issue by mghosh4** [brianfrankcooper/YCSB#96]
Hi,

I was trying to build the YCSB code in Ubuntu 12 64 bit and came across a lot of issues. There were a few packages missing. I have installed Maven 2 and all its dependencies. It is now complaining of some java jar files missing in classpath like slf4j etc. Can you please give me some information as to what should I do.

Also, I want the MongoDB version built only. Is there some build time flags that I can use?

Thanks and Regards,
Mainak.

**Comment by busbey** [comment]
closing as stale. if you are still having this problem please reopen.
