### ISSUE TITLE
got confused by the switches of "-load" and "-t"

### ISSUE THREAD

**Issue by crossz** [brianfrankcooper/YCSB#960]
In the section of "Running the workloads" in the wiki of "Core Workloads".

It says:

> 1. Load the database, using workload A’s parameter file (workloads/workloada) and the “-load” switch to the client.
> 2. Run workload A (using workloads/workloada and “-t”) for a variety of throughputs.

I went through all the wiki and help of ycsb command, could not find the exact matching parts. So, I can guest "-load" is the "loading phase", but what is the "-t"? is it "-threads" or "-target"? or both?

**Comment by allanbank** [comment]
Based on the description in the python launcher I would say 'transaction phase".

https://github.com/brianfrankcooper/YCSB/blob/master/bin/ycsb#L48

**Comment by crossz** [comment]
aha, I see, after I read the source code. ......

Thanks,

**Comment by allanbank** [comment]
No problem. Let us know if you run into any other issues.
