### ISSUE TITLE
YCSB Cassandra DBWrapper: report latency for each error is false and specific error codes to track for latency are: []

### ISSUE THREAD

**Issue by cgara** [brianfrankcooper/YCSB#961]
Hi,

The message "DBWrapper: report latency for each error is false and specific error codes to track for latency are: []" generates interference in benchmark execution?
How to solve?

Environment:
Ycsb 0.12.0
Cassandra 2.1.5, replication factor 2, 6 VMs
Java (TM) SE Runtime Environment (build 1.8.0_121-b13)
Debian 8.7.1

Command:
/opt/ycsb-0.12.0/bin/ycsb load cassandra-cql -p hosts = 192.168.0.131,192.168.0.132,192.168.0.133,192.168.0.134,192.168.0.135,192.168.0.136 -p port = 9042 -p Cassandra.username = cassandra -p cassandra.password = cassandra -threads 128 -P /opt/ycsb-0.12.0/workloads/workloada -s

recordcount=250000
operationcount=250000
workload=com.yahoo.ycsb.workloads.CoreWorkload
readallfields=true
readproportion=0.5
updateproportion=0
scanproportion=0
insertproportion=0.5
requestdistribution=zipfian

Thank you very much

**Comment by BestPractises2GO** [comment]
This is just a warning and doesn't mean anything bad. It's a duplicate of #546 which is the issue for tracking this.

**Comment by cgara** [comment]
Thank you

**Comment by zhoujun90** [comment]
soga~
