### ISSUE TITLE
Unable to create release tar.gz from sources

### ISSUE THREAD

**Issue by sashas-lb** [brianfrankcooper/YCSB#964]
Hi i`m trying to create distribution tar.gz from sources without success, i had tried several maven targets including package, install and assembly:assembly (later one issued an error). 
I`m trying to create an installation archive from source similar in structure to what can be downloaded from 
curl -O --location https://github.com/brianfrankcooper/YCSB/releases/download/0.12.0/ycsb-0.12.0.tar.gz

What is the correct maven target type  
Thanks.

**Comment by busbey** [comment]
you ought to be able to start at the top level and do

```bash
mvn package
```

Then find the assembly in `distribution\target\`.

If that doesn't work, could you include the output of `mvn --version`?

**Comment by busbey** [comment]
@sashas-lb any update?

**Comment by sashas-lb** [comment]
@busbey  sorry forgot to update .. it was my fault .. i tried to reduce build size of YCSB by taking specific databses out (ones that we dont need) and took "distibution" part out by mistake

**Comment by busbey** [comment]
thanks for the update!

if you're still looking to minimize the size and build time, I could point you towards how to build just a given datastore specific distribution artifact.

**Comment by sashas-lb** [comment]
Yes please, it would be of much help.
Thanks,
Sasha.

**Comment by busbey** [comment]
Is there a particular artifact you're trying to use?

If you're looking for something from the 0.12 release, there should be a download of just the particular stuff for each data store that was still marked supported for the release.

e.g. [this is the artifact for using YCSB with Apache Kudu](https://github.com/brianfrankcooper/YCSB/releases/download/0.12.0/ycsb-kudu-binding-0.12.0.tar.gz)

To start from the source tarball and build just that same artifact, you'd run this at the top level of the unpacked tarball:

`mvn -am -pl kudu package`

Then the artifact should be in the `target` directory of the module YCSB uses for talking with that datastore.

```bash
$ tar xzf ycsb-0.12.0.tar.gz
$ cd ycsb-0.12.0
$ mvn -am -pl kudu package
...SNIP...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] YCSB Root .......................................... SUCCESS [  3.834 s]
[INFO] Core YCSB .......................................... SUCCESS [ 16.613 s]
[INFO] Per Datastore Binding descriptor ................... SUCCESS [  0.316 s]
[INFO] YCSB Datastore Binding Parent ...................... SUCCESS [  1.173 s]
[INFO] Kudu DB Binding .................................... SUCCESS [ 14.990 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 37.287 s
[INFO] Finished at: 2017-05-23T09:12:40-05:00
[INFO] Final Memory: 38M/402M
[INFO] ------------------------------------------------------------------------
$ ls -lh kudu/target/*.tar.gz
-rw-r--r--  1 busbey  staff   8.5M May 23 09:12 kudu/target/ycsb-kudu-binding-0.12.0.tar.gz
```

**Comment by busbey** [comment]
great! feel free to reopen if you run into a problem.
