### ISSUE TITLE
Apache licence text is incomplete

### ISSUE THREAD

**Issue by memmerto** [brianfrankcooper/YCSB#967]
The current Apache licence text included is incomplete.  The text of section 6 is truncated, and sections 7 through 9 are missing.

The licence text should be synced with the official copy here: http://www.apache.org/licenses/LICENSE-2.0.txt

**Comment by busbey** [comment]
great catch. goodness. Would you mind putting together a PR that replaces it?

**Comment by memmerto** [comment]
See https://github.com/brianfrankcooper/YCSB/pull/969
