### ISSUE TITLE
Error -" mvn clean package"

### ISSUE THREAD

**Issue by rohini28in** [brianfrankcooper/YCSB#971]
Hi Busbey,
pls help me out..
I installed Java 1.8.0_121 ,Mongodb3.2.12,Maven 3.3.9 and YCSB .
I mentioned the JAVA_HOME, M2_HOME properly in /etc/enviroment , /etc/profile.d/maven.sh
Now I run the command "mvn clean package " facing following problem.

rohini@hadoop:~/YCSB$ mvn clean package
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] YCSB Root
[INFO] Core YCSB
[INFO] Per Datastore Binding descriptor
[INFO] YCSB Datastore Binding Parent
[INFO] Accumulo DB Binding
[INFO] Aerospike DB Binding
[INFO] ArangoDB Binding
[INFO] ArangoDB3 Binding
[INFO] AsyncHBase Client Binding for Apache HBase
[INFO] Azure table storage Binding
[INFO] Cassandra 2.1+ DB Binding
[INFO] Cloud Spanner DB Binding
[INFO] Couchbase Binding
[INFO] Couchbase Java SDK 2.x Binding
[INFO] Azure DocumentDB Binding
[INFO] DynamoDB DB Binding
[INFO] Elasticsearch Binding
[INFO] Geode DB Binding
[INFO] Google Cloud Datastore Binding
[INFO] Google Cloud Bigtable Binding
[INFO] HBase 0.98.x DB Binding
[INFO] HBase 0.94.x DB Binding
[INFO] HBase 1.0 DB Binding
[INFO] HBase 1.2 DB Binding
[INFO] Hypertable DB Binding
[INFO] Infinispan DB Binding
[INFO] JDBC DB Binding
[INFO] Kudu DB Binding
[INFO] memcached binding
[INFO] MongoDB Binding
[INFO] Oracle NoSQL Database Binding
[INFO] OrientDB Binding
[INFO] rados of Ceph FS binding
[INFO] Redis DB Binding
[INFO] Rest Client Binding
[INFO] Riak KV Binding
[INFO] S3 Storage Binding
[INFO] Solr Binding
[INFO] Solr 6 Binding
[INFO] Tarantool DB Binding
[INFO] YCSB Release Distribution Builder
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building YCSB Root 0.13.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ root ---
[INFO] Deleting /home/rohini/YCSB/target
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] YCSB Root .......................................... FAILURE [ 1.305 s]
[INFO] Core YCSB .......................................... SKIPPED
[INFO] Per Datastore Binding descriptor ................... SKIPPED
[INFO] YCSB Datastore Binding Parent ...................... SKIPPED
[INFO] Accumulo DB Binding ................................ SKIPPED
[INFO] Aerospike DB Binding ............................... SKIPPED
[INFO] ArangoDB Binding ................................... SKIPPED
[INFO] ArangoDB3 Binding .................................. SKIPPED
[INFO] AsyncHBase Client Binding for Apache HBase ......... SKIPPED
[INFO] Azure table storage Binding ........................ SKIPPED
[INFO] Cassandra 2.1+ DB Binding .......................... SKIPPED
[INFO] Cloud Spanner DB Binding ........................... SKIPPED
[INFO] Couchbase Binding .................................. SKIPPED
[INFO] Couchbase Java SDK 2.x Binding ..................... SKIPPED
[INFO] Azure DocumentDB Binding ........................... SKIPPED
[INFO] DynamoDB DB Binding ................................ SKIPPED
[INFO] Elasticsearch Binding .............................. SKIPPED
[INFO] Geode DB Binding ................................... SKIPPED
[INFO] Google Cloud Datastore Binding ..................... SKIPPED
[INFO] Google Cloud Bigtable Binding ...................... SKIPPED
[INFO] HBase 0.98.x DB Binding ............................ SKIPPED
[INFO] HBase 0.94.x DB Binding ............................ SKIPPED
[INFO] HBase 1.0 DB Binding ............................... SKIPPED
[INFO] HBase 1.2 DB Binding ............................... SKIPPED
[INFO] Hypertable DB Binding .............................. SKIPPED
[INFO] Infinispan DB Binding .............................. SKIPPED
[INFO] JDBC DB Binding .................................... SKIPPED
[INFO] Kudu DB Binding .................................... SKIPPED
[INFO] memcached binding .................................. SKIPPED
[INFO] MongoDB Binding .................................... SKIPPED
[INFO] Oracle NoSQL Database Binding ...................... SKIPPED
[INFO] OrientDB Binding ................................... SKIPPED
[INFO] rados of Ceph FS binding ........................... SKIPPED
[INFO] Redis DB Binding ................................... SKIPPED
[INFO] Rest Client Binding ................................ SKIPPED
[INFO] Riak KV Binding .................................... SKIPPED
[INFO] S3 Storage Binding ................................. SKIPPED
[INFO] Solr Binding ....................................... SKIPPED
[INFO] Solr 6 Binding ..................................... SKIPPED
[INFO] Tarantool DB Binding ............................... SKIPPED
[INFO] YCSB Release Distribution Builder .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.862 s
[INFO] Finished at: 2017-05-24T10:06:21+05:30
[INFO] Final Memory: 9M/150M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:2.5:clean (default-clean) on project root: Failed to clean project: Failed to delete /home/rohini/YCSB/target/checkstyle.xml -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by busbey** [comment]
please try to use the convenience binary:

https://github.com/brianfrankcooper/YCSB/releases/download/0.12.0/ycsb-0.12.0.tar.gz

**Comment by busbey** [comment]
closing as stale. if the convenience binary doesn't work out, please reopen.
