### ISSUE TITLE
Understanding YCSB status report

### ISSUE THREAD

**Issue by dineiar** [brianfrankcooper/YCSB#974]
I'm testing various databases with YCSB, but I'll focus on Aerospike for this issue. This is the command line I'm using:
```
bin/ycsb run aerospike -s -P workloads/workloadg -p "as.host=<ip>" -p "as.port=3000" -p "as.namespace=ycsb" -threads 24 2>&1
```
(yes, I'm asking for status on stderr with `-s` and redirecting it to stdout with `2>&1`, ignore this)

My `workloads/workloadg` file is this:
```
recordcount=10000
operationcount=5000000
workload=com.yahoo.ycsb.workloads.CoreWorkload

readallfields=true

readproportion=0.5
updateproportion=0
scanproportion=0
insertproportion=0.5
requestdistribution=zipfian

core_workload_insertion_retry_limit = 3
```

I've got this output:
```
2017-05-20 18:55:34:606 0 sec: 0 operations; est completion in 0 seconds 
2017-05-20 18:55:44:512 10 sec: 376385 operations; 37634.74 current ops/sec; est completion in 2 minutes [READ: Count=188431, Max=154495, Min=157, Avg=548.39, 90=739, 99=3513, 99.9=15359, 99.99=44991] [INSERT: Count=189530, Max=160383, Min=177, Avg=534.86, 90=744, 99=2779, 99.9=11935, 99.99=41439] 
2017-05-20 18:55:54:511 20 sec: 1001647 operations; 62526.2 current ops/sec; est completion in 1 minutes [READ: Count=312914, Max=56191, Min=146, Avg=367.63, 90=458, 99=749, 99.9=4991, 99.99=17679] [INSERT: Count=311032, Max=31711, Min=166, Avg=377.82, 90=476, 99=767, 99.9=5103, 99.99=17215] 
... //suppressed by me
2017-05-20 18:57:07:125 92 sec: 5000000 operations; 15391.5 current ops/sec; [READ: Count=20119, Max=32895, Min=146, Avg=253.64, 90=308, 99=485, 99.9=2945, 99.99=14615] [CLEANUP: Count=10, Max=586, Min=135, Avg=267.2, 90=552, 99=586, 99.9=586, 99.99=586] [INSERT: Count=19945, Max=33855, Min=156, Avg=262.57, 90=326, 99=528, 99.9=2129, 99.99=14567] 
[OVERALL], RunTime(ms), 92614.0
[OVERALL], Throughput(ops/sec), 53987.518085818556
[TOTAL_GCS_PS_Scavenge], Count, 148.0
[TOTAL_GC_TIME_PS_Scavenge], Time(ms), 477.0
[TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.515040922538709
[TOTAL_GCS_PS_MarkSweep], Count, 0.0
[TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 0.0
[TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.0
[TOTAL_GCs], Count, 148.0
[TOTAL_GC_TIME], Time(ms), 477.0
[TOTAL_GC_TIME_%], Time(%), 0.515040922538709
[READ], Operations, 2499233.0
[READ], AverageLatency(us), 411.7478678458551
[READ], MinLatency(us), 146.0
[READ], MaxLatency(us), 154495.0
[READ], 95thPercentileLatency(us), 629.0
[READ], 99thPercentileLatency(us), 1168.0
[READ], Return=OK, 2499233
[CLEANUP], Operations, 24.0
[CLEANUP], AverageLatency(us), 374.9583333333333
[CLEANUP], MinLatency(us), 135.0
[CLEANUP], MaxLatency(us), 1130.0
[CLEANUP], 95thPercentileLatency(us), 1019.0
[CLEANUP], 99thPercentileLatency(us), 1130.0
[INSERT], Operations, 2500767.0
[INSERT], AverageLatency(us), 421.6069477884185
[INSERT], MinLatency(us), 156.0
[INSERT], MaxLatency(us), 160383.0
[INSERT], 95thPercentileLatency(us), 648.0
[INSERT], 99thPercentileLatency(us), 1168.0
[INSERT], Return=OK, 2500767
```
(if you guys need the raw output with the suppressed part, just let me know)

What I understand from the second line is: in 10 seconds of test, were completed 376,385 ops, being 188,431 read and 189,530 insert operations. But, if you sum up this numbers it doesn't match. There's 1,576 less operations reported from the first number. Is my understanding wrong, or is the YCSB reporting wrong numbers?

In these lines, what is the unit of `Min`, `Max`, `Avg`, `90`, etc? Are there operations, latency...? (I know 90, 95, 99 are for percentiles, but of what). At first sight I thought they were operations, but `Max=154495` and `Min=157` operations doesn't make sense. If they are latency, are these in milisseconds?

This status report could be better explained in the docs, the only documentation I found about it were two paragraph in the very end of Step 5 of [Running a Workload](https://github.com/brianfrankcooper/YCSB/wiki/Running-a-Workload).

Thanks in advance.

**Comment by busbey** [comment]
Take a look at [the StatusThread definition|https://github.com/brianfrankcooper/YCSB/blob/a12928ec2ef4e234718dc45236d1b28e06adf975/core/src/main/java/com/yahoo/ycsb/Client.java#L42]. The stats across threads for total ops, and individual types of ops are grabbed independently w/o a lock for consistency. so I would be surprised if they ever line up on a system under load.

The Min/Max/ etc are all latency. I believe the units are ultimately up to the measurement type you choose (I think they all currently use us).

I agree this could do with some explanation. Mind drafting something up based on what you've dug out so far?

**Comment by busbey** [comment]
closing as stale. feel free to reopen if you're still poking at this issue.
