### ISSUE TITLE
Can Garbage Collection (GC) affect latency reported by YCSB? (question)

### ISSUE THREAD

**Issue by kirillsc** [brianfrankcooper/YCSB#975]
Hi, 

I am using YCSB to profile Cassandra cluster. I am aware that Cassandra's performance can be negatively affected by GC and there are different tuning techniques that can partially mitigate the issue. 

However, I would like to know if measurements reported by YCSB can also be affected by JVM GC as well, and to what extend? As I understand, YCSB and Cassandra's Java Driver running on JVM. If that JVM runs GC and freezes run time execution (say for 100 ms) wouldn't that affect the YCSB latency measurements? Responses will be queued up in the networking stack until they ACK'ed at the application level?

Thanks!

**Comment by manolama** [comment]
Yes, the YCSB GC behavior can definitely impact latency measurements and GC. You will see that with some of the targets. Check the report output as we now report GC behavior with YCSB runs and you can use that to determine the effect on measurements.

**Comment by busbey** [comment]
closing as stale.
