### ISSUE TITLE
Switching from "histogram" to "hdrhistogram" lost the histogram in ycsb output

### ISSUE THREAD

**Issue by liujiongxin** [brianfrankcooper/YCSB#976]
We are using YCSB 0.9.0, and we try to parse the results in "_str(stderr + stdout)_". 

When using "histogram" for "measurementtype", p50, p75, p90, ... can be obtained from "_str(stderr + stdout)_". When using "hdrhistogram", these percentiles are gone. Maybe there is something we missed?

**Comment by manolama** [comment]
Actually it's odd but with 13-SNAPSHOT I see the percentiles from the hdr histogram:
```
[UPDATE], Operations, 499.0
[UPDATE], AverageLatency(us), 33.88577154308617
[UPDATE], MinLatency(us), 14.0
[UPDATE], MaxLatency(us), 879.0
[UPDATE], 95thPercentileLatency(us), 62.0
[UPDATE], 99thPercentileLatency(us), 86.0
[UPDATE], Return=OK, 499
...
```

but not those from just the regular histogram:
```
[UPDATE], Operations, 499.0
[UPDATE], AverageLatency(us), 33.88577154308617
[UPDATE], MinLatency(us), 14.0
[UPDATE], MaxLatency(us), 879.0
[UPDATE], 95thPercentileLatency(us), 62.0
[UPDATE], 99thPercentileLatency(us), 86.0
[UPDATE], Return=OK, 499
.....
```

**Comment by busbey** [comment]
Can you reproduce this error with the 0.14.0 release @liujiongxin?

**Comment by liujiongxin** [comment]
What's the error? I didn't see any output difference in manolama's comment.

**Comment by busbey** [comment]
Closing as stale. Please reopen if you're still having trouble.

**Comment by liujiongxin** [comment]
Sorry to get back to you this late. I had a chance to test it with version 0.15.0, however the problem still exists. 

The commandline is: /opt/pkb/ycsb/bin/ycsb run hbase10 -cp /opt/pkb/hbase/conf -jvm-args '"'"' -Xmx3699m'"'"' -threads 1 -P /opt/pkb/workloada -p table=ycsb9660d6d8 -p recordcount=100000 -p operationcount=100000000 -p **measurementtype=hdrhistogram** -p **measurement.interval=intended** -p maxexecutiontime=1200 -p columnfamily=cf -p clientbuffering=false

however, the output .json file does not contain the metrics such as update p50 latency, update p95 latency, etc.

**Comment by liujiongxin** [comment]
My bad, It seems I did not use VERBOSE_PROPERTY. Thanks for supporting the hdr histogram output.
