### ISSUE TITLE
operationcount on ycsb run

### ISSUE THREAD

**Issue by tdeneau** [brianfrankcooper/YCSB#979]
Sorry if this is a repeat that someone else has already noticed...

Using ycsb 0.12.0, I have an existing mongodb database that has been set up with ycsb load  with recordcount=1000000.  I want to run workloadc, (read-only) from that database.  I do a ycsb run (not load) with  -p operationcount=xxx property.  The operationcount gets honored correctly but only 1000 unique keys are requested from the database.

I have to additionally set the recordcount property to 1000000 on the ycsb run to get the read requests distributed across all the records.

Is this by design?  Shouldn't the default be to query the size of the usertable and distribute requests across that size?

**Comment by busbey** [comment]
the behavior is what we expect. recordcount is used to specify a priori how big the range of possible keys for operations are. there's also an offset to pick a starting point.

Clearer if we called out use of recordcount with operation count in [Running a Workload](https://github.com/brianfrankcooper/YCSB/wiki/Running-a-Workload) or maybe [running in parallel](https://github.com/brianfrankcooper/YCSB/wiki/Running-a-Workload-in-Parallel)?

**Comment by busbey** [comment]
Closing as stale. Please reopen if you're still having trouble.
