### ISSUE TITLE
Hbase test ,the throughput runned with 0.12.0 less than that runned with 0.1.4

### ISSUE THREAD

**Issue by zxm88888** [brianfrankcooper/YCSB#986]
Why did the throughput runned with the version 0.12.0 less than that runner with version 0.1.4?IF i  use YCSB-0.1.4  test hbase 1.2.4 ，the throughput of test result is 2700 opc/sec based on a thread,but use YCSB-0.12.0,the throughput is 400 opc/sec base a thread,why,all the same configuration.
 AND as used YCSB-0.1.4,if i run with 5 threads ,the CPU of client machine will rise to 99%，this moment，the  throughput is 2700 opc/sec ,and every record size is 323 byte,why so?

**Comment by busbey** [comment]
YCSB 0.1.4 is tragically out of date. it's entirely probably that in the version you're running the hbase client is still defaulting to caching on the client side.

You could check by running 0.12.0 with `-Dclientbuffering=true`.

**Comment by busbey** [comment]
closing as stale. please reopen if you get a chance to follow up.
