### ISSUE TITLE
Unable to load

### ISSUE THREAD

**Issue by nelsonbrabra** [brianfrankcooper/YCSB#987]
Im having some issues here, i think maven is the problem but i've re-installed it plenty of times but i keep getting the same error, would appreciate some help.

[WARN]  Running against a source checkout. In order to get our runtime dependencies we'll have to invoke Maven. Depending on the state of your system, this may take ~30-45 seconds
[DEBUG]  Running 'mvn -pl com.yahoo.ycsb:mongodb-binding -am package -DskipTests dependency:build-classpath -DincludeScope=compile -Dmdep.outputFilterFile=true'
[ERROR]  Attempting to generate a classpath from Maven failed with return code '1'. The output from Maven follows, try running 'mvn -DskipTests package dependency:build=classpath' on your own and correct errors.

mvn output:
[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.yahoo.ycsb:root:0.13.0-SNAPSHOT (/home/machine/Documents/ycsb-0.12.0/pom.xml) has 25 errors
[ERROR]     Child module /home/machine/Documents/ycsb-0.12.0/accumulo of /home/machine/Documents/ycsb-0.12.0/pom.xml does not exist
(...)
[ERROR]     Child module /home/machine/Documents/ycsb-0.12.0/tarantool of /home/machine/Documents/ycsb-0.12.0/pom.xml does not exist
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

**Comment by busbey** [comment]
please try running using the convenience binaries:

https://github.com/brianfrankcooper/YCSB/releases/download/0.12.0/ycsb-0.12.0.tar.gz

**Comment by busbey** [comment]
closing as stale. please reopen if you have the same problem with convenience binaries.
