### ISSUE TITLE
Does YCSB work with Cassandra 3.11.0?

### ISSUE THREAD

**Issue by gothikz** [brianfrankcooper/YCSB#990]
Hello, 

I was wondering if YCSB works with Cassandra version 3.x, or it works only with Cassandra version 2.x or 1.x.

**Comment by vreniers** [comment]
Have u tried it?

**Comment by gothikz** [comment]
Yes, I did and it worked. I also wrote about this on Github. 
    On Tuesday, July 17, 2018, 2:03:02 PM GMT+3, Vincent Reniers <notifications@github.com> wrote:  
 
 
Have u tried it?
