### ISSUE TITLE
How can i connect multi-mongos

### ISSUE THREAD

**Issue by tcsll** [brianfrankcooper/YCSB#992]
how_ can i connect multi-mongos ?
i try use  like   "mongodb://db1.example.net,db2.example.net:2500/?replicaSet=test" 
but  it just connect one db   
how can i do to begin the Pressure test via multi-mongos

**Comment by allanbank** [comment]
The replicaSet=test implies this is a replica set, not a sharded cluster?

Both MongoDB drivers will use the list of servers you provide as a seed list and then determine the closest mongos to use. If all of the mongos servers are the same "ping time" then the requests should eventually be evenly distributed across the shards.

**Comment by manolama** [comment]
Closing since it is likely answered.
