### ISSUE TITLE
hbase - recordcount and readlatency 

### ISSUE THREAD

**Issue by rs8501s** [brianfrankcooper/YCSB#993]
I am running performance tests on our hbase cluster.
I have populated a test table by running ycsb load with record count of 17million.
I ran several ycsb runs with different values for record count.
The AverageLatency for READ operations vary based on record count. 
For record count 10000, the results are under 5ms. For large recordcount, the READ latency is in the order of 100+ ms.

------
recordcount=200000
fieldcount=34
fieldlength=210
readproportion=1
readallfields=true
maxscanlength=400
operationcount=15000
-------
Output:
<clipped ..>
[READ], AverageLatency(us), 173285.88850011662
-----

Question is, how does recordcount affect read latency?
Does it do read operation only within the given record count?
 
recordcount: number of records to load into the database initially (default: 0)

**Comment by manolama** [comment]
Hi, for HBase the latency may be due to splits on the region server which you would see more often with higher record counts. Take a look at your region count before and after or try running the read-only workloads to see what it looks like.

**Comment by busbey** [comment]
closing as stale. if you're still facing issues please reopen.
