### ISSUE TITLE
S3Client could not estimate read perfomance correctly

### ISSUE THREAD

**Issue by bosher** [brianfrankcooper/YCSB#994]
The S3Client does not read the whole object. 

The  problem is in the call  "objectData.read(inputStreamToByte, 0, sizeOfFile)" inside readFromStorage method. This call is returning only the beginning of the object if the object is long enough. We should have something like below:
...
int len;
int offset = 0;
while ((len = objectData.read(inputStreamToByte, offset, sizeOfFile - offset)) > 0) {
      	offset  += len;
}
...

**Comment by busbey** [comment]
good find! could you put up a pull request?

**Comment by bosher** [comment]
I have sent pull request #1010.
